[package]
name = "discover_exports"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
fixedbitset = { workspace = true }
log = { workspace = true }
petgraph = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits", "visit", "visit-mut"] }
