#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [BlendComponentBuilder] for building [`wgpu_27::BlendComponent`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [src_factor](BlendComponentBuilder::src_factor) Optional, defaults to [wgpu_27::BlendFactor::One]\n  - [dst_factor](BlendComponentBuilder::dst_factor) Optional, defaults to [wgpu_27::BlendFactor::Zero]\n  - [operation](BlendComponentBuilder::operation) Optional, defaults to [wgpu_27::BlendOperation::Add]\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_27::BlendComponent`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [src_factor](BlendComponentBuilder::src_factor) Optional, defaults to [wgpu_27::BlendFactor::One]\n  - [dst_factor](BlendComponentBuilder::dst_factor) Optional, defaults to [wgpu_27::BlendFactor::Zero]\n  - [operation](BlendComponentBuilder::operation) Optional, defaults to [wgpu_27::BlendOperation::Add]\n"]
pub fn blend_component(
    # [builder (default = wgpu_27 :: BlendFactor :: One ,)] src_factor: wgpu_27::BlendFactor,
    # [builder (default = wgpu_27 :: BlendFactor :: Zero ,)] dst_factor: wgpu_27::BlendFactor,
    # [builder (default = wgpu_27 :: BlendOperation :: Add ,)] operation: wgpu_27::BlendOperation,
) -> wgpu_27::BlendComponent {
    wgpu_27::BlendComponent {
        src_factor,
        dst_factor,
        operation,
    }
}
pub trait NestedBlendComponent {
    fn unnest(self) -> wgpu_27::BlendComponent;
}
impl NestedBlendComponent for wgpu_27::BlendComponent {
    fn unnest(self) -> wgpu_27::BlendComponent {
        self
    }
}
impl<S: state::IsComplete> NestedBlendComponent for BlendComponentBuilder<S> {
    fn unnest(self) -> wgpu_27::BlendComponent {
        self.build()
    }
}
