#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [CreateTlasDescriptorBuilder] for building [`wgpu_27::CreateTlasDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [max_instances](CreateTlasDescriptorBuilder::max_instances) Required\n  - [flags](CreateTlasDescriptorBuilder::flags) Required\n  - [update_mode](CreateTlasDescriptorBuilder::update_mode) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_27::CreateTlasDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [max_instances](CreateTlasDescriptorBuilder::max_instances) Required\n  - [flags](CreateTlasDescriptorBuilder::flags) Required\n  - [update_mode](CreateTlasDescriptorBuilder::update_mode) Required\n"]
pub fn create_tlas_descriptor<'a>(
    #[builder(start_fn)] label: wgpu_27::Label<'a>,
    max_instances: u32,
    flags: wgpu_27::wgt::AccelerationStructureFlags,
    update_mode: wgpu_27::wgt::AccelerationStructureUpdateMode,
) -> wgpu_27::CreateTlasDescriptor<'a> {
    wgpu_27::CreateTlasDescriptor {
        label,
        max_instances,
        flags,
        update_mode,
    }
}
impl<'a, S: state::IsComplete> CreateTlasDescriptorBuilder<'a, S> {
    pub fn create_with(self, device: &wgpu_27::Device) -> wgpu_27::Tlas {
        device.create_tlas(&self.build())
    }
}
