#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [DispatchIndirectArgsBuilder] for building [`wgpu_27::util::DispatchIndirectArgs`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [x](DispatchIndirectArgsBuilder::x) Optional, defaults to `0u32`\n  - [y](DispatchIndirectArgsBuilder::y) Optional, defaults to `0u32`\n  - [z](DispatchIndirectArgsBuilder::z) Optional, defaults to `0u32`\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_27::util::DispatchIndirectArgs`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [x](DispatchIndirectArgsBuilder::x) Optional, defaults to `0u32`\n  - [y](DispatchIndirectArgsBuilder::y) Optional, defaults to `0u32`\n  - [z](DispatchIndirectArgsBuilder::z) Optional, defaults to `0u32`\n"]
pub fn dispatch_indirect_args(
    #[builder(default = 0u32)] x: u32,
    #[builder(default = 0u32)] y: u32,
    #[builder(default = 0u32)] z: u32,
) -> wgpu_27::util::DispatchIndirectArgs {
    wgpu_27::util::DispatchIndirectArgs { x, y, z }
}
pub trait NestedDispatchIndirectArgs {
    fn unnest(self) -> wgpu_27::util::DispatchIndirectArgs;
}
impl NestedDispatchIndirectArgs for wgpu_27::util::DispatchIndirectArgs {
    fn unnest(self) -> wgpu_27::util::DispatchIndirectArgs {
        self
    }
}
impl<S: state::IsComplete> NestedDispatchIndirectArgs for DispatchIndirectArgsBuilder<S> {
    fn unnest(self) -> wgpu_27::util::DispatchIndirectArgs {
        self.build()
    }
}
