#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [DownlevelLimitsBuilder] for building [`wgpu_27::DownlevelLimits`]\n        "] }) ,)]
#[doc = "\nBuilder for [`wgpu_27::DownlevelLimits`]\n        "]
pub fn downlevel_limits() -> wgpu_27::DownlevelLimits {
    wgpu_27::DownlevelLimits {}
}
pub trait NestedDownlevelLimits {
    fn unnest(self) -> wgpu_27::DownlevelLimits;
}
impl NestedDownlevelLimits for wgpu_27::DownlevelLimits {
    fn unnest(self) -> wgpu_27::DownlevelLimits {
        self
    }
}
impl NestedDownlevelLimits for DownlevelLimitsBuilder {
    fn unnest(self) -> wgpu_27::DownlevelLimits {
        self.build()
    }
}
