#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [Dx12BackendOptionsBuilder] for building [`wgpu_27::Dx12BackendOptions`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [shader_compiler](Dx12BackendOptionsBuilder::shader_compiler) Optional, defaults to [wgpu_27::Dx12Compiler::Fxc]\n  - [presentation_system](Dx12BackendOptionsBuilder::presentation_system) Optional, defaults to [wgpu_27::wgt::Dx12SwapchainKind::DxgiFromHwnd]\n  - [latency_waitable_object](Dx12BackendOptionsBuilder::latency_waitable_object) Optional, defaults to [wgpu_27::wgt::Dx12UseFrameLatencyWaitableObject::Wait]\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_27::Dx12BackendOptions`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [shader_compiler](Dx12BackendOptionsBuilder::shader_compiler) Optional, defaults to [wgpu_27::Dx12Compiler::Fxc]\n  - [presentation_system](Dx12BackendOptionsBuilder::presentation_system) Optional, defaults to [wgpu_27::wgt::Dx12SwapchainKind::DxgiFromHwnd]\n  - [latency_waitable_object](Dx12BackendOptionsBuilder::latency_waitable_object) Optional, defaults to [wgpu_27::wgt::Dx12UseFrameLatencyWaitableObject::Wait]\n"]
pub fn dx12_backend_options(
    # [builder (default = wgpu_27 :: Dx12Compiler :: Fxc ,)] shader_compiler: wgpu_27::Dx12Compiler,
    # [builder (default = wgpu_27 :: wgt :: Dx12SwapchainKind :: DxgiFromHwnd ,)]
    presentation_system: wgpu_27::wgt::Dx12SwapchainKind,
    # [builder (default = wgpu_27 :: wgt :: Dx12UseFrameLatencyWaitableObject :: Wait ,)]
    latency_waitable_object: wgpu_27::wgt::Dx12UseFrameLatencyWaitableObject,
) -> wgpu_27::Dx12BackendOptions {
    wgpu_27::Dx12BackendOptions {
        shader_compiler,
        presentation_system,
        latency_waitable_object,
    }
}
pub trait NestedDx12BackendOptions {
    fn unnest(self) -> wgpu_27::Dx12BackendOptions;
}
impl NestedDx12BackendOptions for wgpu_27::Dx12BackendOptions {
    fn unnest(self) -> wgpu_27::Dx12BackendOptions {
        self
    }
}
impl<S: state::IsComplete> NestedDx12BackendOptions for Dx12BackendOptionsBuilder<S> {
    fn unnest(self) -> wgpu_27::Dx12BackendOptions {
        self.build()
    }
}
