#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [Extent3dBuilder] for building [`wgpu_27::Extent3d`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [width](Extent3dBuilder::width) Optional, defaults to `1`\n  - [height](Extent3dBuilder::height) Optional, defaults to `1`\n  - [depth_or_array_layers](Extent3dBuilder::depth_or_array_layers) Optional, defaults to `1`\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_27::Extent3d`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [width](Extent3dBuilder::width) Optional, defaults to `1`\n  - [height](Extent3dBuilder::height) Optional, defaults to `1`\n  - [depth_or_array_layers](Extent3dBuilder::depth_or_array_layers) Optional, defaults to `1`\n"]
pub fn extent3d(
    #[builder(default = 1)] width: u32,
    #[builder(default = 1)] height: u32,
    #[builder(default = 1)] depth_or_array_layers: u32,
) -> wgpu_27::Extent3d {
    wgpu_27::Extent3d {
        width,
        height,
        depth_or_array_layers,
    }
}
pub trait NestedExtent3d {
    fn unnest(self) -> wgpu_27::Extent3d;
}
impl NestedExtent3d for wgpu_27::Extent3d {
    fn unnest(self) -> wgpu_27::Extent3d {
        self
    }
}
impl<S: state::IsComplete> NestedExtent3d for Extent3dBuilder<S> {
    fn unnest(self) -> wgpu_27::Extent3d {
        self.build()
    }
}
