#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [OperationsBuilder] for building [`wgpu_27::Operations`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [load](OperationsBuilder::load) Optional, defaults to [wgpu_27::LoadOp::Clear(Default::default())]\n  - [store](OperationsBuilder::store) Optional, defaults to [wgpu_27::StoreOp::Store]\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_27::Operations`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [load](OperationsBuilder::load) Optional, defaults to [wgpu_27::LoadOp::Clear(Default::default())]\n  - [store](OperationsBuilder::store) Optional, defaults to [wgpu_27::StoreOp::Store]\n"]
pub fn operations<V: Default>(
    # [builder (default = wgpu_27 :: LoadOp :: Clear (Default :: default ()) ,)]
    load: wgpu_27::LoadOp<V>,
    # [builder (default = wgpu_27 :: StoreOp :: Store ,)] store: wgpu_27::StoreOp,
) -> wgpu_27::Operations<V> {
    wgpu_27::Operations { load, store }
}
pub trait NestedOperations<V: Default> {
    fn unnest(self) -> wgpu_27::Operations<V>;
}
impl<V: Default> NestedOperations<V> for wgpu_27::Operations<V> {
    fn unnest(self) -> wgpu_27::Operations<V> {
        self
    }
}
impl<V: Default, S: state::IsComplete> NestedOperations<V> for OperationsBuilder<V, S> {
    fn unnest(self) -> wgpu_27::Operations<V> {
        self.build()
    }
}
