#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [PipelineLayoutDescriptorBuilder] for building [`wgpu_27::PipelineLayoutDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [bind_group_layouts](PipelineLayoutDescriptorBuilder::bind_group_layouts) Optional, defaults to [::core::default::Default::default()]\n  - [push_constant_ranges](PipelineLayoutDescriptorBuilder::push_constant_ranges) Optional, defaults to [::core::default::Default::default()]\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_27::PipelineLayoutDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [bind_group_layouts](PipelineLayoutDescriptorBuilder::bind_group_layouts) Optional, defaults to [::core::default::Default::default()]\n  - [push_constant_ranges](PipelineLayoutDescriptorBuilder::push_constant_ranges) Optional, defaults to [::core::default::Default::default()]\n"]
pub fn pipeline_layout_descriptor<'a>(
    #[builder(start_fn)] label: wgpu_27::Label<'a>,
    # [builder (default = :: core :: default :: Default :: default () ,)]
    bind_group_layouts: &'a [&'a wgpu_27::BindGroupLayout],
    # [builder (default = :: core :: default :: Default :: default () ,)]
    push_constant_ranges: &'a [wgpu_27::PushConstantRange],
) -> wgpu_27::PipelineLayoutDescriptor<'a> {
    wgpu_27::PipelineLayoutDescriptor {
        label,
        bind_group_layouts,
        push_constant_ranges,
    }
}
impl<'a, S: state::IsComplete> PipelineLayoutDescriptorBuilder<'a, S> {
    pub fn create_with(self, device: &wgpu_27::Device) -> wgpu_27::PipelineLayout {
        device.create_pipeline_layout(&self.build())
    }
}
pub trait NestedPipelineLayoutDescriptor<'a> {
    fn unnest(self) -> wgpu_27::PipelineLayoutDescriptor<'a>;
}
impl<'a> NestedPipelineLayoutDescriptor<'a> for wgpu_27::PipelineLayoutDescriptor<'a> {
    fn unnest(self) -> wgpu_27::PipelineLayoutDescriptor<'a> {
        self
    }
}
impl<'a, S: state::IsComplete> NestedPipelineLayoutDescriptor<'a>
    for PipelineLayoutDescriptorBuilder<'a, S>
{
    fn unnest(self) -> wgpu_27::PipelineLayoutDescriptor<'a> {
        self.build()
    }
}
