#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_27::RenderBundleDepthStencil`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [format](RenderBundleDepthStencilBuilder::format) Required\n  - [depth_read_only](RenderBundleDepthStencilBuilder::depth_read_only) Required\n  - [stencil_read_only](RenderBundleDepthStencilBuilder::stencil_read_only) Required\n"]
pub struct RenderBundleDepthStencilBuilder<CS: State> {
    format: CS::Format,
    depth_read_only: CS::DepthReadOnly,
    stencil_read_only: CS::StencilReadOnly,
}
impl RenderBundleDepthStencilBuilder<Empty> {
    pub fn new() -> RenderBundleDepthStencilBuilder<Empty> {
        RenderBundleDepthStencilBuilder {
            format: FormatEmpty,
            depth_read_only: DepthReadOnlyEmpty,
            stencil_read_only: StencilReadOnlyEmpty,
        }
    }
}
#[doc = "\nReturns [RenderBundleDepthStencilBuilder] for building [`wgpu_27::RenderBundleDepthStencil`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [format](RenderBundleDepthStencilBuilder::format) Required\n  - [depth_read_only](RenderBundleDepthStencilBuilder::depth_read_only) Required\n  - [stencil_read_only](RenderBundleDepthStencilBuilder::stencil_read_only) Required\n"]
pub fn render_bundle_depth_stencil() -> RenderBundleDepthStencilBuilder<Empty> {
    RenderBundleDepthStencilBuilder::new()
}
pub struct FormatEmpty;
impl Field for FormatEmpty {}
pub trait FormatIsEmpty {}
impl FormatIsEmpty for FormatEmpty {}
pub trait IsSetFormat {
    fn get(self) -> wgpu_27::TextureFormat;
}
pub struct FormatValue(pub wgpu_27::TextureFormat);
impl Field for FormatValue {}
impl IsSetFormat for FormatValue {
    fn get(self) -> wgpu_27::TextureFormat {
        self.0
    }
}
pub struct DepthReadOnlyEmpty;
impl Field for DepthReadOnlyEmpty {}
pub trait DepthReadOnlyIsEmpty {}
impl DepthReadOnlyIsEmpty for DepthReadOnlyEmpty {}
pub trait IsSetDepthReadOnly {
    fn get(self) -> bool;
}
pub struct DepthReadOnlyValue(pub bool);
impl Field for DepthReadOnlyValue {}
impl IsSetDepthReadOnly for DepthReadOnlyValue {
    fn get(self) -> bool {
        self.0
    }
}
pub struct StencilReadOnlyEmpty;
impl Field for StencilReadOnlyEmpty {}
pub trait StencilReadOnlyIsEmpty {}
impl StencilReadOnlyIsEmpty for StencilReadOnlyEmpty {}
pub trait IsSetStencilReadOnly {
    fn get(self) -> bool;
}
pub struct StencilReadOnlyValue(pub bool);
impl Field for StencilReadOnlyValue {}
impl IsSetStencilReadOnly for StencilReadOnlyValue {
    fn get(self) -> bool {
        self.0
    }
}
pub trait State {
    type Format: Field;
    type DepthReadOnly: Field;
    type StencilReadOnly: Field;
}
pub struct Empty;
impl State for Empty {
    type Format = FormatEmpty;
    type DepthReadOnly = DepthReadOnlyEmpty;
    type StencilReadOnly = StencilReadOnlyEmpty;
}
pub struct SetFormat<CS>(CS);
impl<CS: State> State for SetFormat<CS> {
    type Format = FormatValue;
    type DepthReadOnly = CS::DepthReadOnly;
    type StencilReadOnly = CS::StencilReadOnly;
}
pub struct SetDepthReadOnly<CS>(CS);
impl<CS: State> State for SetDepthReadOnly<CS> {
    type Format = CS::Format;
    type DepthReadOnly = DepthReadOnlyValue;
    type StencilReadOnly = CS::StencilReadOnly;
}
pub struct SetStencilReadOnly<CS>(CS);
impl<CS: State> State for SetStencilReadOnly<CS> {
    type Format = CS::Format;
    type DepthReadOnly = CS::DepthReadOnly;
    type StencilReadOnly = StencilReadOnlyValue;
}
impl<CS: State> RenderBundleDepthStencilBuilder<CS> {
    #[doc = "Setter for [wgpu_27::RenderBundleDepthStencil::format]. Required.\n"]
    pub fn format(
        self,
        format: wgpu_27::TextureFormat,
    ) -> RenderBundleDepthStencilBuilder<SetFormat<CS>>
    where
        CS::Format: FormatIsEmpty,
    {
        RenderBundleDepthStencilBuilder {
            format: FormatValue(format),
            depth_read_only: self.depth_read_only,
            stencil_read_only: self.stencil_read_only,
        }
    }
    #[doc = "Setter for [wgpu_27::RenderBundleDepthStencil::depth_read_only]. Required.\n"]
    pub fn depth_read_only(
        self,
        depth_read_only: bool,
    ) -> RenderBundleDepthStencilBuilder<SetDepthReadOnly<CS>>
    where
        CS::DepthReadOnly: DepthReadOnlyIsEmpty,
    {
        RenderBundleDepthStencilBuilder {
            format: self.format,
            depth_read_only: DepthReadOnlyValue(depth_read_only),
            stencil_read_only: self.stencil_read_only,
        }
    }
    #[doc = "Setter for [wgpu_27::RenderBundleDepthStencil::stencil_read_only]. Required.\n"]
    pub fn stencil_read_only(
        self,
        stencil_read_only: bool,
    ) -> RenderBundleDepthStencilBuilder<SetStencilReadOnly<CS>>
    where
        CS::StencilReadOnly: StencilReadOnlyIsEmpty,
    {
        RenderBundleDepthStencilBuilder {
            format: self.format,
            depth_read_only: self.depth_read_only,
            stencil_read_only: StencilReadOnlyValue(stencil_read_only),
        }
    }
}
pub trait Complete:
    State<Format: IsSetFormat, DepthReadOnly: IsSetDepthReadOnly, StencilReadOnly: IsSetStencilReadOnly>
{
}
impl<
        CS: State<
            Format: IsSetFormat,
            DepthReadOnly: IsSetDepthReadOnly,
            StencilReadOnly: IsSetStencilReadOnly,
        >,
    > Complete for CS
{
}
impl<CS: Complete> RenderBundleDepthStencilBuilder<CS> {
    pub fn build(self) -> wgpu_27::RenderBundleDepthStencil {
        wgpu_27::RenderBundleDepthStencil {
            format: IsSetFormat::get(self.format),
            depth_read_only: IsSetDepthReadOnly::get(self.depth_read_only),
            stencil_read_only: IsSetStencilReadOnly::get(self.stencil_read_only),
        }
    }
}
impl Nested<wgpu_27::RenderBundleDepthStencil> for wgpu_27::RenderBundleDepthStencil {
    fn unnest(self) -> wgpu_27::RenderBundleDepthStencil {
        self
    }
}
impl<CS: Complete> Nested<wgpu_27::RenderBundleDepthStencil>
    for RenderBundleDepthStencilBuilder<CS>
{
    fn unnest(self) -> wgpu_27::RenderBundleDepthStencil {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {}
}
