#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [RenderPassTimestampWritesBuilder] for building [`wgpu_27::RenderPassTimestampWrites`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [query_set](RenderPassTimestampWritesBuilder::query_set) Required\n  - [beginning_of_pass_write_index](RenderPassTimestampWritesBuilder::beginning_of_pass_write_index) Required\n  - [end_of_pass_write_index](RenderPassTimestampWritesBuilder::end_of_pass_write_index) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_27::RenderPassTimestampWrites`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [query_set](RenderPassTimestampWritesBuilder::query_set) Required\n  - [beginning_of_pass_write_index](RenderPassTimestampWritesBuilder::beginning_of_pass_write_index) Required\n  - [end_of_pass_write_index](RenderPassTimestampWritesBuilder::end_of_pass_write_index) Required\n"]
pub fn render_pass_timestamp_writes<'a>(
    query_set: &'a wgpu_27::QuerySet,
    beginning_of_pass_write_index: Option<u32>,
    end_of_pass_write_index: Option<u32>,
) -> wgpu_27::RenderPassTimestampWrites<'a> {
    wgpu_27::RenderPassTimestampWrites {
        query_set,
        beginning_of_pass_write_index,
        end_of_pass_write_index,
    }
}
pub trait NestedRenderPassTimestampWrites<'a> {
    fn unnest(self) -> wgpu_27::RenderPassTimestampWrites<'a>;
}
impl<'a> NestedRenderPassTimestampWrites<'a> for wgpu_27::RenderPassTimestampWrites<'a> {
    fn unnest(self) -> wgpu_27::RenderPassTimestampWrites<'a> {
        self
    }
}
impl<'a, S: state::IsComplete> NestedRenderPassTimestampWrites<'a>
    for RenderPassTimestampWritesBuilder<'a, S>
{
    fn unnest(self) -> wgpu_27::RenderPassTimestampWrites<'a> {
        self.build()
    }
}
