#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [RenderPipelineDescriptorBuilder] for building [`wgpu_27::RenderPipelineDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [layout](RenderPipelineDescriptorBuilder::layout) Required\n  - [vertex](RenderPipelineDescriptorBuilder::vertex) Required\n  - [primitive](RenderPipelineDescriptorBuilder::primitive) Optional, defaults to [wgpu_27::PrimitiveState::default()]\n  - [depth_stencil](RenderPipelineDescriptorBuilder::depth_stencil) Required\n  - [multisample](RenderPipelineDescriptorBuilder::multisample) Optional, defaults to [wgpu_27::MultisampleState::default()]\n  - [fragment](RenderPipelineDescriptorBuilder::fragment) Required\n  - [multiview](RenderPipelineDescriptorBuilder::multiview) Required\n  - [cache](RenderPipelineDescriptorBuilder::cache) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_27::RenderPipelineDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [layout](RenderPipelineDescriptorBuilder::layout) Required\n  - [vertex](RenderPipelineDescriptorBuilder::vertex) Required\n  - [primitive](RenderPipelineDescriptorBuilder::primitive) Optional, defaults to [wgpu_27::PrimitiveState::default()]\n  - [depth_stencil](RenderPipelineDescriptorBuilder::depth_stencil) Required\n  - [multisample](RenderPipelineDescriptorBuilder::multisample) Optional, defaults to [wgpu_27::MultisampleState::default()]\n  - [fragment](RenderPipelineDescriptorBuilder::fragment) Required\n  - [multiview](RenderPipelineDescriptorBuilder::multiview) Required\n  - [cache](RenderPipelineDescriptorBuilder::cache) Required\n"]
pub fn render_pipeline_descriptor<'a>(
    #[builder(start_fn)] label: wgpu_27::Label<'a>,
    layout: Option<&'a wgpu_27::PipelineLayout>,
    # [builder (with = | b : impl super :: vertex_state_builder :: NestedVertexState < 'a > | b . unnest () ,)]
    vertex: wgpu_27::VertexState<'a>,
    # [builder (with = | b : impl super :: primitive_state_builder :: NestedPrimitiveState | b . unnest () , default = wgpu_27 :: PrimitiveState :: default () ,)]
    primitive: wgpu_27::PrimitiveState,
    # [builder (with = | b : impl super :: depth_stencil_state_builder :: NestedDepthStencilState | b . unnest () ,)]
    depth_stencil: Option<wgpu_27::DepthStencilState>,
    # [builder (with = | b : impl super :: multisample_state_builder :: NestedMultisampleState | b . unnest () , default = wgpu_27 :: MultisampleState :: default () ,)]
    multisample: wgpu_27::MultisampleState,
    # [builder (with = | b : impl super :: fragment_state_builder :: NestedFragmentState < 'a > | b . unnest () ,)]
    fragment: Option<wgpu_27::FragmentState<'a>>,
    multiview: Option<NonZeroU32>,
    cache: Option<&'a wgpu_27::PipelineCache>,
) -> wgpu_27::RenderPipelineDescriptor<'a> {
    wgpu_27::RenderPipelineDescriptor {
        label,
        layout,
        vertex,
        primitive,
        depth_stencil,
        multisample,
        fragment,
        multiview,
        cache,
    }
}
impl<'a, S: state::IsComplete> RenderPipelineDescriptorBuilder<'a, S> {
    pub fn create_with(self, device: &wgpu_27::Device) -> wgpu_27::RenderPipeline {
        device.create_render_pipeline(&self.build())
    }
}
pub trait NestedRenderPipelineDescriptor<'a> {
    fn unnest(self) -> wgpu_27::RenderPipelineDescriptor<'a>;
}
impl<'a> NestedRenderPipelineDescriptor<'a> for wgpu_27::RenderPipelineDescriptor<'a> {
    fn unnest(self) -> wgpu_27::RenderPipelineDescriptor<'a> {
        self
    }
}
impl<'a, S: state::IsComplete> NestedRenderPipelineDescriptor<'a>
    for RenderPipelineDescriptorBuilder<'a, S>
{
    fn unnest(self) -> wgpu_27::RenderPipelineDescriptor<'a> {
        self.build()
    }
}
