#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [StencilStateBuilder] for building [`wgpu_27::StencilState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [front](StencilStateBuilder::front) Optional, defaults to [wgpu_27::StencilFaceState::IGNORE]\n  - [back](StencilStateBuilder::back) Optional, defaults to [wgpu_27::StencilFaceState::IGNORE]\n  - [read_mask](StencilStateBuilder::read_mask) Optional, defaults to `0u32`\n  - [write_mask](StencilStateBuilder::write_mask) Optional, defaults to `0u32`\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_27::StencilState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [front](StencilStateBuilder::front) Optional, defaults to [wgpu_27::StencilFaceState::IGNORE]\n  - [back](StencilStateBuilder::back) Optional, defaults to [wgpu_27::StencilFaceState::IGNORE]\n  - [read_mask](StencilStateBuilder::read_mask) Optional, defaults to `0u32`\n  - [write_mask](StencilStateBuilder::write_mask) Optional, defaults to `0u32`\n"]
pub fn stencil_state(
    # [builder (with = | b : impl super :: stencil_face_state_builder :: NestedStencilFaceState | b . unnest () , default = wgpu_27 :: StencilFaceState :: IGNORE ,)]
    front: wgpu_27::StencilFaceState,
    # [builder (with = | b : impl super :: stencil_face_state_builder :: NestedStencilFaceState | b . unnest () , default = wgpu_27 :: StencilFaceState :: IGNORE ,)]
    back: wgpu_27::StencilFaceState,
    #[builder(default = 0u32)] read_mask: u32,
    #[builder(default = 0u32)] write_mask: u32,
) -> wgpu_27::StencilState {
    wgpu_27::StencilState {
        front,
        back,
        read_mask,
        write_mask,
    }
}
pub trait NestedStencilState {
    fn unnest(self) -> wgpu_27::StencilState;
}
impl NestedStencilState for wgpu_27::StencilState {
    fn unnest(self) -> wgpu_27::StencilState {
        self
    }
}
impl<S: state::IsComplete> NestedStencilState for StencilStateBuilder<S> {
    fn unnest(self) -> wgpu_27::StencilState {
        self.build()
    }
}
