#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_27::SurfaceConfiguration`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [usage](SurfaceConfigurationBuilder::usage) Required\n  - [format](SurfaceConfigurationBuilder::format) Required\n  - [width](SurfaceConfigurationBuilder::width) Required\n  - [height](SurfaceConfigurationBuilder::height) Required\n  - [present_mode](SurfaceConfigurationBuilder::present_mode) Optional, defaults to [wgpu_27::PresentMode::Fifo]\n  - [desired_maximum_frame_latency](SurfaceConfigurationBuilder::desired_maximum_frame_latency) Required\n  - [alpha_mode](SurfaceConfigurationBuilder::alpha_mode) Optional, defaults to [wgpu_27::CompositeAlphaMode::Auto]\n  - [view_formats](SurfaceConfigurationBuilder::view_formats) Required\n"]
pub struct SurfaceConfigurationBuilder<CS: State> {
    usage: CS::Usage,
    format: CS::Format,
    width: CS::Width,
    height: CS::Height,
    present_mode: CS::PresentMode,
    desired_maximum_frame_latency: CS::DesiredMaximumFrameLatency,
    alpha_mode: CS::AlphaMode,
    view_formats: CS::ViewFormats,
}
impl SurfaceConfigurationBuilder<Empty> {
    pub fn new() -> SurfaceConfigurationBuilder<Empty> {
        SurfaceConfigurationBuilder {
            usage: UsageEmpty,
            format: FormatEmpty,
            width: WidthEmpty,
            height: HeightEmpty,
            present_mode: PresentModeEmpty,
            desired_maximum_frame_latency: DesiredMaximumFrameLatencyEmpty,
            alpha_mode: AlphaModeEmpty,
            view_formats: ViewFormatsEmpty,
        }
    }
}
#[doc = "\nReturns [SurfaceConfigurationBuilder] for building [`wgpu_27::SurfaceConfiguration`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [usage](SurfaceConfigurationBuilder::usage) Required\n  - [format](SurfaceConfigurationBuilder::format) Required\n  - [width](SurfaceConfigurationBuilder::width) Required\n  - [height](SurfaceConfigurationBuilder::height) Required\n  - [present_mode](SurfaceConfigurationBuilder::present_mode) Optional, defaults to [wgpu_27::PresentMode::Fifo]\n  - [desired_maximum_frame_latency](SurfaceConfigurationBuilder::desired_maximum_frame_latency) Required\n  - [alpha_mode](SurfaceConfigurationBuilder::alpha_mode) Optional, defaults to [wgpu_27::CompositeAlphaMode::Auto]\n  - [view_formats](SurfaceConfigurationBuilder::view_formats) Required\n"]
pub fn surface_configuration() -> SurfaceConfigurationBuilder<Empty> {
    SurfaceConfigurationBuilder::new()
}
pub struct UsageEmpty;
impl Field for UsageEmpty {}
pub trait UsageIsEmpty {}
impl UsageIsEmpty for UsageEmpty {}
pub trait IsSetUsage {
    fn get(self) -> wgpu_27::TextureUsages;
}
pub struct UsageValue(pub wgpu_27::TextureUsages);
impl Field for UsageValue {}
impl IsSetUsage for UsageValue {
    fn get(self) -> wgpu_27::TextureUsages {
        self.0
    }
}
pub struct FormatEmpty;
impl Field for FormatEmpty {}
pub trait FormatIsEmpty {}
impl FormatIsEmpty for FormatEmpty {}
pub trait IsSetFormat {
    fn get(self) -> wgpu_27::TextureFormat;
}
pub struct FormatValue(pub wgpu_27::TextureFormat);
impl Field for FormatValue {}
impl IsSetFormat for FormatValue {
    fn get(self) -> wgpu_27::TextureFormat {
        self.0
    }
}
pub struct WidthEmpty;
impl Field for WidthEmpty {}
pub trait WidthIsEmpty {}
impl WidthIsEmpty for WidthEmpty {}
pub trait IsSetWidth {
    fn get(self) -> u32;
}
pub struct WidthValue(pub u32);
impl Field for WidthValue {}
impl IsSetWidth for WidthValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub struct HeightEmpty;
impl Field for HeightEmpty {}
pub trait HeightIsEmpty {}
impl HeightIsEmpty for HeightEmpty {}
pub trait IsSetHeight {
    fn get(self) -> u32;
}
pub struct HeightValue(pub u32);
impl Field for HeightValue {}
impl IsSetHeight for HeightValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub struct PresentModeEmpty;
impl Field for PresentModeEmpty {}
pub trait PresentModeIsEmpty {}
impl PresentModeIsEmpty for PresentModeEmpty {}
pub trait IsSetPresentMode {
    fn get(self) -> wgpu_27::PresentMode;
}
impl IsSetPresentMode for PresentModeEmpty {
    fn get(self) -> wgpu_27::PresentMode {
        wgpu_27::PresentMode::Fifo
    }
}
pub struct PresentModeValue(pub wgpu_27::PresentMode);
impl Field for PresentModeValue {}
impl IsSetPresentMode for PresentModeValue {
    fn get(self) -> wgpu_27::PresentMode {
        self.0
    }
}
pub struct DesiredMaximumFrameLatencyEmpty;
impl Field for DesiredMaximumFrameLatencyEmpty {}
pub trait DesiredMaximumFrameLatencyIsEmpty {}
impl DesiredMaximumFrameLatencyIsEmpty for DesiredMaximumFrameLatencyEmpty {}
pub trait IsSetDesiredMaximumFrameLatency {
    fn get(self) -> u32;
}
pub struct DesiredMaximumFrameLatencyValue(pub u32);
impl Field for DesiredMaximumFrameLatencyValue {}
impl IsSetDesiredMaximumFrameLatency for DesiredMaximumFrameLatencyValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub struct AlphaModeEmpty;
impl Field for AlphaModeEmpty {}
pub trait AlphaModeIsEmpty {}
impl AlphaModeIsEmpty for AlphaModeEmpty {}
pub trait IsSetAlphaMode {
    fn get(self) -> wgpu_27::CompositeAlphaMode;
}
impl IsSetAlphaMode for AlphaModeEmpty {
    fn get(self) -> wgpu_27::CompositeAlphaMode {
        wgpu_27::CompositeAlphaMode::Auto
    }
}
pub struct AlphaModeValue(pub wgpu_27::CompositeAlphaMode);
impl Field for AlphaModeValue {}
impl IsSetAlphaMode for AlphaModeValue {
    fn get(self) -> wgpu_27::CompositeAlphaMode {
        self.0
    }
}
pub struct ViewFormatsEmpty;
impl Field for ViewFormatsEmpty {}
pub trait ViewFormatsIsEmpty {}
impl ViewFormatsIsEmpty for ViewFormatsEmpty {}
pub trait IsSetViewFormats {
    fn get(self) -> Vec<wgpu_27::TextureFormat>;
}
pub struct ViewFormatsValue(pub Vec<wgpu_27::TextureFormat>);
impl Field for ViewFormatsValue {}
impl IsSetViewFormats for ViewFormatsValue {
    fn get(self) -> Vec<wgpu_27::TextureFormat> {
        self.0
    }
}
pub trait State {
    type Usage: Field;
    type Format: Field;
    type Width: Field;
    type Height: Field;
    type PresentMode: Field;
    type DesiredMaximumFrameLatency: Field;
    type AlphaMode: Field;
    type ViewFormats: Field;
}
pub struct Empty;
impl State for Empty {
    type Usage = UsageEmpty;
    type Format = FormatEmpty;
    type Width = WidthEmpty;
    type Height = HeightEmpty;
    type PresentMode = PresentModeEmpty;
    type DesiredMaximumFrameLatency = DesiredMaximumFrameLatencyEmpty;
    type AlphaMode = AlphaModeEmpty;
    type ViewFormats = ViewFormatsEmpty;
}
pub struct SetUsage<CS>(CS);
impl<CS: State> State for SetUsage<CS> {
    type Usage = UsageValue;
    type Format = CS::Format;
    type Width = CS::Width;
    type Height = CS::Height;
    type PresentMode = CS::PresentMode;
    type DesiredMaximumFrameLatency = CS::DesiredMaximumFrameLatency;
    type AlphaMode = CS::AlphaMode;
    type ViewFormats = CS::ViewFormats;
}
pub struct SetFormat<CS>(CS);
impl<CS: State> State for SetFormat<CS> {
    type Usage = CS::Usage;
    type Format = FormatValue;
    type Width = CS::Width;
    type Height = CS::Height;
    type PresentMode = CS::PresentMode;
    type DesiredMaximumFrameLatency = CS::DesiredMaximumFrameLatency;
    type AlphaMode = CS::AlphaMode;
    type ViewFormats = CS::ViewFormats;
}
pub struct SetWidth<CS>(CS);
impl<CS: State> State for SetWidth<CS> {
    type Usage = CS::Usage;
    type Format = CS::Format;
    type Width = WidthValue;
    type Height = CS::Height;
    type PresentMode = CS::PresentMode;
    type DesiredMaximumFrameLatency = CS::DesiredMaximumFrameLatency;
    type AlphaMode = CS::AlphaMode;
    type ViewFormats = CS::ViewFormats;
}
pub struct SetHeight<CS>(CS);
impl<CS: State> State for SetHeight<CS> {
    type Usage = CS::Usage;
    type Format = CS::Format;
    type Width = CS::Width;
    type Height = HeightValue;
    type PresentMode = CS::PresentMode;
    type DesiredMaximumFrameLatency = CS::DesiredMaximumFrameLatency;
    type AlphaMode = CS::AlphaMode;
    type ViewFormats = CS::ViewFormats;
}
pub struct SetPresentMode<CS>(CS);
impl<CS: State> State for SetPresentMode<CS> {
    type Usage = CS::Usage;
    type Format = CS::Format;
    type Width = CS::Width;
    type Height = CS::Height;
    type PresentMode = PresentModeValue;
    type DesiredMaximumFrameLatency = CS::DesiredMaximumFrameLatency;
    type AlphaMode = CS::AlphaMode;
    type ViewFormats = CS::ViewFormats;
}
pub struct SetDesiredMaximumFrameLatency<CS>(CS);
impl<CS: State> State for SetDesiredMaximumFrameLatency<CS> {
    type Usage = CS::Usage;
    type Format = CS::Format;
    type Width = CS::Width;
    type Height = CS::Height;
    type PresentMode = CS::PresentMode;
    type DesiredMaximumFrameLatency = DesiredMaximumFrameLatencyValue;
    type AlphaMode = CS::AlphaMode;
    type ViewFormats = CS::ViewFormats;
}
pub struct SetAlphaMode<CS>(CS);
impl<CS: State> State for SetAlphaMode<CS> {
    type Usage = CS::Usage;
    type Format = CS::Format;
    type Width = CS::Width;
    type Height = CS::Height;
    type PresentMode = CS::PresentMode;
    type DesiredMaximumFrameLatency = CS::DesiredMaximumFrameLatency;
    type AlphaMode = AlphaModeValue;
    type ViewFormats = CS::ViewFormats;
}
pub struct SetViewFormats<CS>(CS);
impl<CS: State> State for SetViewFormats<CS> {
    type Usage = CS::Usage;
    type Format = CS::Format;
    type Width = CS::Width;
    type Height = CS::Height;
    type PresentMode = CS::PresentMode;
    type DesiredMaximumFrameLatency = CS::DesiredMaximumFrameLatency;
    type AlphaMode = CS::AlphaMode;
    type ViewFormats = ViewFormatsValue;
}
impl<CS: State> SurfaceConfigurationBuilder<CS> {
    #[doc = "Setter for [wgpu_27::SurfaceConfiguration::usage]. Required.\n"]
    pub fn usage(self, usage: wgpu_27::TextureUsages) -> SurfaceConfigurationBuilder<SetUsage<CS>>
    where
        CS::Usage: UsageIsEmpty,
    {
        SurfaceConfigurationBuilder {
            usage: UsageValue(usage),
            format: self.format,
            width: self.width,
            height: self.height,
            present_mode: self.present_mode,
            desired_maximum_frame_latency: self.desired_maximum_frame_latency,
            alpha_mode: self.alpha_mode,
            view_formats: self.view_formats,
        }
    }
    #[doc = "Setter for [wgpu_27::SurfaceConfiguration::format]. Required.\n"]
    pub fn format(
        self,
        format: wgpu_27::TextureFormat,
    ) -> SurfaceConfigurationBuilder<SetFormat<CS>>
    where
        CS::Format: FormatIsEmpty,
    {
        SurfaceConfigurationBuilder {
            usage: self.usage,
            format: FormatValue(format),
            width: self.width,
            height: self.height,
            present_mode: self.present_mode,
            desired_maximum_frame_latency: self.desired_maximum_frame_latency,
            alpha_mode: self.alpha_mode,
            view_formats: self.view_formats,
        }
    }
    #[doc = "Setter for [wgpu_27::SurfaceConfiguration::width]. Required.\n"]
    pub fn width(self, width: u32) -> SurfaceConfigurationBuilder<SetWidth<CS>>
    where
        CS::Width: WidthIsEmpty,
    {
        SurfaceConfigurationBuilder {
            usage: self.usage,
            format: self.format,
            width: WidthValue(width),
            height: self.height,
            present_mode: self.present_mode,
            desired_maximum_frame_latency: self.desired_maximum_frame_latency,
            alpha_mode: self.alpha_mode,
            view_formats: self.view_formats,
        }
    }
    #[doc = "Setter for [wgpu_27::SurfaceConfiguration::height]. Required.\n"]
    pub fn height(self, height: u32) -> SurfaceConfigurationBuilder<SetHeight<CS>>
    where
        CS::Height: HeightIsEmpty,
    {
        SurfaceConfigurationBuilder {
            usage: self.usage,
            format: self.format,
            width: self.width,
            height: HeightValue(height),
            present_mode: self.present_mode,
            desired_maximum_frame_latency: self.desired_maximum_frame_latency,
            alpha_mode: self.alpha_mode,
            view_formats: self.view_formats,
        }
    }
    #[doc = "Setter for [wgpu_27::SurfaceConfiguration::present_mode]. Optional, defaults to [wgpu_27::PresentMode::Fifo].\n"]
    pub fn present_mode(
        self,
        present_mode: wgpu_27::PresentMode,
    ) -> SurfaceConfigurationBuilder<SetPresentMode<CS>>
    where
        CS::PresentMode: PresentModeIsEmpty,
    {
        SurfaceConfigurationBuilder {
            usage: self.usage,
            format: self.format,
            width: self.width,
            height: self.height,
            present_mode: PresentModeValue(present_mode),
            desired_maximum_frame_latency: self.desired_maximum_frame_latency,
            alpha_mode: self.alpha_mode,
            view_formats: self.view_formats,
        }
    }
    #[doc = "Setter for [wgpu_27::SurfaceConfiguration::desired_maximum_frame_latency]. Required.\n"]
    pub fn desired_maximum_frame_latency(
        self,
        desired_maximum_frame_latency: u32,
    ) -> SurfaceConfigurationBuilder<SetDesiredMaximumFrameLatency<CS>>
    where
        CS::DesiredMaximumFrameLatency: DesiredMaximumFrameLatencyIsEmpty,
    {
        SurfaceConfigurationBuilder {
            usage: self.usage,
            format: self.format,
            width: self.width,
            height: self.height,
            present_mode: self.present_mode,
            desired_maximum_frame_latency: DesiredMaximumFrameLatencyValue(
                desired_maximum_frame_latency,
            ),
            alpha_mode: self.alpha_mode,
            view_formats: self.view_formats,
        }
    }
    #[doc = "Setter for [wgpu_27::SurfaceConfiguration::alpha_mode]. Optional, defaults to [wgpu_27::CompositeAlphaMode::Auto].\n"]
    pub fn alpha_mode(
        self,
        alpha_mode: wgpu_27::CompositeAlphaMode,
    ) -> SurfaceConfigurationBuilder<SetAlphaMode<CS>>
    where
        CS::AlphaMode: AlphaModeIsEmpty,
    {
        SurfaceConfigurationBuilder {
            usage: self.usage,
            format: self.format,
            width: self.width,
            height: self.height,
            present_mode: self.present_mode,
            desired_maximum_frame_latency: self.desired_maximum_frame_latency,
            alpha_mode: AlphaModeValue(alpha_mode),
            view_formats: self.view_formats,
        }
    }
    #[doc = "Setter for [wgpu_27::SurfaceConfiguration::view_formats]. Required.\n"]
    pub fn view_formats(
        self,
        view_formats: Vec<wgpu_27::TextureFormat>,
    ) -> SurfaceConfigurationBuilder<SetViewFormats<CS>>
    where
        CS::ViewFormats: ViewFormatsIsEmpty,
    {
        SurfaceConfigurationBuilder {
            usage: self.usage,
            format: self.format,
            width: self.width,
            height: self.height,
            present_mode: self.present_mode,
            desired_maximum_frame_latency: self.desired_maximum_frame_latency,
            alpha_mode: self.alpha_mode,
            view_formats: ViewFormatsValue(view_formats),
        }
    }
}
pub trait Complete:
    State<
    Usage: IsSetUsage,
    Format: IsSetFormat,
    Width: IsSetWidth,
    Height: IsSetHeight,
    PresentMode: IsSetPresentMode,
    DesiredMaximumFrameLatency: IsSetDesiredMaximumFrameLatency,
    AlphaMode: IsSetAlphaMode,
    ViewFormats: IsSetViewFormats,
>
{
}
impl<
        CS: State<
            Usage: IsSetUsage,
            Format: IsSetFormat,
            Width: IsSetWidth,
            Height: IsSetHeight,
            PresentMode: IsSetPresentMode,
            DesiredMaximumFrameLatency: IsSetDesiredMaximumFrameLatency,
            AlphaMode: IsSetAlphaMode,
            ViewFormats: IsSetViewFormats,
        >,
    > Complete for CS
{
}
impl<CS: Complete> SurfaceConfigurationBuilder<CS> {
    pub fn build(self) -> wgpu_27::SurfaceConfiguration {
        wgpu_27::SurfaceConfiguration {
            usage: IsSetUsage::get(self.usage),
            format: IsSetFormat::get(self.format),
            width: IsSetWidth::get(self.width),
            height: IsSetHeight::get(self.height),
            present_mode: IsSetPresentMode::get(self.present_mode),
            desired_maximum_frame_latency: IsSetDesiredMaximumFrameLatency::get(
                self.desired_maximum_frame_latency,
            ),
            alpha_mode: IsSetAlphaMode::get(self.alpha_mode),
            view_formats: IsSetViewFormats::get(self.view_formats),
        }
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!(
                "{:#?}",
                super::IsSetPresentMode::get(super::PresentModeEmpty)
            ),
            format!("{:#?}", wgpu_27::PresentMode::default()),
        );
        assert_eq!(
            format!("{:#?}", super::IsSetAlphaMode::get(super::AlphaModeEmpty)),
            format!("{:#?}", wgpu_27::CompositeAlphaMode::default()),
        );
    }
}
