#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [TaskStateBuilder] for building [`wgpu_27::TaskState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [module](TaskStateBuilder::module) Required\n  - [entry_point](TaskStateBuilder::entry_point) Required\n  - [compilation_options](TaskStateBuilder::compilation_options) Optional, defaults to [wgpu_27::PipelineCompilationOptions::default()]\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_27::TaskState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [module](TaskStateBuilder::module) Required\n  - [entry_point](TaskStateBuilder::entry_point) Required\n  - [compilation_options](TaskStateBuilder::compilation_options) Optional, defaults to [wgpu_27::PipelineCompilationOptions::default()]\n"]
pub fn task_state<'a>(
    module: &'a wgpu_27::ShaderModule,
    entry_point: Option<&'a str>,
    # [builder (with = | b : impl super :: pipeline_compilation_options_builder :: NestedPipelineCompilationOptions < 'a > | b . unnest () , default = wgpu_27 :: PipelineCompilationOptions :: default () ,)]
    compilation_options: wgpu_27::PipelineCompilationOptions<'a>,
) -> wgpu_27::TaskState<'a> {
    wgpu_27::TaskState {
        module,
        entry_point,
        compilation_options,
    }
}
pub trait NestedTaskState<'a> {
    fn unnest(self) -> wgpu_27::TaskState<'a>;
}
impl<'a> NestedTaskState<'a> for wgpu_27::TaskState<'a> {
    fn unnest(self) -> wgpu_27::TaskState<'a> {
        self
    }
}
impl<'a, S: state::IsComplete> NestedTaskState<'a> for TaskStateBuilder<'a, S> {
    fn unnest(self) -> wgpu_27::TaskState<'a> {
        self.build()
    }
}
