#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_27::TexelCopyBufferInfo`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [buffer](TexelCopyBufferInfoBuilder::buffer) Required\n  - [layout](TexelCopyBufferInfoBuilder::layout) Optional, defaults to [wgpu_27::TexelCopyBufferLayout::default()]\n"]
pub struct TexelCopyBufferInfoBuilder<'a, CS: State<'a>> {
    buffer: CS::Buffer,
    layout: CS::Layout,
}
impl<'a> TexelCopyBufferInfoBuilder<'a, Empty> {
    pub fn new() -> TexelCopyBufferInfoBuilder<'a, Empty> {
        TexelCopyBufferInfoBuilder {
            buffer: BufferEmpty,
            layout: LayoutEmpty,
        }
    }
}
#[doc = "\nReturns [TexelCopyBufferInfoBuilder] for building [`wgpu_27::TexelCopyBufferInfo`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [buffer](TexelCopyBufferInfoBuilder::buffer) Required\n  - [layout](TexelCopyBufferInfoBuilder::layout) Optional, defaults to [wgpu_27::TexelCopyBufferLayout::default()]\n"]
pub fn texel_copy_buffer_info<'a>() -> TexelCopyBufferInfoBuilder<'a, Empty> {
    TexelCopyBufferInfoBuilder::new()
}
pub struct BufferEmpty;
impl Field for BufferEmpty {}
pub trait BufferIsEmpty {}
impl BufferIsEmpty for BufferEmpty {}
pub trait IsSetBuffer<'a> {
    fn get(self) -> &'a wgpu_27::Buffer;
}
pub struct BufferValue<'a>(pub &'a wgpu_27::Buffer);
impl<'a> Field for BufferValue<'a> {}
impl<'a> IsSetBuffer<'a> for BufferValue<'a> {
    fn get(self) -> &'a wgpu_27::Buffer {
        self.0
    }
}
pub struct LayoutEmpty;
impl Field for LayoutEmpty {}
pub trait LayoutIsEmpty {}
impl LayoutIsEmpty for LayoutEmpty {}
pub trait IsSetLayout {
    fn get(self) -> wgpu_27::TexelCopyBufferLayout;
}
impl IsSetLayout for LayoutEmpty {
    fn get(self) -> wgpu_27::TexelCopyBufferLayout {
        wgpu_27::TexelCopyBufferLayout::default()
    }
}
pub struct LayoutValue(pub wgpu_27::TexelCopyBufferLayout);
impl Field for LayoutValue {}
impl IsSetLayout for LayoutValue {
    fn get(self) -> wgpu_27::TexelCopyBufferLayout {
        self.0
    }
}
pub trait State<'a> {
    type Buffer: Field;
    type Layout: Field;
}
pub struct Empty;
impl<'a> State<'a> for Empty {
    type Buffer = BufferEmpty;
    type Layout = LayoutEmpty;
}
pub struct SetBuffer<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetBuffer<CS> {
    type Buffer = BufferValue<'a>;
    type Layout = CS::Layout;
}
pub struct SetLayout<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetLayout<CS> {
    type Buffer = CS::Buffer;
    type Layout = LayoutValue;
}
impl<'a, CS: State<'a>> TexelCopyBufferInfoBuilder<'a, CS> {
    #[doc = "Setter for [wgpu_27::TexelCopyBufferInfo::buffer]. Required.\n"]
    pub fn buffer(
        self,
        buffer: &'a wgpu_27::Buffer,
    ) -> TexelCopyBufferInfoBuilder<'a, SetBuffer<CS>>
    where
        CS::Buffer: BufferIsEmpty,
    {
        TexelCopyBufferInfoBuilder {
            buffer: BufferValue(buffer),
            layout: self.layout,
        }
    }
    #[doc = "Setter for [wgpu_27::TexelCopyBufferInfo::layout]. Optional, defaults to [wgpu_27::TexelCopyBufferLayout::default()].\n"]
    pub fn layout(
        self,
        layout: impl Nested<wgpu_27::TexelCopyBufferLayout>,
    ) -> TexelCopyBufferInfoBuilder<'a, SetLayout<CS>>
    where
        CS::Layout: LayoutIsEmpty,
    {
        TexelCopyBufferInfoBuilder {
            buffer: self.buffer,
            layout: LayoutValue(Nested::unnest(layout)),
        }
    }
}
pub trait Complete<'a>: State<'a, Buffer: IsSetBuffer<'a>, Layout: IsSetLayout> {}
impl<'a, CS: State<'a, Buffer: IsSetBuffer<'a>, Layout: IsSetLayout>> Complete<'a> for CS {}
impl<'a, CS: Complete<'a>> TexelCopyBufferInfoBuilder<'a, CS> {
    pub fn build(self) -> wgpu_27::TexelCopyBufferInfo<'a> {
        wgpu_27::TexelCopyBufferInfo {
            buffer: IsSetBuffer::get(self.buffer),
            layout: IsSetLayout::get(self.layout),
        }
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::IsSetLayout::get(super::LayoutEmpty)),
            format!("{:#?}", wgpu_27::TexelCopyBufferLayout::default()),
        );
    }
}
