#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_27::VertexState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [module](VertexStateBuilder::module) Required\n  - [entry_point](VertexStateBuilder::entry_point) Optional, defaults to `None`\n  - [compilation_options](VertexStateBuilder::compilation_options) Optional, defaults to [wgpu_27::PipelineCompilationOptions::default()]\n  - [buffers](VertexStateBuilder::buffers) Required\n"]
pub struct VertexStateBuilder<'a, CS: State<'a>> {
    module: CS::Module,
    entry_point: CS::EntryPoint,
    compilation_options: CS::CompilationOptions,
    buffers: CS::Buffers,
}
impl<'a> VertexStateBuilder<'a, Empty> {
    pub fn new() -> VertexStateBuilder<'a, Empty> {
        VertexStateBuilder {
            module: ModuleEmpty,
            entry_point: EntryPointEmpty,
            compilation_options: CompilationOptionsEmpty,
            buffers: BuffersEmpty,
        }
    }
}
#[doc = "\nReturns [VertexStateBuilder] for building [`wgpu_27::VertexState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [module](VertexStateBuilder::module) Required\n  - [entry_point](VertexStateBuilder::entry_point) Optional, defaults to `None`\n  - [compilation_options](VertexStateBuilder::compilation_options) Optional, defaults to [wgpu_27::PipelineCompilationOptions::default()]\n  - [buffers](VertexStateBuilder::buffers) Required\n"]
pub fn vertex_state<'a>() -> VertexStateBuilder<'a, Empty> {
    VertexStateBuilder::new()
}
pub struct ModuleEmpty;
impl Field for ModuleEmpty {}
pub trait ModuleIsEmpty {}
impl ModuleIsEmpty for ModuleEmpty {}
pub trait IsSetModule<'a> {
    fn get(self) -> &'a wgpu_27::ShaderModule;
}
pub struct ModuleValue<'a>(pub &'a wgpu_27::ShaderModule);
impl<'a> Field for ModuleValue<'a> {}
impl<'a> IsSetModule<'a> for ModuleValue<'a> {
    fn get(self) -> &'a wgpu_27::ShaderModule {
        self.0
    }
}
pub struct EntryPointEmpty;
impl Field for EntryPointEmpty {}
pub trait EntryPointIsEmpty {}
impl EntryPointIsEmpty for EntryPointEmpty {}
pub trait IsSetEntryPoint<'a> {
    fn get(self) -> Option<&'a str>;
}
impl<'a> IsSetEntryPoint<'a> for EntryPointEmpty {
    fn get(self) -> Option<&'a str> {
        None
    }
}
pub struct EntryPointValue<'a>(pub Option<&'a str>);
impl<'a> Field for EntryPointValue<'a> {}
impl<'a> IsSetEntryPoint<'a> for EntryPointValue<'a> {
    fn get(self) -> Option<&'a str> {
        self.0
    }
}
pub struct CompilationOptionsEmpty;
impl Field for CompilationOptionsEmpty {}
pub trait CompilationOptionsIsEmpty {}
impl CompilationOptionsIsEmpty for CompilationOptionsEmpty {}
pub trait IsSetCompilationOptions<'a> {
    fn get(self) -> wgpu_27::PipelineCompilationOptions<'a>;
}
impl<'a> IsSetCompilationOptions<'a> for CompilationOptionsEmpty {
    fn get(self) -> wgpu_27::PipelineCompilationOptions<'a> {
        wgpu_27::PipelineCompilationOptions::default()
    }
}
pub struct CompilationOptionsValue<'a>(pub wgpu_27::PipelineCompilationOptions<'a>);
impl<'a> Field for CompilationOptionsValue<'a> {}
impl<'a> IsSetCompilationOptions<'a> for CompilationOptionsValue<'a> {
    fn get(self) -> wgpu_27::PipelineCompilationOptions<'a> {
        self.0
    }
}
pub struct BuffersEmpty;
impl Field for BuffersEmpty {}
pub trait BuffersIsEmpty {}
impl BuffersIsEmpty for BuffersEmpty {}
pub trait IsSetBuffers<'a> {
    fn get(self) -> &'a [wgpu_27::VertexBufferLayout<'a>];
}
pub struct BuffersValue<'a>(pub &'a [wgpu_27::VertexBufferLayout<'a>]);
impl<'a> Field for BuffersValue<'a> {}
impl<'a> IsSetBuffers<'a> for BuffersValue<'a> {
    fn get(self) -> &'a [wgpu_27::VertexBufferLayout<'a>] {
        self.0
    }
}
pub trait State<'a> {
    type Module: Field;
    type EntryPoint: Field;
    type CompilationOptions: Field;
    type Buffers: Field;
}
pub struct Empty;
impl<'a> State<'a> for Empty {
    type Module = ModuleEmpty;
    type EntryPoint = EntryPointEmpty;
    type CompilationOptions = CompilationOptionsEmpty;
    type Buffers = BuffersEmpty;
}
pub struct SetModule<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetModule<CS> {
    type Module = ModuleValue<'a>;
    type EntryPoint = CS::EntryPoint;
    type CompilationOptions = CS::CompilationOptions;
    type Buffers = CS::Buffers;
}
pub struct SetEntryPoint<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetEntryPoint<CS> {
    type Module = CS::Module;
    type EntryPoint = EntryPointValue<'a>;
    type CompilationOptions = CS::CompilationOptions;
    type Buffers = CS::Buffers;
}
pub struct SetCompilationOptions<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetCompilationOptions<CS> {
    type Module = CS::Module;
    type EntryPoint = CS::EntryPoint;
    type CompilationOptions = CompilationOptionsValue<'a>;
    type Buffers = CS::Buffers;
}
pub struct SetBuffers<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetBuffers<CS> {
    type Module = CS::Module;
    type EntryPoint = CS::EntryPoint;
    type CompilationOptions = CS::CompilationOptions;
    type Buffers = BuffersValue<'a>;
}
impl<'a, CS: State<'a>> VertexStateBuilder<'a, CS> {
    #[doc = "Setter for [wgpu_27::VertexState::module]. Required.\n"]
    pub fn module(self, module: &'a wgpu_27::ShaderModule) -> VertexStateBuilder<'a, SetModule<CS>>
    where
        CS::Module: ModuleIsEmpty,
    {
        VertexStateBuilder {
            module: ModuleValue(module),
            entry_point: self.entry_point,
            compilation_options: self.compilation_options,
            buffers: self.buffers,
        }
    }
    #[doc = "Setter for [wgpu_27::VertexState::entry_point]. Optional, defaults to `None`.\n"]
    pub fn entry_point(self, entry_point: &'a str) -> VertexStateBuilder<'a, SetEntryPoint<CS>>
    where
        CS::EntryPoint: EntryPointIsEmpty,
    {
        VertexStateBuilder {
            module: self.module,
            entry_point: EntryPointValue(Some(entry_point)),
            compilation_options: self.compilation_options,
            buffers: self.buffers,
        }
    }
    #[doc = "Setter for [wgpu_27::VertexState::entry_point]. Optional, defaults to `None`.\n"]
    pub fn maybe_entry_point(
        self,
        entry_point: Option<&'a str>,
    ) -> VertexStateBuilder<'a, SetEntryPoint<CS>>
    where
        CS::EntryPoint: EntryPointIsEmpty,
    {
        VertexStateBuilder {
            module: self.module,
            entry_point: EntryPointValue(entry_point),
            compilation_options: self.compilation_options,
            buffers: self.buffers,
        }
    }
    #[doc = "Setter for [wgpu_27::VertexState::compilation_options]. Optional, defaults to [wgpu_27::PipelineCompilationOptions::default()].\n"]
    pub fn compilation_options(
        self,
        compilation_options: impl Nested<wgpu_27::PipelineCompilationOptions<'a>>,
    ) -> VertexStateBuilder<'a, SetCompilationOptions<CS>>
    where
        CS::CompilationOptions: CompilationOptionsIsEmpty,
    {
        VertexStateBuilder {
            module: self.module,
            entry_point: self.entry_point,
            compilation_options: CompilationOptionsValue(Nested::unnest(compilation_options)),
            buffers: self.buffers,
        }
    }
    #[doc = "Setter for [wgpu_27::VertexState::buffers]. Required.\n"]
    pub fn buffers(
        self,
        buffers: &'a [wgpu_27::VertexBufferLayout<'a>],
    ) -> VertexStateBuilder<'a, SetBuffers<CS>>
    where
        CS::Buffers: BuffersIsEmpty,
    {
        VertexStateBuilder {
            module: self.module,
            entry_point: self.entry_point,
            compilation_options: self.compilation_options,
            buffers: BuffersValue(buffers),
        }
    }
}
pub trait Complete<'a>:
    State<
    'a,
    Module: IsSetModule<'a>,
    EntryPoint: IsSetEntryPoint<'a>,
    CompilationOptions: IsSetCompilationOptions<'a>,
    Buffers: IsSetBuffers<'a>,
>
{
}
impl<
        'a,
        CS: State<
            'a,
            Module: IsSetModule<'a>,
            EntryPoint: IsSetEntryPoint<'a>,
            CompilationOptions: IsSetCompilationOptions<'a>,
            Buffers: IsSetBuffers<'a>,
        >,
    > Complete<'a> for CS
{
}
impl<'a, CS: Complete<'a>> VertexStateBuilder<'a, CS> {
    pub fn build(self) -> wgpu_27::VertexState<'a> {
        wgpu_27::VertexState {
            module: IsSetModule::get(self.module),
            entry_point: IsSetEntryPoint::get(self.entry_point),
            compilation_options: IsSetCompilationOptions::get(self.compilation_options),
            buffers: IsSetBuffers::get(self.buffers),
        }
    }
}
impl<'a> Nested<wgpu_27::VertexState<'a>> for wgpu_27::VertexState<'a> {
    fn unnest(self) -> wgpu_27::VertexState<'a> {
        self
    }
}
impl<'a, CS: Complete<'a>> Nested<wgpu_27::VertexState<'a>> for VertexStateBuilder<'a, CS> {
    fn unnest(self) -> wgpu_27::VertexState<'a> {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::IsSetEntryPoint::get(super::EntryPointEmpty)),
            format!("{:#?}", Option::<&str>::default()),
        );
        assert_eq!(
            format!(
                "{:#?}",
                super::IsSetCompilationOptions::get(super::CompilationOptionsEmpty)
            ),
            format!("{:#?}", wgpu_27::PipelineCompilationOptions::default()),
        );
    }
}
