#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [VertexStateBuilder] for building [`wgpu_27::VertexState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [module](VertexStateBuilder::module) Required\n  - [entry_point](VertexStateBuilder::entry_point) Required\n  - [compilation_options](VertexStateBuilder::compilation_options) Optional, defaults to [wgpu_27::PipelineCompilationOptions::default()]\n  - [buffers](VertexStateBuilder::buffers) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_27::VertexState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [module](VertexStateBuilder::module) Required\n  - [entry_point](VertexStateBuilder::entry_point) Required\n  - [compilation_options](VertexStateBuilder::compilation_options) Optional, defaults to [wgpu_27::PipelineCompilationOptions::default()]\n  - [buffers](VertexStateBuilder::buffers) Required\n"]
pub fn vertex_state<'a>(
    module: &'a wgpu_27::ShaderModule,
    entry_point: Option<&'a str>,
    # [builder (with = | b : impl super :: pipeline_compilation_options_builder :: NestedPipelineCompilationOptions < 'a > | b . unnest () , default = wgpu_27 :: PipelineCompilationOptions :: default () ,)]
    compilation_options: wgpu_27::PipelineCompilationOptions<'a>,
    buffers: &'a [wgpu_27::VertexBufferLayout<'a>],
) -> wgpu_27::VertexState<'a> {
    wgpu_27::VertexState {
        module,
        entry_point,
        compilation_options,
        buffers,
    }
}
pub trait NestedVertexState<'a> {
    fn unnest(self) -> wgpu_27::VertexState<'a>;
}
impl<'a> NestedVertexState<'a> for wgpu_27::VertexState<'a> {
    fn unnest(self) -> wgpu_27::VertexState<'a> {
        self
    }
}
impl<'a, S: state::IsComplete> NestedVertexState<'a> for VertexStateBuilder<'a, S> {
    fn unnest(self) -> wgpu_27::VertexState<'a> {
        self.build()
    }
}
