
[package]
name = "quickgpu"
version = "0.0.9"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "quickgpu wraps the wgpu API allowing users to write shorter, clearer code"
repository = "https://github.com/k9/quickgpu"
homepage = "https://github.com/k9/quickgpu"
documentation = "https://docs.rs/quickgpu"
readme = "../README.md"

[features]
w27 = ["dep:wgpu_27"]
w28 = ["dep:wgpu_28"]

[dependencies]
wgpu_27 = { package = "wgpu", version = "^27.0.0", optional = true }
wgpu_28 = { package = "wgpu", version = "^28.0.0", optional = true }

[dev-dependencies]
bytemuck = { workspace = true }
wgpu_27 = { package = "wgpu", version = "^27.0.0", features = ["noop"] }
wgpu_28 = { package = "wgpu", version = "^28.0.0", features = ["noop"] }
