// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_27::CommandEncoderDescriptor`]\n        "]
pub struct CommandEncoderDescriptorBuilder<'a, CS: State<'a>> {
    label: CS::Label,
}
impl<'a> CommandEncoderDescriptorBuilder<'a, Empty> {
    pub fn new() -> CommandEncoderDescriptorBuilder<'a, Empty> {
        CommandEncoderDescriptorBuilder { label: LabelEmpty }
    }
}
#[doc = "\nReturns [CommandEncoderDescriptorBuilder] for building [`wgpu_27::CommandEncoderDescriptor`]\n        "]
pub fn command_encoder_descriptor<'a>(
    label: wgpu_27::Label<'a>,
) -> CommandEncoderDescriptorBuilder<'a, SetLabel<Empty>> {
    CommandEncoderDescriptorBuilder::new().label(label)
}
pub struct LabelEmpty;
impl Field for LabelEmpty {}
pub trait LabelIsEmpty {}
impl LabelIsEmpty for LabelEmpty {}
pub trait IsSetLabel<'a> {
    fn get(self) -> wgpu_27::Label<'a>;
}
impl<'a> IsSetLabel<'a> for LabelEmpty {
    fn get(self) -> wgpu_27::Label<'a> {
        None
    }
}
pub struct LabelValue<'a>(pub wgpu_27::Label<'a>);
impl<'a> Field for LabelValue<'a> {}
impl<'a> IsSetLabel<'a> for LabelValue<'a> {
    fn get(self) -> wgpu_27::Label<'a> {
        self.0
    }
}
pub trait State<'a> {
    type Label: Field;
}
pub struct Empty;
impl<'a> State<'a> for Empty {
    type Label = LabelEmpty;
}
pub struct SetLabel<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetLabel<CS> {
    type Label = LabelValue<'a>;
}
impl<'a, CS: State<'a>> CommandEncoderDescriptorBuilder<'a, CS> {
    #[doc = "Setter for [wgpu_27::CommandEncoderDescriptor::label]. Optional, defaults to `None`.\n"]
    pub fn label(
        self,
        label: wgpu_27::Label<'a>,
    ) -> CommandEncoderDescriptorBuilder<'a, SetLabel<CS>>
    where
        CS::Label: LabelIsEmpty,
    {
        CommandEncoderDescriptorBuilder {
            label: LabelValue(label),
        }
    }
}
pub trait Complete<'a>: State<'a, Label: IsSetLabel<'a>> {}
impl<'a, CS: State<'a, Label: IsSetLabel<'a>>> Complete<'a> for CS {}
impl<'a, CS: Complete<'a>> CommandEncoderDescriptorBuilder<'a, CS> {
    pub fn build(self) -> wgpu_27::CommandEncoderDescriptor<'a> {
        wgpu_27::CommandEncoderDescriptor {
            label: IsSetLabel::get(self.label),
        }
    }
    pub fn create_with(self, device: &wgpu_27::Device) -> wgpu_27::CommandEncoder {
        device.create_command_encoder(&self.build())
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!(
                "{:#?}",
                super::command_encoder_descriptor(Option::<&str>::None).build()
            ),
            format!("{:#?}", wgpu_27::CommandEncoderDescriptor::default()),
        );
    }
}
