// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_27::ComputePipelineDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [layout](ComputePipelineDescriptorBuilder::layout) Optional, defaults to `None`\n  - [module](ComputePipelineDescriptorBuilder::module) Required\n  - [entry_point](ComputePipelineDescriptorBuilder::entry_point) Optional, defaults to `None`\n  - [compilation_options](ComputePipelineDescriptorBuilder::compilation_options) Optional, defaults to [wgpu_27::PipelineCompilationOptions::default()]\n  - [cache](ComputePipelineDescriptorBuilder::cache) Optional, defaults to `None`\n"]
pub struct ComputePipelineDescriptorBuilder<'a, CS: State<'a>> {
    label: CS::Label,
    layout: CS::Layout,
    module: CS::Module,
    entry_point: CS::EntryPoint,
    compilation_options: CS::CompilationOptions,
    cache: CS::Cache,
}
impl<'a> ComputePipelineDescriptorBuilder<'a, Empty> {
    pub fn new() -> ComputePipelineDescriptorBuilder<'a, Empty> {
        ComputePipelineDescriptorBuilder {
            label: LabelEmpty,
            layout: LayoutEmpty,
            module: ModuleEmpty,
            entry_point: EntryPointEmpty,
            compilation_options: CompilationOptionsEmpty,
            cache: CacheEmpty,
        }
    }
}
#[doc = "\nReturns [ComputePipelineDescriptorBuilder] for building [`wgpu_27::ComputePipelineDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [layout](ComputePipelineDescriptorBuilder::layout) Optional, defaults to `None`\n  - [module](ComputePipelineDescriptorBuilder::module) Required\n  - [entry_point](ComputePipelineDescriptorBuilder::entry_point) Optional, defaults to `None`\n  - [compilation_options](ComputePipelineDescriptorBuilder::compilation_options) Optional, defaults to [wgpu_27::PipelineCompilationOptions::default()]\n  - [cache](ComputePipelineDescriptorBuilder::cache) Optional, defaults to `None`\n"]
pub fn compute_pipeline_descriptor<'a>(
    label: wgpu_27::Label<'a>,
) -> ComputePipelineDescriptorBuilder<'a, SetLabel<Empty>> {
    ComputePipelineDescriptorBuilder::new().label(label)
}
pub struct LabelEmpty;
impl Field for LabelEmpty {}
pub trait LabelIsEmpty {}
impl LabelIsEmpty for LabelEmpty {}
pub trait IsSetLabel<'a> {
    fn get(self) -> wgpu_27::Label<'a>;
}
impl<'a> IsSetLabel<'a> for LabelEmpty {
    fn get(self) -> wgpu_27::Label<'a> {
        None
    }
}
pub struct LabelValue<'a>(pub wgpu_27::Label<'a>);
impl<'a> Field for LabelValue<'a> {}
impl<'a> IsSetLabel<'a> for LabelValue<'a> {
    fn get(self) -> wgpu_27::Label<'a> {
        self.0
    }
}
pub struct LayoutEmpty;
impl Field for LayoutEmpty {}
pub trait LayoutIsEmpty {}
impl LayoutIsEmpty for LayoutEmpty {}
pub trait IsSetLayout<'a> {
    fn get(self) -> Option<&'a wgpu_27::PipelineLayout>;
}
impl<'a> IsSetLayout<'a> for LayoutEmpty {
    fn get(self) -> Option<&'a wgpu_27::PipelineLayout> {
        None
    }
}
pub struct LayoutValue<'a>(pub Option<&'a wgpu_27::PipelineLayout>);
impl<'a> Field for LayoutValue<'a> {}
impl<'a> IsSetLayout<'a> for LayoutValue<'a> {
    fn get(self) -> Option<&'a wgpu_27::PipelineLayout> {
        self.0
    }
}
pub struct ModuleEmpty;
impl Field for ModuleEmpty {}
pub trait ModuleIsEmpty {}
impl ModuleIsEmpty for ModuleEmpty {}
pub trait IsSetModule<'a> {
    fn get(self) -> &'a wgpu_27::ShaderModule;
}
pub struct ModuleValue<'a>(pub &'a wgpu_27::ShaderModule);
impl<'a> Field for ModuleValue<'a> {}
impl<'a> IsSetModule<'a> for ModuleValue<'a> {
    fn get(self) -> &'a wgpu_27::ShaderModule {
        self.0
    }
}
pub struct EntryPointEmpty;
impl Field for EntryPointEmpty {}
pub trait EntryPointIsEmpty {}
impl EntryPointIsEmpty for EntryPointEmpty {}
pub trait IsSetEntryPoint<'a> {
    fn get(self) -> Option<&'a str>;
}
impl<'a> IsSetEntryPoint<'a> for EntryPointEmpty {
    fn get(self) -> Option<&'a str> {
        None
    }
}
pub struct EntryPointValue<'a>(pub Option<&'a str>);
impl<'a> Field for EntryPointValue<'a> {}
impl<'a> IsSetEntryPoint<'a> for EntryPointValue<'a> {
    fn get(self) -> Option<&'a str> {
        self.0
    }
}
pub struct CompilationOptionsEmpty;
impl Field for CompilationOptionsEmpty {}
pub trait CompilationOptionsIsEmpty {}
impl CompilationOptionsIsEmpty for CompilationOptionsEmpty {}
pub trait IsSetCompilationOptions<'a> {
    fn get(self) -> wgpu_27::PipelineCompilationOptions<'a>;
}
impl<'a> IsSetCompilationOptions<'a> for CompilationOptionsEmpty {
    fn get(self) -> wgpu_27::PipelineCompilationOptions<'a> {
        wgpu_27::PipelineCompilationOptions::default()
    }
}
pub struct CompilationOptionsValue<'a>(pub wgpu_27::PipelineCompilationOptions<'a>);
impl<'a> Field for CompilationOptionsValue<'a> {}
impl<'a> IsSetCompilationOptions<'a> for CompilationOptionsValue<'a> {
    fn get(self) -> wgpu_27::PipelineCompilationOptions<'a> {
        self.0
    }
}
pub struct CacheEmpty;
impl Field for CacheEmpty {}
pub trait CacheIsEmpty {}
impl CacheIsEmpty for CacheEmpty {}
pub trait IsSetCache<'a> {
    fn get(self) -> Option<&'a wgpu_27::PipelineCache>;
}
impl<'a> IsSetCache<'a> for CacheEmpty {
    fn get(self) -> Option<&'a wgpu_27::PipelineCache> {
        None
    }
}
pub struct CacheValue<'a>(pub Option<&'a wgpu_27::PipelineCache>);
impl<'a> Field for CacheValue<'a> {}
impl<'a> IsSetCache<'a> for CacheValue<'a> {
    fn get(self) -> Option<&'a wgpu_27::PipelineCache> {
        self.0
    }
}
pub trait State<'a> {
    type Label: Field;
    type Layout: Field;
    type Module: Field;
    type EntryPoint: Field;
    type CompilationOptions: Field;
    type Cache: Field;
}
pub struct Empty;
impl<'a> State<'a> for Empty {
    type Label = LabelEmpty;
    type Layout = LayoutEmpty;
    type Module = ModuleEmpty;
    type EntryPoint = EntryPointEmpty;
    type CompilationOptions = CompilationOptionsEmpty;
    type Cache = CacheEmpty;
}
pub struct SetLabel<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetLabel<CS> {
    type Label = LabelValue<'a>;
    type Layout = CS::Layout;
    type Module = CS::Module;
    type EntryPoint = CS::EntryPoint;
    type CompilationOptions = CS::CompilationOptions;
    type Cache = CS::Cache;
}
pub struct SetLayout<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetLayout<CS> {
    type Label = CS::Label;
    type Layout = LayoutValue<'a>;
    type Module = CS::Module;
    type EntryPoint = CS::EntryPoint;
    type CompilationOptions = CS::CompilationOptions;
    type Cache = CS::Cache;
}
pub struct SetModule<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetModule<CS> {
    type Label = CS::Label;
    type Layout = CS::Layout;
    type Module = ModuleValue<'a>;
    type EntryPoint = CS::EntryPoint;
    type CompilationOptions = CS::CompilationOptions;
    type Cache = CS::Cache;
}
pub struct SetEntryPoint<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetEntryPoint<CS> {
    type Label = CS::Label;
    type Layout = CS::Layout;
    type Module = CS::Module;
    type EntryPoint = EntryPointValue<'a>;
    type CompilationOptions = CS::CompilationOptions;
    type Cache = CS::Cache;
}
pub struct SetCompilationOptions<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetCompilationOptions<CS> {
    type Label = CS::Label;
    type Layout = CS::Layout;
    type Module = CS::Module;
    type EntryPoint = CS::EntryPoint;
    type CompilationOptions = CompilationOptionsValue<'a>;
    type Cache = CS::Cache;
}
pub struct SetCache<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetCache<CS> {
    type Label = CS::Label;
    type Layout = CS::Layout;
    type Module = CS::Module;
    type EntryPoint = CS::EntryPoint;
    type CompilationOptions = CS::CompilationOptions;
    type Cache = CacheValue<'a>;
}
impl<'a, CS: State<'a>> ComputePipelineDescriptorBuilder<'a, CS> {
    #[doc = "Setter for [wgpu_27::ComputePipelineDescriptor::label]. Optional, defaults to `None`.\n"]
    pub fn label(
        self,
        label: wgpu_27::Label<'a>,
    ) -> ComputePipelineDescriptorBuilder<'a, SetLabel<CS>>
    where
        CS::Label: LabelIsEmpty,
    {
        ComputePipelineDescriptorBuilder {
            label: LabelValue(label),
            layout: self.layout,
            module: self.module,
            entry_point: self.entry_point,
            compilation_options: self.compilation_options,
            cache: self.cache,
        }
    }
    #[doc = "Setter for [wgpu_27::ComputePipelineDescriptor::layout]. Optional, defaults to `None`.\n"]
    pub fn layout(
        self,
        layout: &'a wgpu_27::PipelineLayout,
    ) -> ComputePipelineDescriptorBuilder<'a, SetLayout<CS>>
    where
        CS::Layout: LayoutIsEmpty,
    {
        ComputePipelineDescriptorBuilder {
            label: self.label,
            layout: LayoutValue(Some(layout)),
            module: self.module,
            entry_point: self.entry_point,
            compilation_options: self.compilation_options,
            cache: self.cache,
        }
    }
    #[doc = "Setter for [wgpu_27::ComputePipelineDescriptor::layout]. Optional, defaults to `None`.\n"]
    pub fn maybe_layout(
        self,
        layout: Option<&'a wgpu_27::PipelineLayout>,
    ) -> ComputePipelineDescriptorBuilder<'a, SetLayout<CS>>
    where
        CS::Layout: LayoutIsEmpty,
    {
        ComputePipelineDescriptorBuilder {
            label: self.label,
            layout: LayoutValue(layout),
            module: self.module,
            entry_point: self.entry_point,
            compilation_options: self.compilation_options,
            cache: self.cache,
        }
    }
    #[doc = "Setter for [wgpu_27::ComputePipelineDescriptor::module]. Required.\n"]
    pub fn module(
        self,
        module: &'a wgpu_27::ShaderModule,
    ) -> ComputePipelineDescriptorBuilder<'a, SetModule<CS>>
    where
        CS::Module: ModuleIsEmpty,
    {
        ComputePipelineDescriptorBuilder {
            label: self.label,
            layout: self.layout,
            module: ModuleValue(module),
            entry_point: self.entry_point,
            compilation_options: self.compilation_options,
            cache: self.cache,
        }
    }
    #[doc = "Setter for [wgpu_27::ComputePipelineDescriptor::entry_point]. Optional, defaults to `None`.\n"]
    pub fn entry_point(
        self,
        entry_point: &'a str,
    ) -> ComputePipelineDescriptorBuilder<'a, SetEntryPoint<CS>>
    where
        CS::EntryPoint: EntryPointIsEmpty,
    {
        ComputePipelineDescriptorBuilder {
            label: self.label,
            layout: self.layout,
            module: self.module,
            entry_point: EntryPointValue(Some(entry_point)),
            compilation_options: self.compilation_options,
            cache: self.cache,
        }
    }
    #[doc = "Setter for [wgpu_27::ComputePipelineDescriptor::entry_point]. Optional, defaults to `None`.\n"]
    pub fn maybe_entry_point(
        self,
        entry_point: Option<&'a str>,
    ) -> ComputePipelineDescriptorBuilder<'a, SetEntryPoint<CS>>
    where
        CS::EntryPoint: EntryPointIsEmpty,
    {
        ComputePipelineDescriptorBuilder {
            label: self.label,
            layout: self.layout,
            module: self.module,
            entry_point: EntryPointValue(entry_point),
            compilation_options: self.compilation_options,
            cache: self.cache,
        }
    }
    #[doc = "Setter for [wgpu_27::ComputePipelineDescriptor::compilation_options]. Optional, defaults to [wgpu_27::PipelineCompilationOptions::default()].\n"]
    pub fn compilation_options(
        self,
        compilation_options: impl Nested<wgpu_27::PipelineCompilationOptions<'a>>,
    ) -> ComputePipelineDescriptorBuilder<'a, SetCompilationOptions<CS>>
    where
        CS::CompilationOptions: CompilationOptionsIsEmpty,
    {
        ComputePipelineDescriptorBuilder {
            label: self.label,
            layout: self.layout,
            module: self.module,
            entry_point: self.entry_point,
            compilation_options: CompilationOptionsValue(Nested::unnest(compilation_options)),
            cache: self.cache,
        }
    }
    #[doc = "Setter for [wgpu_27::ComputePipelineDescriptor::cache]. Optional, defaults to `None`.\n"]
    pub fn cache(
        self,
        cache: &'a wgpu_27::PipelineCache,
    ) -> ComputePipelineDescriptorBuilder<'a, SetCache<CS>>
    where
        CS::Cache: CacheIsEmpty,
    {
        ComputePipelineDescriptorBuilder {
            label: self.label,
            layout: self.layout,
            module: self.module,
            entry_point: self.entry_point,
            compilation_options: self.compilation_options,
            cache: CacheValue(Some(cache)),
        }
    }
    #[doc = "Setter for [wgpu_27::ComputePipelineDescriptor::cache]. Optional, defaults to `None`.\n"]
    pub fn maybe_cache(
        self,
        cache: Option<&'a wgpu_27::PipelineCache>,
    ) -> ComputePipelineDescriptorBuilder<'a, SetCache<CS>>
    where
        CS::Cache: CacheIsEmpty,
    {
        ComputePipelineDescriptorBuilder {
            label: self.label,
            layout: self.layout,
            module: self.module,
            entry_point: self.entry_point,
            compilation_options: self.compilation_options,
            cache: CacheValue(cache),
        }
    }
}
pub trait Complete<'a>:
    State<
    'a,
    Label: IsSetLabel<'a>,
    Layout: IsSetLayout<'a>,
    Module: IsSetModule<'a>,
    EntryPoint: IsSetEntryPoint<'a>,
    CompilationOptions: IsSetCompilationOptions<'a>,
    Cache: IsSetCache<'a>,
>
{
}
impl<
        'a,
        CS: State<
            'a,
            Label: IsSetLabel<'a>,
            Layout: IsSetLayout<'a>,
            Module: IsSetModule<'a>,
            EntryPoint: IsSetEntryPoint<'a>,
            CompilationOptions: IsSetCompilationOptions<'a>,
            Cache: IsSetCache<'a>,
        >,
    > Complete<'a> for CS
{
}
impl<'a, CS: Complete<'a>> ComputePipelineDescriptorBuilder<'a, CS> {
    pub fn build(self) -> wgpu_27::ComputePipelineDescriptor<'a> {
        wgpu_27::ComputePipelineDescriptor {
            label: IsSetLabel::get(self.label),
            layout: IsSetLayout::get(self.layout),
            module: IsSetModule::get(self.module),
            entry_point: IsSetEntryPoint::get(self.entry_point),
            compilation_options: IsSetCompilationOptions::get(self.compilation_options),
            cache: IsSetCache::get(self.cache),
        }
    }
    pub fn create_with(self, device: &wgpu_27::Device) -> wgpu_27::ComputePipeline {
        device.create_compute_pipeline(&self.build())
    }
}
impl<'a> Nested<wgpu_27::ComputePipelineDescriptor<'a>> for wgpu_27::ComputePipelineDescriptor<'a> {
    fn unnest(self) -> wgpu_27::ComputePipelineDescriptor<'a> {
        self
    }
}
impl<'a, CS: Complete<'a>> Nested<wgpu_27::ComputePipelineDescriptor<'a>>
    for ComputePipelineDescriptorBuilder<'a, CS>
{
    fn unnest(self) -> wgpu_27::ComputePipelineDescriptor<'a> {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::IsSetLabel::get(super::LabelEmpty)),
            format!("{:#?}", wgpu_27::Label::default()),
        );
        assert_eq!(
            format!("{:#?}", super::IsSetLayout::get(super::LayoutEmpty)),
            format!("{:#?}", Option::<&wgpu_27::PipelineLayout>::default()),
        );
        assert_eq!(
            format!("{:#?}", super::IsSetEntryPoint::get(super::EntryPointEmpty)),
            format!("{:#?}", Option::<&str>::default()),
        );
        assert_eq!(
            format!(
                "{:#?}",
                super::IsSetCompilationOptions::get(super::CompilationOptionsEmpty)
            ),
            format!("{:#?}", wgpu_27::PipelineCompilationOptions::default()),
        );
        assert_eq!(
            format!("{:#?}", super::IsSetCache::get(super::CacheEmpty)),
            format!("{:#?}", Option::<&wgpu_27::PipelineCache>::default()),
        );
    }
}
