// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_27::DepthStencilState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [format](DepthStencilStateBuilder::format) Required\n  - [depth_write_enabled](DepthStencilStateBuilder::depth_write_enabled) Required\n  - [depth_compare](DepthStencilStateBuilder::depth_compare) Required\n  - [stencil](DepthStencilStateBuilder::stencil) Optional, defaults to [wgpu_27::StencilState::default()]\n  - [bias](DepthStencilStateBuilder::bias) Optional, defaults to [wgpu_27::DepthBiasState::default()]\n"]
pub struct DepthStencilStateBuilder<CS: State> {
    format: CS::Format,
    depth_write_enabled: CS::DepthWriteEnabled,
    depth_compare: CS::DepthCompare,
    stencil: CS::Stencil,
    bias: CS::Bias,
}
impl DepthStencilStateBuilder<Empty> {
    pub fn new() -> DepthStencilStateBuilder<Empty> {
        DepthStencilStateBuilder {
            format: FormatEmpty,
            depth_write_enabled: DepthWriteEnabledEmpty,
            depth_compare: DepthCompareEmpty,
            stencil: StencilEmpty,
            bias: BiasEmpty,
        }
    }
}
#[doc = "\nReturns [DepthStencilStateBuilder] for building [`wgpu_27::DepthStencilState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [format](DepthStencilStateBuilder::format) Required\n  - [depth_write_enabled](DepthStencilStateBuilder::depth_write_enabled) Required\n  - [depth_compare](DepthStencilStateBuilder::depth_compare) Required\n  - [stencil](DepthStencilStateBuilder::stencil) Optional, defaults to [wgpu_27::StencilState::default()]\n  - [bias](DepthStencilStateBuilder::bias) Optional, defaults to [wgpu_27::DepthBiasState::default()]\n"]
pub fn depth_stencil_state() -> DepthStencilStateBuilder<Empty> {
    DepthStencilStateBuilder::new()
}
pub struct FormatEmpty;
impl Field for FormatEmpty {}
pub trait FormatIsEmpty {}
impl FormatIsEmpty for FormatEmpty {}
pub trait IsSetFormat {
    fn get(self) -> wgpu_27::TextureFormat;
}
pub struct FormatValue(pub wgpu_27::TextureFormat);
impl Field for FormatValue {}
impl IsSetFormat for FormatValue {
    fn get(self) -> wgpu_27::TextureFormat {
        self.0
    }
}
pub struct DepthWriteEnabledEmpty;
impl Field for DepthWriteEnabledEmpty {}
pub trait DepthWriteEnabledIsEmpty {}
impl DepthWriteEnabledIsEmpty for DepthWriteEnabledEmpty {}
pub trait IsSetDepthWriteEnabled {
    fn get(self) -> bool;
}
pub struct DepthWriteEnabledValue(pub bool);
impl Field for DepthWriteEnabledValue {}
impl IsSetDepthWriteEnabled for DepthWriteEnabledValue {
    fn get(self) -> bool {
        self.0
    }
}
pub struct DepthCompareEmpty;
impl Field for DepthCompareEmpty {}
pub trait DepthCompareIsEmpty {}
impl DepthCompareIsEmpty for DepthCompareEmpty {}
pub trait IsSetDepthCompare {
    fn get(self) -> wgpu_27::CompareFunction;
}
pub struct DepthCompareValue(pub wgpu_27::CompareFunction);
impl Field for DepthCompareValue {}
impl IsSetDepthCompare for DepthCompareValue {
    fn get(self) -> wgpu_27::CompareFunction {
        self.0
    }
}
pub struct StencilEmpty;
impl Field for StencilEmpty {}
pub trait StencilIsEmpty {}
impl StencilIsEmpty for StencilEmpty {}
pub trait IsSetStencil {
    fn get(self) -> wgpu_27::StencilState;
}
impl IsSetStencil for StencilEmpty {
    fn get(self) -> wgpu_27::StencilState {
        wgpu_27::StencilState::default()
    }
}
pub struct StencilValue(pub wgpu_27::StencilState);
impl Field for StencilValue {}
impl IsSetStencil for StencilValue {
    fn get(self) -> wgpu_27::StencilState {
        self.0
    }
}
pub struct BiasEmpty;
impl Field for BiasEmpty {}
pub trait BiasIsEmpty {}
impl BiasIsEmpty for BiasEmpty {}
pub trait IsSetBias {
    fn get(self) -> wgpu_27::DepthBiasState;
}
impl IsSetBias for BiasEmpty {
    fn get(self) -> wgpu_27::DepthBiasState {
        wgpu_27::DepthBiasState::default()
    }
}
pub struct BiasValue(pub wgpu_27::DepthBiasState);
impl Field for BiasValue {}
impl IsSetBias for BiasValue {
    fn get(self) -> wgpu_27::DepthBiasState {
        self.0
    }
}
pub trait State {
    type Format: Field;
    type DepthWriteEnabled: Field;
    type DepthCompare: Field;
    type Stencil: Field;
    type Bias: Field;
}
pub struct Empty;
impl State for Empty {
    type Format = FormatEmpty;
    type DepthWriteEnabled = DepthWriteEnabledEmpty;
    type DepthCompare = DepthCompareEmpty;
    type Stencil = StencilEmpty;
    type Bias = BiasEmpty;
}
pub struct SetFormat<CS>(CS);
impl<CS: State> State for SetFormat<CS> {
    type Format = FormatValue;
    type DepthWriteEnabled = CS::DepthWriteEnabled;
    type DepthCompare = CS::DepthCompare;
    type Stencil = CS::Stencil;
    type Bias = CS::Bias;
}
pub struct SetDepthWriteEnabled<CS>(CS);
impl<CS: State> State for SetDepthWriteEnabled<CS> {
    type Format = CS::Format;
    type DepthWriteEnabled = DepthWriteEnabledValue;
    type DepthCompare = CS::DepthCompare;
    type Stencil = CS::Stencil;
    type Bias = CS::Bias;
}
pub struct SetDepthCompare<CS>(CS);
impl<CS: State> State for SetDepthCompare<CS> {
    type Format = CS::Format;
    type DepthWriteEnabled = CS::DepthWriteEnabled;
    type DepthCompare = DepthCompareValue;
    type Stencil = CS::Stencil;
    type Bias = CS::Bias;
}
pub struct SetStencil<CS>(CS);
impl<CS: State> State for SetStencil<CS> {
    type Format = CS::Format;
    type DepthWriteEnabled = CS::DepthWriteEnabled;
    type DepthCompare = CS::DepthCompare;
    type Stencil = StencilValue;
    type Bias = CS::Bias;
}
pub struct SetBias<CS>(CS);
impl<CS: State> State for SetBias<CS> {
    type Format = CS::Format;
    type DepthWriteEnabled = CS::DepthWriteEnabled;
    type DepthCompare = CS::DepthCompare;
    type Stencil = CS::Stencil;
    type Bias = BiasValue;
}
impl<CS: State> DepthStencilStateBuilder<CS> {
    #[doc = "Setter for [wgpu_27::DepthStencilState::format]. Required.\n"]
    pub fn format(self, format: wgpu_27::TextureFormat) -> DepthStencilStateBuilder<SetFormat<CS>>
    where
        CS::Format: FormatIsEmpty,
    {
        DepthStencilStateBuilder {
            format: FormatValue(format),
            depth_write_enabled: self.depth_write_enabled,
            depth_compare: self.depth_compare,
            stencil: self.stencil,
            bias: self.bias,
        }
    }
    #[doc = "Setter for [wgpu_27::DepthStencilState::depth_write_enabled]. Required.\n"]
    pub fn depth_write_enabled(
        self,
        depth_write_enabled: bool,
    ) -> DepthStencilStateBuilder<SetDepthWriteEnabled<CS>>
    where
        CS::DepthWriteEnabled: DepthWriteEnabledIsEmpty,
    {
        DepthStencilStateBuilder {
            format: self.format,
            depth_write_enabled: DepthWriteEnabledValue(depth_write_enabled),
            depth_compare: self.depth_compare,
            stencil: self.stencil,
            bias: self.bias,
        }
    }
    #[doc = "Setter for [wgpu_27::DepthStencilState::depth_compare]. Required.\n"]
    pub fn depth_compare(
        self,
        depth_compare: wgpu_27::CompareFunction,
    ) -> DepthStencilStateBuilder<SetDepthCompare<CS>>
    where
        CS::DepthCompare: DepthCompareIsEmpty,
    {
        DepthStencilStateBuilder {
            format: self.format,
            depth_write_enabled: self.depth_write_enabled,
            depth_compare: DepthCompareValue(depth_compare),
            stencil: self.stencil,
            bias: self.bias,
        }
    }
    #[doc = "Setter for [wgpu_27::DepthStencilState::stencil]. Optional, defaults to [wgpu_27::StencilState::default()].\n"]
    pub fn stencil(
        self,
        stencil: impl Nested<wgpu_27::StencilState>,
    ) -> DepthStencilStateBuilder<SetStencil<CS>>
    where
        CS::Stencil: StencilIsEmpty,
    {
        DepthStencilStateBuilder {
            format: self.format,
            depth_write_enabled: self.depth_write_enabled,
            depth_compare: self.depth_compare,
            stencil: StencilValue(Nested::unnest(stencil)),
            bias: self.bias,
        }
    }
    #[doc = "Setter for [wgpu_27::DepthStencilState::bias]. Optional, defaults to [wgpu_27::DepthBiasState::default()].\n"]
    pub fn bias(
        self,
        bias: impl Nested<wgpu_27::DepthBiasState>,
    ) -> DepthStencilStateBuilder<SetBias<CS>>
    where
        CS::Bias: BiasIsEmpty,
    {
        DepthStencilStateBuilder {
            format: self.format,
            depth_write_enabled: self.depth_write_enabled,
            depth_compare: self.depth_compare,
            stencil: self.stencil,
            bias: BiasValue(Nested::unnest(bias)),
        }
    }
}
pub trait Complete:
    State<
    Format: IsSetFormat,
    DepthWriteEnabled: IsSetDepthWriteEnabled,
    DepthCompare: IsSetDepthCompare,
    Stencil: IsSetStencil,
    Bias: IsSetBias,
>
{
}
impl<
        CS: State<
            Format: IsSetFormat,
            DepthWriteEnabled: IsSetDepthWriteEnabled,
            DepthCompare: IsSetDepthCompare,
            Stencil: IsSetStencil,
            Bias: IsSetBias,
        >,
    > Complete for CS
{
}
impl<CS: Complete> DepthStencilStateBuilder<CS> {
    pub fn build(self) -> wgpu_27::DepthStencilState {
        wgpu_27::DepthStencilState {
            format: IsSetFormat::get(self.format),
            depth_write_enabled: IsSetDepthWriteEnabled::get(self.depth_write_enabled),
            depth_compare: IsSetDepthCompare::get(self.depth_compare),
            stencil: IsSetStencil::get(self.stencil),
            bias: IsSetBias::get(self.bias),
        }
    }
}
impl Nested<wgpu_27::DepthStencilState> for wgpu_27::DepthStencilState {
    fn unnest(self) -> wgpu_27::DepthStencilState {
        self
    }
}
impl<CS: Complete> Nested<wgpu_27::DepthStencilState> for DepthStencilStateBuilder<CS> {
    fn unnest(self) -> wgpu_27::DepthStencilState {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::IsSetStencil::get(super::StencilEmpty)),
            format!("{:#?}", wgpu_27::StencilState::default()),
        );
        assert_eq!(
            format!("{:#?}", super::IsSetBias::get(super::BiasEmpty)),
            format!("{:#?}", wgpu_27::DepthBiasState::default()),
        );
    }
}
