// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_27::FragmentState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [module](FragmentStateBuilder::module) Required\n  - [entry_point](FragmentStateBuilder::entry_point) Optional, defaults to `None`\n  - [compilation_options](FragmentStateBuilder::compilation_options) Optional, defaults to [wgpu_27::PipelineCompilationOptions::default()]\n  - [targets](FragmentStateBuilder::targets) Required\n"]
pub struct FragmentStateBuilder<'a, CS: State<'a>> {
    module: CS::Module,
    entry_point: CS::EntryPoint,
    compilation_options: CS::CompilationOptions,
    targets: CS::Targets,
}
impl<'a> FragmentStateBuilder<'a, Empty> {
    pub fn new() -> FragmentStateBuilder<'a, Empty> {
        FragmentStateBuilder {
            module: ModuleEmpty,
            entry_point: EntryPointEmpty,
            compilation_options: CompilationOptionsEmpty,
            targets: TargetsEmpty,
        }
    }
}
#[doc = "\nReturns [FragmentStateBuilder] for building [`wgpu_27::FragmentState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [module](FragmentStateBuilder::module) Required\n  - [entry_point](FragmentStateBuilder::entry_point) Optional, defaults to `None`\n  - [compilation_options](FragmentStateBuilder::compilation_options) Optional, defaults to [wgpu_27::PipelineCompilationOptions::default()]\n  - [targets](FragmentStateBuilder::targets) Required\n"]
pub fn fragment_state<'a>() -> FragmentStateBuilder<'a, Empty> {
    FragmentStateBuilder::new()
}
pub struct ModuleEmpty;
impl Field for ModuleEmpty {}
pub trait ModuleIsEmpty {}
impl ModuleIsEmpty for ModuleEmpty {}
pub trait IsSetModule<'a> {
    fn get(self) -> &'a wgpu_27::ShaderModule;
}
pub struct ModuleValue<'a>(pub &'a wgpu_27::ShaderModule);
impl<'a> Field for ModuleValue<'a> {}
impl<'a> IsSetModule<'a> for ModuleValue<'a> {
    fn get(self) -> &'a wgpu_27::ShaderModule {
        self.0
    }
}
pub struct EntryPointEmpty;
impl Field for EntryPointEmpty {}
pub trait EntryPointIsEmpty {}
impl EntryPointIsEmpty for EntryPointEmpty {}
pub trait IsSetEntryPoint<'a> {
    fn get(self) -> Option<&'a str>;
}
impl<'a> IsSetEntryPoint<'a> for EntryPointEmpty {
    fn get(self) -> Option<&'a str> {
        None
    }
}
pub struct EntryPointValue<'a>(pub Option<&'a str>);
impl<'a> Field for EntryPointValue<'a> {}
impl<'a> IsSetEntryPoint<'a> for EntryPointValue<'a> {
    fn get(self) -> Option<&'a str> {
        self.0
    }
}
pub struct CompilationOptionsEmpty;
impl Field for CompilationOptionsEmpty {}
pub trait CompilationOptionsIsEmpty {}
impl CompilationOptionsIsEmpty for CompilationOptionsEmpty {}
pub trait IsSetCompilationOptions<'a> {
    fn get(self) -> wgpu_27::PipelineCompilationOptions<'a>;
}
impl<'a> IsSetCompilationOptions<'a> for CompilationOptionsEmpty {
    fn get(self) -> wgpu_27::PipelineCompilationOptions<'a> {
        wgpu_27::PipelineCompilationOptions::default()
    }
}
pub struct CompilationOptionsValue<'a>(pub wgpu_27::PipelineCompilationOptions<'a>);
impl<'a> Field for CompilationOptionsValue<'a> {}
impl<'a> IsSetCompilationOptions<'a> for CompilationOptionsValue<'a> {
    fn get(self) -> wgpu_27::PipelineCompilationOptions<'a> {
        self.0
    }
}
pub struct TargetsEmpty;
impl Field for TargetsEmpty {}
pub trait TargetsIsEmpty {}
impl TargetsIsEmpty for TargetsEmpty {}
pub trait IsSetTargets<'a> {
    fn get(self) -> &'a [Option<wgpu_27::ColorTargetState>];
}
pub struct TargetsValue<'a>(pub &'a [Option<wgpu_27::ColorTargetState>]);
impl<'a> Field for TargetsValue<'a> {}
impl<'a> IsSetTargets<'a> for TargetsValue<'a> {
    fn get(self) -> &'a [Option<wgpu_27::ColorTargetState>] {
        self.0
    }
}
pub trait State<'a> {
    type Module: Field;
    type EntryPoint: Field;
    type CompilationOptions: Field;
    type Targets: Field;
}
pub struct Empty;
impl<'a> State<'a> for Empty {
    type Module = ModuleEmpty;
    type EntryPoint = EntryPointEmpty;
    type CompilationOptions = CompilationOptionsEmpty;
    type Targets = TargetsEmpty;
}
pub struct SetModule<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetModule<CS> {
    type Module = ModuleValue<'a>;
    type EntryPoint = CS::EntryPoint;
    type CompilationOptions = CS::CompilationOptions;
    type Targets = CS::Targets;
}
pub struct SetEntryPoint<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetEntryPoint<CS> {
    type Module = CS::Module;
    type EntryPoint = EntryPointValue<'a>;
    type CompilationOptions = CS::CompilationOptions;
    type Targets = CS::Targets;
}
pub struct SetCompilationOptions<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetCompilationOptions<CS> {
    type Module = CS::Module;
    type EntryPoint = CS::EntryPoint;
    type CompilationOptions = CompilationOptionsValue<'a>;
    type Targets = CS::Targets;
}
pub struct SetTargets<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetTargets<CS> {
    type Module = CS::Module;
    type EntryPoint = CS::EntryPoint;
    type CompilationOptions = CS::CompilationOptions;
    type Targets = TargetsValue<'a>;
}
impl<'a, CS: State<'a>> FragmentStateBuilder<'a, CS> {
    #[doc = "Setter for [wgpu_27::FragmentState::module]. Required.\n"]
    pub fn module(
        self,
        module: &'a wgpu_27::ShaderModule,
    ) -> FragmentStateBuilder<'a, SetModule<CS>>
    where
        CS::Module: ModuleIsEmpty,
    {
        FragmentStateBuilder {
            module: ModuleValue(module),
            entry_point: self.entry_point,
            compilation_options: self.compilation_options,
            targets: self.targets,
        }
    }
    #[doc = "Setter for [wgpu_27::FragmentState::entry_point]. Optional, defaults to `None`.\n"]
    pub fn entry_point(self, entry_point: &'a str) -> FragmentStateBuilder<'a, SetEntryPoint<CS>>
    where
        CS::EntryPoint: EntryPointIsEmpty,
    {
        FragmentStateBuilder {
            module: self.module,
            entry_point: EntryPointValue(Some(entry_point)),
            compilation_options: self.compilation_options,
            targets: self.targets,
        }
    }
    #[doc = "Setter for [wgpu_27::FragmentState::entry_point]. Optional, defaults to `None`.\n"]
    pub fn maybe_entry_point(
        self,
        entry_point: Option<&'a str>,
    ) -> FragmentStateBuilder<'a, SetEntryPoint<CS>>
    where
        CS::EntryPoint: EntryPointIsEmpty,
    {
        FragmentStateBuilder {
            module: self.module,
            entry_point: EntryPointValue(entry_point),
            compilation_options: self.compilation_options,
            targets: self.targets,
        }
    }
    #[doc = "Setter for [wgpu_27::FragmentState::compilation_options]. Optional, defaults to [wgpu_27::PipelineCompilationOptions::default()].\n"]
    pub fn compilation_options(
        self,
        compilation_options: impl Nested<wgpu_27::PipelineCompilationOptions<'a>>,
    ) -> FragmentStateBuilder<'a, SetCompilationOptions<CS>>
    where
        CS::CompilationOptions: CompilationOptionsIsEmpty,
    {
        FragmentStateBuilder {
            module: self.module,
            entry_point: self.entry_point,
            compilation_options: CompilationOptionsValue(Nested::unnest(compilation_options)),
            targets: self.targets,
        }
    }
    #[doc = "Setter for [wgpu_27::FragmentState::targets]. Required.\n"]
    pub fn targets(
        self,
        targets: &'a [Option<wgpu_27::ColorTargetState>],
    ) -> FragmentStateBuilder<'a, SetTargets<CS>>
    where
        CS::Targets: TargetsIsEmpty,
    {
        FragmentStateBuilder {
            module: self.module,
            entry_point: self.entry_point,
            compilation_options: self.compilation_options,
            targets: TargetsValue(targets),
        }
    }
}
pub trait Complete<'a>:
    State<
    'a,
    Module: IsSetModule<'a>,
    EntryPoint: IsSetEntryPoint<'a>,
    CompilationOptions: IsSetCompilationOptions<'a>,
    Targets: IsSetTargets<'a>,
>
{
}
impl<
        'a,
        CS: State<
            'a,
            Module: IsSetModule<'a>,
            EntryPoint: IsSetEntryPoint<'a>,
            CompilationOptions: IsSetCompilationOptions<'a>,
            Targets: IsSetTargets<'a>,
        >,
    > Complete<'a> for CS
{
}
impl<'a, CS: Complete<'a>> FragmentStateBuilder<'a, CS> {
    pub fn build(self) -> wgpu_27::FragmentState<'a> {
        wgpu_27::FragmentState {
            module: IsSetModule::get(self.module),
            entry_point: IsSetEntryPoint::get(self.entry_point),
            compilation_options: IsSetCompilationOptions::get(self.compilation_options),
            targets: IsSetTargets::get(self.targets),
        }
    }
}
impl<'a> Nested<wgpu_27::FragmentState<'a>> for wgpu_27::FragmentState<'a> {
    fn unnest(self) -> wgpu_27::FragmentState<'a> {
        self
    }
}
impl<'a, CS: Complete<'a>> Nested<wgpu_27::FragmentState<'a>> for FragmentStateBuilder<'a, CS> {
    fn unnest(self) -> wgpu_27::FragmentState<'a> {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::IsSetEntryPoint::get(super::EntryPointEmpty)),
            format!("{:#?}", Option::<&str>::default()),
        );
        assert_eq!(
            format!(
                "{:#?}",
                super::IsSetCompilationOptions::get(super::CompilationOptionsEmpty)
            ),
            format!("{:#?}", wgpu_27::PipelineCompilationOptions::default()),
        );
    }
}
