// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_27::PrimitiveState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [topology](PrimitiveStateBuilder::topology) Optional, defaults to [wgpu_27::PrimitiveTopology::TriangleList]\n  - [strip_index_format](PrimitiveStateBuilder::strip_index_format) Optional, defaults to `None`\n  - [front_face](PrimitiveStateBuilder::front_face) Optional, defaults to [wgpu_27::FrontFace::Ccw]\n  - [cull_mode](PrimitiveStateBuilder::cull_mode) Optional, defaults to `None`\n  - [unclipped_depth](PrimitiveStateBuilder::unclipped_depth) Optional, defaults to `false`\n  - [polygon_mode](PrimitiveStateBuilder::polygon_mode) Optional, defaults to [wgpu_27::PolygonMode::Fill]\n  - [conservative](PrimitiveStateBuilder::conservative) Optional, defaults to `false`\n"]
pub struct PrimitiveStateBuilder<CS: State> {
    topology: CS::Topology,
    strip_index_format: CS::StripIndexFormat,
    front_face: CS::FrontFace,
    cull_mode: CS::CullMode,
    unclipped_depth: CS::UnclippedDepth,
    polygon_mode: CS::PolygonMode,
    conservative: CS::Conservative,
}
impl PrimitiveStateBuilder<Empty> {
    pub fn new() -> PrimitiveStateBuilder<Empty> {
        PrimitiveStateBuilder {
            topology: TopologyEmpty,
            strip_index_format: StripIndexFormatEmpty,
            front_face: FrontFaceEmpty,
            cull_mode: CullModeEmpty,
            unclipped_depth: UnclippedDepthEmpty,
            polygon_mode: PolygonModeEmpty,
            conservative: ConservativeEmpty,
        }
    }
}
#[doc = "\nReturns [PrimitiveStateBuilder] for building [`wgpu_27::PrimitiveState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [topology](PrimitiveStateBuilder::topology) Optional, defaults to [wgpu_27::PrimitiveTopology::TriangleList]\n  - [strip_index_format](PrimitiveStateBuilder::strip_index_format) Optional, defaults to `None`\n  - [front_face](PrimitiveStateBuilder::front_face) Optional, defaults to [wgpu_27::FrontFace::Ccw]\n  - [cull_mode](PrimitiveStateBuilder::cull_mode) Optional, defaults to `None`\n  - [unclipped_depth](PrimitiveStateBuilder::unclipped_depth) Optional, defaults to `false`\n  - [polygon_mode](PrimitiveStateBuilder::polygon_mode) Optional, defaults to [wgpu_27::PolygonMode::Fill]\n  - [conservative](PrimitiveStateBuilder::conservative) Optional, defaults to `false`\n"]
pub fn primitive_state() -> PrimitiveStateBuilder<Empty> {
    PrimitiveStateBuilder::new()
}
pub struct TopologyEmpty;
impl Field for TopologyEmpty {}
pub trait TopologyIsEmpty {}
impl TopologyIsEmpty for TopologyEmpty {}
pub trait IsSetTopology {
    fn get(self) -> wgpu_27::PrimitiveTopology;
}
impl IsSetTopology for TopologyEmpty {
    fn get(self) -> wgpu_27::PrimitiveTopology {
        wgpu_27::PrimitiveTopology::TriangleList
    }
}
pub struct TopologyValue(pub wgpu_27::PrimitiveTopology);
impl Field for TopologyValue {}
impl IsSetTopology for TopologyValue {
    fn get(self) -> wgpu_27::PrimitiveTopology {
        self.0
    }
}
pub struct StripIndexFormatEmpty;
impl Field for StripIndexFormatEmpty {}
pub trait StripIndexFormatIsEmpty {}
impl StripIndexFormatIsEmpty for StripIndexFormatEmpty {}
pub trait IsSetStripIndexFormat {
    fn get(self) -> Option<wgpu_27::IndexFormat>;
}
impl IsSetStripIndexFormat for StripIndexFormatEmpty {
    fn get(self) -> Option<wgpu_27::IndexFormat> {
        None
    }
}
pub struct StripIndexFormatValue(pub Option<wgpu_27::IndexFormat>);
impl Field for StripIndexFormatValue {}
impl IsSetStripIndexFormat for StripIndexFormatValue {
    fn get(self) -> Option<wgpu_27::IndexFormat> {
        self.0
    }
}
pub struct FrontFaceEmpty;
impl Field for FrontFaceEmpty {}
pub trait FrontFaceIsEmpty {}
impl FrontFaceIsEmpty for FrontFaceEmpty {}
pub trait IsSetFrontFace {
    fn get(self) -> wgpu_27::FrontFace;
}
impl IsSetFrontFace for FrontFaceEmpty {
    fn get(self) -> wgpu_27::FrontFace {
        wgpu_27::FrontFace::Ccw
    }
}
pub struct FrontFaceValue(pub wgpu_27::FrontFace);
impl Field for FrontFaceValue {}
impl IsSetFrontFace for FrontFaceValue {
    fn get(self) -> wgpu_27::FrontFace {
        self.0
    }
}
pub struct CullModeEmpty;
impl Field for CullModeEmpty {}
pub trait CullModeIsEmpty {}
impl CullModeIsEmpty for CullModeEmpty {}
pub trait IsSetCullMode {
    fn get(self) -> Option<wgpu_27::Face>;
}
impl IsSetCullMode for CullModeEmpty {
    fn get(self) -> Option<wgpu_27::Face> {
        None
    }
}
pub struct CullModeValue(pub Option<wgpu_27::Face>);
impl Field for CullModeValue {}
impl IsSetCullMode for CullModeValue {
    fn get(self) -> Option<wgpu_27::Face> {
        self.0
    }
}
pub struct UnclippedDepthEmpty;
impl Field for UnclippedDepthEmpty {}
pub trait UnclippedDepthIsEmpty {}
impl UnclippedDepthIsEmpty for UnclippedDepthEmpty {}
pub trait IsSetUnclippedDepth {
    fn get(self) -> bool;
}
impl IsSetUnclippedDepth for UnclippedDepthEmpty {
    fn get(self) -> bool {
        false
    }
}
pub struct UnclippedDepthValue(pub bool);
impl Field for UnclippedDepthValue {}
impl IsSetUnclippedDepth for UnclippedDepthValue {
    fn get(self) -> bool {
        self.0
    }
}
pub struct PolygonModeEmpty;
impl Field for PolygonModeEmpty {}
pub trait PolygonModeIsEmpty {}
impl PolygonModeIsEmpty for PolygonModeEmpty {}
pub trait IsSetPolygonMode {
    fn get(self) -> wgpu_27::PolygonMode;
}
impl IsSetPolygonMode for PolygonModeEmpty {
    fn get(self) -> wgpu_27::PolygonMode {
        wgpu_27::PolygonMode::Fill
    }
}
pub struct PolygonModeValue(pub wgpu_27::PolygonMode);
impl Field for PolygonModeValue {}
impl IsSetPolygonMode for PolygonModeValue {
    fn get(self) -> wgpu_27::PolygonMode {
        self.0
    }
}
pub struct ConservativeEmpty;
impl Field for ConservativeEmpty {}
pub trait ConservativeIsEmpty {}
impl ConservativeIsEmpty for ConservativeEmpty {}
pub trait IsSetConservative {
    fn get(self) -> bool;
}
impl IsSetConservative for ConservativeEmpty {
    fn get(self) -> bool {
        false
    }
}
pub struct ConservativeValue(pub bool);
impl Field for ConservativeValue {}
impl IsSetConservative for ConservativeValue {
    fn get(self) -> bool {
        self.0
    }
}
pub trait State {
    type Topology: Field;
    type StripIndexFormat: Field;
    type FrontFace: Field;
    type CullMode: Field;
    type UnclippedDepth: Field;
    type PolygonMode: Field;
    type Conservative: Field;
}
pub struct Empty;
impl State for Empty {
    type Topology = TopologyEmpty;
    type StripIndexFormat = StripIndexFormatEmpty;
    type FrontFace = FrontFaceEmpty;
    type CullMode = CullModeEmpty;
    type UnclippedDepth = UnclippedDepthEmpty;
    type PolygonMode = PolygonModeEmpty;
    type Conservative = ConservativeEmpty;
}
pub struct SetTopology<CS>(CS);
impl<CS: State> State for SetTopology<CS> {
    type Topology = TopologyValue;
    type StripIndexFormat = CS::StripIndexFormat;
    type FrontFace = CS::FrontFace;
    type CullMode = CS::CullMode;
    type UnclippedDepth = CS::UnclippedDepth;
    type PolygonMode = CS::PolygonMode;
    type Conservative = CS::Conservative;
}
pub struct SetStripIndexFormat<CS>(CS);
impl<CS: State> State for SetStripIndexFormat<CS> {
    type Topology = CS::Topology;
    type StripIndexFormat = StripIndexFormatValue;
    type FrontFace = CS::FrontFace;
    type CullMode = CS::CullMode;
    type UnclippedDepth = CS::UnclippedDepth;
    type PolygonMode = CS::PolygonMode;
    type Conservative = CS::Conservative;
}
pub struct SetFrontFace<CS>(CS);
impl<CS: State> State for SetFrontFace<CS> {
    type Topology = CS::Topology;
    type StripIndexFormat = CS::StripIndexFormat;
    type FrontFace = FrontFaceValue;
    type CullMode = CS::CullMode;
    type UnclippedDepth = CS::UnclippedDepth;
    type PolygonMode = CS::PolygonMode;
    type Conservative = CS::Conservative;
}
pub struct SetCullMode<CS>(CS);
impl<CS: State> State for SetCullMode<CS> {
    type Topology = CS::Topology;
    type StripIndexFormat = CS::StripIndexFormat;
    type FrontFace = CS::FrontFace;
    type CullMode = CullModeValue;
    type UnclippedDepth = CS::UnclippedDepth;
    type PolygonMode = CS::PolygonMode;
    type Conservative = CS::Conservative;
}
pub struct SetUnclippedDepth<CS>(CS);
impl<CS: State> State for SetUnclippedDepth<CS> {
    type Topology = CS::Topology;
    type StripIndexFormat = CS::StripIndexFormat;
    type FrontFace = CS::FrontFace;
    type CullMode = CS::CullMode;
    type UnclippedDepth = UnclippedDepthValue;
    type PolygonMode = CS::PolygonMode;
    type Conservative = CS::Conservative;
}
pub struct SetPolygonMode<CS>(CS);
impl<CS: State> State for SetPolygonMode<CS> {
    type Topology = CS::Topology;
    type StripIndexFormat = CS::StripIndexFormat;
    type FrontFace = CS::FrontFace;
    type CullMode = CS::CullMode;
    type UnclippedDepth = CS::UnclippedDepth;
    type PolygonMode = PolygonModeValue;
    type Conservative = CS::Conservative;
}
pub struct SetConservative<CS>(CS);
impl<CS: State> State for SetConservative<CS> {
    type Topology = CS::Topology;
    type StripIndexFormat = CS::StripIndexFormat;
    type FrontFace = CS::FrontFace;
    type CullMode = CS::CullMode;
    type UnclippedDepth = CS::UnclippedDepth;
    type PolygonMode = CS::PolygonMode;
    type Conservative = ConservativeValue;
}
impl<CS: State> PrimitiveStateBuilder<CS> {
    #[doc = "Setter for [wgpu_27::PrimitiveState::topology]. Optional, defaults to [wgpu_27::PrimitiveTopology::TriangleList].\n"]
    pub fn topology(
        self,
        topology: wgpu_27::PrimitiveTopology,
    ) -> PrimitiveStateBuilder<SetTopology<CS>>
    where
        CS::Topology: TopologyIsEmpty,
    {
        PrimitiveStateBuilder {
            topology: TopologyValue(topology),
            strip_index_format: self.strip_index_format,
            front_face: self.front_face,
            cull_mode: self.cull_mode,
            unclipped_depth: self.unclipped_depth,
            polygon_mode: self.polygon_mode,
            conservative: self.conservative,
        }
    }
    #[doc = "Setter for [wgpu_27::PrimitiveState::strip_index_format]. Optional, defaults to `None`.\n"]
    pub fn strip_index_format(
        self,
        strip_index_format: wgpu_27::IndexFormat,
    ) -> PrimitiveStateBuilder<SetStripIndexFormat<CS>>
    where
        CS::StripIndexFormat: StripIndexFormatIsEmpty,
    {
        PrimitiveStateBuilder {
            topology: self.topology,
            strip_index_format: StripIndexFormatValue(Some(strip_index_format)),
            front_face: self.front_face,
            cull_mode: self.cull_mode,
            unclipped_depth: self.unclipped_depth,
            polygon_mode: self.polygon_mode,
            conservative: self.conservative,
        }
    }
    #[doc = "Setter for [wgpu_27::PrimitiveState::strip_index_format]. Optional, defaults to `None`.\n"]
    pub fn maybe_strip_index_format(
        self,
        strip_index_format: Option<wgpu_27::IndexFormat>,
    ) -> PrimitiveStateBuilder<SetStripIndexFormat<CS>>
    where
        CS::StripIndexFormat: StripIndexFormatIsEmpty,
    {
        PrimitiveStateBuilder {
            topology: self.topology,
            strip_index_format: StripIndexFormatValue(strip_index_format),
            front_face: self.front_face,
            cull_mode: self.cull_mode,
            unclipped_depth: self.unclipped_depth,
            polygon_mode: self.polygon_mode,
            conservative: self.conservative,
        }
    }
    #[doc = "Setter for [wgpu_27::PrimitiveState::front_face]. Optional, defaults to [wgpu_27::FrontFace::Ccw].\n"]
    pub fn front_face(
        self,
        front_face: wgpu_27::FrontFace,
    ) -> PrimitiveStateBuilder<SetFrontFace<CS>>
    where
        CS::FrontFace: FrontFaceIsEmpty,
    {
        PrimitiveStateBuilder {
            topology: self.topology,
            strip_index_format: self.strip_index_format,
            front_face: FrontFaceValue(front_face),
            cull_mode: self.cull_mode,
            unclipped_depth: self.unclipped_depth,
            polygon_mode: self.polygon_mode,
            conservative: self.conservative,
        }
    }
    #[doc = "Setter for [wgpu_27::PrimitiveState::cull_mode]. Optional, defaults to `None`.\n"]
    pub fn cull_mode(self, cull_mode: wgpu_27::Face) -> PrimitiveStateBuilder<SetCullMode<CS>>
    where
        CS::CullMode: CullModeIsEmpty,
    {
        PrimitiveStateBuilder {
            topology: self.topology,
            strip_index_format: self.strip_index_format,
            front_face: self.front_face,
            cull_mode: CullModeValue(Some(cull_mode)),
            unclipped_depth: self.unclipped_depth,
            polygon_mode: self.polygon_mode,
            conservative: self.conservative,
        }
    }
    #[doc = "Setter for [wgpu_27::PrimitiveState::cull_mode]. Optional, defaults to `None`.\n"]
    pub fn maybe_cull_mode(
        self,
        cull_mode: Option<wgpu_27::Face>,
    ) -> PrimitiveStateBuilder<SetCullMode<CS>>
    where
        CS::CullMode: CullModeIsEmpty,
    {
        PrimitiveStateBuilder {
            topology: self.topology,
            strip_index_format: self.strip_index_format,
            front_face: self.front_face,
            cull_mode: CullModeValue(cull_mode),
            unclipped_depth: self.unclipped_depth,
            polygon_mode: self.polygon_mode,
            conservative: self.conservative,
        }
    }
    #[doc = "Setter for [wgpu_27::PrimitiveState::unclipped_depth]. Optional, defaults to `false`.\n"]
    pub fn unclipped_depth(
        self,
        unclipped_depth: bool,
    ) -> PrimitiveStateBuilder<SetUnclippedDepth<CS>>
    where
        CS::UnclippedDepth: UnclippedDepthIsEmpty,
    {
        PrimitiveStateBuilder {
            topology: self.topology,
            strip_index_format: self.strip_index_format,
            front_face: self.front_face,
            cull_mode: self.cull_mode,
            unclipped_depth: UnclippedDepthValue(unclipped_depth),
            polygon_mode: self.polygon_mode,
            conservative: self.conservative,
        }
    }
    #[doc = "Setter for [wgpu_27::PrimitiveState::polygon_mode]. Optional, defaults to [wgpu_27::PolygonMode::Fill].\n"]
    pub fn polygon_mode(
        self,
        polygon_mode: wgpu_27::PolygonMode,
    ) -> PrimitiveStateBuilder<SetPolygonMode<CS>>
    where
        CS::PolygonMode: PolygonModeIsEmpty,
    {
        PrimitiveStateBuilder {
            topology: self.topology,
            strip_index_format: self.strip_index_format,
            front_face: self.front_face,
            cull_mode: self.cull_mode,
            unclipped_depth: self.unclipped_depth,
            polygon_mode: PolygonModeValue(polygon_mode),
            conservative: self.conservative,
        }
    }
    #[doc = "Setter for [wgpu_27::PrimitiveState::conservative]. Optional, defaults to `false`.\n"]
    pub fn conservative(self, conservative: bool) -> PrimitiveStateBuilder<SetConservative<CS>>
    where
        CS::Conservative: ConservativeIsEmpty,
    {
        PrimitiveStateBuilder {
            topology: self.topology,
            strip_index_format: self.strip_index_format,
            front_face: self.front_face,
            cull_mode: self.cull_mode,
            unclipped_depth: self.unclipped_depth,
            polygon_mode: self.polygon_mode,
            conservative: ConservativeValue(conservative),
        }
    }
}
pub trait Complete:
    State<
    Topology: IsSetTopology,
    StripIndexFormat: IsSetStripIndexFormat,
    FrontFace: IsSetFrontFace,
    CullMode: IsSetCullMode,
    UnclippedDepth: IsSetUnclippedDepth,
    PolygonMode: IsSetPolygonMode,
    Conservative: IsSetConservative,
>
{
}
impl<
        CS: State<
            Topology: IsSetTopology,
            StripIndexFormat: IsSetStripIndexFormat,
            FrontFace: IsSetFrontFace,
            CullMode: IsSetCullMode,
            UnclippedDepth: IsSetUnclippedDepth,
            PolygonMode: IsSetPolygonMode,
            Conservative: IsSetConservative,
        >,
    > Complete for CS
{
}
impl<CS: Complete> PrimitiveStateBuilder<CS> {
    pub fn build(self) -> wgpu_27::PrimitiveState {
        wgpu_27::PrimitiveState {
            topology: IsSetTopology::get(self.topology),
            strip_index_format: IsSetStripIndexFormat::get(self.strip_index_format),
            front_face: IsSetFrontFace::get(self.front_face),
            cull_mode: IsSetCullMode::get(self.cull_mode),
            unclipped_depth: IsSetUnclippedDepth::get(self.unclipped_depth),
            polygon_mode: IsSetPolygonMode::get(self.polygon_mode),
            conservative: IsSetConservative::get(self.conservative),
        }
    }
}
impl Nested<wgpu_27::PrimitiveState> for wgpu_27::PrimitiveState {
    fn unnest(self) -> wgpu_27::PrimitiveState {
        self
    }
}
impl<CS: Complete> Nested<wgpu_27::PrimitiveState> for PrimitiveStateBuilder<CS> {
    fn unnest(self) -> wgpu_27::PrimitiveState {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::primitive_state().build()),
            format!("{:#?}", wgpu_27::PrimitiveState::default()),
        );
    }
}
