#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_27::RequestAdapterOptionsBase`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [power_preference](RequestAdapterOptionsBaseBuilder::power_preference) Optional, defaults to [wgpu_27::PowerPreference::None]\n  - [force_fallback_adapter](RequestAdapterOptionsBaseBuilder::force_fallback_adapter) Optional, defaults to `false`\n  - [compatible_surface](RequestAdapterOptionsBaseBuilder::compatible_surface) Optional, defaults to `None`\n"]
pub struct RequestAdapterOptionsBaseBuilder<S, CS: State<S>> {
    power_preference: CS::PowerPreference,
    force_fallback_adapter: CS::ForceFallbackAdapter,
    compatible_surface: CS::CompatibleSurface,
}
impl<S> RequestAdapterOptionsBaseBuilder<S, Empty> {
    pub fn new() -> RequestAdapterOptionsBaseBuilder<S, Empty> {
        RequestAdapterOptionsBaseBuilder {
            power_preference: PowerPreferenceEmpty,
            force_fallback_adapter: ForceFallbackAdapterEmpty,
            compatible_surface: CompatibleSurfaceEmpty,
        }
    }
}
#[doc = "\nReturns [RequestAdapterOptionsBaseBuilder] for building [`wgpu_27::RequestAdapterOptionsBase`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [power_preference](RequestAdapterOptionsBaseBuilder::power_preference) Optional, defaults to [wgpu_27::PowerPreference::None]\n  - [force_fallback_adapter](RequestAdapterOptionsBaseBuilder::force_fallback_adapter) Optional, defaults to `false`\n  - [compatible_surface](RequestAdapterOptionsBaseBuilder::compatible_surface) Optional, defaults to `None`\n"]
pub fn request_adapter_options_base<S>() -> RequestAdapterOptionsBaseBuilder<S, Empty> {
    RequestAdapterOptionsBaseBuilder::new()
}
pub struct PowerPreferenceEmpty;
impl Field for PowerPreferenceEmpty {}
pub trait PowerPreferenceIsEmpty {}
impl PowerPreferenceIsEmpty for PowerPreferenceEmpty {}
pub trait IsSetPowerPreference {
    fn get(self) -> wgpu_27::PowerPreference;
}
impl IsSetPowerPreference for PowerPreferenceEmpty {
    fn get(self) -> wgpu_27::PowerPreference {
        wgpu_27::PowerPreference::None
    }
}
pub struct PowerPreferenceValue(pub wgpu_27::PowerPreference);
impl Field for PowerPreferenceValue {}
impl IsSetPowerPreference for PowerPreferenceValue {
    fn get(self) -> wgpu_27::PowerPreference {
        self.0
    }
}
pub struct ForceFallbackAdapterEmpty;
impl Field for ForceFallbackAdapterEmpty {}
pub trait ForceFallbackAdapterIsEmpty {}
impl ForceFallbackAdapterIsEmpty for ForceFallbackAdapterEmpty {}
pub trait IsSetForceFallbackAdapter {
    fn get(self) -> bool;
}
impl IsSetForceFallbackAdapter for ForceFallbackAdapterEmpty {
    fn get(self) -> bool {
        false
    }
}
pub struct ForceFallbackAdapterValue(pub bool);
impl Field for ForceFallbackAdapterValue {}
impl IsSetForceFallbackAdapter for ForceFallbackAdapterValue {
    fn get(self) -> bool {
        self.0
    }
}
pub struct CompatibleSurfaceEmpty;
impl Field for CompatibleSurfaceEmpty {}
pub trait CompatibleSurfaceIsEmpty {}
impl CompatibleSurfaceIsEmpty for CompatibleSurfaceEmpty {}
pub trait IsSetCompatibleSurface<S> {
    fn get(self) -> Option<S>;
}
impl<S> IsSetCompatibleSurface<S> for CompatibleSurfaceEmpty {
    fn get(self) -> Option<S> {
        None
    }
}
pub struct CompatibleSurfaceValue<S>(pub Option<S>);
impl<S> Field for CompatibleSurfaceValue<S> {}
impl<S> IsSetCompatibleSurface<S> for CompatibleSurfaceValue<S> {
    fn get(self) -> Option<S> {
        self.0
    }
}
pub trait State<S> {
    type PowerPreference: Field;
    type ForceFallbackAdapter: Field;
    type CompatibleSurface: Field;
}
pub struct Empty;
impl<S> State<S> for Empty {
    type PowerPreference = PowerPreferenceEmpty;
    type ForceFallbackAdapter = ForceFallbackAdapterEmpty;
    type CompatibleSurface = CompatibleSurfaceEmpty;
}
pub struct SetPowerPreference<CS>(CS);
impl<S, CS: State<S>> State<S> for SetPowerPreference<CS> {
    type PowerPreference = PowerPreferenceValue;
    type ForceFallbackAdapter = CS::ForceFallbackAdapter;
    type CompatibleSurface = CS::CompatibleSurface;
}
pub struct SetForceFallbackAdapter<CS>(CS);
impl<S, CS: State<S>> State<S> for SetForceFallbackAdapter<CS> {
    type PowerPreference = CS::PowerPreference;
    type ForceFallbackAdapter = ForceFallbackAdapterValue;
    type CompatibleSurface = CS::CompatibleSurface;
}
pub struct SetCompatibleSurface<CS>(CS);
impl<S, CS: State<S>> State<S> for SetCompatibleSurface<CS> {
    type PowerPreference = CS::PowerPreference;
    type ForceFallbackAdapter = CS::ForceFallbackAdapter;
    type CompatibleSurface = CompatibleSurfaceValue<S>;
}
impl<S, CS: State<S>> RequestAdapterOptionsBaseBuilder<S, CS> {
    #[doc = "Setter for [wgpu_27::RequestAdapterOptionsBase::power_preference]. Optional, defaults to [wgpu_27::PowerPreference::None].\n"]
    pub fn power_preference(
        self,
        power_preference: wgpu_27::PowerPreference,
    ) -> RequestAdapterOptionsBaseBuilder<S, SetPowerPreference<CS>>
    where
        CS::PowerPreference: PowerPreferenceIsEmpty,
    {
        RequestAdapterOptionsBaseBuilder {
            power_preference: PowerPreferenceValue(power_preference),
            force_fallback_adapter: self.force_fallback_adapter,
            compatible_surface: self.compatible_surface,
        }
    }
    #[doc = "Setter for [wgpu_27::RequestAdapterOptionsBase::force_fallback_adapter]. Optional, defaults to `false`.\n"]
    pub fn force_fallback_adapter(
        self,
        force_fallback_adapter: bool,
    ) -> RequestAdapterOptionsBaseBuilder<S, SetForceFallbackAdapter<CS>>
    where
        CS::ForceFallbackAdapter: ForceFallbackAdapterIsEmpty,
    {
        RequestAdapterOptionsBaseBuilder {
            power_preference: self.power_preference,
            force_fallback_adapter: ForceFallbackAdapterValue(force_fallback_adapter),
            compatible_surface: self.compatible_surface,
        }
    }
    #[doc = "Setter for [wgpu_27::RequestAdapterOptionsBase::compatible_surface]. Optional, defaults to `None`.\n"]
    pub fn compatible_surface(
        self,
        compatible_surface: S,
    ) -> RequestAdapterOptionsBaseBuilder<S, SetCompatibleSurface<CS>>
    where
        CS::CompatibleSurface: CompatibleSurfaceIsEmpty,
    {
        RequestAdapterOptionsBaseBuilder {
            power_preference: self.power_preference,
            force_fallback_adapter: self.force_fallback_adapter,
            compatible_surface: CompatibleSurfaceValue(Some(compatible_surface)),
        }
    }
    #[doc = "Setter for [wgpu_27::RequestAdapterOptionsBase::compatible_surface]. Optional, defaults to `None`.\n"]
    pub fn maybe_compatible_surface(
        self,
        compatible_surface: Option<S>,
    ) -> RequestAdapterOptionsBaseBuilder<S, SetCompatibleSurface<CS>>
    where
        CS::CompatibleSurface: CompatibleSurfaceIsEmpty,
    {
        RequestAdapterOptionsBaseBuilder {
            power_preference: self.power_preference,
            force_fallback_adapter: self.force_fallback_adapter,
            compatible_surface: CompatibleSurfaceValue(compatible_surface),
        }
    }
}
pub trait Complete<S>:
    State<
    S,
    PowerPreference: IsSetPowerPreference,
    ForceFallbackAdapter: IsSetForceFallbackAdapter,
    CompatibleSurface: IsSetCompatibleSurface<S>,
>
{
}
impl<
        S,
        CS: State<
            S,
            PowerPreference: IsSetPowerPreference,
            ForceFallbackAdapter: IsSetForceFallbackAdapter,
            CompatibleSurface: IsSetCompatibleSurface<S>,
        >,
    > Complete<S> for CS
{
}
impl<S, CS: Complete<S>> RequestAdapterOptionsBaseBuilder<S, CS> {
    pub fn build(self) -> wgpu_27::RequestAdapterOptionsBase<S> {
        wgpu_27::RequestAdapterOptionsBase {
            power_preference: IsSetPowerPreference::get(self.power_preference),
            force_fallback_adapter: IsSetForceFallbackAdapter::get(self.force_fallback_adapter),
            compatible_surface: IsSetCompatibleSurface::get(self.compatible_surface),
        }
    }
}
impl<S> Nested<wgpu_27::RequestAdapterOptionsBase<S>> for wgpu_27::RequestAdapterOptionsBase<S> {
    fn unnest(self) -> wgpu_27::RequestAdapterOptionsBase<S> {
        self
    }
}
impl<S, CS: Complete<S>> Nested<wgpu_27::RequestAdapterOptionsBase<S>>
    for RequestAdapterOptionsBaseBuilder<S, CS>
{
    fn unnest(self) -> wgpu_27::RequestAdapterOptionsBase<S> {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!(
                "{:#?}",
                super::request_adapter_options_base::<u32>().build()
            ),
            format!(
                "{:#?}",
                wgpu_27::RequestAdapterOptionsBase::<u32>::default()
            ),
        );
    }
}
