#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_27::CompilationInfo`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [messages](CompilationInfoBuilder::messages) Required\n"]
pub struct CompilationInfoBuilder<CS: State> {
    messages: CS::Messages,
}
impl CompilationInfoBuilder<Empty> {
    pub fn new() -> CompilationInfoBuilder<Empty> {
        CompilationInfoBuilder {
            messages: MessagesEmpty,
        }
    }
}
#[doc = "\nReturns [CompilationInfoBuilder] for building [`wgpu_27::CompilationInfo`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [messages](CompilationInfoBuilder::messages) Required\n"]
pub fn compilation_info() -> CompilationInfoBuilder<Empty> {
    CompilationInfoBuilder::new()
}
pub struct MessagesEmpty;
impl Field for MessagesEmpty {}
pub trait MessagesIsEmpty {}
impl MessagesIsEmpty for MessagesEmpty {}
pub trait IsSetMessages {
    fn get(self) -> Vec<wgpu_27::CompilationMessage>;
}
pub struct MessagesValue(pub Vec<wgpu_27::CompilationMessage>);
impl Field for MessagesValue {}
impl IsSetMessages for MessagesValue {
    fn get(self) -> Vec<wgpu_27::CompilationMessage> {
        self.0
    }
}
pub trait State {
    type Messages: Field;
}
pub struct Empty;
impl State for Empty {
    type Messages = MessagesEmpty;
}
pub struct SetMessages<CS>(CS);
impl<CS: State> State for SetMessages<CS> {
    type Messages = MessagesValue;
}
impl<CS: State> CompilationInfoBuilder<CS> {
    #[doc = "Setter for [wgpu_27::CompilationInfo::messages]. Required.\n"]
    pub fn messages(
        self,
        messages: Vec<wgpu_27::CompilationMessage>,
    ) -> CompilationInfoBuilder<SetMessages<CS>>
    where
        CS::Messages: MessagesIsEmpty,
    {
        CompilationInfoBuilder {
            messages: MessagesValue(messages),
        }
    }
}
pub trait Complete: State<Messages: IsSetMessages> {}
impl<CS: State<Messages: IsSetMessages>> Complete for CS {}
impl<CS: Complete> CompilationInfoBuilder<CS> {
    pub fn build(self) -> wgpu_27::CompilationInfo {
        wgpu_27::CompilationInfo {
            messages: IsSetMessages::get(self.messages),
        }
    }
}
impl Nested<wgpu_27::CompilationInfo> for wgpu_27::CompilationInfo {
    fn unnest(self) -> wgpu_27::CompilationInfo {
        self
    }
}
impl<CS: Complete> Nested<wgpu_27::CompilationInfo> for CompilationInfoBuilder<CS> {
    fn unnest(self) -> wgpu_27::CompilationInfo {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {}
}
