#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_27::RenderPassColorAttachment`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [view](RenderPassColorAttachmentBuilder::view) Required\n  - [depth_slice](RenderPassColorAttachmentBuilder::depth_slice) Optional, defaults to `None`\n  - [resolve_target](RenderPassColorAttachmentBuilder::resolve_target) Optional, defaults to `None`\n  - [ops](RenderPassColorAttachmentBuilder::ops) Optional, defaults to [wgpu_27::Operations::default()]\n"]
pub struct RenderPassColorAttachmentBuilder<'tex, CS: State<'tex>> {
    view: CS::View,
    depth_slice: CS::DepthSlice,
    resolve_target: CS::ResolveTarget,
    ops: CS::Ops,
}
impl<'tex> RenderPassColorAttachmentBuilder<'tex, Empty> {
    pub fn new() -> RenderPassColorAttachmentBuilder<'tex, Empty> {
        RenderPassColorAttachmentBuilder {
            view: ViewEmpty,
            depth_slice: DepthSliceEmpty,
            resolve_target: ResolveTargetEmpty,
            ops: OpsEmpty,
        }
    }
}
#[doc = "\nReturns [RenderPassColorAttachmentBuilder] for building [`wgpu_27::RenderPassColorAttachment`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [view](RenderPassColorAttachmentBuilder::view) Required\n  - [depth_slice](RenderPassColorAttachmentBuilder::depth_slice) Optional, defaults to `None`\n  - [resolve_target](RenderPassColorAttachmentBuilder::resolve_target) Optional, defaults to `None`\n  - [ops](RenderPassColorAttachmentBuilder::ops) Optional, defaults to [wgpu_27::Operations::default()]\n"]
pub fn render_pass_color_attachment<'tex>() -> RenderPassColorAttachmentBuilder<'tex, Empty> {
    RenderPassColorAttachmentBuilder::new()
}
pub struct ViewEmpty;
impl Field for ViewEmpty {}
pub trait ViewIsEmpty {}
impl ViewIsEmpty for ViewEmpty {}
pub trait IsSetView<'tex> {
    fn get(self) -> &'tex wgpu_27::TextureView;
}
pub struct ViewValue<'tex>(pub &'tex wgpu_27::TextureView);
impl<'tex> Field for ViewValue<'tex> {}
impl<'tex> IsSetView<'tex> for ViewValue<'tex> {
    fn get(self) -> &'tex wgpu_27::TextureView {
        self.0
    }
}
pub struct DepthSliceEmpty;
impl Field for DepthSliceEmpty {}
pub trait DepthSliceIsEmpty {}
impl DepthSliceIsEmpty for DepthSliceEmpty {}
pub trait IsSetDepthSlice {
    fn get(self) -> Option<u32>;
}
impl IsSetDepthSlice for DepthSliceEmpty {
    fn get(self) -> Option<u32> {
        None
    }
}
pub struct DepthSliceValue(pub Option<u32>);
impl Field for DepthSliceValue {}
impl IsSetDepthSlice for DepthSliceValue {
    fn get(self) -> Option<u32> {
        self.0
    }
}
pub struct ResolveTargetEmpty;
impl Field for ResolveTargetEmpty {}
pub trait ResolveTargetIsEmpty {}
impl ResolveTargetIsEmpty for ResolveTargetEmpty {}
pub trait IsSetResolveTarget<'tex> {
    fn get(self) -> Option<&'tex wgpu_27::TextureView>;
}
impl<'tex> IsSetResolveTarget<'tex> for ResolveTargetEmpty {
    fn get(self) -> Option<&'tex wgpu_27::TextureView> {
        None
    }
}
pub struct ResolveTargetValue<'tex>(pub Option<&'tex wgpu_27::TextureView>);
impl<'tex> Field for ResolveTargetValue<'tex> {}
impl<'tex> IsSetResolveTarget<'tex> for ResolveTargetValue<'tex> {
    fn get(self) -> Option<&'tex wgpu_27::TextureView> {
        self.0
    }
}
pub struct OpsEmpty;
impl Field for OpsEmpty {}
pub trait OpsIsEmpty {}
impl OpsIsEmpty for OpsEmpty {}
pub trait IsSetOps {
    fn get(self) -> wgpu_27::Operations<wgpu_27::Color>;
}
impl IsSetOps for OpsEmpty {
    fn get(self) -> wgpu_27::Operations<wgpu_27::Color> {
        wgpu_27::Operations::default()
    }
}
pub struct OpsValue(pub wgpu_27::Operations<wgpu_27::Color>);
impl Field for OpsValue {}
impl IsSetOps for OpsValue {
    fn get(self) -> wgpu_27::Operations<wgpu_27::Color> {
        self.0
    }
}
pub trait State<'tex> {
    type View: Field;
    type DepthSlice: Field;
    type ResolveTarget: Field;
    type Ops: Field;
}
pub struct Empty;
impl<'tex> State<'tex> for Empty {
    type View = ViewEmpty;
    type DepthSlice = DepthSliceEmpty;
    type ResolveTarget = ResolveTargetEmpty;
    type Ops = OpsEmpty;
}
pub struct SetView<CS>(CS);
impl<'tex, CS: State<'tex>> State<'tex> for SetView<CS> {
    type View = ViewValue<'tex>;
    type DepthSlice = CS::DepthSlice;
    type ResolveTarget = CS::ResolveTarget;
    type Ops = CS::Ops;
}
pub struct SetDepthSlice<CS>(CS);
impl<'tex, CS: State<'tex>> State<'tex> for SetDepthSlice<CS> {
    type View = CS::View;
    type DepthSlice = DepthSliceValue;
    type ResolveTarget = CS::ResolveTarget;
    type Ops = CS::Ops;
}
pub struct SetResolveTarget<CS>(CS);
impl<'tex, CS: State<'tex>> State<'tex> for SetResolveTarget<CS> {
    type View = CS::View;
    type DepthSlice = CS::DepthSlice;
    type ResolveTarget = ResolveTargetValue<'tex>;
    type Ops = CS::Ops;
}
pub struct SetOps<CS>(CS);
impl<'tex, CS: State<'tex>> State<'tex> for SetOps<CS> {
    type View = CS::View;
    type DepthSlice = CS::DepthSlice;
    type ResolveTarget = CS::ResolveTarget;
    type Ops = OpsValue;
}
impl<'tex, CS: State<'tex>> RenderPassColorAttachmentBuilder<'tex, CS> {
    #[doc = "Setter for [wgpu_27::RenderPassColorAttachment::view]. Required.\n"]
    pub fn view(
        self,
        view: &'tex wgpu_27::TextureView,
    ) -> RenderPassColorAttachmentBuilder<'tex, SetView<CS>>
    where
        CS::View: ViewIsEmpty,
    {
        RenderPassColorAttachmentBuilder {
            view: ViewValue(view),
            depth_slice: self.depth_slice,
            resolve_target: self.resolve_target,
            ops: self.ops,
        }
    }
    #[doc = "Setter for [wgpu_27::RenderPassColorAttachment::depth_slice]. Optional, defaults to `None`.\n"]
    pub fn depth_slice(
        self,
        depth_slice: u32,
    ) -> RenderPassColorAttachmentBuilder<'tex, SetDepthSlice<CS>>
    where
        CS::DepthSlice: DepthSliceIsEmpty,
    {
        RenderPassColorAttachmentBuilder {
            view: self.view,
            depth_slice: DepthSliceValue(Some(depth_slice)),
            resolve_target: self.resolve_target,
            ops: self.ops,
        }
    }
    #[doc = "Setter for [wgpu_27::RenderPassColorAttachment::depth_slice]. Optional, defaults to `None`.\n"]
    pub fn maybe_depth_slice(
        self,
        depth_slice: Option<u32>,
    ) -> RenderPassColorAttachmentBuilder<'tex, SetDepthSlice<CS>>
    where
        CS::DepthSlice: DepthSliceIsEmpty,
    {
        RenderPassColorAttachmentBuilder {
            view: self.view,
            depth_slice: DepthSliceValue(depth_slice),
            resolve_target: self.resolve_target,
            ops: self.ops,
        }
    }
    #[doc = "Setter for [wgpu_27::RenderPassColorAttachment::resolve_target]. Optional, defaults to `None`.\n"]
    pub fn resolve_target(
        self,
        resolve_target: &'tex wgpu_27::TextureView,
    ) -> RenderPassColorAttachmentBuilder<'tex, SetResolveTarget<CS>>
    where
        CS::ResolveTarget: ResolveTargetIsEmpty,
    {
        RenderPassColorAttachmentBuilder {
            view: self.view,
            depth_slice: self.depth_slice,
            resolve_target: ResolveTargetValue(Some(resolve_target)),
            ops: self.ops,
        }
    }
    #[doc = "Setter for [wgpu_27::RenderPassColorAttachment::resolve_target]. Optional, defaults to `None`.\n"]
    pub fn maybe_resolve_target(
        self,
        resolve_target: Option<&'tex wgpu_27::TextureView>,
    ) -> RenderPassColorAttachmentBuilder<'tex, SetResolveTarget<CS>>
    where
        CS::ResolveTarget: ResolveTargetIsEmpty,
    {
        RenderPassColorAttachmentBuilder {
            view: self.view,
            depth_slice: self.depth_slice,
            resolve_target: ResolveTargetValue(resolve_target),
            ops: self.ops,
        }
    }
    #[doc = "Setter for [wgpu_27::RenderPassColorAttachment::ops]. Optional, defaults to [wgpu_27::Operations::default()].\n"]
    pub fn ops(
        self,
        ops: impl Nested<wgpu_27::Operations<wgpu_27::Color>>,
    ) -> RenderPassColorAttachmentBuilder<'tex, SetOps<CS>>
    where
        CS::Ops: OpsIsEmpty,
    {
        RenderPassColorAttachmentBuilder {
            view: self.view,
            depth_slice: self.depth_slice,
            resolve_target: self.resolve_target,
            ops: OpsValue(Nested::unnest(ops)),
        }
    }
}
pub trait Complete<'tex>:
    State<
    'tex,
    View: IsSetView<'tex>,
    DepthSlice: IsSetDepthSlice,
    ResolveTarget: IsSetResolveTarget<'tex>,
    Ops: IsSetOps,
>
{
}
impl<
        'tex,
        CS: State<
            'tex,
            View: IsSetView<'tex>,
            DepthSlice: IsSetDepthSlice,
            ResolveTarget: IsSetResolveTarget<'tex>,
            Ops: IsSetOps,
        >,
    > Complete<'tex> for CS
{
}
impl<'tex, CS: Complete<'tex>> RenderPassColorAttachmentBuilder<'tex, CS> {
    pub fn build(self) -> wgpu_27::RenderPassColorAttachment<'tex> {
        wgpu_27::RenderPassColorAttachment {
            view: IsSetView::get(self.view),
            depth_slice: IsSetDepthSlice::get(self.depth_slice),
            resolve_target: IsSetResolveTarget::get(self.resolve_target),
            ops: IsSetOps::get(self.ops),
        }
    }
}
impl<'tex> Nested<wgpu_27::RenderPassColorAttachment<'tex>>
    for wgpu_27::RenderPassColorAttachment<'tex>
{
    fn unnest(self) -> wgpu_27::RenderPassColorAttachment<'tex> {
        self
    }
}
impl<'tex, CS: Complete<'tex>> Nested<wgpu_27::RenderPassColorAttachment<'tex>>
    for RenderPassColorAttachmentBuilder<'tex, CS>
{
    fn unnest(self) -> wgpu_27::RenderPassColorAttachment<'tex> {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::IsSetDepthSlice::get(super::DepthSliceEmpty)),
            format!("{:#?}", Option::<u32>::default()),
        );
        assert_eq!(
            format!(
                "{:#?}",
                super::IsSetResolveTarget::get(super::ResolveTargetEmpty)
            ),
            format!("{:#?}", Option::<&wgpu_27::TextureView>::default()),
        );
        assert_eq!(
            format!("{:#?}", super::IsSetOps::get(super::OpsEmpty)),
            format!("{:#?}", wgpu_27::Operations::<wgpu_27::Color>::default()),
        );
    }
}
