#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_27::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_27::TextureTransition`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [texture](TextureTransitionBuilder::texture) Required\n  - [selector](TextureTransitionBuilder::selector) Optional, defaults to `None`\n  - [state](TextureTransitionBuilder::state) Required\n"]
pub struct TextureTransitionBuilder<T, CS: State<T>> {
    texture: CS::Texture,
    selector: CS::Selector,
    state: CS::State,
}
impl<T> TextureTransitionBuilder<T, Empty> {
    pub fn new() -> TextureTransitionBuilder<T, Empty> {
        TextureTransitionBuilder {
            texture: TextureEmpty,
            selector: SelectorEmpty,
            state: StateEmpty,
        }
    }
}
#[doc = "\nReturns [TextureTransitionBuilder] for building [`wgpu_27::TextureTransition`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [texture](TextureTransitionBuilder::texture) Required\n  - [selector](TextureTransitionBuilder::selector) Optional, defaults to `None`\n  - [state](TextureTransitionBuilder::state) Required\n"]
pub fn texture_transition<T>() -> TextureTransitionBuilder<T, Empty> {
    TextureTransitionBuilder::new()
}
pub struct TextureEmpty;
impl Field for TextureEmpty {}
pub trait TextureIsEmpty {}
impl TextureIsEmpty for TextureEmpty {}
pub trait IsSetTexture<T> {
    fn get(self) -> T;
}
pub struct TextureValue<T>(pub T);
impl<T> Field for TextureValue<T> {}
impl<T> IsSetTexture<T> for TextureValue<T> {
    fn get(self) -> T {
        self.0
    }
}
pub struct SelectorEmpty;
impl Field for SelectorEmpty {}
pub trait SelectorIsEmpty {}
impl SelectorIsEmpty for SelectorEmpty {}
pub trait IsSetSelector {
    fn get(self) -> Option<wgpu_27::wgt::TextureSelector>;
}
impl IsSetSelector for SelectorEmpty {
    fn get(self) -> Option<wgpu_27::wgt::TextureSelector> {
        None
    }
}
pub struct SelectorValue(pub Option<wgpu_27::wgt::TextureSelector>);
impl Field for SelectorValue {}
impl IsSetSelector for SelectorValue {
    fn get(self) -> Option<wgpu_27::wgt::TextureSelector> {
        self.0
    }
}
pub struct StateEmpty;
impl Field for StateEmpty {}
pub trait StateIsEmpty {}
impl StateIsEmpty for StateEmpty {}
pub trait IsSetState {
    fn get(self) -> wgpu_27::TextureUses;
}
pub struct StateValue(pub wgpu_27::TextureUses);
impl Field for StateValue {}
impl IsSetState for StateValue {
    fn get(self) -> wgpu_27::TextureUses {
        self.0
    }
}
pub trait State<T> {
    type Texture: Field;
    type Selector: Field;
    type State: Field;
}
pub struct Empty;
impl<T> State<T> for Empty {
    type Texture = TextureEmpty;
    type Selector = SelectorEmpty;
    type State = StateEmpty;
}
pub struct SetTexture<CS>(CS);
impl<T, CS: State<T>> State<T> for SetTexture<CS> {
    type Texture = TextureValue<T>;
    type Selector = CS::Selector;
    type State = CS::State;
}
pub struct SetSelector<CS>(CS);
impl<T, CS: State<T>> State<T> for SetSelector<CS> {
    type Texture = CS::Texture;
    type Selector = SelectorValue;
    type State = CS::State;
}
pub struct SetState<CS>(CS);
impl<T, CS: State<T>> State<T> for SetState<CS> {
    type Texture = CS::Texture;
    type Selector = CS::Selector;
    type State = StateValue;
}
impl<T, CS: State<T>> TextureTransitionBuilder<T, CS> {
    #[doc = "Setter for [wgpu_27::TextureTransition::texture]. Required.\n"]
    pub fn texture(self, texture: T) -> TextureTransitionBuilder<T, SetTexture<CS>>
    where
        CS::Texture: TextureIsEmpty,
    {
        TextureTransitionBuilder {
            texture: TextureValue(texture),
            selector: self.selector,
            state: self.state,
        }
    }
    #[doc = "Setter for [wgpu_27::TextureTransition::selector]. Optional, defaults to `None`.\n"]
    pub fn selector(
        self,
        selector: wgpu_27::wgt::TextureSelector,
    ) -> TextureTransitionBuilder<T, SetSelector<CS>>
    where
        CS::Selector: SelectorIsEmpty,
    {
        TextureTransitionBuilder {
            texture: self.texture,
            selector: SelectorValue(Some(selector)),
            state: self.state,
        }
    }
    #[doc = "Setter for [wgpu_27::TextureTransition::selector]. Optional, defaults to `None`.\n"]
    pub fn maybe_selector(
        self,
        selector: Option<wgpu_27::wgt::TextureSelector>,
    ) -> TextureTransitionBuilder<T, SetSelector<CS>>
    where
        CS::Selector: SelectorIsEmpty,
    {
        TextureTransitionBuilder {
            texture: self.texture,
            selector: SelectorValue(selector),
            state: self.state,
        }
    }
    #[doc = "Setter for [wgpu_27::TextureTransition::state]. Required.\n"]
    pub fn state(self, state: wgpu_27::TextureUses) -> TextureTransitionBuilder<T, SetState<CS>>
    where
        CS::State: StateIsEmpty,
    {
        TextureTransitionBuilder {
            texture: self.texture,
            selector: self.selector,
            state: StateValue(state),
        }
    }
}
pub trait Complete<T>:
    State<T, Texture: IsSetTexture<T>, Selector: IsSetSelector, State: IsSetState>
{
}
impl<T, CS: State<T, Texture: IsSetTexture<T>, Selector: IsSetSelector, State: IsSetState>>
    Complete<T> for CS
{
}
impl<T, CS: Complete<T>> TextureTransitionBuilder<T, CS> {
    pub fn build(self) -> wgpu_27::TextureTransition<T> {
        wgpu_27::TextureTransition {
            texture: IsSetTexture::get(self.texture),
            selector: IsSetSelector::get(self.selector),
            state: IsSetState::get(self.state),
        }
    }
}
impl<T> Nested<wgpu_27::TextureTransition<T>> for wgpu_27::TextureTransition<T> {
    fn unnest(self) -> wgpu_27::TextureTransition<T> {
        self
    }
}
impl<T, CS: Complete<T>> Nested<wgpu_27::TextureTransition<T>> for TextureTransitionBuilder<T, CS> {
    fn unnest(self) -> wgpu_27::TextureTransition<T> {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::IsSetSelector::get(super::SelectorEmpty)),
            format!("{:#?}", Option::<wgpu_27::wgt::TextureSelector>::default()),
        );
    }
}
