[package]
name = "quickgpu_bunnymark"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
pollster = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
quickgpu = { workspace = true }
nanorand = "0.8.0"
png = "0.18.0"
glam = "0.30.9"
web-time = "1.1.0"
