[package]
name = "quickgpu_bunnymark"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
pollster = { workspace = true }
wgpu = "^28.0.0"
winit = { workspace = true }
quickgpu = { path = "../quickgpu", features = ["v28"] }
nanorand = { workspace = true }
png = { workspace = true }
glam = { workspace = true }
web-time = { workspace = true }
bon = "3.9.1"
pastey = "0.2.3"
