// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_28::ExternalTextureTransferFunction`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [a](ExternalTextureTransferFunctionBuilder::a) Optional, defaults to `1.0`\n  - [b](ExternalTextureTransferFunctionBuilder::b) Optional, defaults to `1.0`\n  - [g](ExternalTextureTransferFunctionBuilder::g) Optional, defaults to `1.0`\n  - [k](ExternalTextureTransferFunctionBuilder::k) Optional, defaults to `1.0`\n"]
pub struct ExternalTextureTransferFunctionBuilder<CS: State> {
    a: CS::A,
    b: CS::B,
    g: CS::G,
    k: CS::K,
}
impl ExternalTextureTransferFunctionBuilder<Empty> {
    pub fn new() -> ExternalTextureTransferFunctionBuilder<Empty> {
        ExternalTextureTransferFunctionBuilder {
            a: AEmpty,
            b: BEmpty,
            g: GEmpty,
            k: KEmpty,
        }
    }
}
#[doc = "\nReturns [ExternalTextureTransferFunctionBuilder] for building [`wgpu_28::ExternalTextureTransferFunction`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [a](ExternalTextureTransferFunctionBuilder::a) Optional, defaults to `1.0`\n  - [b](ExternalTextureTransferFunctionBuilder::b) Optional, defaults to `1.0`\n  - [g](ExternalTextureTransferFunctionBuilder::g) Optional, defaults to `1.0`\n  - [k](ExternalTextureTransferFunctionBuilder::k) Optional, defaults to `1.0`\n"]
pub fn external_texture_transfer_function() -> ExternalTextureTransferFunctionBuilder<Empty> {
    ExternalTextureTransferFunctionBuilder::new()
}
pub struct AEmpty;
impl Field for AEmpty {}
pub trait AIsEmpty {}
impl AIsEmpty for AEmpty {}
pub trait IsSetA {
    fn get(self) -> f32;
}
impl IsSetA for AEmpty {
    fn get(self) -> f32 {
        1.0
    }
}
pub struct AValue(pub f32);
impl Field for AValue {}
impl IsSetA for AValue {
    fn get(self) -> f32 {
        self.0
    }
}
pub struct BEmpty;
impl Field for BEmpty {}
pub trait BIsEmpty {}
impl BIsEmpty for BEmpty {}
pub trait IsSetB {
    fn get(self) -> f32;
}
impl IsSetB for BEmpty {
    fn get(self) -> f32 {
        1.0
    }
}
pub struct BValue(pub f32);
impl Field for BValue {}
impl IsSetB for BValue {
    fn get(self) -> f32 {
        self.0
    }
}
pub struct GEmpty;
impl Field for GEmpty {}
pub trait GIsEmpty {}
impl GIsEmpty for GEmpty {}
pub trait IsSetG {
    fn get(self) -> f32;
}
impl IsSetG for GEmpty {
    fn get(self) -> f32 {
        1.0
    }
}
pub struct GValue(pub f32);
impl Field for GValue {}
impl IsSetG for GValue {
    fn get(self) -> f32 {
        self.0
    }
}
pub struct KEmpty;
impl Field for KEmpty {}
pub trait KIsEmpty {}
impl KIsEmpty for KEmpty {}
pub trait IsSetK {
    fn get(self) -> f32;
}
impl IsSetK for KEmpty {
    fn get(self) -> f32 {
        1.0
    }
}
pub struct KValue(pub f32);
impl Field for KValue {}
impl IsSetK for KValue {
    fn get(self) -> f32 {
        self.0
    }
}
pub trait State {
    type A: Field;
    type B: Field;
    type G: Field;
    type K: Field;
}
pub struct Empty;
impl State for Empty {
    type A = AEmpty;
    type B = BEmpty;
    type G = GEmpty;
    type K = KEmpty;
}
pub struct SetA<CS>(CS);
impl<CS: State> State for SetA<CS> {
    type A = AValue;
    type B = CS::B;
    type G = CS::G;
    type K = CS::K;
}
pub struct SetB<CS>(CS);
impl<CS: State> State for SetB<CS> {
    type A = CS::A;
    type B = BValue;
    type G = CS::G;
    type K = CS::K;
}
pub struct SetG<CS>(CS);
impl<CS: State> State for SetG<CS> {
    type A = CS::A;
    type B = CS::B;
    type G = GValue;
    type K = CS::K;
}
pub struct SetK<CS>(CS);
impl<CS: State> State for SetK<CS> {
    type A = CS::A;
    type B = CS::B;
    type G = CS::G;
    type K = KValue;
}
impl<CS: State> ExternalTextureTransferFunctionBuilder<CS> {
    #[doc = "Setter for [wgpu_28::ExternalTextureTransferFunction::a]. Optional, defaults to `1.0`.\n"]
    pub fn a(self, a: f32) -> ExternalTextureTransferFunctionBuilder<SetA<CS>>
    where
        CS::A: AIsEmpty,
    {
        ExternalTextureTransferFunctionBuilder {
            a: AValue(a),
            b: self.b,
            g: self.g,
            k: self.k,
        }
    }
    #[doc = "Setter for [wgpu_28::ExternalTextureTransferFunction::b]. Optional, defaults to `1.0`.\n"]
    pub fn b(self, b: f32) -> ExternalTextureTransferFunctionBuilder<SetB<CS>>
    where
        CS::B: BIsEmpty,
    {
        ExternalTextureTransferFunctionBuilder {
            a: self.a,
            b: BValue(b),
            g: self.g,
            k: self.k,
        }
    }
    #[doc = "Setter for [wgpu_28::ExternalTextureTransferFunction::g]. Optional, defaults to `1.0`.\n"]
    pub fn g(self, g: f32) -> ExternalTextureTransferFunctionBuilder<SetG<CS>>
    where
        CS::G: GIsEmpty,
    {
        ExternalTextureTransferFunctionBuilder {
            a: self.a,
            b: self.b,
            g: GValue(g),
            k: self.k,
        }
    }
    #[doc = "Setter for [wgpu_28::ExternalTextureTransferFunction::k]. Optional, defaults to `1.0`.\n"]
    pub fn k(self, k: f32) -> ExternalTextureTransferFunctionBuilder<SetK<CS>>
    where
        CS::K: KIsEmpty,
    {
        ExternalTextureTransferFunctionBuilder {
            a: self.a,
            b: self.b,
            g: self.g,
            k: KValue(k),
        }
    }
}
pub trait Complete: State<A: IsSetA, B: IsSetB, G: IsSetG, K: IsSetK> {}
impl<CS: State<A: IsSetA, B: IsSetB, G: IsSetG, K: IsSetK>> Complete for CS {}
impl<CS: Complete> ExternalTextureTransferFunctionBuilder<CS> {
    pub fn build(self) -> wgpu_28::ExternalTextureTransferFunction {
        wgpu_28::ExternalTextureTransferFunction {
            a: IsSetA::get(self.a),
            b: IsSetB::get(self.b),
            g: IsSetG::get(self.g),
            k: IsSetK::get(self.k),
        }
    }
}
impl Nested<wgpu_28::ExternalTextureTransferFunction> for wgpu_28::ExternalTextureTransferFunction {
    fn unnest(self) -> wgpu_28::ExternalTextureTransferFunction {
        self
    }
}
impl<CS: Complete> Nested<wgpu_28::ExternalTextureTransferFunction>
    for ExternalTextureTransferFunctionBuilder<CS>
{
    fn unnest(self) -> wgpu_28::ExternalTextureTransferFunction {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::external_texture_transfer_function().build()),
            format!("{:#?}", wgpu_28::ExternalTextureTransferFunction::default()),
        );
    }
}
