// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_28::MemoryBudgetThresholds`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [for_resource_creation](MemoryBudgetThresholdsBuilder::for_resource_creation) Optional, defaults to `None`\n  - [for_device_loss](MemoryBudgetThresholdsBuilder::for_device_loss) Optional, defaults to `None`\n"]
pub struct MemoryBudgetThresholdsBuilder<CS: State> {
    for_resource_creation: CS::ForResourceCreation,
    for_device_loss: CS::ForDeviceLoss,
}
impl MemoryBudgetThresholdsBuilder<Empty> {
    pub fn new() -> MemoryBudgetThresholdsBuilder<Empty> {
        MemoryBudgetThresholdsBuilder {
            for_resource_creation: ForResourceCreationEmpty,
            for_device_loss: ForDeviceLossEmpty,
        }
    }
}
#[doc = "\nReturns [MemoryBudgetThresholdsBuilder] for building [`wgpu_28::MemoryBudgetThresholds`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [for_resource_creation](MemoryBudgetThresholdsBuilder::for_resource_creation) Optional, defaults to `None`\n  - [for_device_loss](MemoryBudgetThresholdsBuilder::for_device_loss) Optional, defaults to `None`\n"]
pub fn memory_budget_thresholds() -> MemoryBudgetThresholdsBuilder<Empty> {
    MemoryBudgetThresholdsBuilder::new()
}
pub struct ForResourceCreationEmpty;
impl Field for ForResourceCreationEmpty {}
pub trait ForResourceCreationIsEmpty {}
impl ForResourceCreationIsEmpty for ForResourceCreationEmpty {}
pub trait IsSetForResourceCreation {
    fn get(self) -> Option<u8>;
}
impl IsSetForResourceCreation for ForResourceCreationEmpty {
    fn get(self) -> Option<u8> {
        None
    }
}
pub struct ForResourceCreationValue(pub Option<u8>);
impl Field for ForResourceCreationValue {}
impl IsSetForResourceCreation for ForResourceCreationValue {
    fn get(self) -> Option<u8> {
        self.0
    }
}
pub struct ForDeviceLossEmpty;
impl Field for ForDeviceLossEmpty {}
pub trait ForDeviceLossIsEmpty {}
impl ForDeviceLossIsEmpty for ForDeviceLossEmpty {}
pub trait IsSetForDeviceLoss {
    fn get(self) -> Option<u8>;
}
impl IsSetForDeviceLoss for ForDeviceLossEmpty {
    fn get(self) -> Option<u8> {
        None
    }
}
pub struct ForDeviceLossValue(pub Option<u8>);
impl Field for ForDeviceLossValue {}
impl IsSetForDeviceLoss for ForDeviceLossValue {
    fn get(self) -> Option<u8> {
        self.0
    }
}
pub trait State {
    type ForResourceCreation: Field;
    type ForDeviceLoss: Field;
}
pub struct Empty;
impl State for Empty {
    type ForResourceCreation = ForResourceCreationEmpty;
    type ForDeviceLoss = ForDeviceLossEmpty;
}
pub struct SetForResourceCreation<CS>(CS);
impl<CS: State> State for SetForResourceCreation<CS> {
    type ForResourceCreation = ForResourceCreationValue;
    type ForDeviceLoss = CS::ForDeviceLoss;
}
pub struct SetForDeviceLoss<CS>(CS);
impl<CS: State> State for SetForDeviceLoss<CS> {
    type ForResourceCreation = CS::ForResourceCreation;
    type ForDeviceLoss = ForDeviceLossValue;
}
impl<CS: State> MemoryBudgetThresholdsBuilder<CS> {
    #[doc = "Setter for [wgpu_28::MemoryBudgetThresholds::for_resource_creation]. Optional, defaults to `None`.\n"]
    pub fn for_resource_creation(
        self,
        for_resource_creation: u8,
    ) -> MemoryBudgetThresholdsBuilder<SetForResourceCreation<CS>>
    where
        CS::ForResourceCreation: ForResourceCreationIsEmpty,
    {
        MemoryBudgetThresholdsBuilder {
            for_resource_creation: ForResourceCreationValue(Some(for_resource_creation)),
            for_device_loss: self.for_device_loss,
        }
    }
    #[doc = "Setter for [wgpu_28::MemoryBudgetThresholds::for_resource_creation]. Optional, defaults to `None`.\n"]
    pub fn maybe_for_resource_creation(
        self,
        for_resource_creation: Option<u8>,
    ) -> MemoryBudgetThresholdsBuilder<SetForResourceCreation<CS>>
    where
        CS::ForResourceCreation: ForResourceCreationIsEmpty,
    {
        MemoryBudgetThresholdsBuilder {
            for_resource_creation: ForResourceCreationValue(for_resource_creation),
            for_device_loss: self.for_device_loss,
        }
    }
    #[doc = "Setter for [wgpu_28::MemoryBudgetThresholds::for_device_loss]. Optional, defaults to `None`.\n"]
    pub fn for_device_loss(
        self,
        for_device_loss: u8,
    ) -> MemoryBudgetThresholdsBuilder<SetForDeviceLoss<CS>>
    where
        CS::ForDeviceLoss: ForDeviceLossIsEmpty,
    {
        MemoryBudgetThresholdsBuilder {
            for_resource_creation: self.for_resource_creation,
            for_device_loss: ForDeviceLossValue(Some(for_device_loss)),
        }
    }
    #[doc = "Setter for [wgpu_28::MemoryBudgetThresholds::for_device_loss]. Optional, defaults to `None`.\n"]
    pub fn maybe_for_device_loss(
        self,
        for_device_loss: Option<u8>,
    ) -> MemoryBudgetThresholdsBuilder<SetForDeviceLoss<CS>>
    where
        CS::ForDeviceLoss: ForDeviceLossIsEmpty,
    {
        MemoryBudgetThresholdsBuilder {
            for_resource_creation: self.for_resource_creation,
            for_device_loss: ForDeviceLossValue(for_device_loss),
        }
    }
}
pub trait Complete:
    State<ForResourceCreation: IsSetForResourceCreation, ForDeviceLoss: IsSetForDeviceLoss>
{
}
impl<
        CS: State<ForResourceCreation: IsSetForResourceCreation, ForDeviceLoss: IsSetForDeviceLoss>,
    > Complete for CS
{
}
impl<CS: Complete> MemoryBudgetThresholdsBuilder<CS> {
    pub fn build(self) -> wgpu_28::MemoryBudgetThresholds {
        wgpu_28::MemoryBudgetThresholds {
            for_resource_creation: IsSetForResourceCreation::get(self.for_resource_creation),
            for_device_loss: IsSetForDeviceLoss::get(self.for_device_loss),
        }
    }
}
impl Nested<wgpu_28::MemoryBudgetThresholds> for wgpu_28::MemoryBudgetThresholds {
    fn unnest(self) -> wgpu_28::MemoryBudgetThresholds {
        self
    }
}
impl<CS: Complete> Nested<wgpu_28::MemoryBudgetThresholds> for MemoryBudgetThresholdsBuilder<CS> {
    fn unnest(self) -> wgpu_28::MemoryBudgetThresholds {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::memory_budget_thresholds().build()),
            format!("{:#?}", wgpu_28::MemoryBudgetThresholds::default()),
        );
    }
}
