// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_28::RequestAdapterOptions`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [power_preference](RequestAdapterOptionsBuilder::power_preference) Optional, defaults to [wgpu_28::PowerPreference::None]\n  - [force_fallback_adapter](RequestAdapterOptionsBuilder::force_fallback_adapter) Optional, defaults to `false`\n  - [compatible_surface](RequestAdapterOptionsBuilder::compatible_surface) Optional, defaults to `None`\n"]
pub struct RequestAdapterOptionsBuilder<'a, 'b: 'a, CS: State<'a, 'b>> {
    power_preference: CS::PowerPreference,
    force_fallback_adapter: CS::ForceFallbackAdapter,
    compatible_surface: CS::CompatibleSurface,
}
impl<'a, 'b: 'a> RequestAdapterOptionsBuilder<'a, 'b, Empty> {
    pub fn new() -> RequestAdapterOptionsBuilder<'a, 'b, Empty> {
        RequestAdapterOptionsBuilder {
            power_preference: PowerPreferenceEmpty,
            force_fallback_adapter: ForceFallbackAdapterEmpty,
            compatible_surface: CompatibleSurfaceEmpty,
        }
    }
}
#[doc = "\nReturns [RequestAdapterOptionsBuilder] for building [`wgpu_28::RequestAdapterOptions`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [power_preference](RequestAdapterOptionsBuilder::power_preference) Optional, defaults to [wgpu_28::PowerPreference::None]\n  - [force_fallback_adapter](RequestAdapterOptionsBuilder::force_fallback_adapter) Optional, defaults to `false`\n  - [compatible_surface](RequestAdapterOptionsBuilder::compatible_surface) Optional, defaults to `None`\n"]
pub fn request_adapter_options<'a, 'b: 'a>() -> RequestAdapterOptionsBuilder<'a, 'b, Empty> {
    RequestAdapterOptionsBuilder::new()
}
pub struct PowerPreferenceEmpty;
impl Field for PowerPreferenceEmpty {}
pub trait PowerPreferenceIsEmpty {}
impl PowerPreferenceIsEmpty for PowerPreferenceEmpty {}
pub trait IsSetPowerPreference {
    fn get(self) -> wgpu_28::PowerPreference;
}
impl IsSetPowerPreference for PowerPreferenceEmpty {
    fn get(self) -> wgpu_28::PowerPreference {
        wgpu_28::PowerPreference::None
    }
}
pub struct PowerPreferenceValue(pub wgpu_28::PowerPreference);
impl Field for PowerPreferenceValue {}
impl IsSetPowerPreference for PowerPreferenceValue {
    fn get(self) -> wgpu_28::PowerPreference {
        self.0
    }
}
pub struct ForceFallbackAdapterEmpty;
impl Field for ForceFallbackAdapterEmpty {}
pub trait ForceFallbackAdapterIsEmpty {}
impl ForceFallbackAdapterIsEmpty for ForceFallbackAdapterEmpty {}
pub trait IsSetForceFallbackAdapter {
    fn get(self) -> bool;
}
impl IsSetForceFallbackAdapter for ForceFallbackAdapterEmpty {
    fn get(self) -> bool {
        false
    }
}
pub struct ForceFallbackAdapterValue(pub bool);
impl Field for ForceFallbackAdapterValue {}
impl IsSetForceFallbackAdapter for ForceFallbackAdapterValue {
    fn get(self) -> bool {
        self.0
    }
}
pub struct CompatibleSurfaceEmpty;
impl Field for CompatibleSurfaceEmpty {}
pub trait CompatibleSurfaceIsEmpty {}
impl CompatibleSurfaceIsEmpty for CompatibleSurfaceEmpty {}
pub trait IsSetCompatibleSurface<'a, 'b> {
    fn get(self) -> Option<&'a wgpu_28::Surface<'b>>;
}
impl<'a, 'b> IsSetCompatibleSurface<'a, 'b> for CompatibleSurfaceEmpty {
    fn get(self) -> Option<&'a wgpu_28::Surface<'b>> {
        None
    }
}
pub struct CompatibleSurfaceValue<'a, 'b>(pub Option<&'a wgpu_28::Surface<'b>>);
impl<'a, 'b> Field for CompatibleSurfaceValue<'a, 'b> {}
impl<'a, 'b> IsSetCompatibleSurface<'a, 'b> for CompatibleSurfaceValue<'a, 'b> {
    fn get(self) -> Option<&'a wgpu_28::Surface<'b>> {
        self.0
    }
}
pub trait State<'a, 'b: 'a> {
    type PowerPreference: Field;
    type ForceFallbackAdapter: Field;
    type CompatibleSurface: Field;
}
pub struct Empty;
impl<'a, 'b: 'a> State<'a, 'b> for Empty {
    type PowerPreference = PowerPreferenceEmpty;
    type ForceFallbackAdapter = ForceFallbackAdapterEmpty;
    type CompatibleSurface = CompatibleSurfaceEmpty;
}
pub struct SetPowerPreference<CS>(CS);
impl<'a, 'b: 'a, CS: State<'a, 'b>> State<'a, 'b> for SetPowerPreference<CS> {
    type PowerPreference = PowerPreferenceValue;
    type ForceFallbackAdapter = CS::ForceFallbackAdapter;
    type CompatibleSurface = CS::CompatibleSurface;
}
pub struct SetForceFallbackAdapter<CS>(CS);
impl<'a, 'b: 'a, CS: State<'a, 'b>> State<'a, 'b> for SetForceFallbackAdapter<CS> {
    type PowerPreference = CS::PowerPreference;
    type ForceFallbackAdapter = ForceFallbackAdapterValue;
    type CompatibleSurface = CS::CompatibleSurface;
}
pub struct SetCompatibleSurface<CS>(CS);
impl<'a, 'b: 'a, CS: State<'a, 'b>> State<'a, 'b> for SetCompatibleSurface<CS> {
    type PowerPreference = CS::PowerPreference;
    type ForceFallbackAdapter = CS::ForceFallbackAdapter;
    type CompatibleSurface = CompatibleSurfaceValue<'a, 'b>;
}
impl<'a, 'b: 'a, CS: State<'a, 'b>> RequestAdapterOptionsBuilder<'a, 'b, CS> {
    #[doc = "Setter for [wgpu_28::RequestAdapterOptions::power_preference]. Optional, defaults to [wgpu_28::PowerPreference::None].\n"]
    pub fn power_preference(
        self,
        power_preference: wgpu_28::PowerPreference,
    ) -> RequestAdapterOptionsBuilder<'a, 'b, SetPowerPreference<CS>>
    where
        CS::PowerPreference: PowerPreferenceIsEmpty,
    {
        RequestAdapterOptionsBuilder {
            power_preference: PowerPreferenceValue(power_preference),
            force_fallback_adapter: self.force_fallback_adapter,
            compatible_surface: self.compatible_surface,
        }
    }
    #[doc = "Setter for [wgpu_28::RequestAdapterOptions::force_fallback_adapter]. Optional, defaults to `false`.\n"]
    pub fn force_fallback_adapter(
        self,
        force_fallback_adapter: bool,
    ) -> RequestAdapterOptionsBuilder<'a, 'b, SetForceFallbackAdapter<CS>>
    where
        CS::ForceFallbackAdapter: ForceFallbackAdapterIsEmpty,
    {
        RequestAdapterOptionsBuilder {
            power_preference: self.power_preference,
            force_fallback_adapter: ForceFallbackAdapterValue(force_fallback_adapter),
            compatible_surface: self.compatible_surface,
        }
    }
    #[doc = "Setter for [wgpu_28::RequestAdapterOptions::compatible_surface]. Optional, defaults to `None`.\n"]
    pub fn compatible_surface(
        self,
        compatible_surface: &'a wgpu_28::Surface<'b>,
    ) -> RequestAdapterOptionsBuilder<'a, 'b, SetCompatibleSurface<CS>>
    where
        CS::CompatibleSurface: CompatibleSurfaceIsEmpty,
    {
        RequestAdapterOptionsBuilder {
            power_preference: self.power_preference,
            force_fallback_adapter: self.force_fallback_adapter,
            compatible_surface: CompatibleSurfaceValue(Some(compatible_surface)),
        }
    }
    #[doc = "Setter for [wgpu_28::RequestAdapterOptions::compatible_surface]. Optional, defaults to `None`.\n"]
    pub fn maybe_compatible_surface(
        self,
        compatible_surface: Option<&'a wgpu_28::Surface<'b>>,
    ) -> RequestAdapterOptionsBuilder<'a, 'b, SetCompatibleSurface<CS>>
    where
        CS::CompatibleSurface: CompatibleSurfaceIsEmpty,
    {
        RequestAdapterOptionsBuilder {
            power_preference: self.power_preference,
            force_fallback_adapter: self.force_fallback_adapter,
            compatible_surface: CompatibleSurfaceValue(compatible_surface),
        }
    }
}
pub trait Complete<'a, 'b: 'a>:
    State<
    'a,
    'b,
    PowerPreference: IsSetPowerPreference,
    ForceFallbackAdapter: IsSetForceFallbackAdapter,
    CompatibleSurface: IsSetCompatibleSurface<'a, 'b>,
>
{
}
impl<
        'a,
        'b: 'a,
        CS: State<
            'a,
            'b,
            PowerPreference: IsSetPowerPreference,
            ForceFallbackAdapter: IsSetForceFallbackAdapter,
            CompatibleSurface: IsSetCompatibleSurface<'a, 'b>,
        >,
    > Complete<'a, 'b> for CS
{
}
impl<'a, 'b: 'a, CS: Complete<'a, 'b>> RequestAdapterOptionsBuilder<'a, 'b, CS> {
    pub fn build(self) -> wgpu_28::RequestAdapterOptions<'a, 'b> {
        wgpu_28::RequestAdapterOptions {
            power_preference: IsSetPowerPreference::get(self.power_preference),
            force_fallback_adapter: IsSetForceFallbackAdapter::get(self.force_fallback_adapter),
            compatible_surface: IsSetCompatibleSurface::get(self.compatible_surface),
        }
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::request_adapter_options().build()),
            format!("{:#?}", wgpu_28::RequestAdapterOptions::default()),
        );
    }
}
