// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_28::ShaderModuleDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [source](ShaderModuleDescriptorBuilder::source) Required\n"]
pub struct ShaderModuleDescriptorBuilder<'a, CS: State<'a>> {
    label: CS::Label,
    source: CS::Source,
}
impl<'a> ShaderModuleDescriptorBuilder<'a, Empty> {
    pub fn new() -> ShaderModuleDescriptorBuilder<'a, Empty> {
        ShaderModuleDescriptorBuilder {
            label: LabelEmpty,
            source: SourceEmpty,
        }
    }
}
#[doc = "\nReturns [ShaderModuleDescriptorBuilder] for building [`wgpu_28::ShaderModuleDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [source](ShaderModuleDescriptorBuilder::source) Required\n"]
pub fn shader_module_descriptor<'a>(
    label: wgpu_28::Label<'a>,
) -> ShaderModuleDescriptorBuilder<'a, SetLabel<Empty>> {
    ShaderModuleDescriptorBuilder::new().label(label)
}
pub struct LabelEmpty;
impl Field for LabelEmpty {}
pub trait LabelIsEmpty {}
impl LabelIsEmpty for LabelEmpty {}
pub trait IsSetLabel<'a> {
    fn get(self) -> wgpu_28::Label<'a>;
}
impl<'a> IsSetLabel<'a> for LabelEmpty {
    fn get(self) -> wgpu_28::Label<'a> {
        None
    }
}
pub struct LabelValue<'a>(pub wgpu_28::Label<'a>);
impl<'a> Field for LabelValue<'a> {}
impl<'a> IsSetLabel<'a> for LabelValue<'a> {
    fn get(self) -> wgpu_28::Label<'a> {
        self.0
    }
}
pub struct SourceEmpty;
impl Field for SourceEmpty {}
pub trait SourceIsEmpty {}
impl SourceIsEmpty for SourceEmpty {}
pub trait IsSetSource<'a> {
    fn get(self) -> wgpu_28::ShaderSource<'a>;
}
pub struct SourceValue<'a>(pub wgpu_28::ShaderSource<'a>);
impl<'a> Field for SourceValue<'a> {}
impl<'a> IsSetSource<'a> for SourceValue<'a> {
    fn get(self) -> wgpu_28::ShaderSource<'a> {
        self.0
    }
}
pub trait State<'a> {
    type Label: Field;
    type Source: Field;
}
pub struct Empty;
impl<'a> State<'a> for Empty {
    type Label = LabelEmpty;
    type Source = SourceEmpty;
}
pub struct SetLabel<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetLabel<CS> {
    type Label = LabelValue<'a>;
    type Source = CS::Source;
}
pub struct SetSource<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetSource<CS> {
    type Label = CS::Label;
    type Source = SourceValue<'a>;
}
impl<'a, CS: State<'a>> ShaderModuleDescriptorBuilder<'a, CS> {
    #[doc = "Setter for [wgpu_28::ShaderModuleDescriptor::label]. Optional, defaults to `None`.\n"]
    pub fn label(self, label: wgpu_28::Label<'a>) -> ShaderModuleDescriptorBuilder<'a, SetLabel<CS>>
    where
        CS::Label: LabelIsEmpty,
    {
        ShaderModuleDescriptorBuilder {
            label: LabelValue(label),
            source: self.source,
        }
    }
    #[doc = "Setter for [wgpu_28::ShaderModuleDescriptor::source]. Required.\n"]
    pub fn source(
        self,
        source: wgpu_28::ShaderSource<'a>,
    ) -> ShaderModuleDescriptorBuilder<'a, SetSource<CS>>
    where
        CS::Source: SourceIsEmpty,
    {
        ShaderModuleDescriptorBuilder {
            label: self.label,
            source: SourceValue(source),
        }
    }
}
pub trait Complete<'a>: State<'a, Label: IsSetLabel<'a>, Source: IsSetSource<'a>> {}
impl<'a, CS: State<'a, Label: IsSetLabel<'a>, Source: IsSetSource<'a>>> Complete<'a> for CS {}
impl<'a, CS: Complete<'a>> ShaderModuleDescriptorBuilder<'a, CS> {
    pub fn build(self) -> wgpu_28::ShaderModuleDescriptor<'a> {
        wgpu_28::ShaderModuleDescriptor {
            label: IsSetLabel::get(self.label),
            source: IsSetSource::get(self.source),
        }
    }
    pub fn create_with(self, device: &wgpu_28::Device) -> wgpu_28::ShaderModule {
        device.create_shader_module(self.build())
    }
}
impl<'a> Nested<wgpu_28::ShaderModuleDescriptor<'a>> for wgpu_28::ShaderModuleDescriptor<'a> {
    fn unnest(self) -> wgpu_28::ShaderModuleDescriptor<'a> {
        self
    }
}
impl<'a, CS: Complete<'a>> Nested<wgpu_28::ShaderModuleDescriptor<'a>>
    for ShaderModuleDescriptorBuilder<'a, CS>
{
    fn unnest(self) -> wgpu_28::ShaderModuleDescriptor<'a> {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::IsSetLabel::get(super::LabelEmpty)),
            format!("{:#?}", wgpu_28::Label::default()),
        );
    }
}
