[package]
name = "xtask"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
convert_case = { workspace = true }
env_logger = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
log = { workspace = true }
duct = { workspace = true }
discover_exports = { workspace = true }
xshell = "0.2.7"
