// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu::BackendOptions`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [gl](BackendOptionsBuilder::gl) Optional, defaults to [wgpu::GlBackendOptions::default()]\n  - [dx12](BackendOptionsBuilder::dx12) Optional, defaults to [wgpu::Dx12BackendOptions::default()]\n  - [noop](BackendOptionsBuilder::noop) Optional, defaults to [wgpu::NoopBackendOptions::default()]\n"]
pub struct BackendOptionsBuilder<CS: State> {
    gl: CS::Gl,
    dx12: CS::Dx12,
    noop: CS::Noop,
}
impl BackendOptionsBuilder<Empty> {
    pub fn new() -> BackendOptionsBuilder<Empty> {
        BackendOptionsBuilder {
            gl: GlEmpty,
            dx12: Dx12Empty,
            noop: NoopEmpty,
        }
    }
}
#[doc = "\nReturns [BackendOptionsBuilder] for building [`wgpu::BackendOptions`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [gl](BackendOptionsBuilder::gl) Optional, defaults to [wgpu::GlBackendOptions::default()]\n  - [dx12](BackendOptionsBuilder::dx12) Optional, defaults to [wgpu::Dx12BackendOptions::default()]\n  - [noop](BackendOptionsBuilder::noop) Optional, defaults to [wgpu::NoopBackendOptions::default()]\n"]
pub fn backend_options() -> BackendOptionsBuilder<Empty> {
    BackendOptionsBuilder::new()
}
pub struct GlEmpty;
impl Field for GlEmpty {}
pub trait GlIsEmpty {}
impl GlIsEmpty for GlEmpty {}
pub trait IsSetGl {
    fn get(self) -> wgpu::GlBackendOptions;
}
impl IsSetGl for GlEmpty {
    fn get(self) -> wgpu::GlBackendOptions {
        wgpu::GlBackendOptions::default()
    }
}
pub struct GlValue(pub wgpu::GlBackendOptions);
impl Field for GlValue {}
impl IsSetGl for GlValue {
    fn get(self) -> wgpu::GlBackendOptions {
        self.0
    }
}
pub struct Dx12Empty;
impl Field for Dx12Empty {}
pub trait Dx12IsEmpty {}
impl Dx12IsEmpty for Dx12Empty {}
pub trait IsSetDx12 {
    fn get(self) -> wgpu::Dx12BackendOptions;
}
impl IsSetDx12 for Dx12Empty {
    fn get(self) -> wgpu::Dx12BackendOptions {
        wgpu::Dx12BackendOptions::default()
    }
}
pub struct Dx12Value(pub wgpu::Dx12BackendOptions);
impl Field for Dx12Value {}
impl IsSetDx12 for Dx12Value {
    fn get(self) -> wgpu::Dx12BackendOptions {
        self.0
    }
}
pub struct NoopEmpty;
impl Field for NoopEmpty {}
pub trait NoopIsEmpty {}
impl NoopIsEmpty for NoopEmpty {}
pub trait IsSetNoop {
    fn get(self) -> wgpu::NoopBackendOptions;
}
impl IsSetNoop for NoopEmpty {
    fn get(self) -> wgpu::NoopBackendOptions {
        wgpu::NoopBackendOptions::default()
    }
}
pub struct NoopValue(pub wgpu::NoopBackendOptions);
impl Field for NoopValue {}
impl IsSetNoop for NoopValue {
    fn get(self) -> wgpu::NoopBackendOptions {
        self.0
    }
}
pub trait State {
    type Gl: Field;
    type Dx12: Field;
    type Noop: Field;
}
pub struct Empty;
impl State for Empty {
    type Gl = GlEmpty;
    type Dx12 = Dx12Empty;
    type Noop = NoopEmpty;
}
pub struct SetGl<CS>(CS);
impl<CS: State> State for SetGl<CS> {
    type Gl = GlValue;
    type Dx12 = CS::Dx12;
    type Noop = CS::Noop;
}
pub struct SetDx12<CS>(CS);
impl<CS: State> State for SetDx12<CS> {
    type Gl = CS::Gl;
    type Dx12 = Dx12Value;
    type Noop = CS::Noop;
}
pub struct SetNoop<CS>(CS);
impl<CS: State> State for SetNoop<CS> {
    type Gl = CS::Gl;
    type Dx12 = CS::Dx12;
    type Noop = NoopValue;
}
impl<CS: State> BackendOptionsBuilder<CS> {
    #[doc = "Setter for [wgpu::BackendOptions::gl]. Optional, defaults to [wgpu::GlBackendOptions::default()].\n"]
    pub fn gl(self, gl: impl Nested<wgpu::GlBackendOptions>) -> BackendOptionsBuilder<SetGl<CS>>
    where
        CS::Gl: GlIsEmpty,
    {
        BackendOptionsBuilder {
            gl: GlValue(Nested::unnest(gl)),
            dx12: self.dx12,
            noop: self.noop,
        }
    }
    #[doc = "Setter for [wgpu::BackendOptions::dx12]. Optional, defaults to [wgpu::Dx12BackendOptions::default()].\n"]
    pub fn dx12(
        self,
        dx12: impl Nested<wgpu::Dx12BackendOptions>,
    ) -> BackendOptionsBuilder<SetDx12<CS>>
    where
        CS::Dx12: Dx12IsEmpty,
    {
        BackendOptionsBuilder {
            gl: self.gl,
            dx12: Dx12Value(Nested::unnest(dx12)),
            noop: self.noop,
        }
    }
    #[doc = "Setter for [wgpu::BackendOptions::noop]. Optional, defaults to [wgpu::NoopBackendOptions::default()].\n"]
    pub fn noop(
        self,
        noop: impl Nested<wgpu::NoopBackendOptions>,
    ) -> BackendOptionsBuilder<SetNoop<CS>>
    where
        CS::Noop: NoopIsEmpty,
    {
        BackendOptionsBuilder {
            gl: self.gl,
            dx12: self.dx12,
            noop: NoopValue(Nested::unnest(noop)),
        }
    }
}
pub trait Complete: State<Gl: IsSetGl, Dx12: IsSetDx12, Noop: IsSetNoop> {}
impl<CS: State<Gl: IsSetGl, Dx12: IsSetDx12, Noop: IsSetNoop>> Complete for CS {}
impl<CS: Complete> BackendOptionsBuilder<CS> {
    pub fn build(self) -> wgpu::BackendOptions {
        wgpu::BackendOptions {
            gl: IsSetGl::get(self.gl),
            dx12: IsSetDx12::get(self.dx12),
            noop: IsSetNoop::get(self.noop),
        }
    }
}
impl Nested<wgpu::BackendOptions> for wgpu::BackendOptions {
    fn unnest(self) -> wgpu::BackendOptions {
        self
    }
}
impl<CS: Complete> Nested<wgpu::BackendOptions> for BackendOptionsBuilder<CS> {
    fn unnest(self) -> wgpu::BackendOptions {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::backend_options().build()),
            format!("{:#?}", wgpu::BackendOptions::default()),
        );
    }
}
