// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu::CommandBufferDescriptor`]\n        "]
pub struct CommandBufferDescriptorBuilder<L: Default, CS: State<L>> {
    label: CS::Label,
}
impl<L: Default> CommandBufferDescriptorBuilder<L, Empty> {
    pub fn new() -> CommandBufferDescriptorBuilder<L, Empty> {
        CommandBufferDescriptorBuilder { label: LabelEmpty }
    }
}
#[doc = "\nReturns [CommandBufferDescriptorBuilder] for building [`wgpu::CommandBufferDescriptor`]\n        "]
pub fn command_buffer_descriptor<L: Default>(
    label: L,
) -> CommandBufferDescriptorBuilder<L, SetLabel<Empty>> {
    CommandBufferDescriptorBuilder::new().label(label)
}
pub struct LabelEmpty;
impl Field for LabelEmpty {}
pub trait LabelIsEmpty {}
impl LabelIsEmpty for LabelEmpty {}
pub trait IsSetLabel<L: Default> {
    fn get(self) -> L;
}
impl<L: Default> IsSetLabel<L> for LabelEmpty {
    fn get(self) -> L {
        L::default()
    }
}
pub struct LabelValue<L: Default>(pub L);
impl<L: Default> Field for LabelValue<L> {}
impl<L: Default> IsSetLabel<L> for LabelValue<L> {
    fn get(self) -> L {
        self.0
    }
}
pub trait State<L: Default> {
    type Label: Field;
}
pub struct Empty;
impl<L: Default> State<L> for Empty {
    type Label = LabelEmpty;
}
pub struct SetLabel<CS>(CS);
impl<L: Default, CS: State<L>> State<L> for SetLabel<CS> {
    type Label = LabelValue<L>;
}
impl<L: Default, CS: State<L>> CommandBufferDescriptorBuilder<L, CS> {
    #[doc = "Setter for [wgpu::CommandBufferDescriptor::label]. Optional, defaults to [L::default()].\n"]
    pub fn label(self, label: L) -> CommandBufferDescriptorBuilder<L, SetLabel<CS>>
    where
        CS::Label: LabelIsEmpty,
    {
        CommandBufferDescriptorBuilder {
            label: LabelValue(label),
        }
    }
}
pub trait Complete<L: Default>: State<L, Label: IsSetLabel<L>> {}
impl<L: Default, CS: State<L, Label: IsSetLabel<L>>> Complete<L> for CS {}
impl<L: Default, CS: Complete<L>> CommandBufferDescriptorBuilder<L, CS> {
    pub fn build(self) -> wgpu::CommandBufferDescriptor<L> {
        wgpu::CommandBufferDescriptor {
            label: IsSetLabel::get(self.label),
        }
    }
}
impl<L: Default> Nested<wgpu::CommandBufferDescriptor<L>> for wgpu::CommandBufferDescriptor<L> {
    fn unnest(self) -> wgpu::CommandBufferDescriptor<L> {
        self
    }
}
impl<L: Default, CS: Complete<L>> Nested<wgpu::CommandBufferDescriptor<L>>
    for CommandBufferDescriptorBuilder<L, CS>
{
    fn unnest(self) -> wgpu::CommandBufferDescriptor<L> {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!(
                "{:#?}",
                super::command_buffer_descriptor::<Option<&str>>(Option::<&str>::None).build()
            ),
            format!(
                "{:#?}",
                wgpu::CommandBufferDescriptor::<Option<&str>>::default()
            ),
        );
    }
}
