// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu::DepthStencilState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [format](DepthStencilStateBuilder::format) Required\n  - [depth_write_enabled](DepthStencilStateBuilder::depth_write_enabled) Optional, defaults to `None`\n  - [depth_compare](DepthStencilStateBuilder::depth_compare) Optional, defaults to `None`\n  - [stencil](DepthStencilStateBuilder::stencil) Optional, defaults to [wgpu::StencilState::default()]\n  - [bias](DepthStencilStateBuilder::bias) Optional, defaults to [wgpu::DepthBiasState::default()]\n"]
pub struct DepthStencilStateBuilder<CS: State> {
    format: CS::Format,
    depth_write_enabled: CS::DepthWriteEnabled,
    depth_compare: CS::DepthCompare,
    stencil: CS::Stencil,
    bias: CS::Bias,
}
impl DepthStencilStateBuilder<Empty> {
    pub fn new() -> DepthStencilStateBuilder<Empty> {
        DepthStencilStateBuilder {
            format: FormatEmpty,
            depth_write_enabled: DepthWriteEnabledEmpty,
            depth_compare: DepthCompareEmpty,
            stencil: StencilEmpty,
            bias: BiasEmpty,
        }
    }
}
#[doc = "\nReturns [DepthStencilStateBuilder] for building [`wgpu::DepthStencilState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [format](DepthStencilStateBuilder::format) Required\n  - [depth_write_enabled](DepthStencilStateBuilder::depth_write_enabled) Optional, defaults to `None`\n  - [depth_compare](DepthStencilStateBuilder::depth_compare) Optional, defaults to `None`\n  - [stencil](DepthStencilStateBuilder::stencil) Optional, defaults to [wgpu::StencilState::default()]\n  - [bias](DepthStencilStateBuilder::bias) Optional, defaults to [wgpu::DepthBiasState::default()]\n"]
pub fn depth_stencil_state() -> DepthStencilStateBuilder<Empty> {
    DepthStencilStateBuilder::new()
}
pub struct FormatEmpty;
impl Field for FormatEmpty {}
pub trait FormatIsEmpty {}
impl FormatIsEmpty for FormatEmpty {}
pub trait IsSetFormat {
    fn get(self) -> wgpu::TextureFormat;
}
pub struct FormatValue(pub wgpu::TextureFormat);
impl Field for FormatValue {}
impl IsSetFormat for FormatValue {
    fn get(self) -> wgpu::TextureFormat {
        self.0
    }
}
pub struct DepthWriteEnabledEmpty;
impl Field for DepthWriteEnabledEmpty {}
pub trait DepthWriteEnabledIsEmpty {}
impl DepthWriteEnabledIsEmpty for DepthWriteEnabledEmpty {}
pub trait IsSetDepthWriteEnabled {
    fn get(self) -> Option<bool>;
}
impl IsSetDepthWriteEnabled for DepthWriteEnabledEmpty {
    fn get(self) -> Option<bool> {
        None
    }
}
pub struct DepthWriteEnabledValue(pub Option<bool>);
impl Field for DepthWriteEnabledValue {}
impl IsSetDepthWriteEnabled for DepthWriteEnabledValue {
    fn get(self) -> Option<bool> {
        self.0
    }
}
pub struct DepthCompareEmpty;
impl Field for DepthCompareEmpty {}
pub trait DepthCompareIsEmpty {}
impl DepthCompareIsEmpty for DepthCompareEmpty {}
pub trait IsSetDepthCompare {
    fn get(self) -> Option<wgpu::CompareFunction>;
}
impl IsSetDepthCompare for DepthCompareEmpty {
    fn get(self) -> Option<wgpu::CompareFunction> {
        None
    }
}
pub struct DepthCompareValue(pub Option<wgpu::CompareFunction>);
impl Field for DepthCompareValue {}
impl IsSetDepthCompare for DepthCompareValue {
    fn get(self) -> Option<wgpu::CompareFunction> {
        self.0
    }
}
pub struct StencilEmpty;
impl Field for StencilEmpty {}
pub trait StencilIsEmpty {}
impl StencilIsEmpty for StencilEmpty {}
pub trait IsSetStencil {
    fn get(self) -> wgpu::StencilState;
}
impl IsSetStencil for StencilEmpty {
    fn get(self) -> wgpu::StencilState {
        wgpu::StencilState::default()
    }
}
pub struct StencilValue(pub wgpu::StencilState);
impl Field for StencilValue {}
impl IsSetStencil for StencilValue {
    fn get(self) -> wgpu::StencilState {
        self.0
    }
}
pub struct BiasEmpty;
impl Field for BiasEmpty {}
pub trait BiasIsEmpty {}
impl BiasIsEmpty for BiasEmpty {}
pub trait IsSetBias {
    fn get(self) -> wgpu::DepthBiasState;
}
impl IsSetBias for BiasEmpty {
    fn get(self) -> wgpu::DepthBiasState {
        wgpu::DepthBiasState::default()
    }
}
pub struct BiasValue(pub wgpu::DepthBiasState);
impl Field for BiasValue {}
impl IsSetBias for BiasValue {
    fn get(self) -> wgpu::DepthBiasState {
        self.0
    }
}
pub trait State {
    type Format: Field;
    type DepthWriteEnabled: Field;
    type DepthCompare: Field;
    type Stencil: Field;
    type Bias: Field;
}
pub struct Empty;
impl State for Empty {
    type Format = FormatEmpty;
    type DepthWriteEnabled = DepthWriteEnabledEmpty;
    type DepthCompare = DepthCompareEmpty;
    type Stencil = StencilEmpty;
    type Bias = BiasEmpty;
}
pub struct SetFormat<CS>(CS);
impl<CS: State> State for SetFormat<CS> {
    type Format = FormatValue;
    type DepthWriteEnabled = CS::DepthWriteEnabled;
    type DepthCompare = CS::DepthCompare;
    type Stencil = CS::Stencil;
    type Bias = CS::Bias;
}
pub struct SetDepthWriteEnabled<CS>(CS);
impl<CS: State> State for SetDepthWriteEnabled<CS> {
    type Format = CS::Format;
    type DepthWriteEnabled = DepthWriteEnabledValue;
    type DepthCompare = CS::DepthCompare;
    type Stencil = CS::Stencil;
    type Bias = CS::Bias;
}
pub struct SetDepthCompare<CS>(CS);
impl<CS: State> State for SetDepthCompare<CS> {
    type Format = CS::Format;
    type DepthWriteEnabled = CS::DepthWriteEnabled;
    type DepthCompare = DepthCompareValue;
    type Stencil = CS::Stencil;
    type Bias = CS::Bias;
}
pub struct SetStencil<CS>(CS);
impl<CS: State> State for SetStencil<CS> {
    type Format = CS::Format;
    type DepthWriteEnabled = CS::DepthWriteEnabled;
    type DepthCompare = CS::DepthCompare;
    type Stencil = StencilValue;
    type Bias = CS::Bias;
}
pub struct SetBias<CS>(CS);
impl<CS: State> State for SetBias<CS> {
    type Format = CS::Format;
    type DepthWriteEnabled = CS::DepthWriteEnabled;
    type DepthCompare = CS::DepthCompare;
    type Stencil = CS::Stencil;
    type Bias = BiasValue;
}
impl<CS: State> DepthStencilStateBuilder<CS> {
    #[doc = "Setter for [wgpu::DepthStencilState::format]. Required.\n"]
    pub fn format(self, format: wgpu::TextureFormat) -> DepthStencilStateBuilder<SetFormat<CS>>
    where
        CS::Format: FormatIsEmpty,
    {
        DepthStencilStateBuilder {
            format: FormatValue(format),
            depth_write_enabled: self.depth_write_enabled,
            depth_compare: self.depth_compare,
            stencil: self.stencil,
            bias: self.bias,
        }
    }
    #[doc = "Setter for [wgpu::DepthStencilState::depth_write_enabled]. Optional, defaults to `None`.\n"]
    pub fn depth_write_enabled(
        self,
        depth_write_enabled: bool,
    ) -> DepthStencilStateBuilder<SetDepthWriteEnabled<CS>>
    where
        CS::DepthWriteEnabled: DepthWriteEnabledIsEmpty,
    {
        DepthStencilStateBuilder {
            format: self.format,
            depth_write_enabled: DepthWriteEnabledValue(Some(depth_write_enabled)),
            depth_compare: self.depth_compare,
            stencil: self.stencil,
            bias: self.bias,
        }
    }
    #[doc = "Setter for [wgpu::DepthStencilState::depth_write_enabled]. Optional, defaults to `None`.\n"]
    pub fn maybe_depth_write_enabled(
        self,
        depth_write_enabled: Option<bool>,
    ) -> DepthStencilStateBuilder<SetDepthWriteEnabled<CS>>
    where
        CS::DepthWriteEnabled: DepthWriteEnabledIsEmpty,
    {
        DepthStencilStateBuilder {
            format: self.format,
            depth_write_enabled: DepthWriteEnabledValue(depth_write_enabled),
            depth_compare: self.depth_compare,
            stencil: self.stencil,
            bias: self.bias,
        }
    }
    #[doc = "Setter for [wgpu::DepthStencilState::depth_compare]. Optional, defaults to `None`.\n"]
    pub fn depth_compare(
        self,
        depth_compare: wgpu::CompareFunction,
    ) -> DepthStencilStateBuilder<SetDepthCompare<CS>>
    where
        CS::DepthCompare: DepthCompareIsEmpty,
    {
        DepthStencilStateBuilder {
            format: self.format,
            depth_write_enabled: self.depth_write_enabled,
            depth_compare: DepthCompareValue(Some(depth_compare)),
            stencil: self.stencil,
            bias: self.bias,
        }
    }
    #[doc = "Setter for [wgpu::DepthStencilState::depth_compare]. Optional, defaults to `None`.\n"]
    pub fn maybe_depth_compare(
        self,
        depth_compare: Option<wgpu::CompareFunction>,
    ) -> DepthStencilStateBuilder<SetDepthCompare<CS>>
    where
        CS::DepthCompare: DepthCompareIsEmpty,
    {
        DepthStencilStateBuilder {
            format: self.format,
            depth_write_enabled: self.depth_write_enabled,
            depth_compare: DepthCompareValue(depth_compare),
            stencil: self.stencil,
            bias: self.bias,
        }
    }
    #[doc = "Setter for [wgpu::DepthStencilState::stencil]. Optional, defaults to [wgpu::StencilState::default()].\n"]
    pub fn stencil(
        self,
        stencil: impl Nested<wgpu::StencilState>,
    ) -> DepthStencilStateBuilder<SetStencil<CS>>
    where
        CS::Stencil: StencilIsEmpty,
    {
        DepthStencilStateBuilder {
            format: self.format,
            depth_write_enabled: self.depth_write_enabled,
            depth_compare: self.depth_compare,
            stencil: StencilValue(Nested::unnest(stencil)),
            bias: self.bias,
        }
    }
    #[doc = "Setter for [wgpu::DepthStencilState::bias]. Optional, defaults to [wgpu::DepthBiasState::default()].\n"]
    pub fn bias(
        self,
        bias: impl Nested<wgpu::DepthBiasState>,
    ) -> DepthStencilStateBuilder<SetBias<CS>>
    where
        CS::Bias: BiasIsEmpty,
    {
        DepthStencilStateBuilder {
            format: self.format,
            depth_write_enabled: self.depth_write_enabled,
            depth_compare: self.depth_compare,
            stencil: self.stencil,
            bias: BiasValue(Nested::unnest(bias)),
        }
    }
}
pub trait Complete:
    State<
    Format: IsSetFormat,
    DepthWriteEnabled: IsSetDepthWriteEnabled,
    DepthCompare: IsSetDepthCompare,
    Stencil: IsSetStencil,
    Bias: IsSetBias,
>
{
}
impl<
        CS: State<
            Format: IsSetFormat,
            DepthWriteEnabled: IsSetDepthWriteEnabled,
            DepthCompare: IsSetDepthCompare,
            Stencil: IsSetStencil,
            Bias: IsSetBias,
        >,
    > Complete for CS
{
}
impl<CS: Complete> DepthStencilStateBuilder<CS> {
    pub fn build(self) -> wgpu::DepthStencilState {
        wgpu::DepthStencilState {
            format: IsSetFormat::get(self.format),
            depth_write_enabled: IsSetDepthWriteEnabled::get(self.depth_write_enabled),
            depth_compare: IsSetDepthCompare::get(self.depth_compare),
            stencil: IsSetStencil::get(self.stencil),
            bias: IsSetBias::get(self.bias),
        }
    }
}
impl Nested<wgpu::DepthStencilState> for wgpu::DepthStencilState {
    fn unnest(self) -> wgpu::DepthStencilState {
        self
    }
}
impl<CS: Complete> Nested<wgpu::DepthStencilState> for DepthStencilStateBuilder<CS> {
    fn unnest(self) -> wgpu::DepthStencilState {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!(
                "{:#?}",
                super::IsSetDepthWriteEnabled::get(super::DepthWriteEnabledEmpty)
            ),
            format!("{:#?}", Option::<bool>::default()),
        );
        assert_eq!(
            format!(
                "{:#?}",
                super::IsSetDepthCompare::get(super::DepthCompareEmpty)
            ),
            format!("{:#?}", Option::<wgpu::CompareFunction>::default()),
        );
        assert_eq!(
            format!("{:#?}", super::IsSetStencil::get(super::StencilEmpty)),
            format!("{:#?}", wgpu::StencilState::default()),
        );
        assert_eq!(
            format!("{:#?}", super::IsSetBias::get(super::BiasEmpty)),
            format!("{:#?}", wgpu::DepthBiasState::default()),
        );
    }
}
