// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu::util::DrawIndexedIndirectArgs`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [index_count](DrawIndexedIndirectArgsBuilder::index_count) Optional, defaults to `0u32`\n  - [instance_count](DrawIndexedIndirectArgsBuilder::instance_count) Optional, defaults to `0u32`\n  - [first_index](DrawIndexedIndirectArgsBuilder::first_index) Optional, defaults to `0u32`\n  - [base_vertex](DrawIndexedIndirectArgsBuilder::base_vertex) Optional, defaults to `0i32`\n  - [first_instance](DrawIndexedIndirectArgsBuilder::first_instance) Optional, defaults to `0u32`\n"]
pub struct DrawIndexedIndirectArgsBuilder<CS: State> {
    index_count: CS::IndexCount,
    instance_count: CS::InstanceCount,
    first_index: CS::FirstIndex,
    base_vertex: CS::BaseVertex,
    first_instance: CS::FirstInstance,
}
impl DrawIndexedIndirectArgsBuilder<Empty> {
    pub fn new() -> DrawIndexedIndirectArgsBuilder<Empty> {
        DrawIndexedIndirectArgsBuilder {
            index_count: IndexCountEmpty,
            instance_count: InstanceCountEmpty,
            first_index: FirstIndexEmpty,
            base_vertex: BaseVertexEmpty,
            first_instance: FirstInstanceEmpty,
        }
    }
}
#[doc = "\nReturns [DrawIndexedIndirectArgsBuilder] for building [`wgpu::util::DrawIndexedIndirectArgs`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [index_count](DrawIndexedIndirectArgsBuilder::index_count) Optional, defaults to `0u32`\n  - [instance_count](DrawIndexedIndirectArgsBuilder::instance_count) Optional, defaults to `0u32`\n  - [first_index](DrawIndexedIndirectArgsBuilder::first_index) Optional, defaults to `0u32`\n  - [base_vertex](DrawIndexedIndirectArgsBuilder::base_vertex) Optional, defaults to `0i32`\n  - [first_instance](DrawIndexedIndirectArgsBuilder::first_instance) Optional, defaults to `0u32`\n"]
pub fn draw_indexed_indirect_args() -> DrawIndexedIndirectArgsBuilder<Empty> {
    DrawIndexedIndirectArgsBuilder::new()
}
pub struct IndexCountEmpty;
impl Field for IndexCountEmpty {}
pub trait IndexCountIsEmpty {}
impl IndexCountIsEmpty for IndexCountEmpty {}
pub trait IsSetIndexCount {
    fn get(self) -> u32;
}
impl IsSetIndexCount for IndexCountEmpty {
    fn get(self) -> u32 {
        0u32
    }
}
pub struct IndexCountValue(pub u32);
impl Field for IndexCountValue {}
impl IsSetIndexCount for IndexCountValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub struct InstanceCountEmpty;
impl Field for InstanceCountEmpty {}
pub trait InstanceCountIsEmpty {}
impl InstanceCountIsEmpty for InstanceCountEmpty {}
pub trait IsSetInstanceCount {
    fn get(self) -> u32;
}
impl IsSetInstanceCount for InstanceCountEmpty {
    fn get(self) -> u32 {
        0u32
    }
}
pub struct InstanceCountValue(pub u32);
impl Field for InstanceCountValue {}
impl IsSetInstanceCount for InstanceCountValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub struct FirstIndexEmpty;
impl Field for FirstIndexEmpty {}
pub trait FirstIndexIsEmpty {}
impl FirstIndexIsEmpty for FirstIndexEmpty {}
pub trait IsSetFirstIndex {
    fn get(self) -> u32;
}
impl IsSetFirstIndex for FirstIndexEmpty {
    fn get(self) -> u32 {
        0u32
    }
}
pub struct FirstIndexValue(pub u32);
impl Field for FirstIndexValue {}
impl IsSetFirstIndex for FirstIndexValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub struct BaseVertexEmpty;
impl Field for BaseVertexEmpty {}
pub trait BaseVertexIsEmpty {}
impl BaseVertexIsEmpty for BaseVertexEmpty {}
pub trait IsSetBaseVertex {
    fn get(self) -> i32;
}
impl IsSetBaseVertex for BaseVertexEmpty {
    fn get(self) -> i32 {
        0i32
    }
}
pub struct BaseVertexValue(pub i32);
impl Field for BaseVertexValue {}
impl IsSetBaseVertex for BaseVertexValue {
    fn get(self) -> i32 {
        self.0
    }
}
pub struct FirstInstanceEmpty;
impl Field for FirstInstanceEmpty {}
pub trait FirstInstanceIsEmpty {}
impl FirstInstanceIsEmpty for FirstInstanceEmpty {}
pub trait IsSetFirstInstance {
    fn get(self) -> u32;
}
impl IsSetFirstInstance for FirstInstanceEmpty {
    fn get(self) -> u32 {
        0u32
    }
}
pub struct FirstInstanceValue(pub u32);
impl Field for FirstInstanceValue {}
impl IsSetFirstInstance for FirstInstanceValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub trait State {
    type IndexCount: Field;
    type InstanceCount: Field;
    type FirstIndex: Field;
    type BaseVertex: Field;
    type FirstInstance: Field;
}
pub struct Empty;
impl State for Empty {
    type IndexCount = IndexCountEmpty;
    type InstanceCount = InstanceCountEmpty;
    type FirstIndex = FirstIndexEmpty;
    type BaseVertex = BaseVertexEmpty;
    type FirstInstance = FirstInstanceEmpty;
}
pub struct SetIndexCount<CS>(CS);
impl<CS: State> State for SetIndexCount<CS> {
    type IndexCount = IndexCountValue;
    type InstanceCount = CS::InstanceCount;
    type FirstIndex = CS::FirstIndex;
    type BaseVertex = CS::BaseVertex;
    type FirstInstance = CS::FirstInstance;
}
pub struct SetInstanceCount<CS>(CS);
impl<CS: State> State for SetInstanceCount<CS> {
    type IndexCount = CS::IndexCount;
    type InstanceCount = InstanceCountValue;
    type FirstIndex = CS::FirstIndex;
    type BaseVertex = CS::BaseVertex;
    type FirstInstance = CS::FirstInstance;
}
pub struct SetFirstIndex<CS>(CS);
impl<CS: State> State for SetFirstIndex<CS> {
    type IndexCount = CS::IndexCount;
    type InstanceCount = CS::InstanceCount;
    type FirstIndex = FirstIndexValue;
    type BaseVertex = CS::BaseVertex;
    type FirstInstance = CS::FirstInstance;
}
pub struct SetBaseVertex<CS>(CS);
impl<CS: State> State for SetBaseVertex<CS> {
    type IndexCount = CS::IndexCount;
    type InstanceCount = CS::InstanceCount;
    type FirstIndex = CS::FirstIndex;
    type BaseVertex = BaseVertexValue;
    type FirstInstance = CS::FirstInstance;
}
pub struct SetFirstInstance<CS>(CS);
impl<CS: State> State for SetFirstInstance<CS> {
    type IndexCount = CS::IndexCount;
    type InstanceCount = CS::InstanceCount;
    type FirstIndex = CS::FirstIndex;
    type BaseVertex = CS::BaseVertex;
    type FirstInstance = FirstInstanceValue;
}
impl<CS: State> DrawIndexedIndirectArgsBuilder<CS> {
    #[doc = "Setter for [wgpu::util::DrawIndexedIndirectArgs::index_count]. Optional, defaults to `0u32`.\n"]
    pub fn index_count(self, index_count: u32) -> DrawIndexedIndirectArgsBuilder<SetIndexCount<CS>>
    where
        CS::IndexCount: IndexCountIsEmpty,
    {
        DrawIndexedIndirectArgsBuilder {
            index_count: IndexCountValue(index_count),
            instance_count: self.instance_count,
            first_index: self.first_index,
            base_vertex: self.base_vertex,
            first_instance: self.first_instance,
        }
    }
    #[doc = "Setter for [wgpu::util::DrawIndexedIndirectArgs::instance_count]. Optional, defaults to `0u32`.\n"]
    pub fn instance_count(
        self,
        instance_count: u32,
    ) -> DrawIndexedIndirectArgsBuilder<SetInstanceCount<CS>>
    where
        CS::InstanceCount: InstanceCountIsEmpty,
    {
        DrawIndexedIndirectArgsBuilder {
            index_count: self.index_count,
            instance_count: InstanceCountValue(instance_count),
            first_index: self.first_index,
            base_vertex: self.base_vertex,
            first_instance: self.first_instance,
        }
    }
    #[doc = "Setter for [wgpu::util::DrawIndexedIndirectArgs::first_index]. Optional, defaults to `0u32`.\n"]
    pub fn first_index(self, first_index: u32) -> DrawIndexedIndirectArgsBuilder<SetFirstIndex<CS>>
    where
        CS::FirstIndex: FirstIndexIsEmpty,
    {
        DrawIndexedIndirectArgsBuilder {
            index_count: self.index_count,
            instance_count: self.instance_count,
            first_index: FirstIndexValue(first_index),
            base_vertex: self.base_vertex,
            first_instance: self.first_instance,
        }
    }
    #[doc = "Setter for [wgpu::util::DrawIndexedIndirectArgs::base_vertex]. Optional, defaults to `0i32`.\n"]
    pub fn base_vertex(self, base_vertex: i32) -> DrawIndexedIndirectArgsBuilder<SetBaseVertex<CS>>
    where
        CS::BaseVertex: BaseVertexIsEmpty,
    {
        DrawIndexedIndirectArgsBuilder {
            index_count: self.index_count,
            instance_count: self.instance_count,
            first_index: self.first_index,
            base_vertex: BaseVertexValue(base_vertex),
            first_instance: self.first_instance,
        }
    }
    #[doc = "Setter for [wgpu::util::DrawIndexedIndirectArgs::first_instance]. Optional, defaults to `0u32`.\n"]
    pub fn first_instance(
        self,
        first_instance: u32,
    ) -> DrawIndexedIndirectArgsBuilder<SetFirstInstance<CS>>
    where
        CS::FirstInstance: FirstInstanceIsEmpty,
    {
        DrawIndexedIndirectArgsBuilder {
            index_count: self.index_count,
            instance_count: self.instance_count,
            first_index: self.first_index,
            base_vertex: self.base_vertex,
            first_instance: FirstInstanceValue(first_instance),
        }
    }
}
pub trait Complete:
    State<
    IndexCount: IsSetIndexCount,
    InstanceCount: IsSetInstanceCount,
    FirstIndex: IsSetFirstIndex,
    BaseVertex: IsSetBaseVertex,
    FirstInstance: IsSetFirstInstance,
>
{
}
impl<
        CS: State<
            IndexCount: IsSetIndexCount,
            InstanceCount: IsSetInstanceCount,
            FirstIndex: IsSetFirstIndex,
            BaseVertex: IsSetBaseVertex,
            FirstInstance: IsSetFirstInstance,
        >,
    > Complete for CS
{
}
impl<CS: Complete> DrawIndexedIndirectArgsBuilder<CS> {
    pub fn build(self) -> wgpu::util::DrawIndexedIndirectArgs {
        wgpu::util::DrawIndexedIndirectArgs {
            index_count: IsSetIndexCount::get(self.index_count),
            instance_count: IsSetInstanceCount::get(self.instance_count),
            first_index: IsSetFirstIndex::get(self.first_index),
            base_vertex: IsSetBaseVertex::get(self.base_vertex),
            first_instance: IsSetFirstInstance::get(self.first_instance),
        }
    }
}
impl Nested<wgpu::util::DrawIndexedIndirectArgs> for wgpu::util::DrawIndexedIndirectArgs {
    fn unnest(self) -> wgpu::util::DrawIndexedIndirectArgs {
        self
    }
}
impl<CS: Complete> Nested<wgpu::util::DrawIndexedIndirectArgs>
    for DrawIndexedIndirectArgsBuilder<CS>
{
    fn unnest(self) -> wgpu::util::DrawIndexedIndirectArgs {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::draw_indexed_indirect_args().build()),
            format!("{:#?}", wgpu::util::DrawIndexedIndirectArgs::default()),
        );
    }
}
