// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu::util::DrawIndirectArgs`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [vertex_count](DrawIndirectArgsBuilder::vertex_count) Optional, defaults to `0u32`\n  - [instance_count](DrawIndirectArgsBuilder::instance_count) Optional, defaults to `0u32`\n  - [first_vertex](DrawIndirectArgsBuilder::first_vertex) Optional, defaults to `0u32`\n  - [first_instance](DrawIndirectArgsBuilder::first_instance) Optional, defaults to `0u32`\n"]
pub struct DrawIndirectArgsBuilder<CS: State> {
    vertex_count: CS::VertexCount,
    instance_count: CS::InstanceCount,
    first_vertex: CS::FirstVertex,
    first_instance: CS::FirstInstance,
}
impl DrawIndirectArgsBuilder<Empty> {
    pub fn new() -> DrawIndirectArgsBuilder<Empty> {
        DrawIndirectArgsBuilder {
            vertex_count: VertexCountEmpty,
            instance_count: InstanceCountEmpty,
            first_vertex: FirstVertexEmpty,
            first_instance: FirstInstanceEmpty,
        }
    }
}
#[doc = "\nReturns [DrawIndirectArgsBuilder] for building [`wgpu::util::DrawIndirectArgs`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [vertex_count](DrawIndirectArgsBuilder::vertex_count) Optional, defaults to `0u32`\n  - [instance_count](DrawIndirectArgsBuilder::instance_count) Optional, defaults to `0u32`\n  - [first_vertex](DrawIndirectArgsBuilder::first_vertex) Optional, defaults to `0u32`\n  - [first_instance](DrawIndirectArgsBuilder::first_instance) Optional, defaults to `0u32`\n"]
pub fn draw_indirect_args() -> DrawIndirectArgsBuilder<Empty> {
    DrawIndirectArgsBuilder::new()
}
pub struct VertexCountEmpty;
impl Field for VertexCountEmpty {}
pub trait VertexCountIsEmpty {}
impl VertexCountIsEmpty for VertexCountEmpty {}
pub trait IsSetVertexCount {
    fn get(self) -> u32;
}
impl IsSetVertexCount for VertexCountEmpty {
    fn get(self) -> u32 {
        0u32
    }
}
pub struct VertexCountValue(pub u32);
impl Field for VertexCountValue {}
impl IsSetVertexCount for VertexCountValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub struct InstanceCountEmpty;
impl Field for InstanceCountEmpty {}
pub trait InstanceCountIsEmpty {}
impl InstanceCountIsEmpty for InstanceCountEmpty {}
pub trait IsSetInstanceCount {
    fn get(self) -> u32;
}
impl IsSetInstanceCount for InstanceCountEmpty {
    fn get(self) -> u32 {
        0u32
    }
}
pub struct InstanceCountValue(pub u32);
impl Field for InstanceCountValue {}
impl IsSetInstanceCount for InstanceCountValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub struct FirstVertexEmpty;
impl Field for FirstVertexEmpty {}
pub trait FirstVertexIsEmpty {}
impl FirstVertexIsEmpty for FirstVertexEmpty {}
pub trait IsSetFirstVertex {
    fn get(self) -> u32;
}
impl IsSetFirstVertex for FirstVertexEmpty {
    fn get(self) -> u32 {
        0u32
    }
}
pub struct FirstVertexValue(pub u32);
impl Field for FirstVertexValue {}
impl IsSetFirstVertex for FirstVertexValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub struct FirstInstanceEmpty;
impl Field for FirstInstanceEmpty {}
pub trait FirstInstanceIsEmpty {}
impl FirstInstanceIsEmpty for FirstInstanceEmpty {}
pub trait IsSetFirstInstance {
    fn get(self) -> u32;
}
impl IsSetFirstInstance for FirstInstanceEmpty {
    fn get(self) -> u32 {
        0u32
    }
}
pub struct FirstInstanceValue(pub u32);
impl Field for FirstInstanceValue {}
impl IsSetFirstInstance for FirstInstanceValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub trait State {
    type VertexCount: Field;
    type InstanceCount: Field;
    type FirstVertex: Field;
    type FirstInstance: Field;
}
pub struct Empty;
impl State for Empty {
    type VertexCount = VertexCountEmpty;
    type InstanceCount = InstanceCountEmpty;
    type FirstVertex = FirstVertexEmpty;
    type FirstInstance = FirstInstanceEmpty;
}
pub struct SetVertexCount<CS>(CS);
impl<CS: State> State for SetVertexCount<CS> {
    type VertexCount = VertexCountValue;
    type InstanceCount = CS::InstanceCount;
    type FirstVertex = CS::FirstVertex;
    type FirstInstance = CS::FirstInstance;
}
pub struct SetInstanceCount<CS>(CS);
impl<CS: State> State for SetInstanceCount<CS> {
    type VertexCount = CS::VertexCount;
    type InstanceCount = InstanceCountValue;
    type FirstVertex = CS::FirstVertex;
    type FirstInstance = CS::FirstInstance;
}
pub struct SetFirstVertex<CS>(CS);
impl<CS: State> State for SetFirstVertex<CS> {
    type VertexCount = CS::VertexCount;
    type InstanceCount = CS::InstanceCount;
    type FirstVertex = FirstVertexValue;
    type FirstInstance = CS::FirstInstance;
}
pub struct SetFirstInstance<CS>(CS);
impl<CS: State> State for SetFirstInstance<CS> {
    type VertexCount = CS::VertexCount;
    type InstanceCount = CS::InstanceCount;
    type FirstVertex = CS::FirstVertex;
    type FirstInstance = FirstInstanceValue;
}
impl<CS: State> DrawIndirectArgsBuilder<CS> {
    #[doc = "Setter for [wgpu::util::DrawIndirectArgs::vertex_count]. Optional, defaults to `0u32`.\n"]
    pub fn vertex_count(self, vertex_count: u32) -> DrawIndirectArgsBuilder<SetVertexCount<CS>>
    where
        CS::VertexCount: VertexCountIsEmpty,
    {
        DrawIndirectArgsBuilder {
            vertex_count: VertexCountValue(vertex_count),
            instance_count: self.instance_count,
            first_vertex: self.first_vertex,
            first_instance: self.first_instance,
        }
    }
    #[doc = "Setter for [wgpu::util::DrawIndirectArgs::instance_count]. Optional, defaults to `0u32`.\n"]
    pub fn instance_count(
        self,
        instance_count: u32,
    ) -> DrawIndirectArgsBuilder<SetInstanceCount<CS>>
    where
        CS::InstanceCount: InstanceCountIsEmpty,
    {
        DrawIndirectArgsBuilder {
            vertex_count: self.vertex_count,
            instance_count: InstanceCountValue(instance_count),
            first_vertex: self.first_vertex,
            first_instance: self.first_instance,
        }
    }
    #[doc = "Setter for [wgpu::util::DrawIndirectArgs::first_vertex]. Optional, defaults to `0u32`.\n"]
    pub fn first_vertex(self, first_vertex: u32) -> DrawIndirectArgsBuilder<SetFirstVertex<CS>>
    where
        CS::FirstVertex: FirstVertexIsEmpty,
    {
        DrawIndirectArgsBuilder {
            vertex_count: self.vertex_count,
            instance_count: self.instance_count,
            first_vertex: FirstVertexValue(first_vertex),
            first_instance: self.first_instance,
        }
    }
    #[doc = "Setter for [wgpu::util::DrawIndirectArgs::first_instance]. Optional, defaults to `0u32`.\n"]
    pub fn first_instance(
        self,
        first_instance: u32,
    ) -> DrawIndirectArgsBuilder<SetFirstInstance<CS>>
    where
        CS::FirstInstance: FirstInstanceIsEmpty,
    {
        DrawIndirectArgsBuilder {
            vertex_count: self.vertex_count,
            instance_count: self.instance_count,
            first_vertex: self.first_vertex,
            first_instance: FirstInstanceValue(first_instance),
        }
    }
}
pub trait Complete:
    State<
    VertexCount: IsSetVertexCount,
    InstanceCount: IsSetInstanceCount,
    FirstVertex: IsSetFirstVertex,
    FirstInstance: IsSetFirstInstance,
>
{
}
impl<
        CS: State<
            VertexCount: IsSetVertexCount,
            InstanceCount: IsSetInstanceCount,
            FirstVertex: IsSetFirstVertex,
            FirstInstance: IsSetFirstInstance,
        >,
    > Complete for CS
{
}
impl<CS: Complete> DrawIndirectArgsBuilder<CS> {
    pub fn build(self) -> wgpu::util::DrawIndirectArgs {
        wgpu::util::DrawIndirectArgs {
            vertex_count: IsSetVertexCount::get(self.vertex_count),
            instance_count: IsSetInstanceCount::get(self.instance_count),
            first_vertex: IsSetFirstVertex::get(self.first_vertex),
            first_instance: IsSetFirstInstance::get(self.first_instance),
        }
    }
}
impl Nested<wgpu::util::DrawIndirectArgs> for wgpu::util::DrawIndirectArgs {
    fn unnest(self) -> wgpu::util::DrawIndirectArgs {
        self
    }
}
impl<CS: Complete> Nested<wgpu::util::DrawIndirectArgs> for DrawIndirectArgsBuilder<CS> {
    fn unnest(self) -> wgpu::util::DrawIndirectArgs {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::draw_indirect_args().build()),
            format!("{:#?}", wgpu::util::DrawIndirectArgs::default()),
        );
    }
}
