// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu::ImageSubresourceRange`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [aspect](ImageSubresourceRangeBuilder::aspect) Optional, defaults to [wgpu::TextureAspect::All]\n  - [base_mip_level](ImageSubresourceRangeBuilder::base_mip_level) Optional, defaults to `0u32`\n  - [mip_level_count](ImageSubresourceRangeBuilder::mip_level_count) Optional, defaults to `None`\n  - [base_array_layer](ImageSubresourceRangeBuilder::base_array_layer) Optional, defaults to `0u32`\n  - [array_layer_count](ImageSubresourceRangeBuilder::array_layer_count) Optional, defaults to `None`\n"]
pub struct ImageSubresourceRangeBuilder<CS: State> {
    aspect: CS::Aspect,
    base_mip_level: CS::BaseMipLevel,
    mip_level_count: CS::MipLevelCount,
    base_array_layer: CS::BaseArrayLayer,
    array_layer_count: CS::ArrayLayerCount,
}
impl ImageSubresourceRangeBuilder<Empty> {
    pub fn new() -> ImageSubresourceRangeBuilder<Empty> {
        ImageSubresourceRangeBuilder {
            aspect: AspectEmpty,
            base_mip_level: BaseMipLevelEmpty,
            mip_level_count: MipLevelCountEmpty,
            base_array_layer: BaseArrayLayerEmpty,
            array_layer_count: ArrayLayerCountEmpty,
        }
    }
}
#[doc = "\nReturns [ImageSubresourceRangeBuilder] for building [`wgpu::ImageSubresourceRange`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [aspect](ImageSubresourceRangeBuilder::aspect) Optional, defaults to [wgpu::TextureAspect::All]\n  - [base_mip_level](ImageSubresourceRangeBuilder::base_mip_level) Optional, defaults to `0u32`\n  - [mip_level_count](ImageSubresourceRangeBuilder::mip_level_count) Optional, defaults to `None`\n  - [base_array_layer](ImageSubresourceRangeBuilder::base_array_layer) Optional, defaults to `0u32`\n  - [array_layer_count](ImageSubresourceRangeBuilder::array_layer_count) Optional, defaults to `None`\n"]
pub fn image_subresource_range() -> ImageSubresourceRangeBuilder<Empty> {
    ImageSubresourceRangeBuilder::new()
}
pub struct AspectEmpty;
impl Field for AspectEmpty {}
pub trait AspectIsEmpty {}
impl AspectIsEmpty for AspectEmpty {}
pub trait IsSetAspect {
    fn get(self) -> wgpu::TextureAspect;
}
impl IsSetAspect for AspectEmpty {
    fn get(self) -> wgpu::TextureAspect {
        wgpu::TextureAspect::All
    }
}
pub struct AspectValue(pub wgpu::TextureAspect);
impl Field for AspectValue {}
impl IsSetAspect for AspectValue {
    fn get(self) -> wgpu::TextureAspect {
        self.0
    }
}
pub struct BaseMipLevelEmpty;
impl Field for BaseMipLevelEmpty {}
pub trait BaseMipLevelIsEmpty {}
impl BaseMipLevelIsEmpty for BaseMipLevelEmpty {}
pub trait IsSetBaseMipLevel {
    fn get(self) -> u32;
}
impl IsSetBaseMipLevel for BaseMipLevelEmpty {
    fn get(self) -> u32 {
        0u32
    }
}
pub struct BaseMipLevelValue(pub u32);
impl Field for BaseMipLevelValue {}
impl IsSetBaseMipLevel for BaseMipLevelValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub struct MipLevelCountEmpty;
impl Field for MipLevelCountEmpty {}
pub trait MipLevelCountIsEmpty {}
impl MipLevelCountIsEmpty for MipLevelCountEmpty {}
pub trait IsSetMipLevelCount {
    fn get(self) -> Option<u32>;
}
impl IsSetMipLevelCount for MipLevelCountEmpty {
    fn get(self) -> Option<u32> {
        None
    }
}
pub struct MipLevelCountValue(pub Option<u32>);
impl Field for MipLevelCountValue {}
impl IsSetMipLevelCount for MipLevelCountValue {
    fn get(self) -> Option<u32> {
        self.0
    }
}
pub struct BaseArrayLayerEmpty;
impl Field for BaseArrayLayerEmpty {}
pub trait BaseArrayLayerIsEmpty {}
impl BaseArrayLayerIsEmpty for BaseArrayLayerEmpty {}
pub trait IsSetBaseArrayLayer {
    fn get(self) -> u32;
}
impl IsSetBaseArrayLayer for BaseArrayLayerEmpty {
    fn get(self) -> u32 {
        0u32
    }
}
pub struct BaseArrayLayerValue(pub u32);
impl Field for BaseArrayLayerValue {}
impl IsSetBaseArrayLayer for BaseArrayLayerValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub struct ArrayLayerCountEmpty;
impl Field for ArrayLayerCountEmpty {}
pub trait ArrayLayerCountIsEmpty {}
impl ArrayLayerCountIsEmpty for ArrayLayerCountEmpty {}
pub trait IsSetArrayLayerCount {
    fn get(self) -> Option<u32>;
}
impl IsSetArrayLayerCount for ArrayLayerCountEmpty {
    fn get(self) -> Option<u32> {
        None
    }
}
pub struct ArrayLayerCountValue(pub Option<u32>);
impl Field for ArrayLayerCountValue {}
impl IsSetArrayLayerCount for ArrayLayerCountValue {
    fn get(self) -> Option<u32> {
        self.0
    }
}
pub trait State {
    type Aspect: Field;
    type BaseMipLevel: Field;
    type MipLevelCount: Field;
    type BaseArrayLayer: Field;
    type ArrayLayerCount: Field;
}
pub struct Empty;
impl State for Empty {
    type Aspect = AspectEmpty;
    type BaseMipLevel = BaseMipLevelEmpty;
    type MipLevelCount = MipLevelCountEmpty;
    type BaseArrayLayer = BaseArrayLayerEmpty;
    type ArrayLayerCount = ArrayLayerCountEmpty;
}
pub struct SetAspect<CS>(CS);
impl<CS: State> State for SetAspect<CS> {
    type Aspect = AspectValue;
    type BaseMipLevel = CS::BaseMipLevel;
    type MipLevelCount = CS::MipLevelCount;
    type BaseArrayLayer = CS::BaseArrayLayer;
    type ArrayLayerCount = CS::ArrayLayerCount;
}
pub struct SetBaseMipLevel<CS>(CS);
impl<CS: State> State for SetBaseMipLevel<CS> {
    type Aspect = CS::Aspect;
    type BaseMipLevel = BaseMipLevelValue;
    type MipLevelCount = CS::MipLevelCount;
    type BaseArrayLayer = CS::BaseArrayLayer;
    type ArrayLayerCount = CS::ArrayLayerCount;
}
pub struct SetMipLevelCount<CS>(CS);
impl<CS: State> State for SetMipLevelCount<CS> {
    type Aspect = CS::Aspect;
    type BaseMipLevel = CS::BaseMipLevel;
    type MipLevelCount = MipLevelCountValue;
    type BaseArrayLayer = CS::BaseArrayLayer;
    type ArrayLayerCount = CS::ArrayLayerCount;
}
pub struct SetBaseArrayLayer<CS>(CS);
impl<CS: State> State for SetBaseArrayLayer<CS> {
    type Aspect = CS::Aspect;
    type BaseMipLevel = CS::BaseMipLevel;
    type MipLevelCount = CS::MipLevelCount;
    type BaseArrayLayer = BaseArrayLayerValue;
    type ArrayLayerCount = CS::ArrayLayerCount;
}
pub struct SetArrayLayerCount<CS>(CS);
impl<CS: State> State for SetArrayLayerCount<CS> {
    type Aspect = CS::Aspect;
    type BaseMipLevel = CS::BaseMipLevel;
    type MipLevelCount = CS::MipLevelCount;
    type BaseArrayLayer = CS::BaseArrayLayer;
    type ArrayLayerCount = ArrayLayerCountValue;
}
impl<CS: State> ImageSubresourceRangeBuilder<CS> {
    #[doc = "Setter for [wgpu::ImageSubresourceRange::aspect]. Optional, defaults to [wgpu::TextureAspect::All].\n"]
    pub fn aspect(self, aspect: wgpu::TextureAspect) -> ImageSubresourceRangeBuilder<SetAspect<CS>>
    where
        CS::Aspect: AspectIsEmpty,
    {
        ImageSubresourceRangeBuilder {
            aspect: AspectValue(aspect),
            base_mip_level: self.base_mip_level,
            mip_level_count: self.mip_level_count,
            base_array_layer: self.base_array_layer,
            array_layer_count: self.array_layer_count,
        }
    }
    #[doc = "Setter for [wgpu::ImageSubresourceRange::base_mip_level]. Optional, defaults to `0u32`.\n"]
    pub fn base_mip_level(
        self,
        base_mip_level: u32,
    ) -> ImageSubresourceRangeBuilder<SetBaseMipLevel<CS>>
    where
        CS::BaseMipLevel: BaseMipLevelIsEmpty,
    {
        ImageSubresourceRangeBuilder {
            aspect: self.aspect,
            base_mip_level: BaseMipLevelValue(base_mip_level),
            mip_level_count: self.mip_level_count,
            base_array_layer: self.base_array_layer,
            array_layer_count: self.array_layer_count,
        }
    }
    #[doc = "Setter for [wgpu::ImageSubresourceRange::mip_level_count]. Optional, defaults to `None`.\n"]
    pub fn mip_level_count(
        self,
        mip_level_count: u32,
    ) -> ImageSubresourceRangeBuilder<SetMipLevelCount<CS>>
    where
        CS::MipLevelCount: MipLevelCountIsEmpty,
    {
        ImageSubresourceRangeBuilder {
            aspect: self.aspect,
            base_mip_level: self.base_mip_level,
            mip_level_count: MipLevelCountValue(Some(mip_level_count)),
            base_array_layer: self.base_array_layer,
            array_layer_count: self.array_layer_count,
        }
    }
    #[doc = "Setter for [wgpu::ImageSubresourceRange::mip_level_count]. Optional, defaults to `None`.\n"]
    pub fn maybe_mip_level_count(
        self,
        mip_level_count: Option<u32>,
    ) -> ImageSubresourceRangeBuilder<SetMipLevelCount<CS>>
    where
        CS::MipLevelCount: MipLevelCountIsEmpty,
    {
        ImageSubresourceRangeBuilder {
            aspect: self.aspect,
            base_mip_level: self.base_mip_level,
            mip_level_count: MipLevelCountValue(mip_level_count),
            base_array_layer: self.base_array_layer,
            array_layer_count: self.array_layer_count,
        }
    }
    #[doc = "Setter for [wgpu::ImageSubresourceRange::base_array_layer]. Optional, defaults to `0u32`.\n"]
    pub fn base_array_layer(
        self,
        base_array_layer: u32,
    ) -> ImageSubresourceRangeBuilder<SetBaseArrayLayer<CS>>
    where
        CS::BaseArrayLayer: BaseArrayLayerIsEmpty,
    {
        ImageSubresourceRangeBuilder {
            aspect: self.aspect,
            base_mip_level: self.base_mip_level,
            mip_level_count: self.mip_level_count,
            base_array_layer: BaseArrayLayerValue(base_array_layer),
            array_layer_count: self.array_layer_count,
        }
    }
    #[doc = "Setter for [wgpu::ImageSubresourceRange::array_layer_count]. Optional, defaults to `None`.\n"]
    pub fn array_layer_count(
        self,
        array_layer_count: u32,
    ) -> ImageSubresourceRangeBuilder<SetArrayLayerCount<CS>>
    where
        CS::ArrayLayerCount: ArrayLayerCountIsEmpty,
    {
        ImageSubresourceRangeBuilder {
            aspect: self.aspect,
            base_mip_level: self.base_mip_level,
            mip_level_count: self.mip_level_count,
            base_array_layer: self.base_array_layer,
            array_layer_count: ArrayLayerCountValue(Some(array_layer_count)),
        }
    }
    #[doc = "Setter for [wgpu::ImageSubresourceRange::array_layer_count]. Optional, defaults to `None`.\n"]
    pub fn maybe_array_layer_count(
        self,
        array_layer_count: Option<u32>,
    ) -> ImageSubresourceRangeBuilder<SetArrayLayerCount<CS>>
    where
        CS::ArrayLayerCount: ArrayLayerCountIsEmpty,
    {
        ImageSubresourceRangeBuilder {
            aspect: self.aspect,
            base_mip_level: self.base_mip_level,
            mip_level_count: self.mip_level_count,
            base_array_layer: self.base_array_layer,
            array_layer_count: ArrayLayerCountValue(array_layer_count),
        }
    }
}
pub trait Complete:
    State<
    Aspect: IsSetAspect,
    BaseMipLevel: IsSetBaseMipLevel,
    MipLevelCount: IsSetMipLevelCount,
    BaseArrayLayer: IsSetBaseArrayLayer,
    ArrayLayerCount: IsSetArrayLayerCount,
>
{
}
impl<
        CS: State<
            Aspect: IsSetAspect,
            BaseMipLevel: IsSetBaseMipLevel,
            MipLevelCount: IsSetMipLevelCount,
            BaseArrayLayer: IsSetBaseArrayLayer,
            ArrayLayerCount: IsSetArrayLayerCount,
        >,
    > Complete for CS
{
}
impl<CS: Complete> ImageSubresourceRangeBuilder<CS> {
    pub fn build(self) -> wgpu::ImageSubresourceRange {
        wgpu::ImageSubresourceRange {
            aspect: IsSetAspect::get(self.aspect),
            base_mip_level: IsSetBaseMipLevel::get(self.base_mip_level),
            mip_level_count: IsSetMipLevelCount::get(self.mip_level_count),
            base_array_layer: IsSetBaseArrayLayer::get(self.base_array_layer),
            array_layer_count: IsSetArrayLayerCount::get(self.array_layer_count),
        }
    }
}
impl Nested<wgpu::ImageSubresourceRange> for wgpu::ImageSubresourceRange {
    fn unnest(self) -> wgpu::ImageSubresourceRange {
        self
    }
}
impl<CS: Complete> Nested<wgpu::ImageSubresourceRange> for ImageSubresourceRangeBuilder<CS> {
    fn unnest(self) -> wgpu::ImageSubresourceRange {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::image_subresource_range().build()),
            format!("{:#?}", wgpu::ImageSubresourceRange::default()),
        );
    }
}
