// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu::NoopBackendOptions`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [enable](NoopBackendOptionsBuilder::enable) Optional, defaults to `false`\n"]
pub struct NoopBackendOptionsBuilder<CS: State> {
    enable: CS::Enable,
}
impl NoopBackendOptionsBuilder<Empty> {
    pub fn new() -> NoopBackendOptionsBuilder<Empty> {
        NoopBackendOptionsBuilder {
            enable: EnableEmpty,
        }
    }
}
#[doc = "\nReturns [NoopBackendOptionsBuilder] for building [`wgpu::NoopBackendOptions`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [enable](NoopBackendOptionsBuilder::enable) Optional, defaults to `false`\n"]
pub fn noop_backend_options() -> NoopBackendOptionsBuilder<Empty> {
    NoopBackendOptionsBuilder::new()
}
pub struct EnableEmpty;
impl Field for EnableEmpty {}
pub trait EnableIsEmpty {}
impl EnableIsEmpty for EnableEmpty {}
pub trait IsSetEnable {
    fn get(self) -> bool;
}
impl IsSetEnable for EnableEmpty {
    fn get(self) -> bool {
        false
    }
}
pub struct EnableValue(pub bool);
impl Field for EnableValue {}
impl IsSetEnable for EnableValue {
    fn get(self) -> bool {
        self.0
    }
}
pub trait State {
    type Enable: Field;
}
pub struct Empty;
impl State for Empty {
    type Enable = EnableEmpty;
}
pub struct SetEnable<CS>(CS);
impl<CS: State> State for SetEnable<CS> {
    type Enable = EnableValue;
}
impl<CS: State> NoopBackendOptionsBuilder<CS> {
    #[doc = "Setter for [wgpu::NoopBackendOptions::enable]. Optional, defaults to `false`.\n"]
    pub fn enable(self, enable: bool) -> NoopBackendOptionsBuilder<SetEnable<CS>>
    where
        CS::Enable: EnableIsEmpty,
    {
        NoopBackendOptionsBuilder {
            enable: EnableValue(enable),
        }
    }
}
pub trait Complete: State<Enable: IsSetEnable> {}
impl<CS: State<Enable: IsSetEnable>> Complete for CS {}
impl<CS: Complete> NoopBackendOptionsBuilder<CS> {
    pub fn build(self) -> wgpu::NoopBackendOptions {
        wgpu::NoopBackendOptions {
            enable: IsSetEnable::get(self.enable),
        }
    }
}
impl Nested<wgpu::NoopBackendOptions> for wgpu::NoopBackendOptions {
    fn unnest(self) -> wgpu::NoopBackendOptions {
        self
    }
}
impl<CS: Complete> Nested<wgpu::NoopBackendOptions> for NoopBackendOptionsBuilder<CS> {
    fn unnest(self) -> wgpu::NoopBackendOptions {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::noop_backend_options().build()),
            format!("{:#?}", wgpu::NoopBackendOptions::default()),
        );
    }
}
