// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu::PipelineLayoutDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [bind_group_layouts](PipelineLayoutDescriptorBuilder::bind_group_layouts) Optional, defaults to [::core::default::Default::default()]\n  - [immediate_size](PipelineLayoutDescriptorBuilder::immediate_size) Optional, defaults to `0u32`\n"]
pub struct PipelineLayoutDescriptorBuilder<'a, CS: State<'a>> {
    label: CS::Label,
    bind_group_layouts: CS::BindGroupLayouts,
    immediate_size: CS::ImmediateSize,
}
impl<'a> PipelineLayoutDescriptorBuilder<'a, Empty> {
    pub fn new() -> PipelineLayoutDescriptorBuilder<'a, Empty> {
        PipelineLayoutDescriptorBuilder {
            label: LabelEmpty,
            bind_group_layouts: BindGroupLayoutsEmpty,
            immediate_size: ImmediateSizeEmpty,
        }
    }
}
#[doc = "\nReturns [PipelineLayoutDescriptorBuilder] for building [`wgpu::PipelineLayoutDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [bind_group_layouts](PipelineLayoutDescriptorBuilder::bind_group_layouts) Optional, defaults to [::core::default::Default::default()]\n  - [immediate_size](PipelineLayoutDescriptorBuilder::immediate_size) Optional, defaults to `0u32`\n"]
pub fn pipeline_layout_descriptor<'a>(
    label: wgpu::Label<'a>,
) -> PipelineLayoutDescriptorBuilder<'a, SetLabel<Empty>> {
    PipelineLayoutDescriptorBuilder::new().label(label)
}
pub struct LabelEmpty;
impl Field for LabelEmpty {}
pub trait LabelIsEmpty {}
impl LabelIsEmpty for LabelEmpty {}
pub trait IsSetLabel<'a> {
    fn get(self) -> wgpu::Label<'a>;
}
impl<'a> IsSetLabel<'a> for LabelEmpty {
    fn get(self) -> wgpu::Label<'a> {
        None
    }
}
pub struct LabelValue<'a>(pub wgpu::Label<'a>);
impl<'a> Field for LabelValue<'a> {}
impl<'a> IsSetLabel<'a> for LabelValue<'a> {
    fn get(self) -> wgpu::Label<'a> {
        self.0
    }
}
pub struct BindGroupLayoutsEmpty;
impl Field for BindGroupLayoutsEmpty {}
pub trait BindGroupLayoutsIsEmpty {}
impl BindGroupLayoutsIsEmpty for BindGroupLayoutsEmpty {}
pub trait IsSetBindGroupLayouts<'a> {
    fn get(self) -> &'a [Option<&'a wgpu::BindGroupLayout>];
}
impl<'a> IsSetBindGroupLayouts<'a> for BindGroupLayoutsEmpty {
    fn get(self) -> &'a [Option<&'a wgpu::BindGroupLayout>] {
        ::core::default::Default::default()
    }
}
pub struct BindGroupLayoutsValue<'a>(pub &'a [Option<&'a wgpu::BindGroupLayout>]);
impl<'a> Field for BindGroupLayoutsValue<'a> {}
impl<'a> IsSetBindGroupLayouts<'a> for BindGroupLayoutsValue<'a> {
    fn get(self) -> &'a [Option<&'a wgpu::BindGroupLayout>] {
        self.0
    }
}
pub struct ImmediateSizeEmpty;
impl Field for ImmediateSizeEmpty {}
pub trait ImmediateSizeIsEmpty {}
impl ImmediateSizeIsEmpty for ImmediateSizeEmpty {}
pub trait IsSetImmediateSize {
    fn get(self) -> u32;
}
impl IsSetImmediateSize for ImmediateSizeEmpty {
    fn get(self) -> u32 {
        0u32
    }
}
pub struct ImmediateSizeValue(pub u32);
impl Field for ImmediateSizeValue {}
impl IsSetImmediateSize for ImmediateSizeValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub trait State<'a> {
    type Label: Field;
    type BindGroupLayouts: Field;
    type ImmediateSize: Field;
}
pub struct Empty;
impl<'a> State<'a> for Empty {
    type Label = LabelEmpty;
    type BindGroupLayouts = BindGroupLayoutsEmpty;
    type ImmediateSize = ImmediateSizeEmpty;
}
pub struct SetLabel<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetLabel<CS> {
    type Label = LabelValue<'a>;
    type BindGroupLayouts = CS::BindGroupLayouts;
    type ImmediateSize = CS::ImmediateSize;
}
pub struct SetBindGroupLayouts<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetBindGroupLayouts<CS> {
    type Label = CS::Label;
    type BindGroupLayouts = BindGroupLayoutsValue<'a>;
    type ImmediateSize = CS::ImmediateSize;
}
pub struct SetImmediateSize<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetImmediateSize<CS> {
    type Label = CS::Label;
    type BindGroupLayouts = CS::BindGroupLayouts;
    type ImmediateSize = ImmediateSizeValue;
}
impl<'a, CS: State<'a>> PipelineLayoutDescriptorBuilder<'a, CS> {
    #[doc = "Setter for [wgpu::PipelineLayoutDescriptor::label]. Optional, defaults to `None`.\n"]
    pub fn label(self, label: wgpu::Label<'a>) -> PipelineLayoutDescriptorBuilder<'a, SetLabel<CS>>
    where
        CS::Label: LabelIsEmpty,
    {
        PipelineLayoutDescriptorBuilder {
            label: LabelValue(label),
            bind_group_layouts: self.bind_group_layouts,
            immediate_size: self.immediate_size,
        }
    }
    #[doc = "Setter for [wgpu::PipelineLayoutDescriptor::bind_group_layouts]. Optional, defaults to [::core::default::Default::default()].\n"]
    pub fn bind_group_layouts(
        self,
        bind_group_layouts: &'a [Option<&'a wgpu::BindGroupLayout>],
    ) -> PipelineLayoutDescriptorBuilder<'a, SetBindGroupLayouts<CS>>
    where
        CS::BindGroupLayouts: BindGroupLayoutsIsEmpty,
    {
        PipelineLayoutDescriptorBuilder {
            label: self.label,
            bind_group_layouts: BindGroupLayoutsValue(bind_group_layouts),
            immediate_size: self.immediate_size,
        }
    }
    #[doc = "Setter for [wgpu::PipelineLayoutDescriptor::immediate_size]. Optional, defaults to `0u32`.\n"]
    pub fn immediate_size(
        self,
        immediate_size: u32,
    ) -> PipelineLayoutDescriptorBuilder<'a, SetImmediateSize<CS>>
    where
        CS::ImmediateSize: ImmediateSizeIsEmpty,
    {
        PipelineLayoutDescriptorBuilder {
            label: self.label,
            bind_group_layouts: self.bind_group_layouts,
            immediate_size: ImmediateSizeValue(immediate_size),
        }
    }
}
pub trait Complete<'a>:
    State<
    'a,
    Label: IsSetLabel<'a>,
    BindGroupLayouts: IsSetBindGroupLayouts<'a>,
    ImmediateSize: IsSetImmediateSize,
>
{
}
impl<
        'a,
        CS: State<
            'a,
            Label: IsSetLabel<'a>,
            BindGroupLayouts: IsSetBindGroupLayouts<'a>,
            ImmediateSize: IsSetImmediateSize,
        >,
    > Complete<'a> for CS
{
}
impl<'a, CS: Complete<'a>> PipelineLayoutDescriptorBuilder<'a, CS> {
    pub fn build(self) -> wgpu::PipelineLayoutDescriptor<'a> {
        wgpu::PipelineLayoutDescriptor {
            label: IsSetLabel::get(self.label),
            bind_group_layouts: IsSetBindGroupLayouts::get(self.bind_group_layouts),
            immediate_size: IsSetImmediateSize::get(self.immediate_size),
        }
    }
}
impl<'a> Nested<wgpu::PipelineLayoutDescriptor<'a>> for wgpu::PipelineLayoutDescriptor<'a> {
    fn unnest(self) -> wgpu::PipelineLayoutDescriptor<'a> {
        self
    }
}
impl<'a, CS: Complete<'a>> Nested<wgpu::PipelineLayoutDescriptor<'a>>
    for PipelineLayoutDescriptorBuilder<'a, CS>
{
    fn unnest(self) -> wgpu::PipelineLayoutDescriptor<'a> {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!(
                "{:#?}",
                super::pipeline_layout_descriptor(Option::<&str>::None).build()
            ),
            format!("{:#?}", wgpu::PipelineLayoutDescriptor::default()),
        );
    }
}
