// The code in this file is generated by a script. Do not edit it directly.
//

pub use crate::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu::BufferBinding`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder fields:\n  - [buffer](BufferBindingBuilder::buffer) Required\n  - [offset](BufferBindingBuilder::offset) Required\n  - [size](BufferBindingBuilder::size) Optional, defaults to `None`\n"]
pub struct BufferBindingBuilder<'a, CS: State<'a>> {
    buffer: CS::Buffer,
    offset: CS::Offset,
    size: CS::Size,
}
impl<'a> BufferBindingBuilder<'a, Empty> {
    pub fn new() -> BufferBindingBuilder<'a, Empty> {
        BufferBindingBuilder {
            buffer: BufferEmpty,
            offset: OffsetEmpty,
            size: SizeEmpty,
        }
    }
}
#[doc = "\nReturns [BufferBindingBuilder] for building [`wgpu::BufferBinding`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder fields:\n  - [buffer](BufferBindingBuilder::buffer) Required\n  - [offset](BufferBindingBuilder::offset) Required\n  - [size](BufferBindingBuilder::size) Optional, defaults to `None`\n"]
pub fn buffer_binding<'a>() -> BufferBindingBuilder<'a, Empty> {
    BufferBindingBuilder::new()
}
pub struct BufferEmpty;
impl Field for BufferEmpty {}
pub trait BufferIsEmpty {}
impl BufferIsEmpty for BufferEmpty {}
pub trait IsSetBuffer<'a> {
    fn get(self) -> &'a wgpu::Buffer;
}
pub struct BufferValue<'a>(pub &'a wgpu::Buffer);
impl<'a> Field for BufferValue<'a> {}
impl<'a> IsSetBuffer<'a> for BufferValue<'a> {
    fn get(self) -> &'a wgpu::Buffer {
        self.0
    }
}
pub struct OffsetEmpty;
impl Field for OffsetEmpty {}
pub trait OffsetIsEmpty {}
impl OffsetIsEmpty for OffsetEmpty {}
pub trait IsSetOffset {
    fn get(self) -> wgpu::BufferAddress;
}
pub struct OffsetValue(pub wgpu::BufferAddress);
impl Field for OffsetValue {}
impl IsSetOffset for OffsetValue {
    fn get(self) -> wgpu::BufferAddress {
        self.0
    }
}
pub struct SizeEmpty;
impl Field for SizeEmpty {}
pub trait SizeIsEmpty {}
impl SizeIsEmpty for SizeEmpty {}
pub trait IsSetSize {
    fn get(self) -> Option<wgpu::BufferSize>;
}
impl IsSetSize for SizeEmpty {
    fn get(self) -> Option<wgpu::BufferSize> {
        None
    }
}
pub struct SizeValue(pub Option<wgpu::BufferSize>);
impl Field for SizeValue {}
impl IsSetSize for SizeValue {
    fn get(self) -> Option<wgpu::BufferSize> {
        self.0
    }
}
pub trait State<'a> {
    type Buffer: Field;
    type Offset: Field;
    type Size: Field;
}
pub struct Empty;
impl<'a> State<'a> for Empty {
    type Buffer = BufferEmpty;
    type Offset = OffsetEmpty;
    type Size = SizeEmpty;
}
pub struct SetBuffer<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetBuffer<CS> {
    type Buffer = BufferValue<'a>;
    type Offset = CS::Offset;
    type Size = CS::Size;
}
pub struct SetOffset<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetOffset<CS> {
    type Buffer = CS::Buffer;
    type Offset = OffsetValue;
    type Size = CS::Size;
}
pub struct SetSize<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetSize<CS> {
    type Buffer = CS::Buffer;
    type Offset = CS::Offset;
    type Size = SizeValue;
}
impl<'a, CS: State<'a>> BufferBindingBuilder<'a, CS> {
    #[doc = "Setter for [wgpu::BufferBinding::buffer]. Required.\n"]
    pub fn buffer(self, buffer: &'a wgpu::Buffer) -> BufferBindingBuilder<'a, SetBuffer<CS>>
    where
        CS::Buffer: BufferIsEmpty,
    {
        BufferBindingBuilder {
            buffer: BufferValue(buffer),
            offset: self.offset,
            size: self.size,
        }
    }
    #[doc = "Setter for [wgpu::BufferBinding::offset]. Required.\n"]
    pub fn offset(self, offset: wgpu::BufferAddress) -> BufferBindingBuilder<'a, SetOffset<CS>>
    where
        CS::Offset: OffsetIsEmpty,
    {
        BufferBindingBuilder {
            buffer: self.buffer,
            offset: OffsetValue(offset),
            size: self.size,
        }
    }
    #[doc = "Setter for [wgpu::BufferBinding::size]. Optional, defaults to `None`.\n"]
    pub fn size(self, size: wgpu::BufferSize) -> BufferBindingBuilder<'a, SetSize<CS>>
    where
        CS::Size: SizeIsEmpty,
    {
        BufferBindingBuilder {
            buffer: self.buffer,
            offset: self.offset,
            size: SizeValue(Some(size)),
        }
    }
    #[doc = "Setter for [wgpu::BufferBinding::size]. Optional, defaults to `None`.\n"]
    pub fn maybe_size(self, size: Option<wgpu::BufferSize>) -> BufferBindingBuilder<'a, SetSize<CS>>
    where
        CS::Size: SizeIsEmpty,
    {
        BufferBindingBuilder {
            buffer: self.buffer,
            offset: self.offset,
            size: SizeValue(size),
        }
    }
}
pub trait Complete<'a>:
    State<'a, Buffer: IsSetBuffer<'a>, Offset: IsSetOffset, Size: IsSetSize>
{
}
impl<'a, CS: State<'a, Buffer: IsSetBuffer<'a>, Offset: IsSetOffset, Size: IsSetSize>> Complete<'a>
    for CS
{
}
impl<'a, CS: Complete<'a>> BufferBindingBuilder<'a, CS> {
    pub fn build(self) -> wgpu::BufferBinding<'a> {
        wgpu::BufferBinding {
            buffer: IsSetBuffer::get(self.buffer),
            offset: IsSetOffset::get(self.offset),
            size: IsSetSize::get(self.size),
        }
    }
}
impl<'a> Nested<wgpu::BufferBinding<'a>> for wgpu::BufferBinding<'a> {
    fn unnest(self) -> wgpu::BufferBinding<'a> {
        self
    }
}
impl<'a, CS: Complete<'a>> Nested<wgpu::BufferBinding<'a>> for BufferBindingBuilder<'a, CS> {
    fn unnest(self) -> wgpu::BufferBinding<'a> {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::IsSetSize::get(super::SizeEmpty)),
            format!("{:#?}", Option::<wgpu::BufferSize>::default()),
        );
    }
}
