// The code in this file is generated by a script. Do not edit it directly.
//

pub use crate::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu::BufferDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder fields:\n  - [size](BufferDescriptorBuilder::size) Required\n  - [usage](BufferDescriptorBuilder::usage) Required\n  - [mapped_at_creation](BufferDescriptorBuilder::mapped_at_creation) Required\n"]
pub struct BufferDescriptorBuilder<'a, CS: State<'a>> {
    label: CS::Label,
    size: CS::Size,
    usage: CS::Usage,
    mapped_at_creation: CS::MappedAtCreation,
}
impl<'a> BufferDescriptorBuilder<'a, Empty> {
    pub fn new() -> BufferDescriptorBuilder<'a, Empty> {
        BufferDescriptorBuilder {
            label: LabelEmpty,
            size: SizeEmpty,
            usage: UsageEmpty,
            mapped_at_creation: MappedAtCreationEmpty,
        }
    }
}
#[doc = "\nReturns [BufferDescriptorBuilder] for building [`wgpu::BufferDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder fields:\n  - [size](BufferDescriptorBuilder::size) Required\n  - [usage](BufferDescriptorBuilder::usage) Required\n  - [mapped_at_creation](BufferDescriptorBuilder::mapped_at_creation) Required\n"]
pub fn buffer_descriptor<'a>(
    label: wgpu::Label<'a>,
) -> BufferDescriptorBuilder<'a, SetLabel<Empty>> {
    BufferDescriptorBuilder::new().label(label)
}
pub struct LabelEmpty;
impl Field for LabelEmpty {}
pub trait LabelIsEmpty {}
impl LabelIsEmpty for LabelEmpty {}
pub trait IsSetLabel<'a> {
    fn get(self) -> wgpu::Label<'a>;
}
impl<'a> IsSetLabel<'a> for LabelEmpty {
    fn get(self) -> wgpu::Label<'a> {
        None
    }
}
pub struct LabelValue<'a>(pub wgpu::Label<'a>);
impl<'a> Field for LabelValue<'a> {}
impl<'a> IsSetLabel<'a> for LabelValue<'a> {
    fn get(self) -> wgpu::Label<'a> {
        self.0
    }
}
pub struct SizeEmpty;
impl Field for SizeEmpty {}
pub trait SizeIsEmpty {}
impl SizeIsEmpty for SizeEmpty {}
pub trait IsSetSize {
    fn get(self) -> wgpu::BufferAddress;
}
pub struct SizeValue(pub wgpu::BufferAddress);
impl Field for SizeValue {}
impl IsSetSize for SizeValue {
    fn get(self) -> wgpu::BufferAddress {
        self.0
    }
}
pub struct UsageEmpty;
impl Field for UsageEmpty {}
pub trait UsageIsEmpty {}
impl UsageIsEmpty for UsageEmpty {}
pub trait IsSetUsage {
    fn get(self) -> wgpu::BufferUsages;
}
pub struct UsageValue(pub wgpu::BufferUsages);
impl Field for UsageValue {}
impl IsSetUsage for UsageValue {
    fn get(self) -> wgpu::BufferUsages {
        self.0
    }
}
pub struct MappedAtCreationEmpty;
impl Field for MappedAtCreationEmpty {}
pub trait MappedAtCreationIsEmpty {}
impl MappedAtCreationIsEmpty for MappedAtCreationEmpty {}
pub trait IsSetMappedAtCreation {
    fn get(self) -> bool;
}
pub struct MappedAtCreationValue(pub bool);
impl Field for MappedAtCreationValue {}
impl IsSetMappedAtCreation for MappedAtCreationValue {
    fn get(self) -> bool {
        self.0
    }
}
pub trait State<'a> {
    type Label: Field;
    type Size: Field;
    type Usage: Field;
    type MappedAtCreation: Field;
}
pub struct Empty;
impl<'a> State<'a> for Empty {
    type Label = LabelEmpty;
    type Size = SizeEmpty;
    type Usage = UsageEmpty;
    type MappedAtCreation = MappedAtCreationEmpty;
}
pub struct SetLabel<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetLabel<CS> {
    type Label = LabelValue<'a>;
    type Size = CS::Size;
    type Usage = CS::Usage;
    type MappedAtCreation = CS::MappedAtCreation;
}
pub struct SetSize<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetSize<CS> {
    type Label = CS::Label;
    type Size = SizeValue;
    type Usage = CS::Usage;
    type MappedAtCreation = CS::MappedAtCreation;
}
pub struct SetUsage<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetUsage<CS> {
    type Label = CS::Label;
    type Size = CS::Size;
    type Usage = UsageValue;
    type MappedAtCreation = CS::MappedAtCreation;
}
pub struct SetMappedAtCreation<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetMappedAtCreation<CS> {
    type Label = CS::Label;
    type Size = CS::Size;
    type Usage = CS::Usage;
    type MappedAtCreation = MappedAtCreationValue;
}
impl<'a, CS: State<'a>> BufferDescriptorBuilder<'a, CS> {
    #[doc = "Setter for [wgpu::BufferDescriptor::label]. Optional, defaults to `None`.\n"]
    pub fn label(self, label: wgpu::Label<'a>) -> BufferDescriptorBuilder<'a, SetLabel<CS>>
    where
        CS::Label: LabelIsEmpty,
    {
        BufferDescriptorBuilder {
            label: LabelValue(label),
            size: self.size,
            usage: self.usage,
            mapped_at_creation: self.mapped_at_creation,
        }
    }
    #[doc = "Setter for [wgpu::BufferDescriptor::size]. Required.\n"]
    pub fn size(self, size: wgpu::BufferAddress) -> BufferDescriptorBuilder<'a, SetSize<CS>>
    where
        CS::Size: SizeIsEmpty,
    {
        BufferDescriptorBuilder {
            label: self.label,
            size: SizeValue(size),
            usage: self.usage,
            mapped_at_creation: self.mapped_at_creation,
        }
    }
    #[doc = "Setter for [wgpu::BufferDescriptor::usage]. Required.\n"]
    pub fn usage(self, usage: wgpu::BufferUsages) -> BufferDescriptorBuilder<'a, SetUsage<CS>>
    where
        CS::Usage: UsageIsEmpty,
    {
        BufferDescriptorBuilder {
            label: self.label,
            size: self.size,
            usage: UsageValue(usage),
            mapped_at_creation: self.mapped_at_creation,
        }
    }
    #[doc = "Setter for [wgpu::BufferDescriptor::mapped_at_creation]. Required.\n"]
    pub fn mapped_at_creation(
        self,
        mapped_at_creation: bool,
    ) -> BufferDescriptorBuilder<'a, SetMappedAtCreation<CS>>
    where
        CS::MappedAtCreation: MappedAtCreationIsEmpty,
    {
        BufferDescriptorBuilder {
            label: self.label,
            size: self.size,
            usage: self.usage,
            mapped_at_creation: MappedAtCreationValue(mapped_at_creation),
        }
    }
}
pub trait Complete<'a>:
    State<
    'a,
    Label: IsSetLabel<'a>,
    Size: IsSetSize,
    Usage: IsSetUsage,
    MappedAtCreation: IsSetMappedAtCreation,
>
{
}
impl<
        'a,
        CS: State<
            'a,
            Label: IsSetLabel<'a>,
            Size: IsSetSize,
            Usage: IsSetUsage,
            MappedAtCreation: IsSetMappedAtCreation,
        >,
    > Complete<'a> for CS
{
}
impl<'a, CS: Complete<'a>> BufferDescriptorBuilder<'a, CS> {
    pub fn build(self) -> wgpu::BufferDescriptor<'a> {
        wgpu::BufferDescriptor {
            label: IsSetLabel::get(self.label),
            size: IsSetSize::get(self.size),
            usage: IsSetUsage::get(self.usage),
            mapped_at_creation: IsSetMappedAtCreation::get(self.mapped_at_creation),
        }
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::IsSetLabel::get(super::LabelEmpty)),
            format!("{:#?}", wgpu::Label::default()),
        );
    }
}
