// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu::NoopBackendOptions`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [enable](NoopBackendOptionsBuilder::enable) Optional, defaults to `false`\n  - [limits](NoopBackendOptionsBuilder::limits) Optional, defaults to `None`\n  - [features](NoopBackendOptionsBuilder::features) Optional, defaults to `None`\n  - [device_type](NoopBackendOptionsBuilder::device_type) Optional, defaults to `None`\n  - [subgroup_min_size](NoopBackendOptionsBuilder::subgroup_min_size) Optional, defaults to `None`\n  - [subgroup_max_size](NoopBackendOptionsBuilder::subgroup_max_size) Optional, defaults to `None`\n"]
pub struct NoopBackendOptionsBuilder<CS: State> {
    enable: CS::Enable,
    limits: CS::Limits,
    features: CS::Features,
    device_type: CS::DeviceType,
    subgroup_min_size: CS::SubgroupMinSize,
    subgroup_max_size: CS::SubgroupMaxSize,
}
impl NoopBackendOptionsBuilder<Empty> {
    pub fn new() -> NoopBackendOptionsBuilder<Empty> {
        NoopBackendOptionsBuilder {
            enable: EnableEmpty,
            limits: LimitsEmpty,
            features: FeaturesEmpty,
            device_type: DeviceTypeEmpty,
            subgroup_min_size: SubgroupMinSizeEmpty,
            subgroup_max_size: SubgroupMaxSizeEmpty,
        }
    }
}
#[doc = "\nReturns [NoopBackendOptionsBuilder] for building [`wgpu::NoopBackendOptions`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [enable](NoopBackendOptionsBuilder::enable) Optional, defaults to `false`\n  - [limits](NoopBackendOptionsBuilder::limits) Optional, defaults to `None`\n  - [features](NoopBackendOptionsBuilder::features) Optional, defaults to `None`\n  - [device_type](NoopBackendOptionsBuilder::device_type) Optional, defaults to `None`\n  - [subgroup_min_size](NoopBackendOptionsBuilder::subgroup_min_size) Optional, defaults to `None`\n  - [subgroup_max_size](NoopBackendOptionsBuilder::subgroup_max_size) Optional, defaults to `None`\n"]
pub fn noop_backend_options() -> NoopBackendOptionsBuilder<Empty> {
    NoopBackendOptionsBuilder::new()
}
pub struct EnableEmpty;
impl Field for EnableEmpty {}
pub trait EnableIsEmpty {}
impl EnableIsEmpty for EnableEmpty {}
pub trait IsSetEnable {
    fn get(self) -> bool;
}
impl IsSetEnable for EnableEmpty {
    fn get(self) -> bool {
        false
    }
}
pub struct EnableValue(pub bool);
impl Field for EnableValue {}
impl IsSetEnable for EnableValue {
    fn get(self) -> bool {
        self.0
    }
}
pub struct LimitsEmpty;
impl Field for LimitsEmpty {}
pub trait LimitsIsEmpty {}
impl LimitsIsEmpty for LimitsEmpty {}
pub trait IsSetLimits {
    fn get(self) -> Option<wgpu::Limits>;
}
impl IsSetLimits for LimitsEmpty {
    fn get(self) -> Option<wgpu::Limits> {
        None
    }
}
pub struct LimitsValue(pub Option<wgpu::Limits>);
impl Field for LimitsValue {}
impl IsSetLimits for LimitsValue {
    fn get(self) -> Option<wgpu::Limits> {
        self.0
    }
}
pub struct FeaturesEmpty;
impl Field for FeaturesEmpty {}
pub trait FeaturesIsEmpty {}
impl FeaturesIsEmpty for FeaturesEmpty {}
pub trait IsSetFeatures {
    fn get(self) -> Option<wgpu::Features>;
}
impl IsSetFeatures for FeaturesEmpty {
    fn get(self) -> Option<wgpu::Features> {
        None
    }
}
pub struct FeaturesValue(pub Option<wgpu::Features>);
impl Field for FeaturesValue {}
impl IsSetFeatures for FeaturesValue {
    fn get(self) -> Option<wgpu::Features> {
        self.0
    }
}
pub struct DeviceTypeEmpty;
impl Field for DeviceTypeEmpty {}
pub trait DeviceTypeIsEmpty {}
impl DeviceTypeIsEmpty for DeviceTypeEmpty {}
pub trait IsSetDeviceType {
    fn get(self) -> Option<wgpu::DeviceType>;
}
impl IsSetDeviceType for DeviceTypeEmpty {
    fn get(self) -> Option<wgpu::DeviceType> {
        None
    }
}
pub struct DeviceTypeValue(pub Option<wgpu::DeviceType>);
impl Field for DeviceTypeValue {}
impl IsSetDeviceType for DeviceTypeValue {
    fn get(self) -> Option<wgpu::DeviceType> {
        self.0
    }
}
pub struct SubgroupMinSizeEmpty;
impl Field for SubgroupMinSizeEmpty {}
pub trait SubgroupMinSizeIsEmpty {}
impl SubgroupMinSizeIsEmpty for SubgroupMinSizeEmpty {}
pub trait IsSetSubgroupMinSize {
    fn get(self) -> Option<u32>;
}
impl IsSetSubgroupMinSize for SubgroupMinSizeEmpty {
    fn get(self) -> Option<u32> {
        None
    }
}
pub struct SubgroupMinSizeValue(pub Option<u32>);
impl Field for SubgroupMinSizeValue {}
impl IsSetSubgroupMinSize for SubgroupMinSizeValue {
    fn get(self) -> Option<u32> {
        self.0
    }
}
pub struct SubgroupMaxSizeEmpty;
impl Field for SubgroupMaxSizeEmpty {}
pub trait SubgroupMaxSizeIsEmpty {}
impl SubgroupMaxSizeIsEmpty for SubgroupMaxSizeEmpty {}
pub trait IsSetSubgroupMaxSize {
    fn get(self) -> Option<u32>;
}
impl IsSetSubgroupMaxSize for SubgroupMaxSizeEmpty {
    fn get(self) -> Option<u32> {
        None
    }
}
pub struct SubgroupMaxSizeValue(pub Option<u32>);
impl Field for SubgroupMaxSizeValue {}
impl IsSetSubgroupMaxSize for SubgroupMaxSizeValue {
    fn get(self) -> Option<u32> {
        self.0
    }
}
pub trait State {
    type Enable: Field;
    type Limits: Field;
    type Features: Field;
    type DeviceType: Field;
    type SubgroupMinSize: Field;
    type SubgroupMaxSize: Field;
}
pub struct Empty;
impl State for Empty {
    type Enable = EnableEmpty;
    type Limits = LimitsEmpty;
    type Features = FeaturesEmpty;
    type DeviceType = DeviceTypeEmpty;
    type SubgroupMinSize = SubgroupMinSizeEmpty;
    type SubgroupMaxSize = SubgroupMaxSizeEmpty;
}
pub struct SetEnable<CS>(CS);
impl<CS: State> State for SetEnable<CS> {
    type Enable = EnableValue;
    type Limits = CS::Limits;
    type Features = CS::Features;
    type DeviceType = CS::DeviceType;
    type SubgroupMinSize = CS::SubgroupMinSize;
    type SubgroupMaxSize = CS::SubgroupMaxSize;
}
pub struct SetLimits<CS>(CS);
impl<CS: State> State for SetLimits<CS> {
    type Enable = CS::Enable;
    type Limits = LimitsValue;
    type Features = CS::Features;
    type DeviceType = CS::DeviceType;
    type SubgroupMinSize = CS::SubgroupMinSize;
    type SubgroupMaxSize = CS::SubgroupMaxSize;
}
pub struct SetFeatures<CS>(CS);
impl<CS: State> State for SetFeatures<CS> {
    type Enable = CS::Enable;
    type Limits = CS::Limits;
    type Features = FeaturesValue;
    type DeviceType = CS::DeviceType;
    type SubgroupMinSize = CS::SubgroupMinSize;
    type SubgroupMaxSize = CS::SubgroupMaxSize;
}
pub struct SetDeviceType<CS>(CS);
impl<CS: State> State for SetDeviceType<CS> {
    type Enable = CS::Enable;
    type Limits = CS::Limits;
    type Features = CS::Features;
    type DeviceType = DeviceTypeValue;
    type SubgroupMinSize = CS::SubgroupMinSize;
    type SubgroupMaxSize = CS::SubgroupMaxSize;
}
pub struct SetSubgroupMinSize<CS>(CS);
impl<CS: State> State for SetSubgroupMinSize<CS> {
    type Enable = CS::Enable;
    type Limits = CS::Limits;
    type Features = CS::Features;
    type DeviceType = CS::DeviceType;
    type SubgroupMinSize = SubgroupMinSizeValue;
    type SubgroupMaxSize = CS::SubgroupMaxSize;
}
pub struct SetSubgroupMaxSize<CS>(CS);
impl<CS: State> State for SetSubgroupMaxSize<CS> {
    type Enable = CS::Enable;
    type Limits = CS::Limits;
    type Features = CS::Features;
    type DeviceType = CS::DeviceType;
    type SubgroupMinSize = CS::SubgroupMinSize;
    type SubgroupMaxSize = SubgroupMaxSizeValue;
}
impl<CS: State> NoopBackendOptionsBuilder<CS> {
    #[doc = "Setter for [wgpu::NoopBackendOptions::enable]. Optional, defaults to `false`.\n"]
    pub fn enable(self, enable: bool) -> NoopBackendOptionsBuilder<SetEnable<CS>>
    where
        CS::Enable: EnableIsEmpty,
    {
        NoopBackendOptionsBuilder {
            enable: EnableValue(enable),
            limits: self.limits,
            features: self.features,
            device_type: self.device_type,
            subgroup_min_size: self.subgroup_min_size,
            subgroup_max_size: self.subgroup_max_size,
        }
    }
    #[doc = "Setter for [wgpu::NoopBackendOptions::limits]. Optional, defaults to `None`.\n"]
    pub fn limits(self, limits: wgpu::Limits) -> NoopBackendOptionsBuilder<SetLimits<CS>>
    where
        CS::Limits: LimitsIsEmpty,
    {
        NoopBackendOptionsBuilder {
            enable: self.enable,
            limits: LimitsValue(Some(limits)),
            features: self.features,
            device_type: self.device_type,
            subgroup_min_size: self.subgroup_min_size,
            subgroup_max_size: self.subgroup_max_size,
        }
    }
    #[doc = "Setter for [wgpu::NoopBackendOptions::limits]. Optional, defaults to `None`.\n"]
    pub fn maybe_limits(
        self,
        limits: Option<wgpu::Limits>,
    ) -> NoopBackendOptionsBuilder<SetLimits<CS>>
    where
        CS::Limits: LimitsIsEmpty,
    {
        NoopBackendOptionsBuilder {
            enable: self.enable,
            limits: LimitsValue(limits),
            features: self.features,
            device_type: self.device_type,
            subgroup_min_size: self.subgroup_min_size,
            subgroup_max_size: self.subgroup_max_size,
        }
    }
    #[doc = "Setter for [wgpu::NoopBackendOptions::features]. Optional, defaults to `None`.\n"]
    pub fn features(self, features: wgpu::Features) -> NoopBackendOptionsBuilder<SetFeatures<CS>>
    where
        CS::Features: FeaturesIsEmpty,
    {
        NoopBackendOptionsBuilder {
            enable: self.enable,
            limits: self.limits,
            features: FeaturesValue(Some(features)),
            device_type: self.device_type,
            subgroup_min_size: self.subgroup_min_size,
            subgroup_max_size: self.subgroup_max_size,
        }
    }
    #[doc = "Setter for [wgpu::NoopBackendOptions::features]. Optional, defaults to `None`.\n"]
    pub fn maybe_features(
        self,
        features: Option<wgpu::Features>,
    ) -> NoopBackendOptionsBuilder<SetFeatures<CS>>
    where
        CS::Features: FeaturesIsEmpty,
    {
        NoopBackendOptionsBuilder {
            enable: self.enable,
            limits: self.limits,
            features: FeaturesValue(features),
            device_type: self.device_type,
            subgroup_min_size: self.subgroup_min_size,
            subgroup_max_size: self.subgroup_max_size,
        }
    }
    #[doc = "Setter for [wgpu::NoopBackendOptions::device_type]. Optional, defaults to `None`.\n"]
    pub fn device_type(
        self,
        device_type: wgpu::DeviceType,
    ) -> NoopBackendOptionsBuilder<SetDeviceType<CS>>
    where
        CS::DeviceType: DeviceTypeIsEmpty,
    {
        NoopBackendOptionsBuilder {
            enable: self.enable,
            limits: self.limits,
            features: self.features,
            device_type: DeviceTypeValue(Some(device_type)),
            subgroup_min_size: self.subgroup_min_size,
            subgroup_max_size: self.subgroup_max_size,
        }
    }
    #[doc = "Setter for [wgpu::NoopBackendOptions::device_type]. Optional, defaults to `None`.\n"]
    pub fn maybe_device_type(
        self,
        device_type: Option<wgpu::DeviceType>,
    ) -> NoopBackendOptionsBuilder<SetDeviceType<CS>>
    where
        CS::DeviceType: DeviceTypeIsEmpty,
    {
        NoopBackendOptionsBuilder {
            enable: self.enable,
            limits: self.limits,
            features: self.features,
            device_type: DeviceTypeValue(device_type),
            subgroup_min_size: self.subgroup_min_size,
            subgroup_max_size: self.subgroup_max_size,
        }
    }
    #[doc = "Setter for [wgpu::NoopBackendOptions::subgroup_min_size]. Optional, defaults to `None`.\n"]
    pub fn subgroup_min_size(
        self,
        subgroup_min_size: u32,
    ) -> NoopBackendOptionsBuilder<SetSubgroupMinSize<CS>>
    where
        CS::SubgroupMinSize: SubgroupMinSizeIsEmpty,
    {
        NoopBackendOptionsBuilder {
            enable: self.enable,
            limits: self.limits,
            features: self.features,
            device_type: self.device_type,
            subgroup_min_size: SubgroupMinSizeValue(Some(subgroup_min_size)),
            subgroup_max_size: self.subgroup_max_size,
        }
    }
    #[doc = "Setter for [wgpu::NoopBackendOptions::subgroup_min_size]. Optional, defaults to `None`.\n"]
    pub fn maybe_subgroup_min_size(
        self,
        subgroup_min_size: Option<u32>,
    ) -> NoopBackendOptionsBuilder<SetSubgroupMinSize<CS>>
    where
        CS::SubgroupMinSize: SubgroupMinSizeIsEmpty,
    {
        NoopBackendOptionsBuilder {
            enable: self.enable,
            limits: self.limits,
            features: self.features,
            device_type: self.device_type,
            subgroup_min_size: SubgroupMinSizeValue(subgroup_min_size),
            subgroup_max_size: self.subgroup_max_size,
        }
    }
    #[doc = "Setter for [wgpu::NoopBackendOptions::subgroup_max_size]. Optional, defaults to `None`.\n"]
    pub fn subgroup_max_size(
        self,
        subgroup_max_size: u32,
    ) -> NoopBackendOptionsBuilder<SetSubgroupMaxSize<CS>>
    where
        CS::SubgroupMaxSize: SubgroupMaxSizeIsEmpty,
    {
        NoopBackendOptionsBuilder {
            enable: self.enable,
            limits: self.limits,
            features: self.features,
            device_type: self.device_type,
            subgroup_min_size: self.subgroup_min_size,
            subgroup_max_size: SubgroupMaxSizeValue(Some(subgroup_max_size)),
        }
    }
    #[doc = "Setter for [wgpu::NoopBackendOptions::subgroup_max_size]. Optional, defaults to `None`.\n"]
    pub fn maybe_subgroup_max_size(
        self,
        subgroup_max_size: Option<u32>,
    ) -> NoopBackendOptionsBuilder<SetSubgroupMaxSize<CS>>
    where
        CS::SubgroupMaxSize: SubgroupMaxSizeIsEmpty,
    {
        NoopBackendOptionsBuilder {
            enable: self.enable,
            limits: self.limits,
            features: self.features,
            device_type: self.device_type,
            subgroup_min_size: self.subgroup_min_size,
            subgroup_max_size: SubgroupMaxSizeValue(subgroup_max_size),
        }
    }
}
pub trait Complete:
    State<
    Enable: IsSetEnable,
    Limits: IsSetLimits,
    Features: IsSetFeatures,
    DeviceType: IsSetDeviceType,
    SubgroupMinSize: IsSetSubgroupMinSize,
    SubgroupMaxSize: IsSetSubgroupMaxSize,
>
{
}
impl<
        CS: State<
            Enable: IsSetEnable,
            Limits: IsSetLimits,
            Features: IsSetFeatures,
            DeviceType: IsSetDeviceType,
            SubgroupMinSize: IsSetSubgroupMinSize,
            SubgroupMaxSize: IsSetSubgroupMaxSize,
        >,
    > Complete for CS
{
}
impl<CS: Complete> NoopBackendOptionsBuilder<CS> {
    pub fn build(self) -> wgpu::NoopBackendOptions {
        wgpu::NoopBackendOptions {
            enable: IsSetEnable::get(self.enable),
            limits: IsSetLimits::get(self.limits),
            features: IsSetFeatures::get(self.features),
            device_type: IsSetDeviceType::get(self.device_type),
            subgroup_min_size: IsSetSubgroupMinSize::get(self.subgroup_min_size),
            subgroup_max_size: IsSetSubgroupMaxSize::get(self.subgroup_max_size),
        }
    }
}
impl Nested<wgpu::NoopBackendOptions> for wgpu::NoopBackendOptions {
    fn unnest(self) -> wgpu::NoopBackendOptions {
        self
    }
}
impl<CS: Complete> Nested<wgpu::NoopBackendOptions> for NoopBackendOptionsBuilder<CS> {
    fn unnest(self) -> wgpu::NoopBackendOptions {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::noop_backend_options().build()),
            format!("{:#?}", wgpu::NoopBackendOptions::default()),
        );
    }
}
