// The code in this file is generated by a script. Do not edit it directly.
//

pub use crate::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu::Operations`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder fields:\n  - [load](OperationsBuilder::load) Optional, defaults to [wgpu::LoadOp::Clear(Default::default())]\n  - [store](OperationsBuilder::store) Optional, defaults to [wgpu::StoreOp::Store]\n"]
pub struct OperationsBuilder<V: Default, CS: State<V>> {
    load: CS::Load,
    store: CS::Store,
}
impl<V: Default> OperationsBuilder<V, Empty> {
    pub fn new() -> OperationsBuilder<V, Empty> {
        OperationsBuilder {
            load: LoadEmpty,
            store: StoreEmpty,
        }
    }
}
#[doc = "\nReturns [OperationsBuilder] for building [`wgpu::Operations`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder fields:\n  - [load](OperationsBuilder::load) Optional, defaults to [wgpu::LoadOp::Clear(Default::default())]\n  - [store](OperationsBuilder::store) Optional, defaults to [wgpu::StoreOp::Store]\n"]
pub fn operations<V: Default>() -> OperationsBuilder<V, Empty> {
    OperationsBuilder::new()
}
pub struct LoadEmpty;
impl Field for LoadEmpty {}
pub trait LoadIsEmpty {}
impl LoadIsEmpty for LoadEmpty {}
pub trait IsSetLoad<V: Default> {
    fn get(self) -> wgpu::LoadOp<V>;
}
impl<V: Default> IsSetLoad<V> for LoadEmpty {
    fn get(self) -> wgpu::LoadOp<V> {
        wgpu::LoadOp::Clear(Default::default())
    }
}
pub struct LoadValue<V: Default>(pub wgpu::LoadOp<V>);
impl<V: Default> Field for LoadValue<V> {}
impl<V: Default> IsSetLoad<V> for LoadValue<V> {
    fn get(self) -> wgpu::LoadOp<V> {
        self.0
    }
}
pub struct StoreEmpty;
impl Field for StoreEmpty {}
pub trait StoreIsEmpty {}
impl StoreIsEmpty for StoreEmpty {}
pub trait IsSetStore {
    fn get(self) -> wgpu::StoreOp;
}
impl IsSetStore for StoreEmpty {
    fn get(self) -> wgpu::StoreOp {
        wgpu::StoreOp::Store
    }
}
pub struct StoreValue(pub wgpu::StoreOp);
impl Field for StoreValue {}
impl IsSetStore for StoreValue {
    fn get(self) -> wgpu::StoreOp {
        self.0
    }
}
pub trait State<V: Default> {
    type Load: Field;
    type Store: Field;
}
pub struct Empty;
impl<V: Default> State<V> for Empty {
    type Load = LoadEmpty;
    type Store = StoreEmpty;
}
pub struct SetLoad<CS>(CS);
impl<V: Default, CS: State<V>> State<V> for SetLoad<CS> {
    type Load = LoadValue<V>;
    type Store = CS::Store;
}
pub struct SetStore<CS>(CS);
impl<V: Default, CS: State<V>> State<V> for SetStore<CS> {
    type Load = CS::Load;
    type Store = StoreValue;
}
impl<V: Default, CS: State<V>> OperationsBuilder<V, CS> {
    #[doc = "Setter for [wgpu::Operations::load]. Optional, defaults to [wgpu::LoadOp::Clear(Default::default())].\n"]
    pub fn load(self, load: wgpu::LoadOp<V>) -> OperationsBuilder<V, SetLoad<CS>>
    where
        CS::Load: LoadIsEmpty,
    {
        OperationsBuilder {
            load: LoadValue(load),
            store: self.store,
        }
    }
    #[doc = "Setter for [wgpu::Operations::store]. Optional, defaults to [wgpu::StoreOp::Store].\n"]
    pub fn store(self, store: wgpu::StoreOp) -> OperationsBuilder<V, SetStore<CS>>
    where
        CS::Store: StoreIsEmpty,
    {
        OperationsBuilder {
            load: self.load,
            store: StoreValue(store),
        }
    }
}
pub trait Complete<V: Default>: State<V, Load: IsSetLoad<V>, Store: IsSetStore> {}
impl<V: Default, CS: State<V, Load: IsSetLoad<V>, Store: IsSetStore>> Complete<V> for CS {}
impl<V: Default, CS: Complete<V>> OperationsBuilder<V, CS> {
    pub fn build(self) -> wgpu::Operations<V> {
        wgpu::Operations {
            load: IsSetLoad::get(self.load),
            store: IsSetStore::get(self.store),
        }
    }
}
impl<V: Default> Nested<wgpu::Operations<V>> for wgpu::Operations<V> {
    fn unnest(self) -> wgpu::Operations<V> {
        self
    }
}
impl<V: Default, CS: Complete<V>> Nested<wgpu::Operations<V>> for OperationsBuilder<V, CS> {
    fn unnest(self) -> wgpu::Operations<V> {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::operations::<u32>().build()),
            format!("{:#?}", wgpu::Operations::<u32>::default()),
        );
    }
}
