// The code in this file is generated by a script. Do not edit it directly.
//

pub use crate::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu::Origin2d`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder fields:\n  - [x](Origin2dBuilder::x) Required\n  - [y](Origin2dBuilder::y) Required\n"]
pub struct Origin2dBuilder<CS: State> {
    x: CS::X,
    y: CS::Y,
}
impl Origin2dBuilder<Empty> {
    pub fn new() -> Origin2dBuilder<Empty> {
        Origin2dBuilder {
            x: XEmpty,
            y: YEmpty,
        }
    }
}
#[doc = "\nReturns [Origin2dBuilder] for building [`wgpu::Origin2d`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder fields:\n  - [x](Origin2dBuilder::x) Required\n  - [y](Origin2dBuilder::y) Required\n"]
pub fn origin_2_d() -> Origin2dBuilder<Empty> {
    Origin2dBuilder::new()
}
pub struct XEmpty;
impl Field for XEmpty {}
pub trait XIsEmpty {}
impl XIsEmpty for XEmpty {}
pub trait IsSetX {
    fn get(self) -> u32;
}
pub struct XValue(pub u32);
impl Field for XValue {}
impl IsSetX for XValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub struct YEmpty;
impl Field for YEmpty {}
pub trait YIsEmpty {}
impl YIsEmpty for YEmpty {}
pub trait IsSetY {
    fn get(self) -> u32;
}
pub struct YValue(pub u32);
impl Field for YValue {}
impl IsSetY for YValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub trait State {
    type X: Field;
    type Y: Field;
}
pub struct Empty;
impl State for Empty {
    type X = XEmpty;
    type Y = YEmpty;
}
pub struct SetX<CS>(CS);
impl<CS: State> State for SetX<CS> {
    type X = XValue;
    type Y = CS::Y;
}
pub struct SetY<CS>(CS);
impl<CS: State> State for SetY<CS> {
    type X = CS::X;
    type Y = YValue;
}
impl<CS: State> Origin2dBuilder<CS> {
    #[doc = "Setter for [wgpu::Origin2d::x]. Required.\n"]
    pub fn x(self, x: u32) -> Origin2dBuilder<SetX<CS>>
    where
        CS::X: XIsEmpty,
    {
        Origin2dBuilder {
            x: XValue(x),
            y: self.y,
        }
    }
    #[doc = "Setter for [wgpu::Origin2d::y]. Required.\n"]
    pub fn y(self, y: u32) -> Origin2dBuilder<SetY<CS>>
    where
        CS::Y: YIsEmpty,
    {
        Origin2dBuilder {
            x: self.x,
            y: YValue(y),
        }
    }
}
pub trait Complete: State<X: IsSetX, Y: IsSetY> {}
impl<CS: State<X: IsSetX, Y: IsSetY>> Complete for CS {}
impl<CS: Complete> Origin2dBuilder<CS> {
    pub fn build(self) -> wgpu::Origin2d {
        wgpu::Origin2d {
            x: IsSetX::get(self.x),
            y: IsSetY::get(self.y),
        }
    }
}
impl Nested<wgpu::Origin2d> for wgpu::Origin2d {
    fn unnest(self) -> wgpu::Origin2d {
        self
    }
}
impl<CS: Complete> Nested<wgpu::Origin2d> for Origin2dBuilder<CS> {
    fn unnest(self) -> wgpu::Origin2d {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {}
}
