// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu::PassthroughShaderEntryPoint`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [name](PassthroughShaderEntryPointBuilder::name) Required\n  - [workgroup_size](PassthroughShaderEntryPointBuilder::workgroup_size) Required\n"]
pub struct PassthroughShaderEntryPointBuilder<'a, CS: State<'a>> {
    name: CS::Name,
    workgroup_size: CS::WorkgroupSize,
}
impl<'a> PassthroughShaderEntryPointBuilder<'a, Empty> {
    pub fn new() -> PassthroughShaderEntryPointBuilder<'a, Empty> {
        PassthroughShaderEntryPointBuilder {
            name: NameEmpty,
            workgroup_size: WorkgroupSizeEmpty,
        }
    }
}
#[doc = "\nReturns [PassthroughShaderEntryPointBuilder] for building [`wgpu::PassthroughShaderEntryPoint`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [name](PassthroughShaderEntryPointBuilder::name) Required\n  - [workgroup_size](PassthroughShaderEntryPointBuilder::workgroup_size) Required\n"]
pub fn passthrough_shader_entry_point<'a>() -> PassthroughShaderEntryPointBuilder<'a, Empty> {
    PassthroughShaderEntryPointBuilder::new()
}
pub struct NameEmpty;
impl Field for NameEmpty {}
pub trait NameIsEmpty {}
impl NameIsEmpty for NameEmpty {}
pub trait IsSetName<'a> {
    fn get(self) -> Cow<'a, str>;
}
pub struct NameValue<'a>(pub Cow<'a, str>);
impl<'a> Field for NameValue<'a> {}
impl<'a> IsSetName<'a> for NameValue<'a> {
    fn get(self) -> Cow<'a, str> {
        self.0
    }
}
pub struct WorkgroupSizeEmpty;
impl Field for WorkgroupSizeEmpty {}
pub trait WorkgroupSizeIsEmpty {}
impl WorkgroupSizeIsEmpty for WorkgroupSizeEmpty {}
pub trait IsSetWorkgroupSize {
    fn get(self) -> (u32, u32, u32);
}
pub struct WorkgroupSizeValue(pub (u32, u32, u32));
impl Field for WorkgroupSizeValue {}
impl IsSetWorkgroupSize for WorkgroupSizeValue {
    fn get(self) -> (u32, u32, u32) {
        self.0
    }
}
pub trait State<'a> {
    type Name: Field;
    type WorkgroupSize: Field;
}
pub struct Empty;
impl<'a> State<'a> for Empty {
    type Name = NameEmpty;
    type WorkgroupSize = WorkgroupSizeEmpty;
}
pub struct SetName<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetName<CS> {
    type Name = NameValue<'a>;
    type WorkgroupSize = CS::WorkgroupSize;
}
pub struct SetWorkgroupSize<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetWorkgroupSize<CS> {
    type Name = CS::Name;
    type WorkgroupSize = WorkgroupSizeValue;
}
impl<'a, CS: State<'a>> PassthroughShaderEntryPointBuilder<'a, CS> {
    #[doc = "Setter for [wgpu::PassthroughShaderEntryPoint::name]. Required.\n"]
    pub fn name(self, name: Cow<'a, str>) -> PassthroughShaderEntryPointBuilder<'a, SetName<CS>>
    where
        CS::Name: NameIsEmpty,
    {
        PassthroughShaderEntryPointBuilder {
            name: NameValue(name),
            workgroup_size: self.workgroup_size,
        }
    }
    #[doc = "Setter for [wgpu::PassthroughShaderEntryPoint::workgroup_size]. Required.\n"]
    pub fn workgroup_size(
        self,
        workgroup_size: (u32, u32, u32),
    ) -> PassthroughShaderEntryPointBuilder<'a, SetWorkgroupSize<CS>>
    where
        CS::WorkgroupSize: WorkgroupSizeIsEmpty,
    {
        PassthroughShaderEntryPointBuilder {
            name: self.name,
            workgroup_size: WorkgroupSizeValue(workgroup_size),
        }
    }
}
pub trait Complete<'a>: State<'a, Name: IsSetName<'a>, WorkgroupSize: IsSetWorkgroupSize> {}
impl<'a, CS: State<'a, Name: IsSetName<'a>, WorkgroupSize: IsSetWorkgroupSize>> Complete<'a>
    for CS
{
}
impl<'a, CS: Complete<'a>> PassthroughShaderEntryPointBuilder<'a, CS> {
    pub fn build(self) -> wgpu::PassthroughShaderEntryPoint<'a> {
        wgpu::PassthroughShaderEntryPoint {
            name: IsSetName::get(self.name),
            workgroup_size: IsSetWorkgroupSize::get(self.workgroup_size),
        }
    }
}
impl<'a> Nested<wgpu::PassthroughShaderEntryPoint<'a>> for wgpu::PassthroughShaderEntryPoint<'a> {
    fn unnest(self) -> wgpu::PassthroughShaderEntryPoint<'a> {
        self
    }
}
impl<'a, CS: Complete<'a>> Nested<wgpu::PassthroughShaderEntryPoint<'a>>
    for PassthroughShaderEntryPointBuilder<'a, CS>
{
    fn unnest(self) -> wgpu::PassthroughShaderEntryPoint<'a> {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {}
}
