// The code in this file is generated by a script. Do not edit it directly.
//

pub use crate::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu::PushConstantRange`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder fields:\n  - [stages](PushConstantRangeBuilder::stages) Required\n  - [range](PushConstantRangeBuilder::range) Required\n"]
pub struct PushConstantRangeBuilder<CS: State> {
    stages: CS::Stages,
    range: CS::Range,
}
impl PushConstantRangeBuilder<Empty> {
    pub fn new() -> PushConstantRangeBuilder<Empty> {
        PushConstantRangeBuilder {
            stages: StagesEmpty,
            range: RangeEmpty,
        }
    }
}
#[doc = "\nReturns [PushConstantRangeBuilder] for building [`wgpu::PushConstantRange`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder fields:\n  - [stages](PushConstantRangeBuilder::stages) Required\n  - [range](PushConstantRangeBuilder::range) Required\n"]
pub fn push_constant_range() -> PushConstantRangeBuilder<Empty> {
    PushConstantRangeBuilder::new()
}
pub struct StagesEmpty;
impl Field for StagesEmpty {}
pub trait StagesIsEmpty {}
impl StagesIsEmpty for StagesEmpty {}
pub trait IsSetStages {
    fn get(self) -> wgpu::ShaderStages;
}
pub struct StagesValue(pub wgpu::ShaderStages);
impl Field for StagesValue {}
impl IsSetStages for StagesValue {
    fn get(self) -> wgpu::ShaderStages {
        self.0
    }
}
pub struct RangeEmpty;
impl Field for RangeEmpty {}
pub trait RangeIsEmpty {}
impl RangeIsEmpty for RangeEmpty {}
pub trait IsSetRange {
    fn get(self) -> Range<u32>;
}
pub struct RangeValue(pub Range<u32>);
impl Field for RangeValue {}
impl IsSetRange for RangeValue {
    fn get(self) -> Range<u32> {
        self.0
    }
}
pub trait State {
    type Stages: Field;
    type Range: Field;
}
pub struct Empty;
impl State for Empty {
    type Stages = StagesEmpty;
    type Range = RangeEmpty;
}
pub struct SetStages<CS>(CS);
impl<CS: State> State for SetStages<CS> {
    type Stages = StagesValue;
    type Range = CS::Range;
}
pub struct SetRange<CS>(CS);
impl<CS: State> State for SetRange<CS> {
    type Stages = CS::Stages;
    type Range = RangeValue;
}
impl<CS: State> PushConstantRangeBuilder<CS> {
    #[doc = "Setter for [wgpu::PushConstantRange::stages]. Required.\n"]
    pub fn stages(self, stages: wgpu::ShaderStages) -> PushConstantRangeBuilder<SetStages<CS>>
    where
        CS::Stages: StagesIsEmpty,
    {
        PushConstantRangeBuilder {
            stages: StagesValue(stages),
            range: self.range,
        }
    }
    #[doc = "Setter for [wgpu::PushConstantRange::range]. Required.\n"]
    pub fn range(self, range: Range<u32>) -> PushConstantRangeBuilder<SetRange<CS>>
    where
        CS::Range: RangeIsEmpty,
    {
        PushConstantRangeBuilder {
            stages: self.stages,
            range: RangeValue(range),
        }
    }
}
pub trait Complete: State<Stages: IsSetStages, Range: IsSetRange> {}
impl<CS: State<Stages: IsSetStages, Range: IsSetRange>> Complete for CS {}
impl<CS: Complete> PushConstantRangeBuilder<CS> {
    pub fn build(self) -> wgpu::PushConstantRange {
        wgpu::PushConstantRange {
            stages: IsSetStages::get(self.stages),
            range: IsSetRange::get(self.range),
        }
    }
}
impl Nested<wgpu::PushConstantRange> for wgpu::PushConstantRange {
    fn unnest(self) -> wgpu::PushConstantRange {
        self
    }
}
impl<CS: Complete> Nested<wgpu::PushConstantRange> for PushConstantRangeBuilder<CS> {
    fn unnest(self) -> wgpu::PushConstantRange {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {}
}
