use quote::quote as q;
use std::collections::HashMap;

use discover_exports::{
    analysis::Analysis, crate_graph::for_each_node, process::parse_crate, resolve::PathType,
};

use crate::{
    generate::struct_entry::{Output, filter_struct, output_struct},
    utils::{relative_path, rustfmt, without_args},
};

pub mod base;
pub mod builder;
pub mod docs;
pub mod nested;
pub mod setter;
pub mod state;
mod struct_entry;
pub mod tests;
pub mod types;

const SKIP: &[&str] = &[
    "AdapterInfo",
    "AllocatorReport",
    "BufferTextureCopyInfo",
    "CompilationMessage",
    "CoreCounters",
    "DownlevelCapabilities",
    "Features",
    "GLBackendOptions",
    "HalCounters",
    "InternalCounters",
    "Limits",
    "SourceLocation",
    "SurfaceCapabilities",
    "TextureFormatFeatures",
];

pub fn generate() -> anyhow::Result<()> {
    let mut analysis = Analysis::default();
    let wgpu = {
        parse_crate(
            &mut analysis,
            relative_path("expanded/wgpu_types.rs"),
            relative_path("wgpu/wgpu-types"),
            "wgpu_types",
            vec![],
        )
        .unwrap();

        parse_crate(
            &mut analysis,
            relative_path("expanded/wgpu_core.rs"),
            relative_path("wgpu/wgpu-core"),
            "wgpu_core",
            vec!["wgpu_types".to_string()],
        )
        .unwrap();

        parse_crate(
            &mut analysis,
            relative_path("expanded/wgpu_hal.rs"),
            relative_path("wgpu/wgpu-hal"),
            "wgpu_hal",
            vec!["wgpu_core".to_string()],
        )
        .unwrap();

        parse_crate(
            &mut analysis,
            relative_path("expanded/naga.rs"),
            relative_path("wgpu/naga"),
            "wgpu_hal",
            vec![],
        )
        .unwrap();

        let wgpu = parse_crate(
            &mut analysis,
            relative_path("expanded/wgpu.rs"),
            relative_path("wgpu/wgpu"),
            "wgpu",
            vec![],
        )
        .unwrap();

        wgpu
    };

    let mut builders = vec![];
    let mut builder_entries = HashMap::new();

    for_each_node(
        &wgpu,
        |(index, path)| {
            if filter_struct(&wgpu, index, &path).is_some() {
                let idents = without_args(&path);
                builder_entries.insert(q!(#idents).to_string(), (index, path.clone()));
            }
        },
        PathType::TopLevelPublicOnly,
    )
    .unwrap();

    for (_, (index, path)) in builder_entries.iter() {
        builders.push(output_struct(&wgpu, *index, path.clone(), &builder_entries));
    }

    let builder_mods = builders
        .iter()
        .map(|Output { builder_mod, .. }| {
            format!(
                "
{builder_mod}
"
            )
        })
        .collect::<String>();

    let output_path = relative_path("quickgpu/src/builders/mod.rs");
    std::fs::write(output_path.clone(), builder_mods)?;
    rustfmt(output_path)?;

    let use_statements = builders
        .iter()
        .map(|Output { use_statement, .. }| {
            format!(
                "
{use_statement}
"
            )
        })
        .collect::<String>();

    let use_statements = format!(
        "
// The code in this file is generated by a script. Do not edit it directly.
//
#![doc=include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/INTRO.md\"))]

pub mod custom;
pub use custom::*;

pub mod builders;

{use_statements}
"
    );

    let output_path = relative_path("quickgpu/src/lib.rs");
    std::fs::write(output_path.clone(), use_statements)?;
    rustfmt(output_path)?;

    for Output {
        name,
        comment,
        code,
        ..
    } in builders
    {
        let combined = format!(
            "
// The code in this file is generated by a script. Do not edit it directly.
//

{comment}
{code}
        "
        );

        let output_path = relative_path("quickgpu/src/builders/").join(format!("{}.rs", name));
        std::fs::write(output_path.clone(), combined)?;
        rustfmt(output_path)?;
    }

    Ok(())
}
