use clap::ValueEnum;
use quote::{ToTokens, quote as q};
use std::collections::HashMap;
use xshell::Shell;

use discover_exports::{
    analysis::Analysis, crate_graph::for_each_node, process::parse_crate, resolve::PathType,
};

use crate::{
    generate::{
        shared::{cargo_toml, intro},
        struct_entry::{Output, filter_struct, output_struct},
    },
    utils::{relative_path, rustfmt, without_args},
};

pub mod base;
pub mod builder;
pub mod docs;
pub mod nested;
pub mod setter;
pub mod shared;
pub mod state;
mod struct_entry;
pub mod tests;
pub mod types;

const SKIP: &[&str] = &[
    "AdapterInfo",
    "AllocatorReport",
    "BufferTextureCopyInfo",
    "CompilationMessage",
    "CoreCounters",
    "DownlevelCapabilities",
    "Features",
    "GLBackendOptions",
    "HalCounters",
    "InternalCounters",
    "Limits",
    "SourceLocation",
    "SurfaceCapabilities",
    "TextureFormatFeatures",
];

#[derive(Copy, Clone, ValueEnum)]
pub enum Version {
    V27,
    V28,
}

pub fn generate(version: Version) -> anyhow::Result<()> {
    let mut analysis = Analysis::default();

    let wgpu_source = match version {
        Version::V27 => "wgpu_v27",
        Version::V28 => "wgpu_v28",
    };

    let crate_name = match version {
        Version::V27 => "quickgpu27",
        Version::V28 => "quickgpu",
    };

    let wgpu = {
        parse_crate(
            &mut analysis,
            relative_path("expanded/wgpu_types.rs"),
            relative_path(format!("{wgpu_source}/wgpu-types")),
            "wgpu_types",
            vec![],
        )
        .unwrap();

        parse_crate(
            &mut analysis,
            relative_path("expanded/wgpu_core.rs"),
            relative_path(format!("{wgpu_source}/wgpu-core")),
            "wgpu_core",
            vec!["wgpu_types".to_string()],
        )
        .unwrap();

        parse_crate(
            &mut analysis,
            relative_path("expanded/wgpu_hal.rs"),
            relative_path(format!("{wgpu_source}/wgpu-hal")),
            "wgpu_hal",
            vec!["wgpu_core".to_string()],
        )
        .unwrap();

        parse_crate(
            &mut analysis,
            relative_path("expanded/naga.rs"),
            relative_path(format!("{wgpu_source}/naga")),
            "wgpu_hal",
            vec![],
        )
        .unwrap();

        let wgpu = parse_crate(
            &mut analysis,
            relative_path("expanded/wgpu.rs"),
            relative_path(format!("{wgpu_source}/wgpu")),
            "wgpu",
            vec![],
        )
        .unwrap();

        wgpu
    };

    let intro_path = relative_path(format!("{crate_name}/INTRO.md"));
    std::fs::write(intro_path.clone(), intro(version))?;

    let cargo_path = relative_path(format!("{crate_name}/Cargo.toml"));
    std::fs::write(cargo_path.clone(), cargo_toml(version))?;

    let builders_path = relative_path(format!("{crate_name}/src/builders/"));
    let sh = Shell::new()?;
    sh.remove_path(builders_path.clone())?;
    sh.create_dir(builders_path)?;

    let mut builders = vec![];
    let mut builder_entries = HashMap::new();

    for_each_node(
        &wgpu,
        |(index, path)| {
            if filter_struct(&wgpu, index, &path).is_some() {
                let idents = without_args(&path);
                builder_entries.insert(q!(#idents).to_string(), (index, path.clone()));
            }
        },
        PathType::TopLevelPublicOnly,
    )
    .unwrap();

    let mut builder_entries_sorted = builder_entries
        .iter()
        .map(|(_, (index, path))| (index, path))
        .collect::<Vec<_>>();

    builder_entries_sorted.sort_by(|(_, a_path), (_, b_path)| {
        a_path
            .segments
            .last()
            .into_token_stream()
            .to_string()
            .cmp(&b_path.segments.last().into_token_stream().to_string())
    });

    for (index, path) in builder_entries_sorted {
        builders.push(output_struct(&wgpu, *index, path.clone(), &builder_entries));
    }

    for Output {
        name,
        comment,
        code,
        ..
    } in builders.iter()
    {
        let combined = format!(
            "
// The code in this file is generated by a script. Do not edit it directly.
//

{comment}
{code}
        "
        );

        let output_path =
            relative_path(format!("{crate_name}/src/builders/")).join(format!("{}.rs", name));

        std::fs::write(output_path.clone(), combined)?;
        rustfmt(output_path)?;
    }

    let builder_mods = builders
        .iter()
        .map(|Output { builder_mod, .. }| {
            format!(
                "
{builder_mod}
"
            )
        })
        .collect::<String>();

    let output_path = relative_path(format!("{crate_name}/src/builders/mod.rs"));
    std::fs::write(output_path.clone(), builder_mods)?;
    rustfmt(output_path)?;

    let use_statements = builders
        .iter()
        .map(|Output { use_statement, .. }| {
            format!(
                "
{use_statement}
"
            )
        })
        .collect::<String>();

    let use_statements = format!(
        r#"
#![doc=include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/INTRO.md"))]

pub mod custom;
pub use custom::*;
pub mod builders;

{use_statements}
"#
    );

    let output_path = relative_path(format!("{crate_name}/src/lib.rs"));
    std::fs::write(output_path.clone(), use_statements)?;
    rustfmt(output_path)?;

    Ok(())
}
