[package]
name = "binder"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
derive_more = { version = "2.1.1", features = ["debug", "display"] }
env_logger.workspace = true
glam = { version = "0.31.0", features = ["mint"] }
log.workspace = true
mint = { workspace = true }
naga = { workspace = true, features = ["wgsl-in"] }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full", "parsing"] }
