#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_28::BlasTriangleGeometry`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [size](BlasTriangleGeometryBuilder::size) Required\n  - [vertex_buffer](BlasTriangleGeometryBuilder::vertex_buffer) Required\n  - [first_vertex](BlasTriangleGeometryBuilder::first_vertex) Required\n  - [vertex_stride](BlasTriangleGeometryBuilder::vertex_stride) Required\n  - [index_buffer](BlasTriangleGeometryBuilder::index_buffer) Optional, defaults to `None`\n  - [first_index](BlasTriangleGeometryBuilder::first_index) Optional, defaults to `None`\n  - [transform_buffer](BlasTriangleGeometryBuilder::transform_buffer) Optional, defaults to `None`\n  - [transform_buffer_offset](BlasTriangleGeometryBuilder::transform_buffer_offset) Optional, defaults to `None`\n"]
pub struct BlasTriangleGeometryBuilder<'a, CS: State<'a>> {
    size: CS::Size,
    vertex_buffer: CS::VertexBuffer,
    first_vertex: CS::FirstVertex,
    vertex_stride: CS::VertexStride,
    index_buffer: CS::IndexBuffer,
    first_index: CS::FirstIndex,
    transform_buffer: CS::TransformBuffer,
    transform_buffer_offset: CS::TransformBufferOffset,
}
impl<'a> BlasTriangleGeometryBuilder<'a, Empty> {
    pub fn new() -> BlasTriangleGeometryBuilder<'a, Empty> {
        BlasTriangleGeometryBuilder {
            size: SizeEmpty,
            vertex_buffer: VertexBufferEmpty,
            first_vertex: FirstVertexEmpty,
            vertex_stride: VertexStrideEmpty,
            index_buffer: IndexBufferEmpty,
            first_index: FirstIndexEmpty,
            transform_buffer: TransformBufferEmpty,
            transform_buffer_offset: TransformBufferOffsetEmpty,
        }
    }
}
#[doc = "\nReturns [BlasTriangleGeometryBuilder] for building [`wgpu_28::BlasTriangleGeometry`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [size](BlasTriangleGeometryBuilder::size) Required\n  - [vertex_buffer](BlasTriangleGeometryBuilder::vertex_buffer) Required\n  - [first_vertex](BlasTriangleGeometryBuilder::first_vertex) Required\n  - [vertex_stride](BlasTriangleGeometryBuilder::vertex_stride) Required\n  - [index_buffer](BlasTriangleGeometryBuilder::index_buffer) Optional, defaults to `None`\n  - [first_index](BlasTriangleGeometryBuilder::first_index) Optional, defaults to `None`\n  - [transform_buffer](BlasTriangleGeometryBuilder::transform_buffer) Optional, defaults to `None`\n  - [transform_buffer_offset](BlasTriangleGeometryBuilder::transform_buffer_offset) Optional, defaults to `None`\n"]
pub fn blas_triangle_geometry<'a>() -> BlasTriangleGeometryBuilder<'a, Empty> {
    BlasTriangleGeometryBuilder::new()
}
pub struct SizeEmpty;
impl Field for SizeEmpty {}
pub trait SizeIsEmpty {}
impl SizeIsEmpty for SizeEmpty {}
pub trait IsSetSize<'a> {
    fn get(self) -> &'a wgpu_28::BlasTriangleGeometrySizeDescriptor;
}
pub struct SizeValue<'a>(pub &'a wgpu_28::BlasTriangleGeometrySizeDescriptor);
impl<'a> Field for SizeValue<'a> {}
impl<'a> IsSetSize<'a> for SizeValue<'a> {
    fn get(self) -> &'a wgpu_28::BlasTriangleGeometrySizeDescriptor {
        self.0
    }
}
pub struct VertexBufferEmpty;
impl Field for VertexBufferEmpty {}
pub trait VertexBufferIsEmpty {}
impl VertexBufferIsEmpty for VertexBufferEmpty {}
pub trait IsSetVertexBuffer<'a> {
    fn get(self) -> &'a wgpu_28::Buffer;
}
pub struct VertexBufferValue<'a>(pub &'a wgpu_28::Buffer);
impl<'a> Field for VertexBufferValue<'a> {}
impl<'a> IsSetVertexBuffer<'a> for VertexBufferValue<'a> {
    fn get(self) -> &'a wgpu_28::Buffer {
        self.0
    }
}
pub struct FirstVertexEmpty;
impl Field for FirstVertexEmpty {}
pub trait FirstVertexIsEmpty {}
impl FirstVertexIsEmpty for FirstVertexEmpty {}
pub trait IsSetFirstVertex {
    fn get(self) -> u32;
}
pub struct FirstVertexValue(pub u32);
impl Field for FirstVertexValue {}
impl IsSetFirstVertex for FirstVertexValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub struct VertexStrideEmpty;
impl Field for VertexStrideEmpty {}
pub trait VertexStrideIsEmpty {}
impl VertexStrideIsEmpty for VertexStrideEmpty {}
pub trait IsSetVertexStride {
    fn get(self) -> wgpu_28::BufferAddress;
}
pub struct VertexStrideValue(pub wgpu_28::BufferAddress);
impl Field for VertexStrideValue {}
impl IsSetVertexStride for VertexStrideValue {
    fn get(self) -> wgpu_28::BufferAddress {
        self.0
    }
}
pub struct IndexBufferEmpty;
impl Field for IndexBufferEmpty {}
pub trait IndexBufferIsEmpty {}
impl IndexBufferIsEmpty for IndexBufferEmpty {}
pub trait IsSetIndexBuffer<'a> {
    fn get(self) -> Option<&'a wgpu_28::Buffer>;
}
impl<'a> IsSetIndexBuffer<'a> for IndexBufferEmpty {
    fn get(self) -> Option<&'a wgpu_28::Buffer> {
        None
    }
}
pub struct IndexBufferValue<'a>(pub Option<&'a wgpu_28::Buffer>);
impl<'a> Field for IndexBufferValue<'a> {}
impl<'a> IsSetIndexBuffer<'a> for IndexBufferValue<'a> {
    fn get(self) -> Option<&'a wgpu_28::Buffer> {
        self.0
    }
}
pub struct FirstIndexEmpty;
impl Field for FirstIndexEmpty {}
pub trait FirstIndexIsEmpty {}
impl FirstIndexIsEmpty for FirstIndexEmpty {}
pub trait IsSetFirstIndex {
    fn get(self) -> Option<u32>;
}
impl IsSetFirstIndex for FirstIndexEmpty {
    fn get(self) -> Option<u32> {
        None
    }
}
pub struct FirstIndexValue(pub Option<u32>);
impl Field for FirstIndexValue {}
impl IsSetFirstIndex for FirstIndexValue {
    fn get(self) -> Option<u32> {
        self.0
    }
}
pub struct TransformBufferEmpty;
impl Field for TransformBufferEmpty {}
pub trait TransformBufferIsEmpty {}
impl TransformBufferIsEmpty for TransformBufferEmpty {}
pub trait IsSetTransformBuffer<'a> {
    fn get(self) -> Option<&'a wgpu_28::Buffer>;
}
impl<'a> IsSetTransformBuffer<'a> for TransformBufferEmpty {
    fn get(self) -> Option<&'a wgpu_28::Buffer> {
        None
    }
}
pub struct TransformBufferValue<'a>(pub Option<&'a wgpu_28::Buffer>);
impl<'a> Field for TransformBufferValue<'a> {}
impl<'a> IsSetTransformBuffer<'a> for TransformBufferValue<'a> {
    fn get(self) -> Option<&'a wgpu_28::Buffer> {
        self.0
    }
}
pub struct TransformBufferOffsetEmpty;
impl Field for TransformBufferOffsetEmpty {}
pub trait TransformBufferOffsetIsEmpty {}
impl TransformBufferOffsetIsEmpty for TransformBufferOffsetEmpty {}
pub trait IsSetTransformBufferOffset {
    fn get(self) -> Option<wgpu_28::BufferAddress>;
}
impl IsSetTransformBufferOffset for TransformBufferOffsetEmpty {
    fn get(self) -> Option<wgpu_28::BufferAddress> {
        None
    }
}
pub struct TransformBufferOffsetValue(pub Option<wgpu_28::BufferAddress>);
impl Field for TransformBufferOffsetValue {}
impl IsSetTransformBufferOffset for TransformBufferOffsetValue {
    fn get(self) -> Option<wgpu_28::BufferAddress> {
        self.0
    }
}
pub trait State<'a> {
    type Size: Field;
    type VertexBuffer: Field;
    type FirstVertex: Field;
    type VertexStride: Field;
    type IndexBuffer: Field;
    type FirstIndex: Field;
    type TransformBuffer: Field;
    type TransformBufferOffset: Field;
}
pub struct Empty;
impl<'a> State<'a> for Empty {
    type Size = SizeEmpty;
    type VertexBuffer = VertexBufferEmpty;
    type FirstVertex = FirstVertexEmpty;
    type VertexStride = VertexStrideEmpty;
    type IndexBuffer = IndexBufferEmpty;
    type FirstIndex = FirstIndexEmpty;
    type TransformBuffer = TransformBufferEmpty;
    type TransformBufferOffset = TransformBufferOffsetEmpty;
}
pub struct SetSize<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetSize<CS> {
    type Size = SizeValue<'a>;
    type VertexBuffer = CS::VertexBuffer;
    type FirstVertex = CS::FirstVertex;
    type VertexStride = CS::VertexStride;
    type IndexBuffer = CS::IndexBuffer;
    type FirstIndex = CS::FirstIndex;
    type TransformBuffer = CS::TransformBuffer;
    type TransformBufferOffset = CS::TransformBufferOffset;
}
pub struct SetVertexBuffer<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetVertexBuffer<CS> {
    type Size = CS::Size;
    type VertexBuffer = VertexBufferValue<'a>;
    type FirstVertex = CS::FirstVertex;
    type VertexStride = CS::VertexStride;
    type IndexBuffer = CS::IndexBuffer;
    type FirstIndex = CS::FirstIndex;
    type TransformBuffer = CS::TransformBuffer;
    type TransformBufferOffset = CS::TransformBufferOffset;
}
pub struct SetFirstVertex<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetFirstVertex<CS> {
    type Size = CS::Size;
    type VertexBuffer = CS::VertexBuffer;
    type FirstVertex = FirstVertexValue;
    type VertexStride = CS::VertexStride;
    type IndexBuffer = CS::IndexBuffer;
    type FirstIndex = CS::FirstIndex;
    type TransformBuffer = CS::TransformBuffer;
    type TransformBufferOffset = CS::TransformBufferOffset;
}
pub struct SetVertexStride<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetVertexStride<CS> {
    type Size = CS::Size;
    type VertexBuffer = CS::VertexBuffer;
    type FirstVertex = CS::FirstVertex;
    type VertexStride = VertexStrideValue;
    type IndexBuffer = CS::IndexBuffer;
    type FirstIndex = CS::FirstIndex;
    type TransformBuffer = CS::TransformBuffer;
    type TransformBufferOffset = CS::TransformBufferOffset;
}
pub struct SetIndexBuffer<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetIndexBuffer<CS> {
    type Size = CS::Size;
    type VertexBuffer = CS::VertexBuffer;
    type FirstVertex = CS::FirstVertex;
    type VertexStride = CS::VertexStride;
    type IndexBuffer = IndexBufferValue<'a>;
    type FirstIndex = CS::FirstIndex;
    type TransformBuffer = CS::TransformBuffer;
    type TransformBufferOffset = CS::TransformBufferOffset;
}
pub struct SetFirstIndex<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetFirstIndex<CS> {
    type Size = CS::Size;
    type VertexBuffer = CS::VertexBuffer;
    type FirstVertex = CS::FirstVertex;
    type VertexStride = CS::VertexStride;
    type IndexBuffer = CS::IndexBuffer;
    type FirstIndex = FirstIndexValue;
    type TransformBuffer = CS::TransformBuffer;
    type TransformBufferOffset = CS::TransformBufferOffset;
}
pub struct SetTransformBuffer<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetTransformBuffer<CS> {
    type Size = CS::Size;
    type VertexBuffer = CS::VertexBuffer;
    type FirstVertex = CS::FirstVertex;
    type VertexStride = CS::VertexStride;
    type IndexBuffer = CS::IndexBuffer;
    type FirstIndex = CS::FirstIndex;
    type TransformBuffer = TransformBufferValue<'a>;
    type TransformBufferOffset = CS::TransformBufferOffset;
}
pub struct SetTransformBufferOffset<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetTransformBufferOffset<CS> {
    type Size = CS::Size;
    type VertexBuffer = CS::VertexBuffer;
    type FirstVertex = CS::FirstVertex;
    type VertexStride = CS::VertexStride;
    type IndexBuffer = CS::IndexBuffer;
    type FirstIndex = CS::FirstIndex;
    type TransformBuffer = CS::TransformBuffer;
    type TransformBufferOffset = TransformBufferOffsetValue;
}
impl<'a, CS: State<'a>> BlasTriangleGeometryBuilder<'a, CS> {
    #[doc = "Setter for [wgpu_28::BlasTriangleGeometry::size]. Required.\n"]
    pub fn size(
        self,
        size: &'a wgpu_28::BlasTriangleGeometrySizeDescriptor,
    ) -> BlasTriangleGeometryBuilder<'a, SetSize<CS>>
    where
        CS::Size: SizeIsEmpty,
    {
        BlasTriangleGeometryBuilder {
            size: SizeValue(size),
            vertex_buffer: self.vertex_buffer,
            first_vertex: self.first_vertex,
            vertex_stride: self.vertex_stride,
            index_buffer: self.index_buffer,
            first_index: self.first_index,
            transform_buffer: self.transform_buffer,
            transform_buffer_offset: self.transform_buffer_offset,
        }
    }
    #[doc = "Setter for [wgpu_28::BlasTriangleGeometry::vertex_buffer]. Required.\n"]
    pub fn vertex_buffer(
        self,
        vertex_buffer: &'a wgpu_28::Buffer,
    ) -> BlasTriangleGeometryBuilder<'a, SetVertexBuffer<CS>>
    where
        CS::VertexBuffer: VertexBufferIsEmpty,
    {
        BlasTriangleGeometryBuilder {
            size: self.size,
            vertex_buffer: VertexBufferValue(vertex_buffer),
            first_vertex: self.first_vertex,
            vertex_stride: self.vertex_stride,
            index_buffer: self.index_buffer,
            first_index: self.first_index,
            transform_buffer: self.transform_buffer,
            transform_buffer_offset: self.transform_buffer_offset,
        }
    }
    #[doc = "Setter for [wgpu_28::BlasTriangleGeometry::first_vertex]. Required.\n"]
    pub fn first_vertex(
        self,
        first_vertex: u32,
    ) -> BlasTriangleGeometryBuilder<'a, SetFirstVertex<CS>>
    where
        CS::FirstVertex: FirstVertexIsEmpty,
    {
        BlasTriangleGeometryBuilder {
            size: self.size,
            vertex_buffer: self.vertex_buffer,
            first_vertex: FirstVertexValue(first_vertex),
            vertex_stride: self.vertex_stride,
            index_buffer: self.index_buffer,
            first_index: self.first_index,
            transform_buffer: self.transform_buffer,
            transform_buffer_offset: self.transform_buffer_offset,
        }
    }
    #[doc = "Setter for [wgpu_28::BlasTriangleGeometry::vertex_stride]. Required.\n"]
    pub fn vertex_stride(
        self,
        vertex_stride: wgpu_28::BufferAddress,
    ) -> BlasTriangleGeometryBuilder<'a, SetVertexStride<CS>>
    where
        CS::VertexStride: VertexStrideIsEmpty,
    {
        BlasTriangleGeometryBuilder {
            size: self.size,
            vertex_buffer: self.vertex_buffer,
            first_vertex: self.first_vertex,
            vertex_stride: VertexStrideValue(vertex_stride),
            index_buffer: self.index_buffer,
            first_index: self.first_index,
            transform_buffer: self.transform_buffer,
            transform_buffer_offset: self.transform_buffer_offset,
        }
    }
    #[doc = "Setter for [wgpu_28::BlasTriangleGeometry::index_buffer]. Optional, defaults to `None`.\n"]
    pub fn index_buffer(
        self,
        index_buffer: &'a wgpu_28::Buffer,
    ) -> BlasTriangleGeometryBuilder<'a, SetIndexBuffer<CS>>
    where
        CS::IndexBuffer: IndexBufferIsEmpty,
    {
        BlasTriangleGeometryBuilder {
            size: self.size,
            vertex_buffer: self.vertex_buffer,
            first_vertex: self.first_vertex,
            vertex_stride: self.vertex_stride,
            index_buffer: IndexBufferValue(Some(index_buffer)),
            first_index: self.first_index,
            transform_buffer: self.transform_buffer,
            transform_buffer_offset: self.transform_buffer_offset,
        }
    }
    #[doc = "Setter for [wgpu_28::BlasTriangleGeometry::index_buffer]. Optional, defaults to `None`.\n"]
    pub fn maybe_index_buffer(
        self,
        index_buffer: Option<&'a wgpu_28::Buffer>,
    ) -> BlasTriangleGeometryBuilder<'a, SetIndexBuffer<CS>>
    where
        CS::IndexBuffer: IndexBufferIsEmpty,
    {
        BlasTriangleGeometryBuilder {
            size: self.size,
            vertex_buffer: self.vertex_buffer,
            first_vertex: self.first_vertex,
            vertex_stride: self.vertex_stride,
            index_buffer: IndexBufferValue(index_buffer),
            first_index: self.first_index,
            transform_buffer: self.transform_buffer,
            transform_buffer_offset: self.transform_buffer_offset,
        }
    }
    #[doc = "Setter for [wgpu_28::BlasTriangleGeometry::first_index]. Optional, defaults to `None`.\n"]
    pub fn first_index(self, first_index: u32) -> BlasTriangleGeometryBuilder<'a, SetFirstIndex<CS>>
    where
        CS::FirstIndex: FirstIndexIsEmpty,
    {
        BlasTriangleGeometryBuilder {
            size: self.size,
            vertex_buffer: self.vertex_buffer,
            first_vertex: self.first_vertex,
            vertex_stride: self.vertex_stride,
            index_buffer: self.index_buffer,
            first_index: FirstIndexValue(Some(first_index)),
            transform_buffer: self.transform_buffer,
            transform_buffer_offset: self.transform_buffer_offset,
        }
    }
    #[doc = "Setter for [wgpu_28::BlasTriangleGeometry::first_index]. Optional, defaults to `None`.\n"]
    pub fn maybe_first_index(
        self,
        first_index: Option<u32>,
    ) -> BlasTriangleGeometryBuilder<'a, SetFirstIndex<CS>>
    where
        CS::FirstIndex: FirstIndexIsEmpty,
    {
        BlasTriangleGeometryBuilder {
            size: self.size,
            vertex_buffer: self.vertex_buffer,
            first_vertex: self.first_vertex,
            vertex_stride: self.vertex_stride,
            index_buffer: self.index_buffer,
            first_index: FirstIndexValue(first_index),
            transform_buffer: self.transform_buffer,
            transform_buffer_offset: self.transform_buffer_offset,
        }
    }
    #[doc = "Setter for [wgpu_28::BlasTriangleGeometry::transform_buffer]. Optional, defaults to `None`.\n"]
    pub fn transform_buffer(
        self,
        transform_buffer: &'a wgpu_28::Buffer,
    ) -> BlasTriangleGeometryBuilder<'a, SetTransformBuffer<CS>>
    where
        CS::TransformBuffer: TransformBufferIsEmpty,
    {
        BlasTriangleGeometryBuilder {
            size: self.size,
            vertex_buffer: self.vertex_buffer,
            first_vertex: self.first_vertex,
            vertex_stride: self.vertex_stride,
            index_buffer: self.index_buffer,
            first_index: self.first_index,
            transform_buffer: TransformBufferValue(Some(transform_buffer)),
            transform_buffer_offset: self.transform_buffer_offset,
        }
    }
    #[doc = "Setter for [wgpu_28::BlasTriangleGeometry::transform_buffer]. Optional, defaults to `None`.\n"]
    pub fn maybe_transform_buffer(
        self,
        transform_buffer: Option<&'a wgpu_28::Buffer>,
    ) -> BlasTriangleGeometryBuilder<'a, SetTransformBuffer<CS>>
    where
        CS::TransformBuffer: TransformBufferIsEmpty,
    {
        BlasTriangleGeometryBuilder {
            size: self.size,
            vertex_buffer: self.vertex_buffer,
            first_vertex: self.first_vertex,
            vertex_stride: self.vertex_stride,
            index_buffer: self.index_buffer,
            first_index: self.first_index,
            transform_buffer: TransformBufferValue(transform_buffer),
            transform_buffer_offset: self.transform_buffer_offset,
        }
    }
    #[doc = "Setter for [wgpu_28::BlasTriangleGeometry::transform_buffer_offset]. Optional, defaults to `None`.\n"]
    pub fn transform_buffer_offset(
        self,
        transform_buffer_offset: wgpu_28::BufferAddress,
    ) -> BlasTriangleGeometryBuilder<'a, SetTransformBufferOffset<CS>>
    where
        CS::TransformBufferOffset: TransformBufferOffsetIsEmpty,
    {
        BlasTriangleGeometryBuilder {
            size: self.size,
            vertex_buffer: self.vertex_buffer,
            first_vertex: self.first_vertex,
            vertex_stride: self.vertex_stride,
            index_buffer: self.index_buffer,
            first_index: self.first_index,
            transform_buffer: self.transform_buffer,
            transform_buffer_offset: TransformBufferOffsetValue(Some(transform_buffer_offset)),
        }
    }
    #[doc = "Setter for [wgpu_28::BlasTriangleGeometry::transform_buffer_offset]. Optional, defaults to `None`.\n"]
    pub fn maybe_transform_buffer_offset(
        self,
        transform_buffer_offset: Option<wgpu_28::BufferAddress>,
    ) -> BlasTriangleGeometryBuilder<'a, SetTransformBufferOffset<CS>>
    where
        CS::TransformBufferOffset: TransformBufferOffsetIsEmpty,
    {
        BlasTriangleGeometryBuilder {
            size: self.size,
            vertex_buffer: self.vertex_buffer,
            first_vertex: self.first_vertex,
            vertex_stride: self.vertex_stride,
            index_buffer: self.index_buffer,
            first_index: self.first_index,
            transform_buffer: self.transform_buffer,
            transform_buffer_offset: TransformBufferOffsetValue(transform_buffer_offset),
        }
    }
}
pub trait Complete<'a>:
    State<
    'a,
    Size: IsSetSize<'a>,
    VertexBuffer: IsSetVertexBuffer<'a>,
    FirstVertex: IsSetFirstVertex,
    VertexStride: IsSetVertexStride,
    IndexBuffer: IsSetIndexBuffer<'a>,
    FirstIndex: IsSetFirstIndex,
    TransformBuffer: IsSetTransformBuffer<'a>,
    TransformBufferOffset: IsSetTransformBufferOffset,
>
{
}
impl<
        'a,
        CS: State<
            'a,
            Size: IsSetSize<'a>,
            VertexBuffer: IsSetVertexBuffer<'a>,
            FirstVertex: IsSetFirstVertex,
            VertexStride: IsSetVertexStride,
            IndexBuffer: IsSetIndexBuffer<'a>,
            FirstIndex: IsSetFirstIndex,
            TransformBuffer: IsSetTransformBuffer<'a>,
            TransformBufferOffset: IsSetTransformBufferOffset,
        >,
    > Complete<'a> for CS
{
}
impl<'a, CS: Complete<'a>> BlasTriangleGeometryBuilder<'a, CS> {
    pub fn build(self) -> wgpu_28::BlasTriangleGeometry<'a> {
        wgpu_28::BlasTriangleGeometry {
            size: IsSetSize::get(self.size),
            vertex_buffer: IsSetVertexBuffer::get(self.vertex_buffer),
            first_vertex: IsSetFirstVertex::get(self.first_vertex),
            vertex_stride: IsSetVertexStride::get(self.vertex_stride),
            index_buffer: IsSetIndexBuffer::get(self.index_buffer),
            first_index: IsSetFirstIndex::get(self.first_index),
            transform_buffer: IsSetTransformBuffer::get(self.transform_buffer),
            transform_buffer_offset: IsSetTransformBufferOffset::get(self.transform_buffer_offset),
        }
    }
}
impl<'a> Nested<wgpu_28::BlasTriangleGeometry<'a>> for wgpu_28::BlasTriangleGeometry<'a> {
    fn unnest(self) -> wgpu_28::BlasTriangleGeometry<'a> {
        self
    }
}
impl<'a, CS: Complete<'a>> Nested<wgpu_28::BlasTriangleGeometry<'a>>
    for BlasTriangleGeometryBuilder<'a, CS>
{
    fn unnest(self) -> wgpu_28::BlasTriangleGeometry<'a> {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!(
                "{:#?}",
                super::IsSetIndexBuffer::get(super::IndexBufferEmpty)
            ),
            format!("{:#?}", Option::<&wgpu_28::Buffer>::default()),
        );
        assert_eq!(
            format!("{:#?}", super::IsSetFirstIndex::get(super::FirstIndexEmpty)),
            format!("{:#?}", Option::<u32>::default()),
        );
        assert_eq!(
            format!(
                "{:#?}",
                super::IsSetTransformBuffer::get(super::TransformBufferEmpty)
            ),
            format!("{:#?}", Option::<&wgpu_28::Buffer>::default()),
        );
        assert_eq!(
            format!(
                "{:#?}",
                super::IsSetTransformBufferOffset::get(super::TransformBufferOffsetEmpty)
            ),
            format!("{:#?}", Option::<wgpu_28::BufferAddress>::default()),
        );
    }
}
