#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_28::BlendComponent`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [src_factor](BlendComponentBuilder::src_factor) Optional, defaults to [wgpu_28::BlendFactor::One]\n  - [dst_factor](BlendComponentBuilder::dst_factor) Optional, defaults to [wgpu_28::BlendFactor::Zero]\n  - [operation](BlendComponentBuilder::operation) Optional, defaults to [wgpu_28::BlendOperation::Add]\n"]
pub struct BlendComponentBuilder<CS: State> {
    src_factor: CS::SrcFactor,
    dst_factor: CS::DstFactor,
    operation: CS::Operation,
}
impl BlendComponentBuilder<Empty> {
    pub fn new() -> BlendComponentBuilder<Empty> {
        BlendComponentBuilder {
            src_factor: SrcFactorEmpty,
            dst_factor: DstFactorEmpty,
            operation: OperationEmpty,
        }
    }
}
#[doc = "\nReturns [BlendComponentBuilder] for building [`wgpu_28::BlendComponent`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [src_factor](BlendComponentBuilder::src_factor) Optional, defaults to [wgpu_28::BlendFactor::One]\n  - [dst_factor](BlendComponentBuilder::dst_factor) Optional, defaults to [wgpu_28::BlendFactor::Zero]\n  - [operation](BlendComponentBuilder::operation) Optional, defaults to [wgpu_28::BlendOperation::Add]\n"]
pub fn blend_component() -> BlendComponentBuilder<Empty> {
    BlendComponentBuilder::new()
}
pub struct SrcFactorEmpty;
impl Field for SrcFactorEmpty {}
pub trait SrcFactorIsEmpty {}
impl SrcFactorIsEmpty for SrcFactorEmpty {}
pub trait IsSetSrcFactor {
    fn get(self) -> wgpu_28::BlendFactor;
}
impl IsSetSrcFactor for SrcFactorEmpty {
    fn get(self) -> wgpu_28::BlendFactor {
        wgpu_28::BlendFactor::One
    }
}
pub struct SrcFactorValue(pub wgpu_28::BlendFactor);
impl Field for SrcFactorValue {}
impl IsSetSrcFactor for SrcFactorValue {
    fn get(self) -> wgpu_28::BlendFactor {
        self.0
    }
}
pub struct DstFactorEmpty;
impl Field for DstFactorEmpty {}
pub trait DstFactorIsEmpty {}
impl DstFactorIsEmpty for DstFactorEmpty {}
pub trait IsSetDstFactor {
    fn get(self) -> wgpu_28::BlendFactor;
}
impl IsSetDstFactor for DstFactorEmpty {
    fn get(self) -> wgpu_28::BlendFactor {
        wgpu_28::BlendFactor::Zero
    }
}
pub struct DstFactorValue(pub wgpu_28::BlendFactor);
impl Field for DstFactorValue {}
impl IsSetDstFactor for DstFactorValue {
    fn get(self) -> wgpu_28::BlendFactor {
        self.0
    }
}
pub struct OperationEmpty;
impl Field for OperationEmpty {}
pub trait OperationIsEmpty {}
impl OperationIsEmpty for OperationEmpty {}
pub trait IsSetOperation {
    fn get(self) -> wgpu_28::BlendOperation;
}
impl IsSetOperation for OperationEmpty {
    fn get(self) -> wgpu_28::BlendOperation {
        wgpu_28::BlendOperation::Add
    }
}
pub struct OperationValue(pub wgpu_28::BlendOperation);
impl Field for OperationValue {}
impl IsSetOperation for OperationValue {
    fn get(self) -> wgpu_28::BlendOperation {
        self.0
    }
}
pub trait State {
    type SrcFactor: Field;
    type DstFactor: Field;
    type Operation: Field;
}
pub struct Empty;
impl State for Empty {
    type SrcFactor = SrcFactorEmpty;
    type DstFactor = DstFactorEmpty;
    type Operation = OperationEmpty;
}
pub struct SetSrcFactor<CS>(CS);
impl<CS: State> State for SetSrcFactor<CS> {
    type SrcFactor = SrcFactorValue;
    type DstFactor = CS::DstFactor;
    type Operation = CS::Operation;
}
pub struct SetDstFactor<CS>(CS);
impl<CS: State> State for SetDstFactor<CS> {
    type SrcFactor = CS::SrcFactor;
    type DstFactor = DstFactorValue;
    type Operation = CS::Operation;
}
pub struct SetOperation<CS>(CS);
impl<CS: State> State for SetOperation<CS> {
    type SrcFactor = CS::SrcFactor;
    type DstFactor = CS::DstFactor;
    type Operation = OperationValue;
}
impl<CS: State> BlendComponentBuilder<CS> {
    #[doc = "Setter for [wgpu_28::BlendComponent::src_factor]. Optional, defaults to [wgpu_28::BlendFactor::One].\n"]
    pub fn src_factor(
        self,
        src_factor: wgpu_28::BlendFactor,
    ) -> BlendComponentBuilder<SetSrcFactor<CS>>
    where
        CS::SrcFactor: SrcFactorIsEmpty,
    {
        BlendComponentBuilder {
            src_factor: SrcFactorValue(src_factor),
            dst_factor: self.dst_factor,
            operation: self.operation,
        }
    }
    #[doc = "Setter for [wgpu_28::BlendComponent::dst_factor]. Optional, defaults to [wgpu_28::BlendFactor::Zero].\n"]
    pub fn dst_factor(
        self,
        dst_factor: wgpu_28::BlendFactor,
    ) -> BlendComponentBuilder<SetDstFactor<CS>>
    where
        CS::DstFactor: DstFactorIsEmpty,
    {
        BlendComponentBuilder {
            src_factor: self.src_factor,
            dst_factor: DstFactorValue(dst_factor),
            operation: self.operation,
        }
    }
    #[doc = "Setter for [wgpu_28::BlendComponent::operation]. Optional, defaults to [wgpu_28::BlendOperation::Add].\n"]
    pub fn operation(
        self,
        operation: wgpu_28::BlendOperation,
    ) -> BlendComponentBuilder<SetOperation<CS>>
    where
        CS::Operation: OperationIsEmpty,
    {
        BlendComponentBuilder {
            src_factor: self.src_factor,
            dst_factor: self.dst_factor,
            operation: OperationValue(operation),
        }
    }
}
pub trait Complete:
    State<SrcFactor: IsSetSrcFactor, DstFactor: IsSetDstFactor, Operation: IsSetOperation>
{
}
impl<
        CS: State<SrcFactor: IsSetSrcFactor, DstFactor: IsSetDstFactor, Operation: IsSetOperation>,
    > Complete for CS
{
}
impl<CS: Complete> BlendComponentBuilder<CS> {
    pub fn build(self) -> wgpu_28::BlendComponent {
        wgpu_28::BlendComponent {
            src_factor: IsSetSrcFactor::get(self.src_factor),
            dst_factor: IsSetDstFactor::get(self.dst_factor),
            operation: IsSetOperation::get(self.operation),
        }
    }
}
impl Nested<wgpu_28::BlendComponent> for wgpu_28::BlendComponent {
    fn unnest(self) -> wgpu_28::BlendComponent {
        self
    }
}
impl<CS: Complete> Nested<wgpu_28::BlendComponent> for BlendComponentBuilder<CS> {
    fn unnest(self) -> wgpu_28::BlendComponent {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::blend_component().build()),
            format!("{:#?}", wgpu_28::BlendComponent::default()),
        );
    }
}
