#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_28::ShaderRuntimeChecks`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [bounds_checks](ShaderRuntimeChecksBuilder::bounds_checks) Optional, defaults to `true`\n  - [force_loop_bounding](ShaderRuntimeChecksBuilder::force_loop_bounding) Optional, defaults to `true`\n  - [ray_query_initialization_tracking](ShaderRuntimeChecksBuilder::ray_query_initialization_tracking) Optional, defaults to `true`\n"]
pub struct ShaderRuntimeChecksBuilder<CS: State> {
    bounds_checks: CS::BoundsChecks,
    force_loop_bounding: CS::ForceLoopBounding,
    ray_query_initialization_tracking: CS::RayQueryInitializationTracking,
}
impl ShaderRuntimeChecksBuilder<Empty> {
    pub fn new() -> ShaderRuntimeChecksBuilder<Empty> {
        ShaderRuntimeChecksBuilder {
            bounds_checks: BoundsChecksEmpty,
            force_loop_bounding: ForceLoopBoundingEmpty,
            ray_query_initialization_tracking: RayQueryInitializationTrackingEmpty,
        }
    }
}
#[doc = "\nReturns [ShaderRuntimeChecksBuilder] for building [`wgpu_28::ShaderRuntimeChecks`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [bounds_checks](ShaderRuntimeChecksBuilder::bounds_checks) Optional, defaults to `true`\n  - [force_loop_bounding](ShaderRuntimeChecksBuilder::force_loop_bounding) Optional, defaults to `true`\n  - [ray_query_initialization_tracking](ShaderRuntimeChecksBuilder::ray_query_initialization_tracking) Optional, defaults to `true`\n"]
pub fn shader_runtime_checks() -> ShaderRuntimeChecksBuilder<Empty> {
    ShaderRuntimeChecksBuilder::new()
}
pub struct BoundsChecksEmpty;
impl Field for BoundsChecksEmpty {}
pub trait BoundsChecksIsEmpty {}
impl BoundsChecksIsEmpty for BoundsChecksEmpty {}
pub trait IsSetBoundsChecks {
    fn get(self) -> bool;
}
impl IsSetBoundsChecks for BoundsChecksEmpty {
    fn get(self) -> bool {
        true
    }
}
pub struct BoundsChecksValue(pub bool);
impl Field for BoundsChecksValue {}
impl IsSetBoundsChecks for BoundsChecksValue {
    fn get(self) -> bool {
        self.0
    }
}
pub struct ForceLoopBoundingEmpty;
impl Field for ForceLoopBoundingEmpty {}
pub trait ForceLoopBoundingIsEmpty {}
impl ForceLoopBoundingIsEmpty for ForceLoopBoundingEmpty {}
pub trait IsSetForceLoopBounding {
    fn get(self) -> bool;
}
impl IsSetForceLoopBounding for ForceLoopBoundingEmpty {
    fn get(self) -> bool {
        true
    }
}
pub struct ForceLoopBoundingValue(pub bool);
impl Field for ForceLoopBoundingValue {}
impl IsSetForceLoopBounding for ForceLoopBoundingValue {
    fn get(self) -> bool {
        self.0
    }
}
pub struct RayQueryInitializationTrackingEmpty;
impl Field for RayQueryInitializationTrackingEmpty {}
pub trait RayQueryInitializationTrackingIsEmpty {}
impl RayQueryInitializationTrackingIsEmpty for RayQueryInitializationTrackingEmpty {}
pub trait IsSetRayQueryInitializationTracking {
    fn get(self) -> bool;
}
impl IsSetRayQueryInitializationTracking for RayQueryInitializationTrackingEmpty {
    fn get(self) -> bool {
        true
    }
}
pub struct RayQueryInitializationTrackingValue(pub bool);
impl Field for RayQueryInitializationTrackingValue {}
impl IsSetRayQueryInitializationTracking for RayQueryInitializationTrackingValue {
    fn get(self) -> bool {
        self.0
    }
}
pub trait State {
    type BoundsChecks: Field;
    type ForceLoopBounding: Field;
    type RayQueryInitializationTracking: Field;
}
pub struct Empty;
impl State for Empty {
    type BoundsChecks = BoundsChecksEmpty;
    type ForceLoopBounding = ForceLoopBoundingEmpty;
    type RayQueryInitializationTracking = RayQueryInitializationTrackingEmpty;
}
pub struct SetBoundsChecks<CS>(CS);
impl<CS: State> State for SetBoundsChecks<CS> {
    type BoundsChecks = BoundsChecksValue;
    type ForceLoopBounding = CS::ForceLoopBounding;
    type RayQueryInitializationTracking = CS::RayQueryInitializationTracking;
}
pub struct SetForceLoopBounding<CS>(CS);
impl<CS: State> State for SetForceLoopBounding<CS> {
    type BoundsChecks = CS::BoundsChecks;
    type ForceLoopBounding = ForceLoopBoundingValue;
    type RayQueryInitializationTracking = CS::RayQueryInitializationTracking;
}
pub struct SetRayQueryInitializationTracking<CS>(CS);
impl<CS: State> State for SetRayQueryInitializationTracking<CS> {
    type BoundsChecks = CS::BoundsChecks;
    type ForceLoopBounding = CS::ForceLoopBounding;
    type RayQueryInitializationTracking = RayQueryInitializationTrackingValue;
}
impl<CS: State> ShaderRuntimeChecksBuilder<CS> {
    #[doc = "Setter for [wgpu_28::ShaderRuntimeChecks::bounds_checks]. Optional, defaults to `true`.\n"]
    pub fn bounds_checks(
        self,
        bounds_checks: bool,
    ) -> ShaderRuntimeChecksBuilder<SetBoundsChecks<CS>>
    where
        CS::BoundsChecks: BoundsChecksIsEmpty,
    {
        ShaderRuntimeChecksBuilder {
            bounds_checks: BoundsChecksValue(bounds_checks),
            force_loop_bounding: self.force_loop_bounding,
            ray_query_initialization_tracking: self.ray_query_initialization_tracking,
        }
    }
    #[doc = "Setter for [wgpu_28::ShaderRuntimeChecks::force_loop_bounding]. Optional, defaults to `true`.\n"]
    pub fn force_loop_bounding(
        self,
        force_loop_bounding: bool,
    ) -> ShaderRuntimeChecksBuilder<SetForceLoopBounding<CS>>
    where
        CS::ForceLoopBounding: ForceLoopBoundingIsEmpty,
    {
        ShaderRuntimeChecksBuilder {
            bounds_checks: self.bounds_checks,
            force_loop_bounding: ForceLoopBoundingValue(force_loop_bounding),
            ray_query_initialization_tracking: self.ray_query_initialization_tracking,
        }
    }
    #[doc = "Setter for [wgpu_28::ShaderRuntimeChecks::ray_query_initialization_tracking]. Optional, defaults to `true`.\n"]
    pub fn ray_query_initialization_tracking(
        self,
        ray_query_initialization_tracking: bool,
    ) -> ShaderRuntimeChecksBuilder<SetRayQueryInitializationTracking<CS>>
    where
        CS::RayQueryInitializationTracking: RayQueryInitializationTrackingIsEmpty,
    {
        ShaderRuntimeChecksBuilder {
            bounds_checks: self.bounds_checks,
            force_loop_bounding: self.force_loop_bounding,
            ray_query_initialization_tracking: RayQueryInitializationTrackingValue(
                ray_query_initialization_tracking,
            ),
        }
    }
}
pub trait Complete:
    State<
    BoundsChecks: IsSetBoundsChecks,
    ForceLoopBounding: IsSetForceLoopBounding,
    RayQueryInitializationTracking: IsSetRayQueryInitializationTracking,
>
{
}
impl<
        CS: State<
            BoundsChecks: IsSetBoundsChecks,
            ForceLoopBounding: IsSetForceLoopBounding,
            RayQueryInitializationTracking: IsSetRayQueryInitializationTracking,
        >,
    > Complete for CS
{
}
impl<CS: Complete> ShaderRuntimeChecksBuilder<CS> {
    pub fn build(self) -> wgpu_28::ShaderRuntimeChecks {
        wgpu_28::ShaderRuntimeChecks {
            bounds_checks: IsSetBoundsChecks::get(self.bounds_checks),
            force_loop_bounding: IsSetForceLoopBounding::get(self.force_loop_bounding),
            ray_query_initialization_tracking: IsSetRayQueryInitializationTracking::get(
                self.ray_query_initialization_tracking,
            ),
        }
    }
}
impl Nested<wgpu_28::ShaderRuntimeChecks> for wgpu_28::ShaderRuntimeChecks {
    fn unnest(self) -> wgpu_28::ShaderRuntimeChecks {
        self
    }
}
impl<CS: Complete> Nested<wgpu_28::ShaderRuntimeChecks> for ShaderRuntimeChecksBuilder<CS> {
    fn unnest(self) -> wgpu_28::ShaderRuntimeChecks {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::shader_runtime_checks().build()),
            format!("{:#?}", wgpu_28::ShaderRuntimeChecks::default()),
        );
    }
}
