#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [BackendOptionsBuilder] for building [`wgpu_28::BackendOptions`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [gl](BackendOptionsBuilder::gl) Optional, defaults to [wgpu_28::GlBackendOptions::default()]\n  - [dx12](BackendOptionsBuilder::dx12) Optional, defaults to [wgpu_28::Dx12BackendOptions::default()]\n  - [noop](BackendOptionsBuilder::noop) Optional, defaults to [wgpu_28::NoopBackendOptions::default()]\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_28::BackendOptions`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [gl](BackendOptionsBuilder::gl) Optional, defaults to [wgpu_28::GlBackendOptions::default()]\n  - [dx12](BackendOptionsBuilder::dx12) Optional, defaults to [wgpu_28::Dx12BackendOptions::default()]\n  - [noop](BackendOptionsBuilder::noop) Optional, defaults to [wgpu_28::NoopBackendOptions::default()]\n"]
pub fn backend_options(
    # [builder (with = | b : impl super :: gl_backend_options_builder :: NestedGlBackendOptions | b . unnest () , default = wgpu_28 :: GlBackendOptions :: default () ,)]
    gl: wgpu_28::GlBackendOptions,
    # [builder (with = | b : impl super :: dx12_backend_options_builder :: NestedDx12BackendOptions | b . unnest () , default = wgpu_28 :: Dx12BackendOptions :: default () ,)]
    dx12: wgpu_28::Dx12BackendOptions,
    # [builder (with = | b : impl super :: noop_backend_options_builder :: NestedNoopBackendOptions | b . unnest () , default = wgpu_28 :: NoopBackendOptions :: default () ,)]
    noop: wgpu_28::NoopBackendOptions,
) -> wgpu_28::BackendOptions {
    wgpu_28::BackendOptions { gl, dx12, noop }
}
pub trait NestedBackendOptions {
    fn unnest(self) -> wgpu_28::BackendOptions;
}
impl NestedBackendOptions for wgpu_28::BackendOptions {
    fn unnest(self) -> wgpu_28::BackendOptions {
        self
    }
}
impl<S: state::IsComplete> NestedBackendOptions for BackendOptionsBuilder<S> {
    fn unnest(self) -> wgpu_28::BackendOptions {
        self.build()
    }
}
