#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [BindGroupEntryBuilder] for building [`wgpu_28::BindGroupEntry`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [binding](BindGroupEntryBuilder::binding) Required\n  - [resource](BindGroupEntryBuilder::resource) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_28::BindGroupEntry`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [binding](BindGroupEntryBuilder::binding) Required\n  - [resource](BindGroupEntryBuilder::resource) Required\n"]
pub fn bind_group_entry<'a>(
    binding: u32,
    resource: wgpu_28::BindingResource<'a>,
) -> wgpu_28::BindGroupEntry<'a> {
    wgpu_28::BindGroupEntry { binding, resource }
}
pub trait NestedBindGroupEntry<'a> {
    fn unnest(self) -> wgpu_28::BindGroupEntry<'a>;
}
impl<'a> NestedBindGroupEntry<'a> for wgpu_28::BindGroupEntry<'a> {
    fn unnest(self) -> wgpu_28::BindGroupEntry<'a> {
        self
    }
}
impl<'a, S: state::IsComplete> NestedBindGroupEntry<'a> for BindGroupEntryBuilder<'a, S> {
    fn unnest(self) -> wgpu_28::BindGroupEntry<'a> {
        self.build()
    }
}
