#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [ComputePassTimestampWritesBuilder] for building [`wgpu_28::ComputePassTimestampWrites`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [query_set](ComputePassTimestampWritesBuilder::query_set) Required\n  - [beginning_of_pass_write_index](ComputePassTimestampWritesBuilder::beginning_of_pass_write_index) Required\n  - [end_of_pass_write_index](ComputePassTimestampWritesBuilder::end_of_pass_write_index) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_28::ComputePassTimestampWrites`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [query_set](ComputePassTimestampWritesBuilder::query_set) Required\n  - [beginning_of_pass_write_index](ComputePassTimestampWritesBuilder::beginning_of_pass_write_index) Required\n  - [end_of_pass_write_index](ComputePassTimestampWritesBuilder::end_of_pass_write_index) Required\n"]
pub fn compute_pass_timestamp_writes<'a>(
    query_set: &'a wgpu_28::QuerySet,
    beginning_of_pass_write_index: Option<u32>,
    end_of_pass_write_index: Option<u32>,
) -> wgpu_28::ComputePassTimestampWrites<'a> {
    wgpu_28::ComputePassTimestampWrites {
        query_set,
        beginning_of_pass_write_index,
        end_of_pass_write_index,
    }
}
pub trait NestedComputePassTimestampWrites<'a> {
    fn unnest(self) -> wgpu_28::ComputePassTimestampWrites<'a>;
}
impl<'a> NestedComputePassTimestampWrites<'a> for wgpu_28::ComputePassTimestampWrites<'a> {
    fn unnest(self) -> wgpu_28::ComputePassTimestampWrites<'a> {
        self
    }
}
impl<'a, S: state::IsComplete> NestedComputePassTimestampWrites<'a>
    for ComputePassTimestampWritesBuilder<'a, S>
{
    fn unnest(self) -> wgpu_28::ComputePassTimestampWrites<'a> {
        self.build()
    }
}
