#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_28::DownlevelLimits`]\n        "]
pub struct DownlevelLimitsBuilder {}
impl DownlevelLimitsBuilder {
    pub fn new() -> DownlevelLimitsBuilder {
        DownlevelLimitsBuilder {}
    }
}
#[doc = "\nReturns [DownlevelLimitsBuilder] for building [`wgpu_28::DownlevelLimits`]\n        "]
pub fn downlevel_limits() -> DownlevelLimitsBuilder {
    DownlevelLimitsBuilder::new()
}
pub trait State {}
pub struct Empty;
impl State for Empty {}
impl DownlevelLimitsBuilder {}
pub trait Complete: State {}
impl<CS: State> Complete for CS {}
impl DownlevelLimitsBuilder {
    pub fn build(self) -> wgpu_28::DownlevelLimits {
        wgpu_28::DownlevelLimits {}
    }
}
impl Nested<wgpu_28::DownlevelLimits> for wgpu_28::DownlevelLimits {
    fn unnest(self) -> wgpu_28::DownlevelLimits {
        self
    }
}
impl Nested<wgpu_28::DownlevelLimits> for DownlevelLimitsBuilder {
    fn unnest(self) -> wgpu_28::DownlevelLimits {
        self.build()
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::downlevel_limits().build()),
            format!("{:#?}", wgpu_28::DownlevelLimits::default()),
        );
    }
}
