#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [FragmentStateBuilder] for building [`wgpu_28::FragmentState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [module](FragmentStateBuilder::module) Required\n  - [entry_point](FragmentStateBuilder::entry_point) Required\n  - [compilation_options](FragmentStateBuilder::compilation_options) Optional, defaults to [wgpu_28::PipelineCompilationOptions::default()]\n  - [targets](FragmentStateBuilder::targets) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_28::FragmentState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [module](FragmentStateBuilder::module) Required\n  - [entry_point](FragmentStateBuilder::entry_point) Required\n  - [compilation_options](FragmentStateBuilder::compilation_options) Optional, defaults to [wgpu_28::PipelineCompilationOptions::default()]\n  - [targets](FragmentStateBuilder::targets) Required\n"]
pub fn fragment_state<'a>(
    module: &'a wgpu_28::ShaderModule,
    entry_point: Option<&'a str>,
    # [builder (with = | b : impl super :: pipeline_compilation_options_builder :: NestedPipelineCompilationOptions < 'a > | b . unnest () , default = wgpu_28 :: PipelineCompilationOptions :: default () ,)]
    compilation_options: wgpu_28::PipelineCompilationOptions<'a>,
    targets: &'a [Option<wgpu_28::ColorTargetState>],
) -> wgpu_28::FragmentState<'a> {
    wgpu_28::FragmentState {
        module,
        entry_point,
        compilation_options,
        targets,
    }
}
pub trait NestedFragmentState<'a> {
    fn unnest(self) -> wgpu_28::FragmentState<'a>;
}
impl<'a> NestedFragmentState<'a> for wgpu_28::FragmentState<'a> {
    fn unnest(self) -> wgpu_28::FragmentState<'a> {
        self
    }
}
impl<'a, S: state::IsComplete> NestedFragmentState<'a> for FragmentStateBuilder<'a, S> {
    fn unnest(self) -> wgpu_28::FragmentState<'a> {
        self.build()
    }
}
