#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [NoopBackendOptionsBuilder] for building [`wgpu_28::NoopBackendOptions`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [enable](NoopBackendOptionsBuilder::enable) Optional, defaults to `false`\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_28::NoopBackendOptions`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [enable](NoopBackendOptionsBuilder::enable) Optional, defaults to `false`\n"]
pub fn noop_backend_options(
    #[builder(default = false)] enable: bool,
) -> wgpu_28::NoopBackendOptions {
    wgpu_28::NoopBackendOptions { enable }
}
pub trait NestedNoopBackendOptions {
    fn unnest(self) -> wgpu_28::NoopBackendOptions;
}
impl NestedNoopBackendOptions for wgpu_28::NoopBackendOptions {
    fn unnest(self) -> wgpu_28::NoopBackendOptions {
        self
    }
}
impl<S: state::IsComplete> NestedNoopBackendOptions for NoopBackendOptionsBuilder<S> {
    fn unnest(self) -> wgpu_28::NoopBackendOptions {
        self.build()
    }
}
