#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [QuerySetDescriptorBuilder] for building [`wgpu_28::QuerySetDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [ty](QuerySetDescriptorBuilder::ty) Required\n  - [count](QuerySetDescriptorBuilder::count) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_28::QuerySetDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [ty](QuerySetDescriptorBuilder::ty) Required\n  - [count](QuerySetDescriptorBuilder::count) Required\n"]
pub fn query_set_descriptor<'a>(
    #[builder(start_fn)] label: wgpu_28::Label<'a>,
    ty: wgpu_28::QueryType,
    count: u32,
) -> wgpu_28::QuerySetDescriptor<'a> {
    wgpu_28::QuerySetDescriptor { label, ty, count }
}
impl<'a, S: state::IsComplete> QuerySetDescriptorBuilder<'a, S> {
    pub fn create_with(self, device: &wgpu_28::Device) -> wgpu_28::QuerySet {
        device.create_query_set(&self.build())
    }
}
