#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [RenderPassDepthStencilAttachmentBuilder] for building [`wgpu_28::RenderPassDepthStencilAttachment`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [view](RenderPassDepthStencilAttachmentBuilder::view) Required\n  - [depth_ops](RenderPassDepthStencilAttachmentBuilder::depth_ops) Required\n  - [stencil_ops](RenderPassDepthStencilAttachmentBuilder::stencil_ops) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_28::RenderPassDepthStencilAttachment`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [view](RenderPassDepthStencilAttachmentBuilder::view) Required\n  - [depth_ops](RenderPassDepthStencilAttachmentBuilder::depth_ops) Required\n  - [stencil_ops](RenderPassDepthStencilAttachmentBuilder::stencil_ops) Required\n"]
pub fn render_pass_depth_stencil_attachment<'tex>(
    view: &'tex wgpu_28::TextureView,
    # [builder (with = | b : impl super :: operations_builder :: NestedOperations < f32 > | b . unnest () ,)]
    depth_ops: Option<wgpu_28::Operations<f32>>,
    # [builder (with = | b : impl super :: operations_builder :: NestedOperations < u32 > | b . unnest () ,)]
    stencil_ops: Option<wgpu_28::Operations<u32>>,
) -> wgpu_28::RenderPassDepthStencilAttachment<'tex> {
    wgpu_28::RenderPassDepthStencilAttachment {
        view,
        depth_ops,
        stencil_ops,
    }
}
pub trait NestedRenderPassDepthStencilAttachment<'tex> {
    fn unnest(self) -> wgpu_28::RenderPassDepthStencilAttachment<'tex>;
}
impl<'tex> NestedRenderPassDepthStencilAttachment<'tex>
    for wgpu_28::RenderPassDepthStencilAttachment<'tex>
{
    fn unnest(self) -> wgpu_28::RenderPassDepthStencilAttachment<'tex> {
        self
    }
}
impl<'tex, S: state::IsComplete> NestedRenderPassDepthStencilAttachment<'tex>
    for RenderPassDepthStencilAttachmentBuilder<'tex, S>
{
    fn unnest(self) -> wgpu_28::RenderPassDepthStencilAttachment<'tex> {
        self.build()
    }
}
