#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [RenderBundleEncoderDescriptorBuilder] for building [`wgpu_28::RenderBundleEncoderDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [color_formats](RenderBundleEncoderDescriptorBuilder::color_formats) Optional, defaults to [::core::default::Default::default()]\n  - [depth_stencil](RenderBundleEncoderDescriptorBuilder::depth_stencil) Required\n  - [sample_count](RenderBundleEncoderDescriptorBuilder::sample_count) Optional, defaults to `0u32`\n  - [multiview](RenderBundleEncoderDescriptorBuilder::multiview) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_28::RenderBundleEncoderDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [color_formats](RenderBundleEncoderDescriptorBuilder::color_formats) Optional, defaults to [::core::default::Default::default()]\n  - [depth_stencil](RenderBundleEncoderDescriptorBuilder::depth_stencil) Required\n  - [sample_count](RenderBundleEncoderDescriptorBuilder::sample_count) Optional, defaults to `0u32`\n  - [multiview](RenderBundleEncoderDescriptorBuilder::multiview) Required\n"]
pub fn render_bundle_encoder_descriptor<'a>(
    #[builder(start_fn)] label: wgpu_28::Label<'a>,
    # [builder (default = :: core :: default :: Default :: default () ,)]
    color_formats: &'a [Option<wgpu_28::TextureFormat>],
    # [builder (with = | b : impl super :: render_bundle_depth_stencil_builder :: NestedRenderBundleDepthStencil | b . unnest () ,)]
    depth_stencil: Option<wgpu_28::RenderBundleDepthStencil>,
    #[builder(default = 0u32)] sample_count: u32,
    multiview: Option<NonZeroU32>,
) -> wgpu_28::RenderBundleEncoderDescriptor<'a> {
    wgpu_28::RenderBundleEncoderDescriptor {
        label,
        color_formats,
        depth_stencil,
        sample_count,
        multiview,
    }
}
impl<'a, S: state::IsComplete> RenderBundleEncoderDescriptorBuilder<'a, S> {
    pub fn create_with(self, device: &wgpu_28::Device) -> wgpu_28::RenderBundleEncoder<'a> {
        device.create_render_bundle_encoder(&self.build())
    }
}
pub trait NestedRenderBundleEncoderDescriptor<'a> {
    fn unnest(self) -> wgpu_28::RenderBundleEncoderDescriptor<'a>;
}
impl<'a> NestedRenderBundleEncoderDescriptor<'a> for wgpu_28::RenderBundleEncoderDescriptor<'a> {
    fn unnest(self) -> wgpu_28::RenderBundleEncoderDescriptor<'a> {
        self
    }
}
impl<'a, S: state::IsComplete> NestedRenderBundleEncoderDescriptor<'a>
    for RenderBundleEncoderDescriptorBuilder<'a, S>
{
    fn unnest(self) -> wgpu_28::RenderBundleEncoderDescriptor<'a> {
        self.build()
    }
}
