#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [TexelCopyTextureInfoBaseBuilder] for building [`wgpu_28::TexelCopyTextureInfoBase`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [texture](TexelCopyTextureInfoBaseBuilder::texture) Required\n  - [mip_level](TexelCopyTextureInfoBaseBuilder::mip_level) Required\n  - [origin](TexelCopyTextureInfoBaseBuilder::origin) Optional, defaults to [wgpu_28::Origin3d::ZERO]\n  - [aspect](TexelCopyTextureInfoBaseBuilder::aspect) Optional, defaults to [wgpu_28::TextureAspect::All]\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_28::TexelCopyTextureInfoBase`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [texture](TexelCopyTextureInfoBaseBuilder::texture) Required\n  - [mip_level](TexelCopyTextureInfoBaseBuilder::mip_level) Required\n  - [origin](TexelCopyTextureInfoBaseBuilder::origin) Optional, defaults to [wgpu_28::Origin3d::ZERO]\n  - [aspect](TexelCopyTextureInfoBaseBuilder::aspect) Optional, defaults to [wgpu_28::TextureAspect::All]\n"]
pub fn texel_copy_texture_info_base<T>(
    texture: T,
    mip_level: u32,
    # [builder (with = | b : impl super :: origin3d_builder :: NestedOrigin3d | b . unnest () , default = wgpu_28 :: Origin3d :: ZERO ,)]
    origin: wgpu_28::Origin3d,
    # [builder (default = wgpu_28 :: TextureAspect :: All ,)] aspect: wgpu_28::TextureAspect,
) -> wgpu_28::TexelCopyTextureInfoBase<T> {
    wgpu_28::TexelCopyTextureInfoBase {
        texture,
        mip_level,
        origin,
        aspect,
    }
}
pub trait NestedTexelCopyTextureInfoBase<T> {
    fn unnest(self) -> wgpu_28::TexelCopyTextureInfoBase<T>;
}
impl<T> NestedTexelCopyTextureInfoBase<T> for wgpu_28::TexelCopyTextureInfoBase<T> {
    fn unnest(self) -> wgpu_28::TexelCopyTextureInfoBase<T> {
        self
    }
}
impl<T, S: state::IsComplete> NestedTexelCopyTextureInfoBase<T>
    for TexelCopyTextureInfoBaseBuilder<T, S>
{
    fn unnest(self) -> wgpu_28::TexelCopyTextureInfoBase<T> {
        self.build()
    }
}
