#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [TexelCopyBufferLayoutBuilder] for building [`wgpu_28::TexelCopyBufferLayout`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [offset](TexelCopyBufferLayoutBuilder::offset) Optional, defaults to [wgpu_28::BufferAddress::default()]\n  - [bytes_per_row](TexelCopyBufferLayoutBuilder::bytes_per_row) Required\n  - [rows_per_image](TexelCopyBufferLayoutBuilder::rows_per_image) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_28::TexelCopyBufferLayout`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [offset](TexelCopyBufferLayoutBuilder::offset) Optional, defaults to [wgpu_28::BufferAddress::default()]\n  - [bytes_per_row](TexelCopyBufferLayoutBuilder::bytes_per_row) Required\n  - [rows_per_image](TexelCopyBufferLayoutBuilder::rows_per_image) Required\n"]
pub fn texel_copy_buffer_layout(
    # [builder (default = wgpu_28 :: BufferAddress :: default () ,)] offset: wgpu_28::BufferAddress,
    bytes_per_row: Option<u32>,
    rows_per_image: Option<u32>,
) -> wgpu_28::TexelCopyBufferLayout {
    wgpu_28::TexelCopyBufferLayout {
        offset,
        bytes_per_row,
        rows_per_image,
    }
}
pub trait NestedTexelCopyBufferLayout {
    fn unnest(self) -> wgpu_28::TexelCopyBufferLayout;
}
impl NestedTexelCopyBufferLayout for wgpu_28::TexelCopyBufferLayout {
    fn unnest(self) -> wgpu_28::TexelCopyBufferLayout {
        self
    }
}
impl<S: state::IsComplete> NestedTexelCopyBufferLayout for TexelCopyBufferLayoutBuilder<S> {
    fn unnest(self) -> wgpu_28::TexelCopyBufferLayout {
        self.build()
    }
}
