#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [TextureDescriptorBuilder] for building [`wgpu_28::TextureDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [size](TextureDescriptorBuilder::size) Optional, defaults to [wgpu_28::Extent3d::default()]\n  - [mip_level_count](TextureDescriptorBuilder::mip_level_count) Required\n  - [sample_count](TextureDescriptorBuilder::sample_count) Required\n  - [dimension](TextureDescriptorBuilder::dimension) Required\n  - [format](TextureDescriptorBuilder::format) Required\n  - [usage](TextureDescriptorBuilder::usage) Required\n  - [view_formats](TextureDescriptorBuilder::view_formats) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_28::TextureDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [size](TextureDescriptorBuilder::size) Optional, defaults to [wgpu_28::Extent3d::default()]\n  - [mip_level_count](TextureDescriptorBuilder::mip_level_count) Required\n  - [sample_count](TextureDescriptorBuilder::sample_count) Required\n  - [dimension](TextureDescriptorBuilder::dimension) Required\n  - [format](TextureDescriptorBuilder::format) Required\n  - [usage](TextureDescriptorBuilder::usage) Required\n  - [view_formats](TextureDescriptorBuilder::view_formats) Required\n"]
pub fn texture_descriptor<'a>(
    #[builder(start_fn)] label: wgpu_28::Label<'a>,
    # [builder (with = | b : impl super :: extent3d_builder :: NestedExtent3d | b . unnest () , default = wgpu_28 :: Extent3d :: default () ,)]
    size: wgpu_28::Extent3d,
    mip_level_count: u32,
    sample_count: u32,
    dimension: wgpu_28::TextureDimension,
    format: wgpu_28::TextureFormat,
    usage: wgpu_28::TextureUsages,
    view_formats: &'a [wgpu_28::TextureFormat],
) -> wgpu_28::TextureDescriptor<'a> {
    wgpu_28::TextureDescriptor {
        label,
        size,
        mip_level_count,
        sample_count,
        dimension,
        format,
        usage,
        view_formats,
    }
}
impl<'a, S: state::IsComplete> TextureDescriptorBuilder<'a, S> {
    pub fn create_with(self, device: &wgpu_28::Device) -> wgpu_28::Texture {
        device.create_texture(&self.build())
    }
}
