#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

pub use super::super::Nested;
pub use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
pub trait Field {}
pub trait IsOptional {}
#[doc = "\nBuilder for [`wgpu_28::TextureDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [size](TextureDescriptorBuilder::size) Optional, defaults to [wgpu_28::Extent3d::default()]\n  - [mip_level_count](TextureDescriptorBuilder::mip_level_count) Required\n  - [sample_count](TextureDescriptorBuilder::sample_count) Required\n  - [dimension](TextureDescriptorBuilder::dimension) Required\n  - [format](TextureDescriptorBuilder::format) Required\n  - [usage](TextureDescriptorBuilder::usage) Required\n  - [view_formats](TextureDescriptorBuilder::view_formats) Required\n"]
pub struct TextureDescriptorBuilder<'a, CS: State<'a>> {
    label: CS::Label,
    size: CS::Size,
    mip_level_count: CS::MipLevelCount,
    sample_count: CS::SampleCount,
    dimension: CS::Dimension,
    format: CS::Format,
    usage: CS::Usage,
    view_formats: CS::ViewFormats,
}
impl<'a> TextureDescriptorBuilder<'a, Empty> {
    pub fn new() -> TextureDescriptorBuilder<'a, Empty> {
        TextureDescriptorBuilder {
            label: LabelEmpty,
            size: SizeEmpty,
            mip_level_count: MipLevelCountEmpty,
            sample_count: SampleCountEmpty,
            dimension: DimensionEmpty,
            format: FormatEmpty,
            usage: UsageEmpty,
            view_formats: ViewFormatsEmpty,
        }
    }
}
#[doc = "\nReturns [TextureDescriptorBuilder] for building [`wgpu_28::TextureDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [size](TextureDescriptorBuilder::size) Optional, defaults to [wgpu_28::Extent3d::default()]\n  - [mip_level_count](TextureDescriptorBuilder::mip_level_count) Required\n  - [sample_count](TextureDescriptorBuilder::sample_count) Required\n  - [dimension](TextureDescriptorBuilder::dimension) Required\n  - [format](TextureDescriptorBuilder::format) Required\n  - [usage](TextureDescriptorBuilder::usage) Required\n  - [view_formats](TextureDescriptorBuilder::view_formats) Required\n"]
pub fn texture_descriptor<'a>(
    label: wgpu_28::Label<'a>,
) -> TextureDescriptorBuilder<'a, SetLabel<Empty>> {
    TextureDescriptorBuilder::new().label(label)
}
pub struct LabelEmpty;
impl Field for LabelEmpty {}
pub trait LabelIsEmpty {}
impl LabelIsEmpty for LabelEmpty {}
pub trait IsSetLabel<'a> {
    fn get(self) -> wgpu_28::Label<'a>;
}
impl<'a> IsSetLabel<'a> for LabelEmpty {
    fn get(self) -> wgpu_28::Label<'a> {
        None
    }
}
pub struct LabelValue<'a>(pub wgpu_28::Label<'a>);
impl<'a> Field for LabelValue<'a> {}
impl<'a> IsSetLabel<'a> for LabelValue<'a> {
    fn get(self) -> wgpu_28::Label<'a> {
        self.0
    }
}
pub struct SizeEmpty;
impl Field for SizeEmpty {}
pub trait SizeIsEmpty {}
impl SizeIsEmpty for SizeEmpty {}
pub trait IsSetSize {
    fn get(self) -> wgpu_28::Extent3d;
}
impl IsSetSize for SizeEmpty {
    fn get(self) -> wgpu_28::Extent3d {
        wgpu_28::Extent3d::default()
    }
}
pub struct SizeValue(pub wgpu_28::Extent3d);
impl Field for SizeValue {}
impl IsSetSize for SizeValue {
    fn get(self) -> wgpu_28::Extent3d {
        self.0
    }
}
pub struct MipLevelCountEmpty;
impl Field for MipLevelCountEmpty {}
pub trait MipLevelCountIsEmpty {}
impl MipLevelCountIsEmpty for MipLevelCountEmpty {}
pub trait IsSetMipLevelCount {
    fn get(self) -> u32;
}
pub struct MipLevelCountValue(pub u32);
impl Field for MipLevelCountValue {}
impl IsSetMipLevelCount for MipLevelCountValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub struct SampleCountEmpty;
impl Field for SampleCountEmpty {}
pub trait SampleCountIsEmpty {}
impl SampleCountIsEmpty for SampleCountEmpty {}
pub trait IsSetSampleCount {
    fn get(self) -> u32;
}
pub struct SampleCountValue(pub u32);
impl Field for SampleCountValue {}
impl IsSetSampleCount for SampleCountValue {
    fn get(self) -> u32 {
        self.0
    }
}
pub struct DimensionEmpty;
impl Field for DimensionEmpty {}
pub trait DimensionIsEmpty {}
impl DimensionIsEmpty for DimensionEmpty {}
pub trait IsSetDimension {
    fn get(self) -> wgpu_28::TextureDimension;
}
pub struct DimensionValue(pub wgpu_28::TextureDimension);
impl Field for DimensionValue {}
impl IsSetDimension for DimensionValue {
    fn get(self) -> wgpu_28::TextureDimension {
        self.0
    }
}
pub struct FormatEmpty;
impl Field for FormatEmpty {}
pub trait FormatIsEmpty {}
impl FormatIsEmpty for FormatEmpty {}
pub trait IsSetFormat {
    fn get(self) -> wgpu_28::TextureFormat;
}
pub struct FormatValue(pub wgpu_28::TextureFormat);
impl Field for FormatValue {}
impl IsSetFormat for FormatValue {
    fn get(self) -> wgpu_28::TextureFormat {
        self.0
    }
}
pub struct UsageEmpty;
impl Field for UsageEmpty {}
pub trait UsageIsEmpty {}
impl UsageIsEmpty for UsageEmpty {}
pub trait IsSetUsage {
    fn get(self) -> wgpu_28::TextureUsages;
}
pub struct UsageValue(pub wgpu_28::TextureUsages);
impl Field for UsageValue {}
impl IsSetUsage for UsageValue {
    fn get(self) -> wgpu_28::TextureUsages {
        self.0
    }
}
pub struct ViewFormatsEmpty;
impl Field for ViewFormatsEmpty {}
pub trait ViewFormatsIsEmpty {}
impl ViewFormatsIsEmpty for ViewFormatsEmpty {}
pub trait IsSetViewFormats<'a> {
    fn get(self) -> &'a [wgpu_28::TextureFormat];
}
pub struct ViewFormatsValue<'a>(pub &'a [wgpu_28::TextureFormat]);
impl<'a> Field for ViewFormatsValue<'a> {}
impl<'a> IsSetViewFormats<'a> for ViewFormatsValue<'a> {
    fn get(self) -> &'a [wgpu_28::TextureFormat] {
        self.0
    }
}
pub trait State<'a> {
    type Label: Field;
    type Size: Field;
    type MipLevelCount: Field;
    type SampleCount: Field;
    type Dimension: Field;
    type Format: Field;
    type Usage: Field;
    type ViewFormats: Field;
}
pub struct Empty;
impl<'a> State<'a> for Empty {
    type Label = LabelEmpty;
    type Size = SizeEmpty;
    type MipLevelCount = MipLevelCountEmpty;
    type SampleCount = SampleCountEmpty;
    type Dimension = DimensionEmpty;
    type Format = FormatEmpty;
    type Usage = UsageEmpty;
    type ViewFormats = ViewFormatsEmpty;
}
pub struct SetLabel<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetLabel<CS> {
    type Label = LabelValue<'a>;
    type Size = CS::Size;
    type MipLevelCount = CS::MipLevelCount;
    type SampleCount = CS::SampleCount;
    type Dimension = CS::Dimension;
    type Format = CS::Format;
    type Usage = CS::Usage;
    type ViewFormats = CS::ViewFormats;
}
pub struct SetSize<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetSize<CS> {
    type Label = CS::Label;
    type Size = SizeValue;
    type MipLevelCount = CS::MipLevelCount;
    type SampleCount = CS::SampleCount;
    type Dimension = CS::Dimension;
    type Format = CS::Format;
    type Usage = CS::Usage;
    type ViewFormats = CS::ViewFormats;
}
pub struct SetMipLevelCount<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetMipLevelCount<CS> {
    type Label = CS::Label;
    type Size = CS::Size;
    type MipLevelCount = MipLevelCountValue;
    type SampleCount = CS::SampleCount;
    type Dimension = CS::Dimension;
    type Format = CS::Format;
    type Usage = CS::Usage;
    type ViewFormats = CS::ViewFormats;
}
pub struct SetSampleCount<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetSampleCount<CS> {
    type Label = CS::Label;
    type Size = CS::Size;
    type MipLevelCount = CS::MipLevelCount;
    type SampleCount = SampleCountValue;
    type Dimension = CS::Dimension;
    type Format = CS::Format;
    type Usage = CS::Usage;
    type ViewFormats = CS::ViewFormats;
}
pub struct SetDimension<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetDimension<CS> {
    type Label = CS::Label;
    type Size = CS::Size;
    type MipLevelCount = CS::MipLevelCount;
    type SampleCount = CS::SampleCount;
    type Dimension = DimensionValue;
    type Format = CS::Format;
    type Usage = CS::Usage;
    type ViewFormats = CS::ViewFormats;
}
pub struct SetFormat<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetFormat<CS> {
    type Label = CS::Label;
    type Size = CS::Size;
    type MipLevelCount = CS::MipLevelCount;
    type SampleCount = CS::SampleCount;
    type Dimension = CS::Dimension;
    type Format = FormatValue;
    type Usage = CS::Usage;
    type ViewFormats = CS::ViewFormats;
}
pub struct SetUsage<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetUsage<CS> {
    type Label = CS::Label;
    type Size = CS::Size;
    type MipLevelCount = CS::MipLevelCount;
    type SampleCount = CS::SampleCount;
    type Dimension = CS::Dimension;
    type Format = CS::Format;
    type Usage = UsageValue;
    type ViewFormats = CS::ViewFormats;
}
pub struct SetViewFormats<CS>(CS);
impl<'a, CS: State<'a>> State<'a> for SetViewFormats<CS> {
    type Label = CS::Label;
    type Size = CS::Size;
    type MipLevelCount = CS::MipLevelCount;
    type SampleCount = CS::SampleCount;
    type Dimension = CS::Dimension;
    type Format = CS::Format;
    type Usage = CS::Usage;
    type ViewFormats = ViewFormatsValue<'a>;
}
impl<'a, CS: State<'a>> TextureDescriptorBuilder<'a, CS> {
    #[doc = "Setter for [wgpu_28::TextureDescriptor::label]. Optional, defaults to `None`.\n"]
    pub fn label(self, label: wgpu_28::Label<'a>) -> TextureDescriptorBuilder<'a, SetLabel<CS>>
    where
        CS::Label: LabelIsEmpty,
    {
        TextureDescriptorBuilder {
            label: LabelValue(label),
            size: self.size,
            mip_level_count: self.mip_level_count,
            sample_count: self.sample_count,
            dimension: self.dimension,
            format: self.format,
            usage: self.usage,
            view_formats: self.view_formats,
        }
    }
    #[doc = "Setter for [wgpu_28::TextureDescriptor::size]. Optional, defaults to [wgpu_28::Extent3d::default()].\n"]
    pub fn size(
        self,
        size: impl Nested<wgpu_28::Extent3d>,
    ) -> TextureDescriptorBuilder<'a, SetSize<CS>>
    where
        CS::Size: SizeIsEmpty,
    {
        TextureDescriptorBuilder {
            label: self.label,
            size: SizeValue(Nested::unnest(size)),
            mip_level_count: self.mip_level_count,
            sample_count: self.sample_count,
            dimension: self.dimension,
            format: self.format,
            usage: self.usage,
            view_formats: self.view_formats,
        }
    }
    #[doc = "Setter for [wgpu_28::TextureDescriptor::mip_level_count]. Required.\n"]
    pub fn mip_level_count(
        self,
        mip_level_count: u32,
    ) -> TextureDescriptorBuilder<'a, SetMipLevelCount<CS>>
    where
        CS::MipLevelCount: MipLevelCountIsEmpty,
    {
        TextureDescriptorBuilder {
            label: self.label,
            size: self.size,
            mip_level_count: MipLevelCountValue(mip_level_count),
            sample_count: self.sample_count,
            dimension: self.dimension,
            format: self.format,
            usage: self.usage,
            view_formats: self.view_formats,
        }
    }
    #[doc = "Setter for [wgpu_28::TextureDescriptor::sample_count]. Required.\n"]
    pub fn sample_count(self, sample_count: u32) -> TextureDescriptorBuilder<'a, SetSampleCount<CS>>
    where
        CS::SampleCount: SampleCountIsEmpty,
    {
        TextureDescriptorBuilder {
            label: self.label,
            size: self.size,
            mip_level_count: self.mip_level_count,
            sample_count: SampleCountValue(sample_count),
            dimension: self.dimension,
            format: self.format,
            usage: self.usage,
            view_formats: self.view_formats,
        }
    }
    #[doc = "Setter for [wgpu_28::TextureDescriptor::dimension]. Required.\n"]
    pub fn dimension(
        self,
        dimension: wgpu_28::TextureDimension,
    ) -> TextureDescriptorBuilder<'a, SetDimension<CS>>
    where
        CS::Dimension: DimensionIsEmpty,
    {
        TextureDescriptorBuilder {
            label: self.label,
            size: self.size,
            mip_level_count: self.mip_level_count,
            sample_count: self.sample_count,
            dimension: DimensionValue(dimension),
            format: self.format,
            usage: self.usage,
            view_formats: self.view_formats,
        }
    }
    #[doc = "Setter for [wgpu_28::TextureDescriptor::format]. Required.\n"]
    pub fn format(
        self,
        format: wgpu_28::TextureFormat,
    ) -> TextureDescriptorBuilder<'a, SetFormat<CS>>
    where
        CS::Format: FormatIsEmpty,
    {
        TextureDescriptorBuilder {
            label: self.label,
            size: self.size,
            mip_level_count: self.mip_level_count,
            sample_count: self.sample_count,
            dimension: self.dimension,
            format: FormatValue(format),
            usage: self.usage,
            view_formats: self.view_formats,
        }
    }
    #[doc = "Setter for [wgpu_28::TextureDescriptor::usage]. Required.\n"]
    pub fn usage(self, usage: wgpu_28::TextureUsages) -> TextureDescriptorBuilder<'a, SetUsage<CS>>
    where
        CS::Usage: UsageIsEmpty,
    {
        TextureDescriptorBuilder {
            label: self.label,
            size: self.size,
            mip_level_count: self.mip_level_count,
            sample_count: self.sample_count,
            dimension: self.dimension,
            format: self.format,
            usage: UsageValue(usage),
            view_formats: self.view_formats,
        }
    }
    #[doc = "Setter for [wgpu_28::TextureDescriptor::view_formats]. Required.\n"]
    pub fn view_formats(
        self,
        view_formats: &'a [wgpu_28::TextureFormat],
    ) -> TextureDescriptorBuilder<'a, SetViewFormats<CS>>
    where
        CS::ViewFormats: ViewFormatsIsEmpty,
    {
        TextureDescriptorBuilder {
            label: self.label,
            size: self.size,
            mip_level_count: self.mip_level_count,
            sample_count: self.sample_count,
            dimension: self.dimension,
            format: self.format,
            usage: self.usage,
            view_formats: ViewFormatsValue(view_formats),
        }
    }
}
pub trait Complete<'a>:
    State<
    'a,
    Label: IsSetLabel<'a>,
    Size: IsSetSize,
    MipLevelCount: IsSetMipLevelCount,
    SampleCount: IsSetSampleCount,
    Dimension: IsSetDimension,
    Format: IsSetFormat,
    Usage: IsSetUsage,
    ViewFormats: IsSetViewFormats<'a>,
>
{
}
impl<
        'a,
        CS: State<
            'a,
            Label: IsSetLabel<'a>,
            Size: IsSetSize,
            MipLevelCount: IsSetMipLevelCount,
            SampleCount: IsSetSampleCount,
            Dimension: IsSetDimension,
            Format: IsSetFormat,
            Usage: IsSetUsage,
            ViewFormats: IsSetViewFormats<'a>,
        >,
    > Complete<'a> for CS
{
}
impl<'a, CS: Complete<'a>> TextureDescriptorBuilder<'a, CS> {
    pub fn build(self) -> wgpu_28::TextureDescriptor<'a> {
        wgpu_28::TextureDescriptor {
            label: IsSetLabel::get(self.label),
            size: IsSetSize::get(self.size),
            mip_level_count: IsSetMipLevelCount::get(self.mip_level_count),
            sample_count: IsSetSampleCount::get(self.sample_count),
            dimension: IsSetDimension::get(self.dimension),
            format: IsSetFormat::get(self.format),
            usage: IsSetUsage::get(self.usage),
            view_formats: IsSetViewFormats::get(self.view_formats),
        }
    }
    pub fn create_with(self, device: &wgpu_28::Device) -> wgpu_28::Texture {
        device.create_texture(&self.build())
    }
}
#[cfg(test)]
mod tests {
    #[allow(unused_imports)]
    #[allow(unused_imports)]
    use std::num::NonZeroU32;
    #[test]
    pub fn test_default() {
        assert_eq!(
            format!("{:#?}", super::IsSetLabel::get(super::LabelEmpty)),
            format!("{:#?}", wgpu_28::Label::default()),
        );
        assert_eq!(
            format!("{:#?}", super::IsSetSize::get(super::SizeEmpty)),
            format!("{:#?}", wgpu_28::Extent3d::default()),
        );
    }
}
