#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_28::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [VertexAttributeBuilder] for building [`wgpu_28::VertexAttribute`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [format](VertexAttributeBuilder::format) Required\n  - [offset](VertexAttributeBuilder::offset) Required\n  - [shader_location](VertexAttributeBuilder::shader_location) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_28::VertexAttribute`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [format](VertexAttributeBuilder::format) Required\n  - [offset](VertexAttributeBuilder::offset) Required\n  - [shader_location](VertexAttributeBuilder::shader_location) Required\n"]
pub fn vertex_attribute(
    format: wgpu_28::VertexFormat,
    offset: wgpu_28::BufferAddress,
    shader_location: wgpu_28::ShaderLocation,
) -> wgpu_28::VertexAttribute {
    wgpu_28::VertexAttribute {
        format,
        offset,
        shader_location,
    }
}
pub trait NestedVertexAttribute {
    fn unnest(self) -> wgpu_28::VertexAttribute;
}
impl NestedVertexAttribute for wgpu_28::VertexAttribute {
    fn unnest(self) -> wgpu_28::VertexAttribute {
        self
    }
}
impl<S: state::IsComplete> NestedVertexAttribute for VertexAttributeBuilder<S> {
    fn unnest(self) -> wgpu_28::VertexAttribute {
        self.build()
    }
}
