#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_29::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [BindGroupDescriptorBuilder] for building [`wgpu_29::BindGroupDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [layout](BindGroupDescriptorBuilder::layout) Required\n  - [entries](BindGroupDescriptorBuilder::entries) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_29::BindGroupDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [layout](BindGroupDescriptorBuilder::layout) Required\n  - [entries](BindGroupDescriptorBuilder::entries) Required\n"]
pub fn bind_group_descriptor<'a>(
    #[builder(start_fn)] label: wgpu_29::Label<'a>,
    layout: &'a wgpu_29::BindGroupLayout,
    entries: &'a [wgpu_29::BindGroupEntry<'a>],
) -> wgpu_29::BindGroupDescriptor<'a> {
    wgpu_29::BindGroupDescriptor {
        label,
        layout,
        entries,
    }
}
impl<'a, S: state::IsComplete> BindGroupDescriptorBuilder<'a, S> {
    pub fn create_with(self, device: &wgpu_29::Device) -> wgpu_29::BindGroup {
        device.create_bind_group(&self.build())
    }
}
pub trait NestedBindGroupDescriptor<'a> {
    fn unnest(self) -> wgpu_29::BindGroupDescriptor<'a>;
}
impl<'a> NestedBindGroupDescriptor<'a> for wgpu_29::BindGroupDescriptor<'a> {
    fn unnest(self) -> wgpu_29::BindGroupDescriptor<'a> {
        self
    }
}
impl<'a, S: state::IsComplete> NestedBindGroupDescriptor<'a> for BindGroupDescriptorBuilder<'a, S> {
    fn unnest(self) -> wgpu_29::BindGroupDescriptor<'a> {
        self.build()
    }
}
