#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_29::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [BindGroupLayoutEntryBuilder] for building [`wgpu_29::BindGroupLayoutEntry`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [binding](BindGroupLayoutEntryBuilder::binding) Required\n  - [visibility](BindGroupLayoutEntryBuilder::visibility) Required\n  - [ty](BindGroupLayoutEntryBuilder::ty) Required\n  - [count](BindGroupLayoutEntryBuilder::count) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_29::BindGroupLayoutEntry`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [binding](BindGroupLayoutEntryBuilder::binding) Required\n  - [visibility](BindGroupLayoutEntryBuilder::visibility) Required\n  - [ty](BindGroupLayoutEntryBuilder::ty) Required\n  - [count](BindGroupLayoutEntryBuilder::count) Required\n"]
pub fn bind_group_layout_entry(
    binding: u32,
    visibility: wgpu_29::ShaderStages,
    ty: wgpu_29::BindingType,
    count: Option<NonZeroU32>,
) -> wgpu_29::BindGroupLayoutEntry {
    wgpu_29::BindGroupLayoutEntry {
        binding,
        visibility,
        ty,
        count,
    }
}
pub trait NestedBindGroupLayoutEntry {
    fn unnest(self) -> wgpu_29::BindGroupLayoutEntry;
}
impl NestedBindGroupLayoutEntry for wgpu_29::BindGroupLayoutEntry {
    fn unnest(self) -> wgpu_29::BindGroupLayoutEntry {
        self
    }
}
impl<S: state::IsComplete> NestedBindGroupLayoutEntry for BindGroupLayoutEntryBuilder<S> {
    fn unnest(self) -> wgpu_29::BindGroupLayoutEntry {
        self.build()
    }
}
