#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_29::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [BlendStateBuilder] for building [`wgpu_29::BlendState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [color](BlendStateBuilder::color) Optional, defaults to [wgpu_29::BlendComponent::REPLACE]\n  - [alpha](BlendStateBuilder::alpha) Optional, defaults to [wgpu_29::BlendComponent::REPLACE]\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_29::BlendState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [color](BlendStateBuilder::color) Optional, defaults to [wgpu_29::BlendComponent::REPLACE]\n  - [alpha](BlendStateBuilder::alpha) Optional, defaults to [wgpu_29::BlendComponent::REPLACE]\n"]
pub fn blend_state(
    # [builder (with = | b : impl super :: blend_component_builder :: NestedBlendComponent | b . unnest () , default = wgpu_29 :: BlendComponent :: REPLACE ,)]
    color: wgpu_29::BlendComponent,
    # [builder (with = | b : impl super :: blend_component_builder :: NestedBlendComponent | b . unnest () , default = wgpu_29 :: BlendComponent :: REPLACE ,)]
    alpha: wgpu_29::BlendComponent,
) -> wgpu_29::BlendState {
    wgpu_29::BlendState { color, alpha }
}
pub trait NestedBlendState {
    fn unnest(self) -> wgpu_29::BlendState;
}
impl NestedBlendState for wgpu_29::BlendState {
    fn unnest(self) -> wgpu_29::BlendState {
        self
    }
}
impl<S: state::IsComplete> NestedBlendState for BlendStateBuilder<S> {
    fn unnest(self) -> wgpu_29::BlendState {
        self.build()
    }
}
