#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_29::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [ColorBuilder] for building [`wgpu_29::Color`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [r](ColorBuilder::r) Optional, defaults to `0f64`\n  - [g](ColorBuilder::g) Optional, defaults to `0f64`\n  - [b](ColorBuilder::b) Optional, defaults to `0f64`\n  - [a](ColorBuilder::a) Optional, defaults to `0f64`\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_29::Color`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [r](ColorBuilder::r) Optional, defaults to `0f64`\n  - [g](ColorBuilder::g) Optional, defaults to `0f64`\n  - [b](ColorBuilder::b) Optional, defaults to `0f64`\n  - [a](ColorBuilder::a) Optional, defaults to `0f64`\n"]
pub fn color(
    #[builder(default = 0f64)] r: f64,
    #[builder(default = 0f64)] g: f64,
    #[builder(default = 0f64)] b: f64,
    #[builder(default = 0f64)] a: f64,
) -> wgpu_29::Color {
    wgpu_29::Color { r, g, b, a }
}
pub trait NestedColor {
    fn unnest(self) -> wgpu_29::Color;
}
impl NestedColor for wgpu_29::Color {
    fn unnest(self) -> wgpu_29::Color {
        self
    }
}
impl<S: state::IsComplete> NestedColor for ColorBuilder<S> {
    fn unnest(self) -> wgpu_29::Color {
        self.build()
    }
}
