#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_29::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [ComputePassDescriptorBuilder] for building [`wgpu_29::ComputePassDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [timestamp_writes](ComputePassDescriptorBuilder::timestamp_writes) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_29::ComputePassDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [timestamp_writes](ComputePassDescriptorBuilder::timestamp_writes) Required\n"]
pub fn compute_pass_descriptor<'a>(
    #[builder(start_fn)] label: wgpu_29::Label<'a>,
    # [builder (with = | b : impl super :: compute_pass_timestamp_writes_builder :: NestedComputePassTimestampWrites < 'a > | b . unnest () ,)]
    timestamp_writes: Option<wgpu_29::ComputePassTimestampWrites<'a>>,
) -> wgpu_29::ComputePassDescriptor<'a> {
    wgpu_29::ComputePassDescriptor {
        label,
        timestamp_writes,
    }
}
pub trait NestedComputePassDescriptor<'a> {
    fn unnest(self) -> wgpu_29::ComputePassDescriptor<'a>;
}
impl<'a> NestedComputePassDescriptor<'a> for wgpu_29::ComputePassDescriptor<'a> {
    fn unnest(self) -> wgpu_29::ComputePassDescriptor<'a> {
        self
    }
}
impl<'a, S: state::IsComplete> NestedComputePassDescriptor<'a>
    for ComputePassDescriptorBuilder<'a, S>
{
    fn unnest(self) -> wgpu_29::ComputePassDescriptor<'a> {
        self.build()
    }
}
