#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_29::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [CreateBlasDescriptorBuilder] for building [`wgpu_29::CreateBlasDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [flags](CreateBlasDescriptorBuilder::flags) Required\n  - [update_mode](CreateBlasDescriptorBuilder::update_mode) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_29::CreateBlasDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [flags](CreateBlasDescriptorBuilder::flags) Required\n  - [update_mode](CreateBlasDescriptorBuilder::update_mode) Required\n"]
pub fn create_blas_descriptor<'a>(
    #[builder(start_fn)] label: wgpu_29::Label<'a>,
    flags: wgpu_29::wgt::AccelerationStructureFlags,
    update_mode: wgpu_29::wgt::AccelerationStructureUpdateMode,
) -> wgpu_29::CreateBlasDescriptor<'a> {
    wgpu_29::CreateBlasDescriptor {
        label,
        flags,
        update_mode,
    }
}
