#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_29::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [DepthStencilStateBuilder] for building [`wgpu_29::DepthStencilState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [format](DepthStencilStateBuilder::format) Required\n  - [depth_write_enabled](DepthStencilStateBuilder::depth_write_enabled) Required\n  - [depth_compare](DepthStencilStateBuilder::depth_compare) Required\n  - [stencil](DepthStencilStateBuilder::stencil) Optional, defaults to [wgpu_29::StencilState::default()]\n  - [bias](DepthStencilStateBuilder::bias) Optional, defaults to [wgpu_29::DepthBiasState::default()]\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_29::DepthStencilState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [format](DepthStencilStateBuilder::format) Required\n  - [depth_write_enabled](DepthStencilStateBuilder::depth_write_enabled) Required\n  - [depth_compare](DepthStencilStateBuilder::depth_compare) Required\n  - [stencil](DepthStencilStateBuilder::stencil) Optional, defaults to [wgpu_29::StencilState::default()]\n  - [bias](DepthStencilStateBuilder::bias) Optional, defaults to [wgpu_29::DepthBiasState::default()]\n"]
pub fn depth_stencil_state(
    format: wgpu_29::TextureFormat,
    depth_write_enabled: Option<bool>,
    depth_compare: Option<wgpu_29::CompareFunction>,
    # [builder (with = | b : impl super :: stencil_state_builder :: NestedStencilState | b . unnest () , default = wgpu_29 :: StencilState :: default () ,)]
    stencil: wgpu_29::StencilState,
    # [builder (with = | b : impl super :: depth_bias_state_builder :: NestedDepthBiasState | b . unnest () , default = wgpu_29 :: DepthBiasState :: default () ,)]
    bias: wgpu_29::DepthBiasState,
) -> wgpu_29::DepthStencilState {
    wgpu_29::DepthStencilState {
        format,
        depth_write_enabled,
        depth_compare,
        stencil,
        bias,
    }
}
pub trait NestedDepthStencilState {
    fn unnest(self) -> wgpu_29::DepthStencilState;
}
impl NestedDepthStencilState for wgpu_29::DepthStencilState {
    fn unnest(self) -> wgpu_29::DepthStencilState {
        self
    }
}
impl<S: state::IsComplete> NestedDepthStencilState for DepthStencilStateBuilder<S> {
    fn unnest(self) -> wgpu_29::DepthStencilState {
        self.build()
    }
}
