#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_29::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [DepthBiasStateBuilder] for building [`wgpu_29::DepthBiasState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [constant](DepthBiasStateBuilder::constant) Optional, defaults to `0i32`\n  - [slope_scale](DepthBiasStateBuilder::slope_scale) Optional, defaults to `0f32`\n  - [clamp](DepthBiasStateBuilder::clamp) Optional, defaults to `0f32`\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_29::DepthBiasState`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [constant](DepthBiasStateBuilder::constant) Optional, defaults to `0i32`\n  - [slope_scale](DepthBiasStateBuilder::slope_scale) Optional, defaults to `0f32`\n  - [clamp](DepthBiasStateBuilder::clamp) Optional, defaults to `0f32`\n"]
pub fn depth_bias_state(
    #[builder(default = 0i32)] constant: i32,
    #[builder(default = 0f32)] slope_scale: f32,
    #[builder(default = 0f32)] clamp: f32,
) -> wgpu_29::DepthBiasState {
    wgpu_29::DepthBiasState {
        constant,
        slope_scale,
        clamp,
    }
}
pub trait NestedDepthBiasState {
    fn unnest(self) -> wgpu_29::DepthBiasState;
}
impl NestedDepthBiasState for wgpu_29::DepthBiasState {
    fn unnest(self) -> wgpu_29::DepthBiasState {
        self
    }
}
impl<S: state::IsComplete> NestedDepthBiasState for DepthBiasStateBuilder<S> {
    fn unnest(self) -> wgpu_29::DepthBiasState {
        self.build()
    }
}
