#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_29::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [ExternalTextureTransferFunctionBuilder] for building [`wgpu_29::ExternalTextureTransferFunction`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [a](ExternalTextureTransferFunctionBuilder::a) Optional, defaults to `1.0`\n  - [b](ExternalTextureTransferFunctionBuilder::b) Optional, defaults to `1.0`\n  - [g](ExternalTextureTransferFunctionBuilder::g) Optional, defaults to `1.0`\n  - [k](ExternalTextureTransferFunctionBuilder::k) Optional, defaults to `1.0`\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_29::ExternalTextureTransferFunction`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [a](ExternalTextureTransferFunctionBuilder::a) Optional, defaults to `1.0`\n  - [b](ExternalTextureTransferFunctionBuilder::b) Optional, defaults to `1.0`\n  - [g](ExternalTextureTransferFunctionBuilder::g) Optional, defaults to `1.0`\n  - [k](ExternalTextureTransferFunctionBuilder::k) Optional, defaults to `1.0`\n"]
pub fn external_texture_transfer_function(
    #[builder(default = 1.0)] a: f32,
    #[builder(default = 1.0)] b: f32,
    #[builder(default = 1.0)] g: f32,
    #[builder(default = 1.0)] k: f32,
) -> wgpu_29::ExternalTextureTransferFunction {
    wgpu_29::ExternalTextureTransferFunction { a, b, g, k }
}
pub trait NestedExternalTextureTransferFunction {
    fn unnest(self) -> wgpu_29::ExternalTextureTransferFunction;
}
impl NestedExternalTextureTransferFunction for wgpu_29::ExternalTextureTransferFunction {
    fn unnest(self) -> wgpu_29::ExternalTextureTransferFunction {
        self
    }
}
impl<S: state::IsComplete> NestedExternalTextureTransferFunction
    for ExternalTextureTransferFunctionBuilder<S>
{
    fn unnest(self) -> wgpu_29::ExternalTextureTransferFunction {
        self.build()
    }
}
