#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_29::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [ExternalTextureDescriptorBuilder] for building [`wgpu_29::ExternalTextureDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [width](ExternalTextureDescriptorBuilder::width) Required\n  - [height](ExternalTextureDescriptorBuilder::height) Required\n  - [format](ExternalTextureDescriptorBuilder::format) Required\n  - [yuv_conversion_matrix](ExternalTextureDescriptorBuilder::yuv_conversion_matrix) Required\n  - [gamut_conversion_matrix](ExternalTextureDescriptorBuilder::gamut_conversion_matrix) Required\n  - [src_transfer_function](ExternalTextureDescriptorBuilder::src_transfer_function) Optional, defaults to [wgpu_29::ExternalTextureTransferFunction::default()]\n  - [dst_transfer_function](ExternalTextureDescriptorBuilder::dst_transfer_function) Optional, defaults to [wgpu_29::ExternalTextureTransferFunction::default()]\n  - [sample_transform](ExternalTextureDescriptorBuilder::sample_transform) Required\n  - [load_transform](ExternalTextureDescriptorBuilder::load_transform) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_29::ExternalTextureDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [width](ExternalTextureDescriptorBuilder::width) Required\n  - [height](ExternalTextureDescriptorBuilder::height) Required\n  - [format](ExternalTextureDescriptorBuilder::format) Required\n  - [yuv_conversion_matrix](ExternalTextureDescriptorBuilder::yuv_conversion_matrix) Required\n  - [gamut_conversion_matrix](ExternalTextureDescriptorBuilder::gamut_conversion_matrix) Required\n  - [src_transfer_function](ExternalTextureDescriptorBuilder::src_transfer_function) Optional, defaults to [wgpu_29::ExternalTextureTransferFunction::default()]\n  - [dst_transfer_function](ExternalTextureDescriptorBuilder::dst_transfer_function) Optional, defaults to [wgpu_29::ExternalTextureTransferFunction::default()]\n  - [sample_transform](ExternalTextureDescriptorBuilder::sample_transform) Required\n  - [load_transform](ExternalTextureDescriptorBuilder::load_transform) Required\n"]
pub fn external_texture_descriptor<'a>(
    #[builder(start_fn)] label: wgpu_29::Label<'a>,
    width: u32,
    height: u32,
    format: wgpu_29::ExternalTextureFormat,
    yuv_conversion_matrix: [f32; 16],
    gamut_conversion_matrix: [f32; 9],
    # [builder (with = | b : impl super :: external_texture_transfer_function_builder :: NestedExternalTextureTransferFunction | b . unnest () , default = wgpu_29 :: ExternalTextureTransferFunction :: default () ,)]
    src_transfer_function: wgpu_29::ExternalTextureTransferFunction,
    # [builder (with = | b : impl super :: external_texture_transfer_function_builder :: NestedExternalTextureTransferFunction | b . unnest () , default = wgpu_29 :: ExternalTextureTransferFunction :: default () ,)]
    dst_transfer_function: wgpu_29::ExternalTextureTransferFunction,
    sample_transform: [f32; 6],
    load_transform: [f32; 6],
) -> wgpu_29::ExternalTextureDescriptor<'a> {
    wgpu_29::ExternalTextureDescriptor {
        label,
        width,
        height,
        format,
        yuv_conversion_matrix,
        gamut_conversion_matrix,
        src_transfer_function,
        dst_transfer_function,
        sample_transform,
        load_transform,
    }
}
