#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_29::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [MeshPipelineDescriptorBuilder] for building [`wgpu_29::MeshPipelineDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [layout](MeshPipelineDescriptorBuilder::layout) Required\n  - [task](MeshPipelineDescriptorBuilder::task) Required\n  - [mesh](MeshPipelineDescriptorBuilder::mesh) Required\n  - [primitive](MeshPipelineDescriptorBuilder::primitive) Optional, defaults to [wgpu_29::PrimitiveState::default()]\n  - [depth_stencil](MeshPipelineDescriptorBuilder::depth_stencil) Required\n  - [multisample](MeshPipelineDescriptorBuilder::multisample) Optional, defaults to [wgpu_29::MultisampleState::default()]\n  - [fragment](MeshPipelineDescriptorBuilder::fragment) Required\n  - [multiview](MeshPipelineDescriptorBuilder::multiview) Required\n  - [cache](MeshPipelineDescriptorBuilder::cache) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_29::MeshPipelineDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [layout](MeshPipelineDescriptorBuilder::layout) Required\n  - [task](MeshPipelineDescriptorBuilder::task) Required\n  - [mesh](MeshPipelineDescriptorBuilder::mesh) Required\n  - [primitive](MeshPipelineDescriptorBuilder::primitive) Optional, defaults to [wgpu_29::PrimitiveState::default()]\n  - [depth_stencil](MeshPipelineDescriptorBuilder::depth_stencil) Required\n  - [multisample](MeshPipelineDescriptorBuilder::multisample) Optional, defaults to [wgpu_29::MultisampleState::default()]\n  - [fragment](MeshPipelineDescriptorBuilder::fragment) Required\n  - [multiview](MeshPipelineDescriptorBuilder::multiview) Required\n  - [cache](MeshPipelineDescriptorBuilder::cache) Required\n"]
pub fn mesh_pipeline_descriptor<'a>(
    #[builder(start_fn)] label: wgpu_29::Label<'a>,
    layout: Option<&'a wgpu_29::PipelineLayout>,
    # [builder (with = | b : impl super :: task_state_builder :: NestedTaskState < 'a > | b . unnest () ,)]
    task: Option<wgpu_29::TaskState<'a>>,
    # [builder (with = | b : impl super :: mesh_state_builder :: NestedMeshState < 'a > | b . unnest () ,)]
    mesh: wgpu_29::MeshState<'a>,
    # [builder (with = | b : impl super :: primitive_state_builder :: NestedPrimitiveState | b . unnest () , default = wgpu_29 :: PrimitiveState :: default () ,)]
    primitive: wgpu_29::PrimitiveState,
    # [builder (with = | b : impl super :: depth_stencil_state_builder :: NestedDepthStencilState | b . unnest () ,)]
    depth_stencil: Option<wgpu_29::DepthStencilState>,
    # [builder (with = | b : impl super :: multisample_state_builder :: NestedMultisampleState | b . unnest () , default = wgpu_29 :: MultisampleState :: default () ,)]
    multisample: wgpu_29::MultisampleState,
    # [builder (with = | b : impl super :: fragment_state_builder :: NestedFragmentState < 'a > | b . unnest () ,)]
    fragment: Option<wgpu_29::FragmentState<'a>>,
    multiview: Option<NonZeroU32>,
    cache: Option<&'a wgpu_29::PipelineCache>,
) -> wgpu_29::MeshPipelineDescriptor<'a> {
    wgpu_29::MeshPipelineDescriptor {
        label,
        layout,
        task,
        mesh,
        primitive,
        depth_stencil,
        multisample,
        fragment,
        multiview,
        cache,
    }
}
impl<'a, S: state::IsComplete> MeshPipelineDescriptorBuilder<'a, S> {
    pub fn create_with(self, device: &wgpu_29::Device) -> wgpu_29::RenderPipeline {
        device.create_mesh_pipeline(&self.build())
    }
}
pub trait NestedMeshPipelineDescriptor<'a> {
    fn unnest(self) -> wgpu_29::MeshPipelineDescriptor<'a>;
}
impl<'a> NestedMeshPipelineDescriptor<'a> for wgpu_29::MeshPipelineDescriptor<'a> {
    fn unnest(self) -> wgpu_29::MeshPipelineDescriptor<'a> {
        self
    }
}
impl<'a, S: state::IsComplete> NestedMeshPipelineDescriptor<'a>
    for MeshPipelineDescriptorBuilder<'a, S>
{
    fn unnest(self) -> wgpu_29::MeshPipelineDescriptor<'a> {
        self.build()
    }
}
