#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_29::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [Origin2dBuilder] for building [`wgpu_29::Origin2d`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [x](Origin2dBuilder::x) Required\n  - [y](Origin2dBuilder::y) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_29::Origin2d`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [x](Origin2dBuilder::x) Required\n  - [y](Origin2dBuilder::y) Required\n"]
pub fn origin2d(x: u32, y: u32) -> wgpu_29::Origin2d {
    wgpu_29::Origin2d { x, y }
}
pub trait NestedOrigin2d {
    fn unnest(self) -> wgpu_29::Origin2d;
}
impl NestedOrigin2d for wgpu_29::Origin2d {
    fn unnest(self) -> wgpu_29::Origin2d {
        self
    }
}
impl<S: state::IsComplete> NestedOrigin2d for Origin2dBuilder<S> {
    fn unnest(self) -> wgpu_29::Origin2d {
        self.build()
    }
}
