#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_29::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [RequestAdapterOptionsBaseBuilder] for building [`wgpu_29::RequestAdapterOptionsBase`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [power_preference](RequestAdapterOptionsBaseBuilder::power_preference) Optional, defaults to [wgpu_29::PowerPreference::None]\n  - [force_fallback_adapter](RequestAdapterOptionsBaseBuilder::force_fallback_adapter) Optional, defaults to `false`\n  - [compatible_surface](RequestAdapterOptionsBaseBuilder::compatible_surface) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_29::RequestAdapterOptionsBase`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [power_preference](RequestAdapterOptionsBaseBuilder::power_preference) Optional, defaults to [wgpu_29::PowerPreference::None]\n  - [force_fallback_adapter](RequestAdapterOptionsBaseBuilder::force_fallback_adapter) Optional, defaults to `false`\n  - [compatible_surface](RequestAdapterOptionsBaseBuilder::compatible_surface) Required\n"]
pub fn request_adapter_options_base<S>(
    # [builder (default = wgpu_29 :: PowerPreference :: None ,)]
    power_preference: wgpu_29::PowerPreference,
    #[builder(default = false)] force_fallback_adapter: bool,
    compatible_surface: Option<S>,
) -> wgpu_29::RequestAdapterOptionsBase<S> {
    wgpu_29::RequestAdapterOptionsBase {
        power_preference,
        force_fallback_adapter,
        compatible_surface,
    }
}
pub trait NestedRequestAdapterOptionsBase<S> {
    fn unnest(self) -> wgpu_29::RequestAdapterOptionsBase<S>;
}
impl<S> NestedRequestAdapterOptionsBase<S> for wgpu_29::RequestAdapterOptionsBase<S> {
    fn unnest(self) -> wgpu_29::RequestAdapterOptionsBase<S> {
        self
    }
}
impl<S> NestedRequestAdapterOptionsBase<S> for RequestAdapterOptionsBaseBuilder<S> {
    fn unnest(self) -> wgpu_29::RequestAdapterOptionsBase<S> {
        self.build()
    }
}
