#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_29::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [SamplerDescriptorBuilder] for building [`wgpu_29::SamplerDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [address_mode_u](SamplerDescriptorBuilder::address_mode_u) Optional, defaults to [wgpu_29::AddressMode::ClampToEdge]\n  - [address_mode_v](SamplerDescriptorBuilder::address_mode_v) Optional, defaults to [wgpu_29::AddressMode::ClampToEdge]\n  - [address_mode_w](SamplerDescriptorBuilder::address_mode_w) Optional, defaults to [wgpu_29::AddressMode::ClampToEdge]\n  - [mag_filter](SamplerDescriptorBuilder::mag_filter) Optional, defaults to [wgpu_29::FilterMode::Nearest]\n  - [min_filter](SamplerDescriptorBuilder::min_filter) Optional, defaults to [wgpu_29::FilterMode::Nearest]\n  - [mipmap_filter](SamplerDescriptorBuilder::mipmap_filter) Optional, defaults to [wgpu_29::MipmapFilterMode::Nearest]\n  - [lod_min_clamp](SamplerDescriptorBuilder::lod_min_clamp) Optional, defaults to `0.0`\n  - [lod_max_clamp](SamplerDescriptorBuilder::lod_max_clamp) Optional, defaults to `32.0`\n  - [compare](SamplerDescriptorBuilder::compare) Required\n  - [anisotropy_clamp](SamplerDescriptorBuilder::anisotropy_clamp) Optional, defaults to `1`\n  - [border_color](SamplerDescriptorBuilder::border_color) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_29::SamplerDescriptor`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [address_mode_u](SamplerDescriptorBuilder::address_mode_u) Optional, defaults to [wgpu_29::AddressMode::ClampToEdge]\n  - [address_mode_v](SamplerDescriptorBuilder::address_mode_v) Optional, defaults to [wgpu_29::AddressMode::ClampToEdge]\n  - [address_mode_w](SamplerDescriptorBuilder::address_mode_w) Optional, defaults to [wgpu_29::AddressMode::ClampToEdge]\n  - [mag_filter](SamplerDescriptorBuilder::mag_filter) Optional, defaults to [wgpu_29::FilterMode::Nearest]\n  - [min_filter](SamplerDescriptorBuilder::min_filter) Optional, defaults to [wgpu_29::FilterMode::Nearest]\n  - [mipmap_filter](SamplerDescriptorBuilder::mipmap_filter) Optional, defaults to [wgpu_29::MipmapFilterMode::Nearest]\n  - [lod_min_clamp](SamplerDescriptorBuilder::lod_min_clamp) Optional, defaults to `0.0`\n  - [lod_max_clamp](SamplerDescriptorBuilder::lod_max_clamp) Optional, defaults to `32.0`\n  - [compare](SamplerDescriptorBuilder::compare) Required\n  - [anisotropy_clamp](SamplerDescriptorBuilder::anisotropy_clamp) Optional, defaults to `1`\n  - [border_color](SamplerDescriptorBuilder::border_color) Required\n"]
pub fn sampler_descriptor<'a>(
    #[builder(start_fn)] label: wgpu_29::Label<'a>,
    # [builder (default = wgpu_29 :: AddressMode :: ClampToEdge ,)]
    address_mode_u: wgpu_29::AddressMode,
    # [builder (default = wgpu_29 :: AddressMode :: ClampToEdge ,)]
    address_mode_v: wgpu_29::AddressMode,
    # [builder (default = wgpu_29 :: AddressMode :: ClampToEdge ,)]
    address_mode_w: wgpu_29::AddressMode,
    # [builder (default = wgpu_29 :: FilterMode :: Nearest ,)] mag_filter: wgpu_29::FilterMode,
    # [builder (default = wgpu_29 :: FilterMode :: Nearest ,)] min_filter: wgpu_29::FilterMode,
    # [builder (default = wgpu_29 :: MipmapFilterMode :: Nearest ,)]
    mipmap_filter: wgpu_29::MipmapFilterMode,
    #[builder(default = 0.0)] lod_min_clamp: f32,
    #[builder(default = 32.0)] lod_max_clamp: f32,
    compare: Option<wgpu_29::CompareFunction>,
    #[builder(default = 1)] anisotropy_clamp: u16,
    border_color: Option<wgpu_29::SamplerBorderColor>,
) -> wgpu_29::SamplerDescriptor<'a> {
    wgpu_29::SamplerDescriptor {
        label,
        address_mode_u,
        address_mode_v,
        address_mode_w,
        mag_filter,
        min_filter,
        mipmap_filter,
        lod_min_clamp,
        lod_max_clamp,
        compare,
        anisotropy_clamp,
        border_color,
    }
}
impl<'a, S: state::IsComplete> SamplerDescriptorBuilder<'a, S> {
    pub fn create_with(self, device: &wgpu_29::Device) -> wgpu_29::Sampler {
        device.create_sampler(&self.build())
    }
}
