#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_29::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [ShaderRuntimeChecksBuilder] for building [`wgpu_29::ShaderRuntimeChecks`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [bounds_checks](ShaderRuntimeChecksBuilder::bounds_checks) Optional, defaults to `true`\n  - [force_loop_bounding](ShaderRuntimeChecksBuilder::force_loop_bounding) Optional, defaults to `true`\n  - [ray_query_initialization_tracking](ShaderRuntimeChecksBuilder::ray_query_initialization_tracking) Optional, defaults to `true`\n  - [task_shader_dispatch_tracking](ShaderRuntimeChecksBuilder::task_shader_dispatch_tracking) Optional, defaults to `true`\n  - [mesh_shader_primitive_indices_clamp](ShaderRuntimeChecksBuilder::mesh_shader_primitive_indices_clamp) Optional, defaults to `true`\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_29::ShaderRuntimeChecks`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [bounds_checks](ShaderRuntimeChecksBuilder::bounds_checks) Optional, defaults to `true`\n  - [force_loop_bounding](ShaderRuntimeChecksBuilder::force_loop_bounding) Optional, defaults to `true`\n  - [ray_query_initialization_tracking](ShaderRuntimeChecksBuilder::ray_query_initialization_tracking) Optional, defaults to `true`\n  - [task_shader_dispatch_tracking](ShaderRuntimeChecksBuilder::task_shader_dispatch_tracking) Optional, defaults to `true`\n  - [mesh_shader_primitive_indices_clamp](ShaderRuntimeChecksBuilder::mesh_shader_primitive_indices_clamp) Optional, defaults to `true`\n"]
pub fn shader_runtime_checks(
    #[builder(default = true)] bounds_checks: bool,
    #[builder(default = true)] force_loop_bounding: bool,
    #[builder(default = true)] ray_query_initialization_tracking: bool,
    #[builder(default = true)] task_shader_dispatch_tracking: bool,
    #[builder(default = true)] mesh_shader_primitive_indices_clamp: bool,
) -> wgpu_29::ShaderRuntimeChecks {
    wgpu_29::ShaderRuntimeChecks {
        bounds_checks,
        force_loop_bounding,
        ray_query_initialization_tracking,
        task_shader_dispatch_tracking,
        mesh_shader_primitive_indices_clamp,
    }
}
pub trait NestedShaderRuntimeChecks {
    fn unnest(self) -> wgpu_29::ShaderRuntimeChecks;
}
impl NestedShaderRuntimeChecks for wgpu_29::ShaderRuntimeChecks {
    fn unnest(self) -> wgpu_29::ShaderRuntimeChecks {
        self
    }
}
impl<S: state::IsComplete> NestedShaderRuntimeChecks for ShaderRuntimeChecksBuilder<S> {
    fn unnest(self) -> wgpu_29::ShaderRuntimeChecks {
        self.build()
    }
}
