#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_29::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [SurfaceConfigurationBuilder] for building [`wgpu_29::SurfaceConfiguration`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [usage](SurfaceConfigurationBuilder::usage) Required\n  - [format](SurfaceConfigurationBuilder::format) Required\n  - [width](SurfaceConfigurationBuilder::width) Required\n  - [height](SurfaceConfigurationBuilder::height) Required\n  - [present_mode](SurfaceConfigurationBuilder::present_mode) Optional, defaults to [wgpu_29::PresentMode::Fifo]\n  - [desired_maximum_frame_latency](SurfaceConfigurationBuilder::desired_maximum_frame_latency) Required\n  - [alpha_mode](SurfaceConfigurationBuilder::alpha_mode) Optional, defaults to [wgpu_29::CompositeAlphaMode::Auto]\n  - [view_formats](SurfaceConfigurationBuilder::view_formats) Required\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_29::SurfaceConfiguration`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [usage](SurfaceConfigurationBuilder::usage) Required\n  - [format](SurfaceConfigurationBuilder::format) Required\n  - [width](SurfaceConfigurationBuilder::width) Required\n  - [height](SurfaceConfigurationBuilder::height) Required\n  - [present_mode](SurfaceConfigurationBuilder::present_mode) Optional, defaults to [wgpu_29::PresentMode::Fifo]\n  - [desired_maximum_frame_latency](SurfaceConfigurationBuilder::desired_maximum_frame_latency) Required\n  - [alpha_mode](SurfaceConfigurationBuilder::alpha_mode) Optional, defaults to [wgpu_29::CompositeAlphaMode::Auto]\n  - [view_formats](SurfaceConfigurationBuilder::view_formats) Required\n"]
pub fn surface_configuration(
    usage: wgpu_29::TextureUsages,
    format: wgpu_29::TextureFormat,
    width: u32,
    height: u32,
    # [builder (default = wgpu_29 :: PresentMode :: Fifo ,)] present_mode: wgpu_29::PresentMode,
    desired_maximum_frame_latency: u32,
    # [builder (default = wgpu_29 :: CompositeAlphaMode :: Auto ,)]
    alpha_mode: wgpu_29::CompositeAlphaMode,
    view_formats: Vec<wgpu_29::TextureFormat>,
) -> wgpu_29::SurfaceConfiguration {
    wgpu_29::SurfaceConfiguration {
        usage,
        format,
        width,
        height,
        present_mode,
        desired_maximum_frame_latency,
        alpha_mode,
        view_formats,
    }
}
