#![allow(clippy::all)]

// The code in this file is generated by a script. Do not edit it directly.
//

#[allow(unused_imports)]
use std::{borrow::Cow, num::NonZeroU32, ops::Range};
#[allow(unused_imports)]
use wgpu_29::util::DeviceExt;
# [bon :: builder (state_mod (vis = "pub(crate)" , name = "state") , finish_fn = "build" , builder_type (doc { # [doc = "\nReturns [TexelCopyTextureInfoBuilder] for building [`wgpu_29::TexelCopyTextureInfo`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [texture](TexelCopyTextureInfoBuilder::texture) Required\n  - [mip_level](TexelCopyTextureInfoBuilder::mip_level) Required\n  - [origin](TexelCopyTextureInfoBuilder::origin) Optional, defaults to [wgpu_29::Origin3d::ZERO]\n  - [aspect](TexelCopyTextureInfoBuilder::aspect) Optional, defaults to [wgpu_29::TextureAspect::All]\n"] }) ,)]
#[doc = "\nBuilder for [`wgpu_29::TexelCopyTextureInfo`]\n        \nSet all required fields and any optional fields, then call `build()`.\n\nBuilder field setters:\n  - [texture](TexelCopyTextureInfoBuilder::texture) Required\n  - [mip_level](TexelCopyTextureInfoBuilder::mip_level) Required\n  - [origin](TexelCopyTextureInfoBuilder::origin) Optional, defaults to [wgpu_29::Origin3d::ZERO]\n  - [aspect](TexelCopyTextureInfoBuilder::aspect) Optional, defaults to [wgpu_29::TextureAspect::All]\n"]
pub fn texel_copy_texture_info<'a>(
    texture: &'a wgpu_29::Texture,
    mip_level: u32,
    # [builder (with = | b : impl super :: origin3d_builder :: NestedOrigin3d | b . unnest () , default = wgpu_29 :: Origin3d :: ZERO ,)]
    origin: wgpu_29::Origin3d,
    # [builder (default = wgpu_29 :: TextureAspect :: All ,)] aspect: wgpu_29::TextureAspect,
) -> wgpu_29::TexelCopyTextureInfo<'a> {
    wgpu_29::TexelCopyTextureInfo {
        texture,
        mip_level,
        origin,
        aspect,
    }
}
